### ISSUE TITLE
Offset skidding value with *-start/*-end placements

### ISSUE THREAD

**Issue by lozinsky** [floating-ui/floating-ui#1170]
### CodeSandbox demo

https://codesandbox.io/s/popper-skidding-issue-iezrs

### Steps to reproduce the problem

1. Open codesandbox demo
2. Try to comment/uncomment `offset` variables
3. Look at the preview

### What is the expected behavior?

I expect that the skidding value of the offset will be negative for `*-start` placements and positive for `*-end` placements in this case.

### What went wrong?

Popper shifts in the same direction with `*-start` and `*-end` placements.

### Any other comments?

I can define something like this

```js
const offset = ({ placement }) =>
  placement.endsWith("start")
    ? [-arrowPadding, arrowSize]
    : [arrowPadding, arrowSize];
```

and solve the problem, but maybe this behavior should be in the `popper-core`?

**Comment by atomiks** [comment]
I'm split on whether this should be something Floating UI handles considering it's as low level as possible. You wouldn't be able to "undo" the logic if we changed it (even if you would almost? never want to do...)

**Comment by atomiks** [comment]
I made an umbrella issue here to get these changes into v1: https://github.com/floating-ui/floating-ui/issues/1538
