### ISSUE TITLE
Support customized reference rectangle in preventOverflow modifier

### ISSUE THREAD

**Issue by kenticomartinh** [floating-ui/floating-ui#1187]
## Feature description

`preventOverflow` modifier gets reference rectangle directly. Maybe it could use the reference rectangle from `state`.

## Why should this feature be part of the Popper's core?

I tried to use plugin `inlinePositioning` for Tippy together with `preventOverflow` modifier
The plugin customizes the way how reference rectangle is evaluated, but when `preventOverflow` modifier is used, it places the content incorrectly

I tracked it down to this line where `detectOverflow` gets the reference rectangle directly:

https://github.com/popperjs/popper-core/blob/671f71e2b6990765e5ca780daaea7d1f7175beb6/src/utils/detectOverflow.js#L66

By examining `popperOffsets` it looks like it uses `state.rects.reference`, so I am wondering whether the `preventOverflow` modifier could use the same.

https://github.com/popperjs/popper-core/blob/671f71e2b6990765e5ca780daaea7d1f7175beb6/src/modifiers/popperOffsets.js#L11

Not sure if feature or bug, don't know the internals enough to tell whether the problem is in how Tippy plugin is written or in Popper modifier, neither have enough knowledge to be able to reproduce it on a clean CodePen for just Popper.

Please advise

**Comment by kenticomartinh** [comment]
Update:

I found out that the core of my positioning problem was actually caused by using `altBoundary: true` and having `overflow: hidden` on one of the containing elements, while placing Popper element to `document.body`

It seems that my expectations about what a "scrolling containers" mean in the documentation wasn't met. Please consider explaining that a bit better.

![image](https://user-images.githubusercontent.com/11004903/97895752-7a29d980-1d34-11eb-8cd5-1997b598d544.png)

Now I need to find out how to properly set it up to use the actual scrolling parent and not the parent with just `overflow: hidden` modifier which doesn't influence my popper element. If you have any suggestions, please let me know.

I guess my original request may still make sense to support the customization scenario better, just doesn't seem that urgent now

**Comment by FezVrasta** [comment]
`clippingParents` detects the parents that are scrollable, but that also are going to clip the popper if the latter overflows. Usually it doesn't make sense to keep the popper within a scrolling parent boundaries if the above situation is not happening.

You can pass a custom DOM element as `boundary` if you need more control.

**Comment by kenticomartinh** [comment]
I understand it now and using the actual scrolling parent was what I did in the end. It just felt weird and was quite hard to figure out as a user. Even harder when this referred to "effectively replicating `scrollParent`"

![image](https://user-images.githubusercontent.com/11004903/97956438-ecd49c80-1da8-11eb-89d2-c01a81d9735a.png)

In our situation, we have a `flex` layout element involved with `overflow: hidden` to force proper `shrink` inside of it. I think the `scrollParent` option for boundaries would still make sense to offer and could make the behavior clearer.

**Comment by FezVrasta** [comment]
We could make `boundary` and `altBoundary` accept a function with `state` as argument so one can compute the parent they like the most. I'd accept a PR to add this functionality.

**Comment by atomiks** [comment]
Hi, we're closing all feature requests related to Popper as it is entering low maintenance mode. All feature requests should now relate to the new package, [Floating UI](https://floating-ui.com)!

(This is now supported in Floating UI as it reads from the `rect`, but you'd probably use a Virtual Element)
