### ISSUE TITLE
Not possible to set an overflow boundary for the hide modifier

### ISSUE THREAD

**Issue by stenin-nikita** [floating-ui/floating-ui#1252]
### CodeSandbox demo

https://codesandbox.io/s/popper-hide-bug-zesbd

### Steps to reproduce the problem

1. Open CodeSandbox demo
2. Scroll down and click on button

### What is the expected behavior?

The tooltip should be visible.

### What went wrong?

Not possible to set an overflow boundary for the hide modifier. Also, if disable the hide modifier, the tooltip will go beyond the scrollable container.

### Any other comments?

A solution to the problem is to provide options to set boundary for the hide modifier:

```js
createPopper(reference, popper, {
  modifiers: [
    {
      name: 'hide',
      options: {
        boundary: document.querySelector('#someId'),
      },
    },
  ],
});
```

**Comment by SCWR** [comment]
This also brings me inconvenience and doubts.
I thought HIDE is limited to Preventoverflow
That is not actually, but it handles boundary problems.
My components have been running well until I encounter the setting boundary to Preventoverflow is still invalid, and see the source code for the reason.
This may be the illusion of using the version 1.

**Comment by atomiks** [comment]
The main issue here is that `hide()` has two calls to pass options in. I guess they could be separate props but it's kinda awkward. 

https://github.com/floating-ui/floating-ui/blob/b9f683d14a426767de93475125b32701f2f6ad84/packages/core/src/middleware/hide.ts#L25-L30
