### ISSUE TITLE
allow modifiers to operate on multiple phases

### ISSUE THREAD

**Issue by axyz** [floating-ui/floating-ui#1306]
## Feature description

A modifier most likely needs to do something in various phases. The typical scenario being 
1. reading something from the DOM (if unavoidable and not already available on the rects)
2. do some calculations in the `main` phase and save some data
3. write some style to the DOM in the `write` phase or add style in `beforeWrite` to the existing style objects (popper arrow, etc..)

Currently this is not possible as a modifier can only provide a single `fn` function and the phase is a single string.

An alternative approach could be to use hook function named like the relevant phase
```tsx
const myModifier = {
  name: "myModifier",
  read() { /* do stuff on read */ },
  main() { /* do stuff on main */ },
  write() { /* do stuff on write */ },
}
```

Backward compatibility could be guaranteed by considering the `phase` field coupled with the `fn` field and both being optional.

## Why should this feature be part of the Popper's core?

This approach would allow complex third party modifiers to be expressed as a single well isolated modifier and would be particularly useful for modifiers published as npm packages that can then export a single modifier object.

In terms of external contributions this would also make clarity on what is the most idiomatic way to operate on multiple phases and eventually provide some possibilities of optimizations on the core side.

See relevant discussion: https://github.com/popperjs/popper-core/discussions/1305

**Comment by atomiks** [comment]
Hi, we're closing all feature requests related to Popper as it is entering low maintenance mode. All feature requests should now relate to the new package, [Floating UI](https://floating-ui.com)!
