### ISSUE TITLE
TypeError: placement.split is not a function

### ISSUE THREAD

**Issue by mysuf** [floating-ui/floating-ui#1366]
### Steps to reproduce the problem

1. import Popper (esm)
2. use `Popper.createPopper(whatever)`
3. interact with element

### What is the expected behavior?

No errors

### What went wrong?

I was digging this issue into root cause which is variable `top` in `enums.js`. Export is declared globally as `var` so it conflicts with reserved window property `window.top` when deployed as ES modules. What happens after declaration: `top` keeps its default value (Window object) and fails to split as Object has no split method. I'm confused that nobody faced this issue yet. Development builds are usually composed to ES modules.

### Any other comments?

Production builds should be probably fine because modules are internally scoped when bundled.

PS. use scoped/block declarations (let/const) or rename variable

**Comment by jhirn** [comment]
Wow so glad to have found this issue. Experience a related defect stemming from this code that gets emitted. 

```javascript
// node_modules/@popperjs/core/lib/enums.js
init_react_shim();
var top = "top";
var bottom = "bottom";
var right = "right";
var left = "left";
var auto = "auto";
var basePlacements = [top, bottom, right, left];
var start = "start";
var end = "end";
var clippingParents = "clippingParents";
var viewport = "viewport";
var popper = "popper";
var reference = "reference";
var variationPlacements = /* @__PURE__ */ basePlacements.reduce(function(acc, placement) {
  return acc.concat([placement + "-" + start, placement + "-" + end]);
}, []);
var placements = /* @__PURE__ */ [].concat(basePlacements, [auto]).reduce(function(acc, placement) {
  return acc.concat([placement, placement + "-" + start, placement + "-" + end]);
}, []);
```

My specific symptom is that `var top ='top'` has no effect resulting  in reduce failing with `TypeError: Cannot read properties of undefined (reading 'valueOf')`. 

I'm using popper as an indirect dependency of the Mantine library with ESbuild. Latest versions of everything. Can provide more info if necessary but this obscure bug ground me to a halt. Not sure if there are options I can provide to ESbuild so that it can bundle things in a way that doesn't break or if there needs to be a change to Popper itself.

**Comment by atomiks** [comment]
So I'm assuming this only happens if you're not using `type="module"` on your script tag when using an ES module, and therefore isn't relevant. A lib shouldn't have to rename internal variables

**Comment by jhirn** [comment]
> So I'm assuming this only happens if you're not using `type="module"` on your script tag when using an ES module, and therefore isn't relevant. A lib shouldn't have to rename internal variables

Fair enough. Glad this is here for the Google-Fu for someone like myself who did not configure their build correctly. Thank you @atomiks

**Comment by mysuf** [comment]
type=module enables ES modules in node.js environment. It's quite new feature and it requires all bundler config files to use es6 syntax. Older projects have bundling written in cjs and could be difficult or impossible (cos dependencies must support es modules aswell) to rewrite. So I would call type=module workaround fitting for new or small projects.
