### ISSUE TITLE
Popper appears in the wrong place if the body element has the transform css property set

### ISSUE THREAD

**Issue by qqzm** [floating-ui/floating-ui#1375]
### CodeSandbox demo
https://codesandbox.io/s/elastic-sun-r5plx?file=/src/index.css

### Steps to reproduce the problem

1. Set the transform css property on the body element.

### What is the expected behavior?

I'd expect the popper to appear correctly positioned next to the target element.

### What went wrong?

The popper appears offset from the element, both horizontally and vertically, see the CodeSandbox demo above.

### Any other comments?

None

**Comment by baraa-elwan** [comment]
also if the target's position is absolute

**Comment by atomiks** [comment]
Not sure if this is worth fixing and adding extra cost to the lib; in what case is a transform ever set on `<body>`?

**Comment by qqzm** [comment]
I don't know why you would, but somebody does do it.
I'm the author of a browser extension and I've used Popper (+Tippy) to display information in a popup. One of my users raised a bug report that when they visit this third-party site: https://dorcishlibrarian.net/magic-math/
the popup is shown far off to the right. I worked-through what was going on and managed to trace it down to the fact that the site is setting a transform on the body element, which allowed me to create the demo on CodeSandbox demonstrating the issue.

**Comment by atomiks** [comment]
That's kinda nonsensical way to change the padding at the top of the page, but I agree you can't really do much about third party sites re: browser extensions. You could create your own custom modifier to handle it though.

**Comment by qqzm** [comment]
How would I go about doing that?

**Comment by atomiks** [comment]
Create a [custom modifier](https://popper.js.org/docs/v2/modifiers/) that alters the `popperOffsets` state  to take into account transform (`state.modifiersData.popperOffsets`)

**Comment by qqzm** [comment]
So I've got as far as this:
```
modifiers: [{
	name: 'fixBodyTransform',
	enabled: true,
	phase: 'main',
	fn({ state }) {
		let bodyRect = document.body.getBoundingClientRect();
		state.modifiersData.popperOffsets.x -= bodyRect.x + document.documentElement.scrollLeft;
		state.modifiersData.popperOffsets.y -= bodyRect.y + document.documentElement.scrollTop;
	}
}]
```
which fixes it on the site in question. However, it causes other (normal) sites to show the popup misplaced by about 8px in each direction. Am I missing something else?
