### ISSUE TITLE
Allow reusage / caching of popper instance for different references

### ISSUE THREAD

**Issue by ChrisKuBa** [floating-ui/floating-ui#1378]
Allow modifing the references of a popper instance (within a plugin).

I will reuse the popper instance and modify the reference.
This could be possible though a plug modifing the state.elements.reference, but does not work because state.scrollParents calculation uses the original reference argument, instead the parameter of the state.

This must be fixed by the core, to support 3rd party modifiers to update the reference properly.

Two workaround exsists:

1. also update state.scrollParents within the plugin => disadvantage: to be save, setOption must also be overwritten by the plugin to prevent setOption calls with the initial reference
2. wrap the element in a virtual Element => disadvantage: boilerplate

Alternative implementation:

Add an updateReference/setReference Methode to the instance. This will be the cleanest solution and needs no 3rd party plugin.

**Comment by ChrisKuBa** [comment]
It is feasible. This is how it is currently done, because we have no other choice.
We use popper to display many shortcuts for different elements on pressing ALT. So we caching the elements and the logic behind, but not the popper instances.

Another option is to wrap the reference outside of popper with a virtual element. But this is more unnecessary code as the modifications of popper js.

The reference within popper is saved within the state here
https://github.com/popperjs/popper-core/blob/2e909c71b2d09582a373aaa697152012016735ad/src/createPopper.js#L63-L66
and here by setOptions
https://github.com/popperjs/popper-core/blob/2e909c71b2d09582a373aaa697152012016735ad/src/createPopper.js#L91-L98
And used here ...
https://github.com/popperjs/popper-core/blob/2e909c71b2d09582a373aaa697152012016735ad/src/createPopper.js#L175
https://github.com/popperjs/popper-core/blob/2e909c71b2d09582a373aaa697152012016735ad/src/createPopper.js#L235
https://github.com/popperjs/popper-core/blob/2e909c71b2d09582a373aaa697152012016735ad/src/createPopper.js#L277

If setOptions can also updates the state.reference and state.scrollParents.reference uses the state.reference instead of the initial reference parameter, I think it should work.

**Comment by atomiks** [comment]
Destroying and recreating the popper instance is a fast operation, which means you don't need to cache. Updating the reference in this case would be virtually equally as expensive as destroying & re-creating because it needs to undergo the same steps anyway. Is this to do with the speed or just the setup of your code?

**Comment by ChrisKuBa** [comment]
We have no trouble. It's only a speed optimization request.

In the following code the _comp_ reference can change. This is the only reason, why I will update the reference within popper.
Hiding instead of destroying can be done with a modifier if necessary and if the reference in popper is updateable.

Code Snippet: showing mnemonics/shortcuts
```
mnemonicsElements.forEach((comp) => {
    const { mnemonic } = comp.dataset;
    const mnemonicElem = this.#updateMnemonic(mnemonic);
    this.#popperInstances.push(
        createPopper(comp, mnemonicElem, {
            placement: 'top-start',
            modifiers: [hide],
        }),
    );
});
```

Code Snippet: hiding mnemonics/shortcuts
```
this.#popperInstances.forEach((popper) => popper.destroy());
this.#popperInstances = [];
```

**Comment by atomiks** [comment]
Hi, we're closing all feature requests related to Popper as it is entering low maintenance mode. All feature requests should now relate to the new package, [Floating UI](https://floating-ui.com)!
