### ISSUE TITLE
preventOverflow doesn't work on elements other than the container.

### ISSUE THREAD

**Issue by HenrijsS** [floating-ui/floating-ui#1381]
### Steps to reproduce the problem

1. Have 2 div elements that are seperate. 1. Has a preview and 2. Has the options.
2. Adding preventOverflow on 1. element doesn't work. The tooltips are put on the options in the 2. element.
3. It currently looks like this, when it overflows the main belt preview: http://snpy.in/Btw2ZP

### What is the expected behavior?

That when the tooltip is over the 1. element (the preview) it flips down. Currently it only does that when it's out of the viewport.
Note that the 2. (options) container element isn't a fixed size, so theoretically it goes behind the sticky 1. element (preview) and has the same top offset as the viewport.
But I'd like to adjust the maximum height for it to look like it goes out of bounds: http://snpy.in/j43oIl

### What went wrong?

This functionality is already built in when the Tooltip is higher than the screen, it then pops down. I want to make it do it sooner. Is there a way to configure this?

**Comment by atomiks** [comment]
I have opened a generalized feature request related to this here: #1440
