### ISSUE TITLE
[Popper] Update must run twice to account for removal of scroll bar

### ISSUE THREAD

**Issue by OliverJAsh** [floating-ui/floating-ui#1404]
👋 Firstly, thanks for writing this fantastic library!

### CodeSandbox demo

https://stackblitz.com/edit/react-wevp7x?file=src%2FApp.js

### Steps to reproduce the problem

This reduced test case opens a popper. After 2 seconds the content of the popper changes and the popper gets wider and taller. After another 1 second we call `popper.update` and the popper is repositioned according to its new size.

### What is the expected behavior?

The popper is positioned correctly after calling `popper.update`.

### What went wrong?

The popper is not positioned correctly after calling `popper.update`—it is overlapping the trigger slightly.

https://user-images.githubusercontent.com/921609/140426100-2d1138d4-b26f-4352-af61-59f2e9efdcbd.mov

### Any other comments?

I believe this is because of the horizontal scroll bar.

When the popper content changes, the browser adds a horizontal scroll bar to the `body` element because the popper overflows.

This scroll bar is taken into account when we call `popper.update`. However, as soon as the new position is applied, the popper no longer overflows, thus the scroll bar disappears, thus the new position is now wrong.

Note on macOS you can only reproduce this by changing the system settings so that scroll bars are always visible.

To workaround this we can call `popper.update` twice, sequentially: https://stackblitz.com/edit/react-naffux?file=src%2FApp.js

**Comment by atomiks** [comment]
This bug appears to be not present in Floating UI.

**Comment by atomiks** [comment]
We have now released [Floating UI v1](https://floating-ui.com/docs/motivation), the successor to Popper.

Don't worry, Popper 2 will **continue to receive new releases** with bug/security fixes provided by external contributors, but development of new features is not continuing at this point. We are also closing bugs related to it as us maintainers are focusing our energy on tracking issues with Floating UI, however you are welcome to create new pull requests to fix bugs in Popper, which we will review and merge, as many packages (such as MUI, Bootstrap, etc) still rely on it. 

Thanks!
