### ISSUE TITLE
Use .mjs extension for ECMAScript modules

### ISSUE THREAD

**Issue by ImpossibleReality** [floating-ui/floating-ui#1406]
## Feature description

I propose that Popper should use the `.mjs` extension for built ES modules.

## Why should this feature be part of the Popper's core?

This feature should be part of popper's core because native Node ES imports only work on `.mjs` extensions, and give an `Uncaught SyntaxError` if you try importing a normal js file.

I personally am using Nuxt 3, which uses native ES Modules ([see more here](https://v3.nuxtjs.org/concepts/esm#what-is-native-esm)). I have no way of easily using Popper without manually renaming Popper's built files.

**Comment by FezVrasta** [comment]
I think cutting a new major just to refresh the whole distribution targets system to be up to date with the recent trends would make sense.

**Comment by atomiks** [comment]
We previously did use `.mjs` initially for v2 but was changed for some reason:

2.0.0 https://unpkg.com/browse/@popperjs/core@2.0.0/dist/esm/
2.0.4 https://unpkg.com/browse/@popperjs/core@2.0.4/dist/esm/

**Comment by jd-0001** [comment]
@FezVrasta I don't have much experience in publishing and maintaining packages but I guess [this](https://antfu.me/posts/publish-esm-and-cjs) might help.

**Comment by atomiks** [comment]
It looks like CRA doesn't support `.mjs` extensions right now, and many webpack-based bundlers don't resolve them correctly. What's the best way to support both Nuxt 3 and CRA?

See: https://github.com/framer/motion/issues/1307 (a lot of issues with using `.mjs`)

**Comment by atomiks** [comment]
Hi, we're closing all feature requests related to Popper as it is entering low maintenance mode. All feature requests should now relate to the new package, [Floating UI](https://floating-ui.com)!

Floating UI is an ES module by default now
