### ISSUE TITLE
Configure flip modifier to avoid restoring original placement after update

### ISSUE THREAD

**Issue by OliverJAsh** [floating-ui/floating-ui#1417]
In this example, we are using Popper with a preferred placement of `top-start` along with the flip modifier.

When the popper originally mounts, it shows a loading spinner. The flip modifier comes into action and correctly overrides the preferred placement so that the popper doesn't overflow.

When the content finishes loading, the popper size changes. We are calling `update` any time the size changes via a `ResizeObserver`. This time, the popper is smaller in height so it doesn't need to be flipped.

https://user-images.githubusercontent.com/921609/142389942-5a18b92c-1af9-4836-a79a-299bbe32e659.mov

This results in a fairly jarrying user experience—especially if the content loads quickly meaning the load state will appear as a flash.

I think the ideal user experience would be to preserve the placement that was originally applied by the flip modifier after we call `update`, rather than reverting to the preferred placement. We should only revert to the preferred placement if we need to, so the popper position doesn't change.

**Comment by FezVrasta** [comment]
You could disable the flip modifier on the first manual update you trigger and manually set the popper placement to the one returned by the previous positioning run.

**Comment by OliverJAsh** [comment]
Thanks for the response!

Unfortunately I think that's easier said than done. As I mentioned, we're calling `update` in a `ResizeObserver`. When we receive a `ResizeObserver` notification, we don't have the information to make an informed decision on whether or not to preserve the flipped position. I don't think it's as simple as "always preserve the flipped position" because we need to consider that the "flipped position" may no longer be valid, e.g. it now overflows.

This is why I think it should be part of the flip modifier.

**Comment by FezVrasta** [comment]
I'm not sure I get what you are trying to achieve. You can either use the first result of the flip modifier, or leave it always on and let it reposition the popper anytime it's needed.

It looks like you don't want either of the above?

**Comment by OliverJAsh** [comment]
I want the flip modifier to come into effect when we first display the popper, but then it should remain flipped until there's a reason why it can't appear in that position anymore (overflow).

Currently, the flip modifier is "eager"—it reverts to the preferred placement as soon as possible. The behaviour I want can be described as "lazy"—it shouldn't revert to the preferred placement until it needs to (to avoid layout shift).

**Comment by FezVrasta** [comment]
Ok I see, it makes sense. I think you can achieve that by setting the `placement` to the result of the previous flip result right now, but an option would be a nice idea.

**Comment by atomiks** [comment]
> we don't have the information to make an informed decision on whether or not to preserve the flipped position. I don't think it's as simple as "always preserve the flipped position" because we need to consider that the "flipped position" may no longer be valid, e.g. it now overflows.

If you set the placement to the flipped one on the update, it's still fine because it will know to flip again to the opposite placement, which was previously the original one

**Comment by OliverJAsh** [comment]
That makes sense, thank you!

**Comment by FezVrasta** [comment]
@atomiks does the custom modifier I posted above makes sense to you? Anything off?

**Comment by atomiks** [comment]
It will cause an infinite loop, not sure if it can be implemented as a modifier

**Comment by FezVrasta** [comment]
> It will cause an infinite loop, not sure if it can be implemented as a modifier

Why? Does `setOptions` trigger an update implicitly? 🤔

**Comment by atomiks** [comment]
Hi, we're closing all feature requests related to Popper as it is entering low maintenance mode. All feature requests should now relate to the new package, [Floating UI](https://floating-ui.com)!
