### ISSUE TITLE
[Floating UI / Popper] Plans for removal of `navigator.userAgent`

### ISSUE THREAD

**Issue by stsrki** [floating-ui/floating-ui#1423]
Hello. 

Recently we received a notification from one of our users to let us know that Google is making the `navigator.userAgent` obsolete. According to this documentation https://blog.chromium.org/2021/05/update-on-user-agent-string-reduction.html

I must admit I wasn't aware that this was a problem so it got me a little off guard. So I had to check where it is used and indeed it was used in a few places, where Popper library was one of them.

My question is. Are there any plans to remove the usage of `navigator.userAgent` from Popper?

**Comment by FezVrasta** [comment]
From what I'm reading they will not remove the user agent, they will reduce the info exposed by it. But the info we need will still be exposed. I don't think there's any action to take.

**Comment by prsdthkr** [comment]
Hi @FezVrasta,
Though the info we need will still be exposed, we are seeing some browser issues in dev tools.
These might become more server browser warnings in the future. Source: https://web.dev/migrate-to-ua-ch/#are-you-only-using-basic-user-agent-data

![image](https://user-images.githubusercontent.com/43764832/158267832-ec91dded-0db3-4e65-8900-982796054371.png)

In light of this, will you consider updating to use navigator.userAgentData instead?

something like
```js
  const reducedUAString = navigator?.userAgentData?.brands
              ?.map?.(
                  ({ brand, version }) => (`${brand}/${version}`),
              )?.join?.(' ');
  
  // for other browsers
  if( !reducedUAString ) {
      return  <<regex here>>.test(navigator.userAgent);
  } else {
    // for chrome
    return <<regex here>>.test(reducedUAString);
  }
}
```

**Comment by atomiks** [comment]
We can't because other browsers don't support that property.. These things can't be feature detected easily or at all either

**Comment by jbadan** [comment]
@FezVrasta @atomiks Can this be reopened?

**Comment by atomiks** [comment]
I'd really love to get rid of all `userAgent` usage with feature detection. I do think it's hard but anyone want to try to take a stab at it?

**Comment by atomiks** [comment]
Note these are only two small places that `navigator.userAgent` is used.

1. Checking if `.getBoundingClientRect()` measurements take into account "layout" vs. "visual" viewport. WebKit does it via "visual" viewport, while other engines do it via "layout".

https://github.com/floating-ui/floating-ui/blob/e35ae9c5b4d6766fb82aa9ff7be3776a5b113d95/packages/dom/src/utils/is.ts#L65-L73

2. Firefox needs a couple of more checks to determine a "containing block". Could also even be outdated:

https://github.com/floating-ui/floating-ui/blob/e35ae9c5b4d6766fb82aa9ff7be3776a5b113d95/packages/dom/src/utils/is.ts#L46-L49

**Comment by FezVrasta** [comment]
I don't think any of this is feature detectable being browser bugs 🤔

**Comment by atomiks** [comment]
Yes it does seem hard but there may be some tricks to use? The main issue with `userAgent` detection is:

- If the user is spoofing it (for whatever reason) the logic breaks because the rendering engine used remains the same and needs the checks
- If the browser changes/fixes the bug in the future, the check breaks, which then means we somehow need to start detecting versions and it gets really messy. Although, maybe since Popper is widely used, browsers would not change their implementation since it would break a lot of websites.
