### ISSUE TITLE
preventOverflow padding causes viewport overflow

### ISSUE THREAD

**Issue by jhnns** [floating-ui/floating-ui#1424]
### CodeSandbox demo

https://codesandbox.io/s/cool-ramanujan-yfwkp?file=/src/index.js

### Steps to reproduce the problem

1. Use "preventOverflow" with a padding
2. Reduce the viewport until the tooltip overflows

### What is the expected behavior?

The tooltip should not overflow the viewport in the mainAxis

### Any other comments?

Previous issue https://github.com/popperjs/popper-core/issues/673

**Comment by FezVrasta** [comment]
Thanks for the issue, I'm trying to understand why this used to work in the past and now it doesn't. It'd be useful to find which version introduced the regression.

**Comment by atomiks** [comment]
This has never worked and I wouldn't consider it a bug

Popper doesn't do anything to the size of your element, but you've specified `100vw` in your CSS, but the padding is pushing it 50px to the right, thus making it overflow that much. Your workaround is actually just the right way to handle the situation

**Comment by jhnns** [comment]
> Your workaround is actually just the right way to handle the situation

Do you think it would make sense to expose the padding as CSS custom property by default? I could imagine that this is a common problem.

**Comment by FezVrasta** [comment]
It could make sense to publish a custom modifier to do this kind of things. Similar to the one you provided but with maybe some additional configuration options and that also sets the CSS variables as you suggested. It would make for a great 3rd party modifier.

**Comment by jhnns** [comment]
> This has never worked and I wouldn't consider it a bug

I agree that it's debatable. However, I personally find it surprising that the modifier prevents the popper to overflow the viewport on one side of the axis while allowing it to overflow on other sides. So maybe I'm misunderstanding the purpose of this modifier.

@atomiks I guess you're recommending your custom modifier [popper-max-size-modifier](https://www.npmjs.com/package/popper-max-size-modifier). 

Feel free to close this issue if you think that the modifier is working as intended. Maybe you can think about adding the max-size modifier to the core modifiers because I'd consider non-overflowing poppers (at least on three sides of the viewport) to be the main use-case 😀

**Comment by atomiks** [comment]
Well the issue is, there's padding of `50px` on the right side too, so it would overflow the left side instead in the same way if it preferred the right side. The issue is solely related to the size of the popper, which Popper doesn't change.

@jhnns that modifier is a bit buggy though. But `size` comes in the core of [Floating UI](https://www.floating-ui.com/docs/size) which fixes its issues around resizing it.

**Comment by FezVrasta** [comment]
Please @atomiks refrain from spamming other products, it's a matter or being respectful with each other. Thank you for your understanding.

**Comment by atomiks** [comment]
So this isn't a bug, but to fix it, you can use [Floating UI](https://floating-ui.com)'s `size` middleware if you want to resize the element. (Popper is entering low maintenance mode as this is now the new package identify for the repo)

**Comment by inomdzhon** [comment]
@atomiks hi 👋 

Do we have analog of `popper-max-size-modifier` for `@floating-ui`?

Thanks 🙏
