### ISSUE TITLE
Use "browser" tag in package.json

### ISSUE THREAD

**Issue by ryanlsimms** [floating-ui/floating-ui#1426]
Bootstrap imports popper using [`import * as Popper from '@popperjs/core'`](https://github.com/twbs/bootstrap/blob/main/js/src/tooltip.js#L8), which will aways import the cjs version, even if the distribution is intended for browser.  This fails in my semi-buildless workflow when importing bootstrap using rollupjs.

Some of workarounds given in https://github.com/floating-ui/floating-ui/issues/933 work, but I think the best solution would be to use the [`"browser"`](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#browser) field in `package.json` as intended and point it to the umd (or esm?) distribution.
```json
"main": "dist/cjs/popper.js",
"main:umd": "dist/umd/popper.js",
"module": "lib/index.js",
"unpkg": "dist/umd/popper.min.js",
"browser": "dist/umd/popper.js",
```

**Comment by TrySound** [comment]
browser is not supposed to be umd. It can be a map to specify which files need to be aliased to make package work in browser. There is no need for it in this project.

See example
https://github.com/visgl/react-map-gl/blob/e4b44c3feda3458c2a1ea6f0e8ede8ffd01188c2/package.json#L21-L26

**Comment by atomiks** [comment]
At this point in time we are not updating Popper's build setup. For Floating UI we're working on low/no build compatibility here #1502
