### ISSUE TITLE
[React Native] More loosely coupled way for the scrollProps to support more use-cases for libraries

### ISSUE THREAD

**Issue by RichardLindhout** [floating-ui/floating-ui#1430]
I use a Portal from react-native (since a lot of views are positioned relative in RN). It seems the sameScrollView will do what I want but I would like  to manually manage scrollOffsets since I can't control the parent scrollview of the user in [ react-native-paper-autocomplete](https://github.com/web-ridge/react-native-paper-autocomplete) 

And pass the props to hooks, something like

```tsx
const {scrollProps,scrollInsets} = useFloatingScrollView();
```

```tsx
const {x, y, reference, floating} = useFloating({
    placement: 'right',
    scrollInsets,
  });
```

So I can build something for my users like
```tsx
import {useShareScrollViewWithAutocomplete, Autocomplete} 

function App() {
       const {scrollProps,scrollInsets } = useShareScrollViewWithAutocomplete()
       return (
          <ScrollView {...scrollProps}>
              <Autocomplete scrollInsets={scrollInsets} />
              <Autocomplete scrollInsets={scrollInsets} />
              <Autocomplete scrollInsets={scrollInsets} />
         </ScrollView>
       )
}

```

**Comment by atomiks** [comment]
What is `scrollInsets`? `scrollProps` is just this, I don't have much RN experience so a PR to improve this area would be great! 

https://github.com/floating-ui/floating-ui/blob/a5da2b1b4c8827bb40b58da84197bca97a6d55be/packages/react-native/src/index.ts#L136-L139

**Comment by atomiks** [comment]
> And haver multiple floating elements in my scrollview. I don't think that's possible a.t.m.

I think you could do this currently:

```js
const {scrollProps: scrollProps1} = useFloating();
const {scrollProps: scrollProps2} = useFloating();

<ScrollView
  onScroll={event => {
    scrollProps1.onScroll(event);
    scrollProps2.onScroll(event);
  });
  scrollEventThrottle={16}
/>
```

Breaking changes are fine though to support a better API as the lib is still in v0.

**Comment by atomiks** [comment]
Due to a lack of activity, I'm closing this issue
