### ISSUE TITLE
Have a question about the source code in @floating-ui/core/computePosition.ts

### ISSUE THREAD

**Issue by relax-code-relax-life** [floating-ui/floating-ui#1434]
Thank floating-ui, I have implemented a tooltip by using floating-ui.  it's very useful and wonderful! 

And I'm interested in the source code. When I look at the `core/src/computePosition.ts`, found below code in line59:

```javascript
    if (i === 0) {
      ({x, y} = computeCoordsFromPlacement({
        ...rects,
        placement: statefulPlacement,
      }));
    }

```

The `computeCoordsFromPlacement`  is executed already in line39.  so why need to execute `computeCoordsFromPlacement` again when the first middleware is applied? 

Looking forward to your reply, thank you very much！

**Comment by atomiks** [comment]
When the placement changes the coords need to restart from that point. Actually, that code should live here instead.

https://github.com/floating-ui/floating-ui/blob/489b659ee072344c4719ddf3925101af65f0feb2/packages/core/src/computePosition.ts#L89-L92

**Comment by relax-code-relax-life** [comment]
Thank you for your reply.
When the `i===0`, there is no param changed. Execute `computeCoordsFromPlacement` again just for placement change, I think it is unnecessary.  If put it in the `if (reset) ...`, I can understand it.

By the way, I think floating-ui is a very useful base-library. Do you plan to support multi-language about Doc? And I'm a Chinese developer, if you need I'm happy to translate it to Chinese.

**Comment by atomiks** [comment]
It's necessary because of `reset` restarting the loop with `i = -1`, the base placement coords must be recomputed for the new placement

Anyway I've actually moved it to a better spot: 

https://github.com/floating-ui/floating-ui/blob/188efd7b71318a7e800206d08ec8c276dff63b13/packages/core/src/computePosition.ts#L82-L95

> By the way, I think floating-ui is a very useful base-library. Do you plan to support multi-language about Doc? And I'm a Chinese developer, if you need I'm happy to translate it to Chinese.

Sure, why not as long as you will maintain it :) Probably need to add a translations UI to the website too.

**Comment by relax-code-relax-life** [comment]
OK, I'm happy to and will do it in my spare time, the process may not be very fast, but I will do it as possible as I can. If I accomplish some, I will make a PR let you know.
