### ISSUE TITLE
How to use size middleware with React DOM

### ISSUE THREAD

**Issue by ziofat** [floating-ui/floating-ui#1445]
No idea how to get width and height from `useFloating` hook. I assumed it was in `middlewareData` but seems not.

**Comment by atomiks** [comment]
`size` is special because of the way it interferes with the lifecycle which is why it has its own `apply` function to ensure everything works smoothly:

```js
const [sizeData, setSizeData] = useState(null);

const {...} = useFloating({
  middleware: [size({apply: setSizeData})],
});

// floating element
return <div style={{maxHeight: sizeData?.height ?? ''}} />;
```

**Comment by ziofat** [comment]
Thanks, that works.

**Comment by atomiks** [comment]
⚠️ ⚠️ ⚠️ ⚠️ !

This is no longer recommended for React 18 as it's buggy. Instead, just mutate the style directly (more performant also).

Use the `refs` object that gets returned:

```js
  const {x, y, reference, floating, strategy, update, refs} = useFloating({
    placement,
    middleware: [
      size({
        apply({width, height}) {
          if (!refs.floating.current) return;

          Object.assign(refs.floating.current.style, {
            maxWidth: `${width}px`,
            maxHeight: `${height}px`,
          });
        },
        padding: 10,
      }),
    ],
  });
```
