### ISSUE TITLE
How to update floating instance state when reference updates?

### ISSUE THREAD

**Issue by sabetAI** [floating-ui/floating-ui#1447]
I'm trying to use a modifier to update the state of the popper instance without success:

```
modifiers: [
                {
                  name: "setMaxWidth",
                  phase: "write",
                  enabled: true,
                  fn: ({ state, instance }) => {
                    console.log(state);
                    const refWidth = state.rects.reference.width;
                    state.rects.popper.width = refWidth;
                    // instance.update();
                    return state;
                  },
                },
              ],
```

What am I doing wrong?

**Comment by FezVrasta** [comment]
Thank you for your issue.

Unfortunately I can't answer to all the reported issues without a little help from you.
Please, make sure to follow the **issues template** when you submit a new issue, in this way I will already have all the informations needed to understand the problem and help you with it.

I'm closing this issue for now, but feel free to open a new one making sure to follow all the instructions!

Thank you for your understanding.
