### ISSUE TITLE
What is correct way to set popper width same as reference

### ISSUE THREAD

**Issue by olegzaitsevway** [floating-ui/floating-ui#1450]
I'm wondering if there is a simple way to do this without writing a custom useEffect hook that will handle this stuff.
Didn't find anything about this in docs.

Thank you in advance for your help!

**Comment by atomiks** [comment]
- [Floating UI](https://floating-ui.com/docs/size#match-reference-width)
- [Popper 2](https://codesandbox.io/s/bitter-sky-pe3z9?file=/src/index.js)

**Comment by olegzaitsevway** [comment]
@atomiks thanks, but still not clear where to do this in React workflow. and should we search for docs also in popper documentation?

**Comment by atomiks** [comment]
Here's how you use `apply` in React: https://github.com/floating-ui/floating-ui/issues/1445#issuecomment-992598938

> and should we search for docs also in popper documentation?

What do you mean?

**Comment by olegzaitsevway** [comment]
oh, thanks now it's clear!
I'm too stupid to get this without an example :(

**Comment by atomiks** [comment]
⚠️ ⚠️ ⚠️ ⚠️ !

This is no longer recommended for React 18 as it's buggy. Instead, just mutate the style directly (more performant also).

Use the `refs` object that gets returned:

```js
  const {x, y, reference, floating, strategy, update, refs} = useFloating({
    placement,
    middleware: [
      size({
        apply({width, height}) {
          if (!refs.floating.current) return;

          Object.assign(refs.floating.current.style, {
            maxWidth: `${width}px`,
            maxHeight: `${height}px`,
          });
        },
        padding: 10,
      }),
    ],
  });
```
