### ISSUE TITLE
@floating-ui/react-dom@0.3.3 does not contain the arrowRef type fix

### ISSUE THREAD

**Issue by joshwooding** [floating-ui/floating-ui#1460]
According to the [changelog ](https://github.com/floating-ui/floating-ui/blob/master/packages/react-dom/CHANGELOG.md) release 0.3.3 should contain the arrowRef type fix but it doesn't. You can check using https://unpkg.com/@floating-ui/react-dom@0.3.3/src/index.d.ts. Thanks for the awesome library :)

**Comment by atomiks** [comment]
Are you referring to https://github.com/floating-ui/floating-ui/pull/1452? I'm *just* about to publish the release with this in it 😛

**Comment by atomiks** [comment]
`0.3.4` published now, which should contains the `null` fix

**Comment by joshwooding** [comment]
Thank you for the quick fix :)
