### ISSUE TITLE
react-native build - dependency issue

### ISSUE THREAD

**Issue by BlackJohnny** [floating-ui/floating-ui#1463]
Hi,

I would like to test this alpha version of the react-native support however it seems that the dependency to `@floating-ui/core` is broken.

I simply installed the package in my project with `npm install --save @floating-ui/react-native` and tried to run the app.

The error looks like this:

error: Error: While trying to resolve module `@floating-ui/core` from file `xxx/node_modules/@floating-ui/react-native/dist/floating-ui.react-native.js`, the package `xxx/node_modules/@floating-ui/core/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`xxx/node_modules/@floating-ui/core/dist/floating-ui.core.cjs`. Indeed, none of these files exist:...

Any hint on how to fix this is appreciated!

Thanks!

**Comment by atomiks** [comment]
Are you on a node version that supports native ES modules and a modern bundler?

**Comment by BlackJohnny** [comment]
I am using the active LTS (v16.13.1)

**Comment by atomiks** [comment]
Looks like the bundler can't resolve the `.cjs` extension. I guess it's a bug. In the meantime I can bundle in `@floating-ui/core` into the bundle. I will do so in a sec :-)

**Comment by BlackJohnny** [comment]
> Looks like the bundler can't resolve the `.cjs` extension. I guess it's a bug. In the meantime I can bundle in `@floating-ui/core` into the bundle. I will do so in a sec :-)

Thank you!

**Comment by BlackJohnny** [comment]
It does not seem to fix it still. I have created a new hello-world app with the library and it behaves the same.
