### ISSUE TITLE
[Popper] JSPM.org Not Providing the /dist/esm URL

### ISSUE THREAD

**Issue by chadrschroeder** [floating-ui/floating-ui#1465]
I'm using the [Online Import Map Generator](https://generator.jspm.io/) at JSPM.org to see which URL to use for a Popper.js `importmap` reference.  I have "Browser" checked and "Node" unchecked, but it is giving me back:

```
https://ga.jspm.io/npm:@popperjs/core@2.11.0/lib/index.js
```

Here is a minimal example:

```html
<html>
  <head>
    <script type="importmap">{
      "imports": {
        "@popperjs/core": "https://ga.jspm.io/npm:@popperjs/core@2.11.0/lib/index.js"
      }
    }</script>
    <script type="module">
      import { createPopper } from "@popperjs/core";
      const button = document.querySelector("#button");
      const tooltip = document.querySelector("#tooltip");
      createPopper(button, tooltip);
    </script>
  </head>
  <body>
    <button id="button" aria-describedby="tooltip">My button</button>
    <div id="tooltip" role="tooltip">My tooltip</div>
  </body>
</html>
```

This will crash on:

```
Uncaught ReferenceError: process is not defined
createPopper.js:81
```

This is because in the browser there is no `process.env.NODE_ENV` value provided.  According to your [distribution targets documentation](https://github.com/floating-ui/floating-ui/tree/v2.x#distribution-targets) I think the correct "Browser" URL is supposed to be:

```
https://ga.jspm.io/npm:@popperjs/core@2.11.0/dist/esm/index.js
```

Note that I'm really asking about this because the [importmap-rails](https://github.com/rails/importmap-rails) gem makes an API call to JSPM.org to get this URL.  See [this comment for more details](https://github.com/rails/importmap-rails/issues/65#issuecomment-1000389955).

Are you able to provide more info to JSPM.org so that they know about the `/dist/esm` path?

**Comment by atomiks** [comment]
TBH it's better to polyfill `process.env.NODE_ENV` in the browser. Otherwise you aren't getting helpful DEV messages like you would in a regular bundler

**Comment by chadrschroeder** [comment]
Why do you offer the `/dist/esm` version?  If you don't want to have to support both versions, would it be possible to make an update so that the `/lib` code defaults to Production mode rather than crashing?

If you did want to keep supporting both versions and have them work with CDNs like JSPM.org, I think you could set up a [conditional export](https://jspm.org/docs/cdn#conditional-exports) in `package.json` that was something like:

```json
{
  "exports": {
    "node": "./lib/index.js",
    "default": "./dist/esm/index.js"
  }
}
```

Or:

```json
{
  "exports": {
    "browser": "./dist/esm/index.js",
    "default": "./lib/index.js"
  }
}
```

**Comment by chadrschroeder** [comment]
Thanks for working on https://github.com/floating-ui/floating-ui/pull/1502.  Would you be open to a similar pull request in the `v2.x` branch?  Bootstrap 5 still uses `@popper/core`, so that could be helpful.  I saw you made [this comment](https://github.com/floating-ui/floating-ui/issues/1426#issuecomment-1013573183) recently that you're no longer updating the Popper build setup.  If that's the case, I can go ahead and close out this issue.

**Comment by atomiks** [comment]
If you want to work on a new build for Popper v2 in new PR similar to what we did for Floating UI, that would be welcome; it just needs to be fully backwards-compatible
