### ISSUE TITLE
Regression in overflow prevention behavior between @popperjs/core v2.10.2 and v2.11.0

### ISSUE THREAD

**Issue by mitchellstern** [floating-ui/floating-ui#1477]
### CodeSandbox demos

These demos have identical code except for the version of @popperjs/core being used. They include an outer container (red border) with `overflow-x: hidden` and `overflow-y: scroll`, and an inner container (gray background) with `position: relative`.

The screenshots below are consistent across Chrome, Firefox, and Safari.

https://codesandbox.io/s/fervent-jepsen-2bs5e (@popperjs/core v2.10.2)

<img width="503" alt="Screenshot using v2.10.2" src="https://user-images.githubusercontent.com/3311523/147701322-a7b410ba-4302-446c-b427-1bf52e943ff8.png">

https://codesandbox.io/s/delicate-rgb-t3ymt (@popperjs/core v2.11.0)

<img width="503" alt="Screenshot using v2.11.0" src="https://user-images.githubusercontent.com/3311523/147701379-e65ea3f4-1aa7-45e0-93fd-c5eb9f96641a.png">

### What is the expected behavior?

I would expect the tooltip to be positioned within the boundaries of the outer container as in the v2.10.2 demo.

### What went wrong?

The overflow prevention logic seems to have changed starting in v2.11.0, with the tooltip no longer being positioned within the boundaries of the outer container and getting occluded as a result. This only appears to be an issue when using an outer container with `overflow` styles and an inner container with `position: relative`.

**Comment by atomiks** [comment]
Thinking it's this https://github.com/floating-ui/floating-ui/pull/1399

**Comment by mitchellstern** [comment]
Thanks for looking into this!

The motivation here is a fairly common use case: a list of items inside a container, each of which has action buttons in the upper-left or upper-right corner (e.g. edit, delete) that have explanatory tooltips shown upon hover.

Feel free to close this issue if it's fully resolved by your pull request above.

**Comment by atomiks** [comment]
Yeah this type of layout is far more common than the layout fixed #1399 fixes, so reverting makes the most sense for now. Would be nice to solve both solutions but I think it's a bit tricky.

Rolling Versions isn't showing a release button but I'll close this once it's released. @FezVrasta

**Comment by atomiks** [comment]
Released in `v2.11.2`
