### ISSUE TITLE
`limitShift()` affected `offset()`

### ISSUE THREAD

**Issue by inomdzhon** [floating-ui/floating-ui#1482]
Hi there 👋 

When I use `offset(<offset_number>)` and `shift({ limiter: limitShift() })` together, secondary middleware break first.

`codesandbox` [here](https://codesandbox.io/s/floating-ui-dom-issue-limitshift-affected-offset-6qdyg). In `App.tsx` toggle `tethered` property for see problem.

How we can resolve this issue?

Thanks 🙏

**Comment by atomiks** [comment]
`limitShift({crossAxis: false})` will work (if you aren't enabling `shift({crossAxis: true})`

`offset` should be added on that axis, however:

https://github.com/floating-ui/floating-ui/blob/83eafc8d929c0a207e4fbff96ebc117156d49bbe/packages/core/src/middleware/shift.ts#L160

**Comment by inomdzhon** [comment]
Thank you a lot for quick fix 🙏
