### ISSUE TITLE
Include floating-ui as dependency isn't working?

### ISSUE THREAD

**Issue by thednp** [floating-ui/floating-ui#1484]
I'm trying to include your script into a library and it won't work.

I'm getting 
```
Uncaught (in promise) ReferenceError: process is not defined
```

[Here](https://codesandbox.io/s/floating-ui-dom-template-forked-q166f?file=/src/index.js)'s how my code looks like. This sandbox works fine, but not in my compiled ES6 code it doesn't.

**Comment by atomiks** [comment]
> This sandbox works fine, but not in my compiled ES6 code it doesn't.

In what context are you using it? If you're compiling the code using Rollup you need to make sure you're replacing `process.env.NODE_ENV` with either `"development"` or `"production"` when running it inside a browser.

**Comment by thednp** [comment]
> In what context are you using it? If you're compiling the code using Rollup you need to make sure you're replacing `process.env.NODE_ENV` with either `"development"` or `"production"` when running it inside a browser.

I don't know exactly how to set `process` in my Rollup setup, I'm guessing the `rollup.config.json`?

Anyways, I basically need to replace all the crap in my [styleTip](https://github.com/thednp/bootstrap.native/blob/master/src/util/styleTip.js) with something that makes sense and works.

**Comment by atomiks** [comment]
Here's our  Rollup setup to replace `__DEV__`, but you'd use a direct check for `process.env.NODE_ENV`

https://github.com/floating-ui/floating-ui/blob/648b5bd7e4b614c2a40d5f2e678363ec5225ab9a/packages/core/rollup.config.js#L60-L65

i.e.(ensuring you're processing `node_modules`):

```js
replace({
  'process.env.NODE_ENV': `"production"`
});
```

> The other suggestion to import directly from @floating-ui/dom/dist/floating-ui.dom.esm.min.js doesn't work.

What error is there?

**Comment by thednp** [comment]
Same error.

Thank you for your reply, will check it right now.

**Comment by thednp** [comment]
That did it, thank you very much.

BTW: Happy New Year!

**Comment by atomiks** [comment]
Ah yeah because `@floating-ui/dom`'s minified version doesn't point to `/core`'s minified version. Would probably need an alias plugin in that case, but this is a better way to handle it anyway
