### ISSUE TITLE
`@popperjs/core` v2.11.1 includes `closure-compiler` as a dependency

### ISSUE THREAD

**Issue by razh** [floating-ui/floating-ui#1491]
https://www.npmjs.com/package/@popperjs/core?activeTab=dependencies

### v2.11.0

https://unpkg.com/browse/@popperjs/core@2.11.0/package.json

### v2.11.1

https://unpkg.com/browse/@popperjs/core@2.11.1/package.json

```diff
+  },
+  "dependencies": {
+   "closure-compiler": "^0.2.12"
```

I also noticed that [`CultureHQ/actions-yarn`](https://github.com/CultureHQ/actions-yarn) is using yarn v1.17.3 (current version is v1.22.17).

https://github.com/floating-ui/floating-ui/runs/4701540747

**Comment by FezVrasta** [comment]
Uh my bad! Please check out 2.11.2
