### ISSUE TITLE
[Core] Arrow middleware does not point properly if toggle button is small

### ISSUE THREAD

**Issue by megawebmaster** [floating-ui/floating-ui#1493]
Hi!

When working on my own Tooltip / Popover I decided to use Floating-UI thanks to it's great API and ease of use. Everything was going smoothly until I found that when I use `arrow` middleware and the button I use to trigger the tooltip is small then the content and the arrow is not properly aligned.

You can see the reproduction here: https://codesandbox.io/s/floating-ui-dom-arrow-positioning-issue-pgf2g

Here's a screenshot for you:
![image](https://user-images.githubusercontent.com/301700/148194294-b8a1e198-6530-4a1e-b154-68495a3cc272.png)

The library, when using `start` or `end` placement, tries to align the container to the start of the trigger which is not what a user wants if they have an arrow (as you can see in my reproduction).

Is this behavior expected? 

I'd love to work on a PR to fix it, but I don't want to spend time if this is intended behavior. I would expect one of these behaviors:

1. Arrow is aligned to the start of the trigger:
   ![image](https://user-images.githubusercontent.com/301700/148194466-6b72e7e9-ce7c-430a-817e-3e602d81542a.png)
2. Arrow is aligned to the middle of the trigger:
   ![image](https://user-images.githubusercontent.com/301700/148194524-d22c8adf-323a-4ca0-b279-749689b0865d.png)

**Comment by atomiks** [comment]
It's caused by the `TIP_EDGE_MARGIN`, you've given it a value of 16, which means it's at a minimum, 16px from the left edge at all times, resulting in the issue. Setting it to `0` fixes it (or a better value to handle the rounded corners).

**Comment by atomiks** [comment]
Something like this seems to work decently:

```js
    offset(({ reference, placement }) => ({
      mainAxis: TIP_WIDTH,
      crossAxis:
        reference.width / 2 < TIP_SIZE
          ? placement.endsWith("start")
            ? -TIP_WIDTH
            : TIP_WIDTH
          : 0
    })),
```

https://codesandbox.io/s/floating-ui-dom-arrow-positioning-issue-forked-hzg0f?file=/src/index.js

You'd check `TIP_HEIGHT` / `reference.height` for `left/right` placements if needed, too

**Comment by megawebmaster** [comment]
Well, your solution "kinda" works - it's still not really good for right/left cases. Anyway I feel a bit weird if I have to add offset for arrow padding - I'd expect the middleware to handle this case, so I can reason better about how I expect the floating item to appear.

I have worked a bit on a fork to see how I can make it great and transparent to the user. I also made sure we adjust only what we need (so a button that is slightly shorter than what popup needs causes just a bit of movement). I'm not sure how to handle the "shift" case though as clicking at the edges of the screen can still render out of the viewport...

Anyway: the code with my adjustments just works as I would expect it to: it adjusts the X/Y position of the floating element to better point with the arrow. This is especially visible with virtual elements :) Do you want to see the PR?

**Comment by megawebmaster** [comment]
Great: I just created the PR: https://github.com/floating-ui/floating-ui/pull/1496

I'm all in for avoiding automagic stuff: it makes the code less predictable. On the other hand if we want to support `padding` option in `arrow` middleware I think we should do so in a way that leaves no questions. That is why I propose the change :muscle: 

I'm really grateful for your insight and time you spent on my issue :rocket: It's a real pleasure to talk and work with people like you :muscle:
