### ISSUE TITLE
Can't perform a React state update on an unmounted component

### ISSUE THREAD

**Issue by mkomensu** [floating-ui/floating-ui#1494]
https://github.com/floating-ui/floating-ui/blob/ec1aabac66d138f3f5ab1c247b86b7fc0467084e/packages/react-dom/src/index.ts#L78

Hi,

I'm getting **Can't perform a React state update on an unmounted component**, when the component recreated!

The error comes from `setData`: `
    computePosition(reference.current, floating.current, {
      middleware: latestMiddleware,
      placement,
      strategy,
    }).then(setData);
`

**Comment by atomiks** [comment]
Do you have a repro? Interesting that the component can unmount during a promise microtask, but we'd probably need a flag like this

```js
useEffect(() => {
  let isMounted = true;            
  someAsyncOperation().then(data => {
    if (isMounted) setState(data); 
  })
  return () => { isMounted = false };
}, []);                              

```

**Comment by kristho91** [comment]
I get a similar error in v 0.4.3 . 
I think an isMounted check should be added to the beginning of the update method too, like this:

```
if (!isMounted.current || !reference.current || !floating.current) {
    return;
}
```

My issue originates from calling "update()" in setFloating

**Comment by atomiks** [comment]
I don't think that will change anything, `setData()` is somehow getting called after the component is unmounted which is already guarded with the check; you'll need to provide a repro
