### ISSUE TITLE
Export Map expansion?

### ISSUE THREAD

**Issue by Westbrook** [floating-ui/floating-ui#1497]
The use of `process.env.NODE_ENV` causes issues when leveraging the `core` package in no/low build environments. Would you be open to an expansion of the export maps to better support users in this context?

I could see either the addition of the `dev`/`production` listing for the `import` entry so that `production` could point directly to the `.min.js` files that already exclude this. Similarly, I think the `browser`/`node` listings would be similarly.

This does close some debugging options, so it might be useful to include some more build options, particularly a non-minified build without the use of `process.env.NODE_ENV`, but that involves a deeper touch to the overall repo management.

**Comment by Westbrook** [comment]
Possibly related to #1465

**Comment by atomiks** [comment]
Yeah a PR to improve this area is welcome. Alternatively, no/low build environments could import from the `.min` version without any debugging checks, but we need an alias plugin in the Rollup build so the import points to the minified `core` version too.
