### ISSUE TITLE
Ability to inject existing target ref

### ISSUE THREAD

**Issue by m7kvqbe1** [floating-ui/floating-ui#1501]
Thank you for all of your hard work on a wonderful library!

The old Popper interface allowed the consumer to inject their own target and floating element refs.

We have a `FloatingBox` component that wraps the hook and want to inject an external pre-existing ref for a target element (which comes from a prop). 

Is there a way to invert control of the ref to the consumer? I notice the arrow middleware does this. 

https://github.com/floating-ui/floating-ui/blob/5c07610beac68b380850d421bdc1a96681b49bb9/packages/react-dom/src/index.ts#L95

**Comment by m7kvqbe1** [comment]
No problem - i'll create a quick example later.

**Comment by atomiks** [comment]
See https://github.com/floating-ui/floating-ui/issues/1503#issuecomment-1011975726. Calling `reference` achieves this and doesn't have the `update()` drawback.

Added to the docs: https://floating-ui.com/docs/react-dom#external-reference
