### ISSUE TITLE
Allow possibility to use different reference on useFloating

### ISSUE THREAD

**Issue by mauroreisvieira** [floating-ui/floating-ui#1503]
On `usePopper`  we have an option to pass `referenceElement` and `popperElement` but in `useFloating` we don't have that option.

The `useFloating` is responsible to return the `refs` but in some cases is not possible to set the returned ref to an element, because that `referenceElement` is passed as a prop (anchor is outside of my component), but looking to the docs I saw that `useFloating` use `computePosition` that receive this two references as an argument. 

My solution is to use `computePosition` instead of `useFloating` but I will lose all functionalities provided by `useFloating`

**Comment by m7kvqbe1** [comment]
What a coincidence this is the exact same design niggle that I posted about earlier: https://github.com/floating-ui/floating-ui/issues/1501

**Comment by atomiks** [comment]
So you have a parent component which is setting the `ref` and passing that into a child component which is where `useFloating` is called? Can't you hoist `useFloating` to the parent component and pass `floating` (from `useFloating`) as a prop instead?

**Comment by mauroreisvieira** [comment]
What I have is something like that:

```tsx
const Dropdown = forwardRef(({
    anchorRef,
    flipModifierOptions = {
        enabled: true,
    },
    className,
    children,
}: DropdownProps, ref: React.RefObject<DropdownRef>) => {
    const wrapperRef = useRef<HTMLDivElement>(null);

    const { styles, forceUpdate, state } = usePopper(anchorRef.current, wrapperRef.current, {
        placement: 'bottom',
        modifiers: [
            {
                name: 'flip',
                enabled: flipModifierOptions?.enabled,
                options: {
                    fallbackPlacements: placements,
                },
            },
        ],
    });


    const handleClose = (): void => {
        if (onClose) onClose();
    };

    const onDocumentKeydown = (event: React.KeyboardEvent<HTMLDivElement>): void => {
        if (event.key === 'Escape') handleClose();
        event.stopPropagation();
    };

    const computedProps = {
        ref: wrapperRef,
        className: classNames(className, 'dropdown'),
        style: styles.popper,
        tabIndex: 0,
        onKeyDown: onDocumentKeydown,
    };

    // Make Popper's forceUpdate available for the consumer through ref
    useImperativeHandle(ref, () => ({
        forceUpdate: (): void => {
            if (forceUpdate) forceUpdate();
        },
    }));

    return (
        <div {...computedProps}>
            { children }
        </div>
    )
});
```

**Comment by atomiks** [comment]
So you'd do this:

```js
function Component({anchorRef}) {
  const { reference } = useFloating();

  useEffect(() => {
    reference(anchorRef.current);
  }, [anchorRef]);
}
```

Just need to make sure when `anchorRef.current` gets updated that the position can also be updated

**Comment by mauroreisvieira** [comment]
Perfect, thanks @atomiks
