### ISSUE TITLE
Popover that is aware of the viewport and doesn't exceed its height

### ISSUE THREAD

**Issue by emadabdulrahim** [floating-ui/floating-ui#1504]
Using floating-ui, is it possible to build a popover where its height doesn't exceed the viewport height? If so, could you highlight from a high-level point what'd it take to make that possible?

https://user-images.githubusercontent.com/7950797/149269126-60b74009-8a3d-49fc-aa15-ecd5fd772b60.mp4

Video from linear.app

**Comment by atomiks** [comment]
https://floating-ui.com/docs/size

**Comment by emadabdulrahim** [comment]
That must be a world record issue closing response. Much appreciated <3
