### ISSUE TITLE
ReferenceError: process is not defined

### ISSUE THREAD

**Issue by cupcakearmy** [floating-ui/floating-ui#1506]
Thanks for the awesome lib first :)

So I'm building a library and once published the code breaks because the compiled `esm` module of `core` is including an unchecked read on `process`, which is not defined if imported in the browser.
Any ideas/suggestions? Personally I think that an unchecked `process` in a compiled build is not the way to go, but I might be wrong there.

The error btw is in @floating-ui/core/dist/floating-ui.core.esm.js @L87. I'm using the `@floating-ui/dom` library.

**Comment by atomiks** [comment]
There's an open PR to better support low/no-build tooling setups: https://github.com/floating-ui/floating-ui/pull/1502

The current setup works in all major bundlers (webpack, Parcel, Vite, etc.) except for Rollup where you need to use the `replace` plugin like so (but this is done by the consumer, not e.g. your library which uses this lib as a dependency):

```js
plugins: [
  replace({
    'process.env.NODE_ENV': JSON.stringify(process.env.NODE_ENV),
  })
]
```

**Comment by cupcakearmy** [comment]
Unfortunately I can't get it to work with the PR. @atomiks 

There really should not be a `process` access in a production build for a browser library. As you [said yourself](https://github.com/floating-ui/floating-ui/pull/1502#pullrequestreview-853508847) this can be simply checked beforhand! Are you open for a PR?
