### ISSUE TITLE
Is popper.js v1 2kb or 3kb?

### ISSUE THREAD

**Issue by dilyanpalauzov** [floating-ui/floating-ui#1510]
https://popper.js.org says at the top “Weighs just **3 kB!**”.

Under “No compromises” is says “Still lightweight. Handling all of this complexity is still done in an efficient manner. The base Popper is only 2 kB minzipped.”

The inconsistent information about the size can raise the question, whether the remaining information on the website is correct.

**Comment by atomiks** [comment]
- `popper.js` (v1) was 7 kB minzipped and had no tree-shaking ability.
- `@popperjs/core` (v2) has a 2 kB "base" (or core without any features, `popper-base`), 3 kB when importing `popper-lite` (the tagline) and 7 kB when importing the full version (increased over time). That's the discrepancy between the two sizes.


[Floating UI](https://floating-ui.com) (Popper's successor) demonstrates its size/tree-shaking better on its homepage and is designed to be less misleading.

<img width="1184" alt="Screen Shot 2022-01-20 at 9 22 34 pm" src="https://user-images.githubusercontent.com/22450188/150320342-02fefa35-9eb2-4da6-94c0-b5bf90beaf2c.png">

**Comment by dilyanpalauzov** [comment]
Nevertheless the website cannot state at the same time, that the size is 2kb and 3kb, without elaborating further on the discrepancy.
