### ISSUE TITLE
Update popper homepage with deprecation notice.

### ISSUE THREAD

**Issue by janwirth** [floating-ui/floating-ui#1511]
Floating-UI is great!

It could have saved me some time if there was a note of where to obtain the latest version of the library rather than pointing users to the now stale popperjs installation instructions. Thanks!

**Comment by FezVrasta** [comment]
We are planning to add a notice, but keep in mind Popper v2 is in a very mature and stable phase and it's perfectly suitable for production projects.

**Comment by atomiks** [comment]
Popper v2 is still supported and will be getting bugfixes. It won't be receiving features though due to size/architecture constraints. So it depends on what you view as "deprecated". A lot of big projects are using it and will for a while!

**Comment by janwirth** [comment]
Okay, it would be good to have a hint towards floating-ui because it is the better solution for many problems (like in my case)
