### ISSUE TITLE
Missing ) in documentation

### ISSUE THREAD

**Issue by dilyanpalauzov** [floating-ui/floating-ui#1518]
https://popper.js.org/docs/v2/constructors/ misses a `)`:
![Screenshot_20220122-161040_Firefox](https://user-images.githubusercontent.com/4992947/150641846-0374e840-01d3-4715-a4a2-4c03047884a5.png)

**Comment by FezVrasta** [comment]
For this kind of issues I think a pull request with the fix is the most effective way to have them addressed. I don't think tracking them in the issues tracker is going to help.
