### ISSUE TITLE
External floating with reuse of the ref

### ISSUE THREAD

**Issue by Gesma94** [floating-ui/floating-ui#1519]
Hi. I'm trying to create a reusable component that uses the flaoating-UI package, and that does not create intermediate `<div>` element. Please, take a look at this example:
https://codesandbox.io/s/staging-violet-nuj9f?file=/src/App.tsx

As you can see, the `<ExternalFloating>` component expects `props.children` to be a function, function that has the `floating` function and the style as parameters. As you can see, it works pretty good! And, the difference with respect to `<Floating>` component is that no middle `<div>` is created. GREAT.

BUT, here's come the problem: when I use the `<ExternalFloating>`, I need to pass `floating` directly to the `ref` props of the `<div>`.
But, I need the ref of the inner `<div>` to be available in the `<App>` component.. So, like in the commented part of it.
Problem is: if I use that, therefore calling `floating(node)`, it ends up into a infinite loop. So, BE AWARE: if you change the uncommented/commented children, the example will crash :)

**Comment by atomiks** [comment]
The problem (I think) is you're creating a new element on each render, so React keeps calling the `ref` callback function, which calls `update()` in `useFloating` internally, and so on, but it needs to remain stable across renders.

In `ExternalFloating` you can memo the children call:

```js
return useMemo(
  () => children(floating, {position: strategy, top: y ?? '', left: x ?? ''}),
  [floating, strategy, x, y, children]
);
```
