### ISSUE TITLE
Appears to cause "act" warnings in React during testing

### ISSUE THREAD

**Issue by silvenon** [floating-ui/floating-ui#1520]
Hi! Popper v2 had problems with `act` warnings during React testing (floating-ui/react-popper#350), so I wanted to see whether Floating UI has them as well, and it appears it does. I created a minimal [demo branch](https://github.com/silvenon/repro/tree/floating-ui-act-warnings) in my repo where you can reproduce this. Let me know if I'm doing something wrong.

```
Warning: An update to App inside a test was not wrapped in act(...).

When testing, code that causes React state updates should be wrapped into act(...):

act(() => {
  /* fire events that update state */
});
/* assert on the output */

This ensures that you're testing the behavior the user would see in the browser. Learn more at https://reactjs.org/link/wrap-tests-with-act
```

**Comment by atomiks** [comment]
I don't think this is something that can be "fixed" by this lib, and needs to be handled by the consumer. But if it can that would be cool. 

`computePosition` is an async function, so `setData()` is called in a promise microtask, which is executed after the test finishes, causing the warning.

If you're using RTL, you use `await waitFor(() => expect(...))` calls after rendering the component, or when causing state updates for Floating UI.

Letting the queue be flushed before the test can finish is another way:

```js
render(<App />);
await act(async () => await null);
```

**Comment by silvenon** [comment]
Thanks for explaining the limitation 🙂  I'm closing this then.

**Comment by atomiks** [comment]
@silvenon I think it would be worth adding to the documentation if you're up for a PR?

**Comment by silvenon** [comment]
👍 💪
