### ISSUE TITLE
flip does not document the mainAxis and altAxis options

### ISSUE THREAD

**Issue by dilyanpalauzov** [floating-ui/floating-ui#1523]
https://github.com/floating-ui/floating-ui/pull/1095/ adds the `mainAxis` and `altAxis` options to the flip modifier.

https://popper.js.org/docs/v2/modifiers/flip/ does not explain what are these options good for.

**Comment by FezVrasta** [comment]
@atomiks correct me if I'm wrong, but I think these two options were only available on Popper 1.x, they were removed in 2.x

**Comment by atomiks** [comment]
These are v2.x only, so the documentation is missing them

**Comment by atomiks** [comment]
Can you make this issue at https://github.com/floating-ui/popper.js.org? For documentation, issues in this repo should now pertain to Floating UI. Thanks!
