### ISSUE TITLE
Website not working in Firefox

### ISSUE THREAD

**Issue by sedubois** [floating-ui/floating-ui#1524]
Congratulations and thank you for these libraries!

The [website](https://floating-ui.com/) demos (such as Placement, Shift, Flip, Size,...) and [tutorial](https://floating-ui.com/docs/tutorial) don't work in my Firefox 96.0.3 (64-bit) (but they work in Chrome). There are console errors such as:

![Screenshot 2022-02-03 at 13 51 42](https://user-images.githubusercontent.com/4217871/152346366-d857f86c-1dff-4bc7-b985-4d69f6d3249e.png)

Is Floating UI ready for production or is Popper.js still the official stable solution?

**Comment by atomiks** [comment]
The site works fine for me in FF. Do you have an extension or something else blocking the scripts from loading?

**Comment by sedubois** [comment]
🤦‍♂️ Yes, that's it. I just forgot to think. With so many browsers open, I had not realised I was using another browser when comparing with the Popper documentation. Sorry for the trouble.
