### ISSUE TITLE
[Floating UI] [React DOM] `refs` and `middlewareData` are unstable references

### ISSUE THREAD

**Issue by valtism** [floating-ui/floating-ui#1532]
Reproduction: https://stackblitz.com/edit/floating-ui-unstable-references?file=src/Floating.js

Uncomment either `refs` or `middlewareData` in the `useMemo` dependency list and the application will hang as it begins to render endlessly in a loop.

I think both of these properties could be exposed in a stable way using `useMemo` to allow them to be used as a stable reference (e.g. in the case to be passed via context)

I understand that they can be left out of the dependency list, but it would be nice to use them in a way that doesn't upset the hooks linter.

**Comment by atomiks** [comment]
`refs` can be memo'd but not sure if `middlewareData` can as it's part of the `data` object dependency which is already passed in the `useMemo` return. Haven't looked at this deeply but why is it causing an infinite loop without using `memo`?

**Comment by atomiks** [comment]
I need to document this but you can't do `ref={mergeRefs([...])}` inline. You need to memo this value:

```js
const memoRef = useMemo(() => mergeRefs([ref, floating]), []);
```

Then there will be no infinite loop then with the current package version. I did memo `refs` though in the linked PR, but idk how to do it for `middlewareData`, you'd probably need to make a `deepEqual` check

**Comment by valtism** [comment]
Oh really? That's an interesting aspect I hadn't thought about. Thanks for memoing the refs.
