### ISSUE TITLE
::after pseudo element as a tooltip

### ISSUE THREAD

**Issue by thousandsofraccoons** [floating-ui/floating-ui#1533]
Thank you

**Comment by atomiks** [comment]
I'm not sure I understand your question. Adding `mouseenter` and `mouseleave` events don't cause perf issues with lots of elements (which are equivalent to "hover" in CSS). `scroll` and `resize` however will, if element is not currently visible, is that your issue? You just need to make sure you aren't listening while the floating element is not visible.
