### ISSUE TITLE
Issues with initial calculations with top-* in Vue onMounted method

### ISSUE THREAD

**Issue by quantuminformation** [floating-ui/floating-ui#1536]
I have an issue with vue 3 and the top-start option

```js
  const { x, y } = await computePosition(referenceElement, tooltipEl, {
        placement: "top-start",
        strategy: "fixed",
      });
      Object.assign(tooltipEl.style, {
        left: `${x + 20}px`,
        top: `${y - 1 * TOOLTIP_DISTANCE_PX}px`,
      });
      tooltipEl.classList.add("arrow_down");
      tooltipEl.classList.remove("arrow_left");
```

the issue is wrapped in a Vue3 `onMounted(() => {` and on the first render, the `top-start` (also just `top`) is way off, however on the next scroll or resize, the position is correct. However ` placement: "right-end",` works fine first time and continues to work.

**Comment by atomiks** [comment]
Is the value of `{referenceEl|tooltipEl}.getBoundingClientRect()` correct before you call `computePosition()`? This type of thing is never an issue with the function but rather a timing problem where the reference/floating element is not on the DOM (to be measured) when you call it.

**Comment by quantuminformation** [comment]
If I wait 100ms, the problems disappear but terrible for the user exp. In the onMounted and with a debugger in it, the Vue UI doesn't look complete at all, missing background and stuff, its just confusing cause the right-end works perfect even with the missing background stuff. Will get back to you soon.

**Comment by FezVrasta** [comment]
Could you try to call it from a `requestAnimationFrame` maybe?

**Comment by atomiks** [comment]
Closing as it's a timing problem with the framework rather than this lib, however, adding docs on this would be useful I think
