### ISSUE TITLE
[Popper] The required properties for custom modifiers are typed as optional in the `Options` interface

### ISSUE THREAD

**Issue by m4theushw** [floating-ui/floating-ui#1537]
_From https://unpkg.com/browse/@popperjs/core@2.11.2/lib/types.d.ts_

```ts
export declare type Options = {
    placement: Placement;
    modifiers: Array<Partial<Modifier<any, any>>>;
    strategy: PositioningStrategy;
    onFirstUpdate?: (arg0: Partial<State>) => void;
};
```

According to the TypeScript declaration, each `Modifier` is wrapped in `Partial` making every key optional. This doesn't match the [docs](https://popper.js.org/docs/v2/modifiers/#example-modifier) nor the validation which require some attributes to be defined.

### Context

We have a React component built with `createPopper`. Since the prop-types are automatically generated by reusing the members of the `Options` interface, our `modifiers` prop misses the correct checks.

**Comment by atomiks** [comment]
We have now released [Floating UI v1](https://floating-ui.com/docs/motivation), the successor to Popper.

Don't worry, Popper 2 will **continue to receive new releases** with bug/security fixes provided by external contributors, but development of new features is not continuing at this point. We are also closing bugs related to it as us maintainers are focusing our energy on tracking issues with Floating UI, however you are welcome to create new pull requests to fix bugs in Popper, which we will review and merge, as many packages (such as MUI, Bootstrap, etc) still rely on it. 

Thanks!
