### ISSUE TITLE
[BUG] Using virtual element as a reference results in an error

### ISSUE THREAD

**Issue by petercpwong** [floating-ui/floating-ui#1558]
**Package:** @floating-ui/react-dom
**Version:** 0.5.0

**Description of the bug:**
Starting in version 0.5.0, using a virtual element as a reference results in the following error:
 `Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.`

**Code Sandbox:**
https://codesandbox.io/s/sad-saha-x55ni4

**Comment by petercpwong** [comment]
![image](https://user-images.githubusercontent.com/1303285/155878537-d58e50e4-d975-4713-a82e-b3f8d92e351d.png)

My `@floating-ui/dom package` is also on version 0.3.1 but I'm still getting the error locally.

I've also updated the codesandbox to explicitly use version 0.3.1 and the bug is still there.

**Comment by atomiks** [comment]
Ugh you're right, the `core` package had to be updated but wasn't. Sorry.

**Comment by petercpwong** [comment]
Can confirm `@floating-ui/core@0.5.1` fixes the issue. Thanks for looking into this so quickly!
