### ISSUE TITLE
`shift` not working properly with `padding` on right side

### ISSUE THREAD

**Issue by Gesma94** [floating-ui/floating-ui#1561]
Hi. I'm using `floating-dom` on my REACT application. I'm using 4 middlewares, including `shift` one.
Here's a working sandbox: https://codesandbox.io/s/morning-dream-q0qbic?file=/src/App.tsx

### STEP TO REPRODUCE

1. Click on the green `<div>`, the tooltip will open and looks good.
2. Click again, tooltip will close.
3. Resize the region were the example is shown, so that the `shift` kicks in.
4. Click again on the green `<div>`: notice how on the left side, `shift` has "padded" correctly, but NOT on the right side (look image).

![image](https://user-images.githubusercontent.com/46707463/156383651-05823bf3-5388-48f6-9b9a-2cf0d69a55b4.png)

Of course, the firsts two steps are just to see that Tooltip is working ok.

### MANUAL "FIX"
To fix the issue, I just need to set `right: 4px` on the floating element. But, that should be done ONLY when the `shift` middleware fails.. So, I guess this could be included in floating-ui itself.

**EDIT:** I'm pretty sure that, having the very long text influence this behavior.

**Comment by atomiks** [comment]
The issue is the size of the tooltip is not affected by `shift`. The simplest fix is to specify `max-width:  calc(100vh - 8px)` on the tooltip (8px is for each 4px padding side)

https://codesandbox.io/s/elated-dream-hpm7wf?file=/src/App.tsx

**Comment by Gesma94** [comment]
Your proposal fix the issue, that's great!
If I may, I suggest you to add a small paragraph in the documentation, and add this: I suppose that this "problem" could be faced by some more people.
