### ISSUE TITLE
Types are only exported from `@floatingui/core`

### ISSUE THREAD

**Issue by ling1726** [floating-ui/floating-ui#1562]
Is this intentional ?

For library developers, it's quite useful to have access to types but only the exact dependency necessary. I see that all middlewares are defined in core and re-exported in the dom package, but to be able to use the package those types are only avaiable in the core package.

This results in the need to take a dependency on both the core package and the dom package, and gets kind of confusing with middleware imports because they can actually be imported from either package.

**Comment by atomiks** [comment]
In the latest version most of the types are now re-exported from core except the options for middleware. Which types are you missing? You can still extract the options type using e.g. `Parameters<typeof offset>[0]`

**Comment by ling1726** [comment]
Ah yeah, I made this issue incorrectly, as I still had the experience from the earlier versions. Sorry about that.

I'll close the issue
