### ISSUE TITLE
What's a stable / unstable reference?

### ISSUE THREAD

**Issue by aaroniker** [floating-ui/floating-ui#1569]
Can't find an explanation of a stable / unstable reference mentioned here:

https://floating-ui.com/docs/react-dom#stable-ref-prop

I'm getting the following error (sometimes, not always): `ResizeObserver loop limit exceeded` while using Floating UI w/ conditional rendered React Portals.

**Comment by atomiks** [comment]
It means the value remains the same across renders vs. an inline value like `ref={node => ...}`. That error is not related to a stable reference though.

**Comment by atomiks** [comment]
I updated the React DOM docs to be a little clearer about this.
