### ISSUE TITLE
hitting process.env variable after rollup build

### ISSUE THREAD

**Issue by thepassle** [floating-ui/floating-ui#1575]
I'm using `@floating-ui/dom` for a project. During development, everything works as expected, however, after I run my rollup build (pretty straightforward rollup build, with only the `nodeResolve` plugin enabled), I run into the following error:

<img width="463" alt="image" src="https://user-images.githubusercontent.com/17054057/157431653-60a8753b-025c-474f-a164-daec1d96ce98.png">

Which, when inspected, leads to the following code:

```js
if("production"!==process.env.NODE_ENV&&(null==a&&console.error(["Floating UI: `platform` property was not passed to config. If you","want to use Floating UI on the web, install @floating-ui/dom","instead of the /core package. Otherwise, you can create your own","`platform`: https://floating-ui.com/docs/platform"]
```

Interestingly, this error only shows up after the build (which, again, is a pretty standard rollup build). I was surprised to see modern ESM packages still checking for node globals, which then cause breakage in the browser. I had hoped as a community we'd walked away from such practices by now but it seems I'm wrong 😄 

It seems like rollup picks the `default` import from the following export map as [defined in `@floating-ui/core`](https://unpkg.com/@floating-ui/core@0.6.0/package.json)

```json
"exports": {
    ".": {
      "import": {
        "development": "./dist/floating-ui.core.esm.development.js",
        "production": "./dist/floating-ui.core.esm.min.js",
        "default": "./dist/floating-ui.core.esm.js"
      },
      "require": "./dist/floating-ui.core.cjs"
    },
    "./package.json": "./package.json"
  },
```

Which indeed contains the `process.env` check: 
![image](https://user-images.githubusercontent.com/17054057/157433025-6cdc981c-2f6f-4bb8-a811-70309db6fd90.png)

The `./dist/floating-ui.core.esm.development.js` and `./dist/floating-ui.core.esm.min.js"` bundles (`development` and `production` respectively), indeed do _not_ contain the `process.env` check

**Comment by atomiks** [comment]
You need to select one of the exports for Rollup so it doesn't use the default import.

<img width="653" alt="Screen Shot 2022-03-09 at 10 54 57 pm" src="https://user-images.githubusercontent.com/22450188/157437120-46d9cc6d-98f7-4b81-aca9-2955c5642a9e.png">

**Comment by thepassle** [comment]
As a user that doesn't really make sense to me though. For my production build, I have to set the `exportConditions` to _development_? I also wonder what impact that will have on other packages that I might use. 

Additionally, as a user, I'm surprised to see no `process.env` related errors during development, and then in my production build run into `process.env` related errors. Especially when its: `process.env.NODE_ENV !== "production"`, which in the production build will never be true.

**Comment by atomiks** [comment]
> For my production build, I have to set the exportConditions to development?

No you'd select whichever one is correct.

```shell
NODE_ENV=production npx rollup -c
NODE_ENV=development npx rollup -c
```

> I also wonder what impact that will have on other packages that I might use.

Maybe "default" should also be added at the end. In your Rollup config you'd now just do this:

```js
nodeResolve({
  exportConditions: [process.env.NODE_ENV, 'default']
});
```

> Additionally, as a user, I'm surprised to see no process.env related errors during development, and then in my production build run into process.env related errors.

I don't know why you're not getting it in dev in the browser, because the default import will always use that code 🤷, likely something in your setup/config.

**Comment by thepassle** [comment]
> I don't know why you're not getting it in dev in the browser, because the default import will always use that code 🤷, likely something in your setup/config.

I'm just using a pretty plain dev server that uses rollups node-resolve plugin for resolving, and rollup for bundling, so it's not like I'm doing something very unconventional here.

I've also been able to avoid having to use `NODE_ENV` shenanigans in my project so far, so I'd like to not have add it at this point 🙂  Either way, I've been able to work around it by replacing the `process.env` check in my rollup build, but as a consumer of this package with a very low-tooling setup the experience wasn't straightforward and somewhat confusing; do with that feedback as you will. Thanks for your efforts on this package, however, it is a very nice library indeed.

**Comment by thepassle** [comment]
> The checks serve an important purpose - there are useful logging/messages (and even an infinite loop throw) when in development mode. By just using minified/production/browser packages, you're missing out on a good development experience.

Im sure this is true for more advanced usecases
