### ISSUE TITLE
Wrong position with the strategy fixed and containing block

### ISSUE THREAD

**Issue by chudzikm** [floating-ui/floating-ui#1577]
In my project, I have a stategy fixed and everything works fine until 2.11.0 version of Popper. The position of shown element is wrong, because it doesn't take into account that the parents of the element can be a containing block. 

**Example with the bug** 
https://codesandbox.io/s/popper2-bug-wrong-position-csbhq5
<img width="387" alt="Przechwytywanie" src="https://user-images.githubusercontent.com/60264992/157894680-1a9e2cdd-539b-4d92-86f5-44611a59f723.PNG">

**The problematic commit**
I figured out that that problematic is the commit #1398 (adaptive option with fixed strategy on mobile).
`const offsetY =
        isFixed && win.visualViewport
          ? win.visualViewport.height
          : // $FlowFixMe[prop-missing]
            offsetParent[heightProp];`
` const offsetX =
        isFixed && win.visualViewport
          ? win.visualViewport.width
          : // $FlowFixMe[prop-missing]
            offsetParent[widthProp];`

**Solution**
When I add `offsetParent === win` to the conditions, everything works fine again.

**Comment by atomiks** [comment]
> When I add offsetParent === win to the conditions, everything works fine again.

To where? A PR would be great!

**Comment by chudzikm** [comment]
> To where? A PR would be great!

I added PR #1579

**Comment by atomiks** [comment]
Fixed in `@popperjs/core@2.11.3`

**Comment by chudzikm** [comment]
Thank you.
