### ISSUE TITLE
popper在超出部分没有被隐藏

### ISSUE THREAD

**Issue by parrot-designa** [floating-ui/floating-ui#1581]
https://codesandbox.io/s/fast-paper-1ukxcl?file=/src/App.js

<img width="755" alt="image" src="https://user-images.githubusercontent.com/77631518/158020162-43ba5a19-7143-46c3-8dc8-3b1f76c0cb19.png">

**Comment by parrot-designa** [comment]
I don't know if this is a bug.I wonder if Popperjs's author  could tell me

**Comment by atomiks** [comment]
Hi, it's not a bug. The tooltip doesn't get clipped by the container the reference element is in, so it can appear detached as shown. You likely want to use the `hide` modifier in some form in this situation.
