### ISSUE TITLE
Update arrow position manually

### ISSUE THREAD

**Issue by yyywork** [floating-ui/floating-ui#1589]
Hi, I was trying to add popper.js@2.6.0 on my project,
I attached the tooltip to header menu,
but the arrow misplaces when there is item in shopping cart like the demonstration image,
the tooltip is for the TERM tab,
but it moves below the cart because the text content is different from cart tab,
is there any way to update the arrow position manually?
Thank you!
![image](https://user-images.githubusercontent.com/89794192/159228710-0e786944-23c3-416d-a15d-38a76a8c7aeb.png)

**Comment by FezVrasta** [comment]
Thank you for your issue.

Unfortunately I can't answer to all the reported issues without a little help from you.
Please, make sure to follow the **issues template** when you submit a new issue, in this way I will already have all the informations needed to understand the problem and help you with it.

I'm closing this issue for now, but feel free to open a new one making sure to follow all the instructions!

Thank you for your understanding.
