### ISSUE TITLE
[DOM] Element position doesn't get computed properly when `iframe` gets scaled

### ISSUE THREAD

**Issue by seahindeniz** [floating-ui/floating-ui#1594]
I have an element inside an iframe, and I'm trying to compute its position from the parent window. However, when I give `transform: scale(2)` to iframe element, scale doesn't get counted.
https://codesandbox.io/s/floating-ui-dom-template-forked-gz4whh?file=/src/index.js

This is how the tooltip gets rendered:
<img width="402" alt="image" src="https://user-images.githubusercontent.com/5789670/160128684-b39ec960-fb47-470d-adca-37a5613c5f2f.png">

Instead, I was expecting something like this:
<img width="402" alt="image" src="https://user-images.githubusercontent.com/5789670/160128841-f7ad2c15-d93f-4e49-bc7c-d5f5cd1d4e0b.png">

**Comment by seahindeniz** [comment]
@atomiks as a solution, I think if we can pass an external/additional scale value (like passing an offset value) (`{ scaleX: number, scaleY: number }`) somehow which can be passed to the [getBoundingClientRect](https://github.com/floating-ui/floating-ui/blob/master/packages/dom/src/utils/getBoundingClientRect.ts#L6) utility function to be included in the calculations, it could solve the problem. But I'm not 100% sure if this is a good approach, of course.

Something like this:
```ts
import type {ClientRectObject, VirtualElement} from '@floating-ui/core';
import {isElement, isHTMLElement, isLayoutViewport} from './is';
import {round} from './math';
import {getWindow} from './window';

type ExternalScaleType = {
  x: number,
  y: number,
}

export function getBoundingClientRect(
  element: Element | VirtualElement,
  includeScale = false,
  isFixedStrategy = false,
  externalScale?: ExternalScaleType
): ClientRectObject {
  const clientRect = element.getBoundingClientRect();

  let scaleX = 1;
  let scaleY = 1;
  const externalScaleX = externalScale?.x || 1;
  const externalScaleY = externalScale?.y || 1;

  if (includeScale && isHTMLElement(element)) {
    scaleX =
      element.offsetWidth > 0
        ? round(clientRect.width) / element.offsetWidth || 1
        : 1;
    scaleY =
      element.offsetHeight > 0
        ? round(clientRect.height) / element.offsetHeight || 1
        : 1;
  }

  const win = isElement(element) ? getWindow(element) : window;
  const addVisualOffsets = !isLayoutViewport() && isFixedStrategy;

  const x =
    ((clientRect.left + (addVisualOffsets ? win.visualViewport.offsetLeft : 0)) /
    scaleX) * externalScaleX;
  const y =
    ((clientRect.top + (addVisualOffsets ? win.visualViewport.offsetTop : 0)) /
    scaleY) * externalScaleY;
  const width = (clientRect.width / scaleX) * externalScaleX;
  const height = (clientRect.height / scaleY) * externalScaleY;

  return {
    width,
    height,
    top: y,
    right: x + width,
    bottom: y + height,
    left: x,
    x,
    y,
  };
}
```

**Comment by atomiks** [comment]
It's funny how bloated that function is becoming 🤣  there are like 5 hacks written into it at this point. But yeah, I'm assuming something like that will work.

**Comment by seahindeniz** [comment]
Yes 🙂 But I can see that each solves a problem related to scale and offset issues and seems like they are at least a must to have. Maybe separating them into a function pipeline would be more clear

**Comment by cvlmtg** [comment]
ok, I think I've been able to make a PR with the the fix 😬

**Comment by jperterm** [comment]
Hi, I just wanted to mention that I have the same issue with scaling. I get extra x-/y-shifting and the higher the position of the context elements the higher is  the extra x-/y-shifting.

It seems that this use-case often comes with sections of a webapp that have a scaling feature. From my side an opportunity to feed the `computePosition` function with x-/y-scaling numbers is sufficient as I know where those scalings are applied. But there may be others cases for which it is not.

**Comment by Blackfaded** [comment]
I have the same issue. In Scaled Elements the element shifts. The more on the right, the more it shifts

**Comment by atomiks** [comment]
The latest release of `@floating-ui/dom` (1.0.8) fixes two separate bugs with transforms, but it doesn't fix this particular one with iframes. (I have tried to fix this issue btw, but didn't reach a solution)

Regarding transforms in general:

If your floating element has a transform, this is not "negated". The floating element is positioned via layout, and a transform you apply in the CSS happens after the positioning is done. So if you scale or translate the floating element, the positioning doesn't adjust for it (which is usually a good thing especially with animations). Detection of clipping is also done via layout (which now works properly with scaling — but if the element is transformed it may appear to detect the overflow at the wrong point because detection is done via layout boxes, not accounting for transforms. This may be tricky to handle but please open a PR if you get a solution).

You can write custom middleware to handle more complex cases of transforms if needed though, especially now with these fixes in preventing other issues. For example this one handles iframe positioning in general: https://github.com/floating-ui/floating-ui/issues/1711

**Comment by atomiks** [comment]
Okay so at this point, scale issues are killing me 🥲, there were 5 releases (1.0.8-1.0.12) fixing various issues with transform/`scale`, but I did find a solution to this iframe issue with the `getScale` function we now have. 

Apply it to these values as @seahindeniz originally suggested:

https://github.com/floating-ui/floating-ui/blob/99d187876a42fbd7057952d3b273c0978d562770/packages/dom/src/utils/getBoundingClientRect.ts#L28-L37

```js
  const iframe = element.ownerDocument?.defaultView?.frameElement;
  const iframeScale = iframe ? getScale(iframe) : {x: 1, y: 1};

  x *= iframeScale.x;
  y *= iframeScale.y;
  width *= iframeScale.x;
  height *= iframeScale.y;
```
