### ISSUE TITLE
Distribute License File

### ISSUE THREAD

**Issue by michaelbull** [floating-ui/floating-ui#1624]
Hi. I am using your package in conjunction with [`license-webpack-plugin`](https://www.npmjs.com/package/license-webpack-plugin). This plugin automatically fetches licensing information from packages and bundles all licenses into a single file for end-users. It does this by searching for the LICENSE file in your shipped package. For commercial reasons it's critical that I make your license available to my end-users.

Please can you consider shipping the LICENSE to the various npm packages via the `files` section of your `package.json`?

I have seen prior discussion in #546 however this was closed without ever including the LICENSE with the various shipped packages on npm.

Thanks in advance.

**Comment by atomiks** [comment]
The license in the monorepo root needs to be copied into every package

**Comment by michaelbull** [comment]
It does read from `package.json` to understand the license type, but not the license text.

Your license states the following:

> The above copyright notice and this permission notice shall be included in all
> copies or substantial portions of the Software.

Right now you are distributing copies of the software (+ substantial portions with the packages) onto npm and are violating the very license terms by not coupling the LICENSE file with them.

For commercial reasons I need to ship all LICENSE texts for third-party libraries I use with the product that I am responsible for shipping to end-users, so I have had to manually copy the LICENSE file from this repo into mine and ship it manually.

**Comment by atomiks** [comment]
Is that the default for MIT licenses? Is there a license that is "do whatever the hell you want and don't include this license because it will increase your bundle size for no reason"? 😋

**Comment by FezVrasta** [comment]
license collections are usually saved on a separate static text file and linked from the web app so they don't increase the bundle size.

**Comment by michaelbull** [comment]
> Is that the default for MIT licenses? 

Yes. Given the code in this repository is licensed as MIT, you have stated that you will include the above copyright notice in all copies of the software/significant portions.

> license collections are usually saved on a separate static text file and linked from the web app so they don't increase the bundle size.

Yes, this is what I'm achieving with the `license-webpack-plugin`. I'm not suggesting to add the LICENSE text to the minified distribution files, just to the npm package itself.
