### ISSUE TITLE
Custom onFocus not triggered

### ISSUE THREAD

**Issue by blurbyte** [floating-ui/floating-ui#1625]
Hello! I was building **Tooltip** component according to [official example](https://codesandbox.io/s/winter-tree-wmmffl?file=/src/Tooltip.tsx). It seems when passing custom _onFocus_ (and _onBlur_ for that matter) event handler, it's not triggered. I assume props may not get merged correctly? For _mouseEnter_ it works as expected.

Codesandbox: https://codesandbox.io/s/nice-boyd-jn2dmx

**Comment by atomiks** [comment]
It looks like the examples should pass the props into the prop getter from `children.props`:

```js
cloneElement(
  children,
  getReferenceProps({ ref: reference, ...children.props })
)
```

**Comment by atomiks** [comment]
I've updated all the tooltip examples with a better children type (no need for `isValidElement`) and the props spreading. I'm going to update all the sandboxes with this pattern now + show the ref merging as well.

**Comment by atomiks** [comment]
I don't know why TypeScript doesn't recognize `ref` on `children`, but if you want to prevent the component from stealing the ref, this works:

```js 
import mergeRefs from 'react-merge-refs';

const referenceRef = useMemo(
  () => mergeRefs([reference, children.ref]),
  [reference, children.ref]
);

getReferenceProps({ ref: referenceRef });
```

**Comment by blurbyte** [comment]
Awesome 🙏! Btw great library.
