### ISSUE TITLE
[Floating-UI] keyboard navigation works weird with react-virtual

### ISSUE THREAD

**Issue by ChiaJune** [floating-ui/floating-ui#1629]
I want to integrate react-virtual into Autocomplete, but keyboard navigation can't make react-virtual scroll. 
Can you help me to see what I did wrong? 
Thank you! 
Here is the demo:
[https://codesandbox.io/s/sharp-flower-8jfvwv?file=/src/App.tsx](https://codesandbox.io/s/sharp-flower-8jfvwv?file=/src/App.tsx)

**Comment by atomiks** [comment]
My guess is the way the `listRef.current` gets assigned indices is being offset somewhere incorrectly.

```js
ref(node) {
  listRef.current[virtualRow.index] = node;
},
```

This probably needs to be "cleared" in some way to match the virtualization logic.

Possibly this needs to not filter out "nullish" values to keep the virtualized indices in tact? https://github.com/floating-ui/floating-ui/blob/e35ae9c5b4d6766fb82aa9ff7be3776a5b113d95/packages/react-dom-interactions/src/hooks/useListNavigation.ts#L103-L105

**Comment by ChiaJune** [comment]
Thank you very much
