### ISSUE TITLE
Does package this work with SSR?

### ISSUE THREAD

**Issue by karltaylor** [floating-ui/floating-ui#1639]
I'm trying to use this package in a prerendered preact app deployed onto vercel but I've hit this error and now I'm at a bit of a loss as to where to look next.

```
Unable to read file: /vercel/path0/src/node_modules/@floating-ui/core/dist/floating-ui.core.esm.js
14:22:18.595 |  
14:22:18.595 | ReferenceError: regeneratorRuntime is not defined
14:22:18.595 | method: null
14:22:18.595 | at: /vercel/path0/src/node_modules/@floating-ui/core/dist/floating-ui.core.esm.js:88:21
14:22:18.596 |  
14:22:18.596 | Source code:
14:22:18.596 |  
14:22:18.596 |  
14:22:18.596 | This is most likely caused by using DOM or Web APIs.
14:22:18.597 | Pre-render runs in node and has no access to globals available in browsers.
14:22:18.597 |  
14:22:18.597 | Consider wrapping code producing error in: 'if (typeof window !== "undefined") { ... }'
14:22:18.598 |  
14:22:18.598 | Alternatively use 'preact build --no-prerender' to disable prerendering.
```

Works fine if I don't pre-render, is this something I need to fix on my side?

**Comment by atomiks** [comment]
This isn't an SSR issue but a Babel issue. I have no idea why it says it's "most likely caused by using DOM or Web APIs", it's caused by computePosition being an `async` function. Adjust your Babel `targets` to only include browsers that support async functions and the error will go away

**Comment by karltaylor** [comment]
@atomiks Thanks for the quick reply and thanks for the explanation. I fixed my `targets` and worked fine 👍
