### ISSUE TITLE
Dropdown reopens when `useClick` and `referencePointerDown` are used in combination

### ISSUE THREAD

**Issue by dwoznicki** [floating-ui/floating-ui#1641]
### Current behavior
When I set `referencePointerDown: true` in the `useDismiss` props and try to close a dropdown by re-clicking the reference element, the dropdown quickly closes then reopens. You can see this behavior by clicking the "File" button in this sandbox. https://codesandbox.io/s/nice-sky-pz64p0

I imagine that what's happening here is that when I click, the `onPointerDown` event is firing first, causing the dropdown to close, then the `onClick` event is firing, causing the dropdown to open again.

### Expected behavior
The dropdown should not reopen when I click the reference element to close it.

### Possible solutions
We could change the `referencePointerDown` event to be `onClick` instead of `onPointerDown`, then compose the click handler to close the dropdown. I'm not sure what the implications of this would be for mobile, though.

Another option would be to set a flag on pointer down that the click handler could check, and if present, skip the `onOpenChange` call.

**Comment by atomiks** [comment]
Woops I updated that example for `v0.3`, but the `toggle` boolean for `useClick` should be based on the `nested` value: `useClick(context, {toggle: !nested})`. This should achieve what you want.

**Comment by dwoznicki** [comment]
Cool, looks like that does the trick. Is the `toggle` prop stable enough to be documented yet?

**Comment by atomiks** [comment]
It's documented here: https://floating-ui.com/docs/useClick#toggle

This library (`react-dom-interactions` not the main positioning library) is still young though. There's a lot of work to do on it 😄

**Comment by dwoznicki** [comment]
Aha, that's funny. I just had a version of that page open that had `enabled` and `pointerDown`, but no `toggle`. Then I refreshed and `toggle` showed up. I must not have reloaded that page for a while.

For future reference, I changed

```javascript
useInteractions([
    useClick(context),
    useDismiss(contenxt, {referencePointerDown: true})
]);
```

to

```javascript
useInteractions([
    // Typescript doesn't recognize the `toggle` prop on my current version.
    // @ts-ignore
    useClick(context, {toggle: true}),
    useDismiss(contenxt, {referencePointerDown: false})
]);
```
