### ISSUE TITLE
Can't install floating-ui in Codesandbox

### ISSUE THREAD

**Issue by jonathanbutler7** [floating-ui/floating-ui#1644]
I love prototyping things in Codesandbox (looks like you guys do too). But I'm not able to install any of the floating-ui packages (screenshots below). You may already be aware of this issue, but I wanted to ask if you have any insight into when it might be possible to install `@floating-ui/react-dom-interactions` in Codesandbox.

# Couldn't find `@floating-ui/dom`
<img width="460" alt="Screen Shot 2022-04-21 at 12 10 40 PM" src="https://user-images.githubusercontent.com/63125920/164536003-37884062-6047-494e-9548-c46e70aecef4.png">

# Couldn't find `@floating-ui/react-dom-interactions`
<img width="460" alt="Screen Shot 2022-04-21 at 12 06 51 PM" src="https://user-images.githubusercontent.com/63125920/164536014-b61131a6-8dc1-4912-a03a-c8b800290356.png">

**Comment by atomiks** [comment]
I think this is a CodeSandbox issue, but if you press Enter after entering the package it'll still install it

**Comment by jonathanbutler7** [comment]
> I think this is a CodeSandbox issue, but if you press Enter after entering the package it'll still install it

That worked, thanks @atomiks. Loving `floating-ui` so far, thank you for your great work.
