### ISSUE TITLE
Popover is behind element even with FloatingPortal

### ISSUE THREAD

**Issue by wmonecke** [floating-ui/floating-ui#1645]
I am trying to use a FloatingPortal to take the floating elements outside the flow of the document.

However, I am still seeing odd behaviour when the popover should be on top of an element.

<img width="1039" alt="image" src="https://user-images.githubusercontent.com/24256469/164558959-31509962-02d9-41e7-87c9-744e9be31f54.png">

Current code:

MyPopover.js
````
const { x, y, reference, floating, strategy } = useFloating({
    placement: "bottom-start",
    middleware: [flip(), shift(), offset(5)],
 })

...
<>
    <Popover.Button 
       ref={reference} 
       className={contentContainerStyle} 
     />
    <Popover.Panel
      static
      ref={floating}
      style={{
        position: strategy,
        top: y ?? "",
        left: x ?? "",
      }}
    >
    ...
    </Popover.Panel>
</>
````

App.js
````
const AppWithStore = () => {
  return (
    <Provider store={store}>
      <PersistGate loading={null} persistor={persistor}>
        <FloatingPortal>
          <App />
        </FloatingPortal>
      </PersistGate>
    </Provider>
  )
}
````

What am I missing to take the floating UI out of the flow of the document?

Versions:
  "@floating-ui/react-dom": "^0.6.3",
  "@floating-ui/react-dom-interactions": "^0.3.1",

**Comment by atomiks** [comment]
I don't see a FloatingPortal being used anywhere? Also that's Popper's API, not Floating UI's, I'm not sure why you're using `useState`: https://floating-ui.com/docs/react-dom#usage

**Comment by wmonecke** [comment]
@atomiks Sorry, I was migrating away from react-popper. I wrap my whole app with a FloatingPortal.

**Comment by atomiks** [comment]
The `FloatingPortal` should only wrap the floating element, not the whole app. Further, you may need to set a `z-index` on the floating element if there are other positioned elements that can obscure it. `isolation: isolate` on the root app (not the floating portal node) may also help (cc: @FezVrasta  still have no idea how that works lol)

**Comment by wmonecke** [comment]
@atomiks This definitely places the Floater on top. However when you scroll it stays fixed. I guess I will need to call update on scroll?

**Comment by atomiks** [comment]
Yes this is also documented: 

> useFloating() only calculates the position once on render, or when the reference/floating elements changed. Depending on the context in which the floating element lives, you'll likely need to update its position in an effect. See [Updating](https://floating-ui.com/docs/react-dom#updating).

https://floating-ui.com/docs/react-dom#updating

A migration guide for Popper –> Floating UI is probably a good idea

**Comment by wmonecke** [comment]
````
 useEffect(() => {
    if (!refs.reference.current || !refs.floating.current) {
      return;
    }
 
    // Only call this when the floating element is rendered
    return autoUpdate(
      refs.reference.current,
      refs.floating.current,
      update
    );
  }, [refs.reference, refs.floating, update]);
````

This is not working for me.

This is the only hack / code that is working atm:

````
 const isMountedRef = useRef(false)
  const { x, y, reference, floating, strategy, update, refs } = useFloating({
    placement: "bottom-center",
    middleware: [flip(), shift(), offset(5)],
  })


  useEffect(() => {
    if (isMountedRef.current) {
      return debounce(update, 100)
    }
    isMountedRef.current = true
  })
````
