### ISSUE TITLE
[React DOM Interactions] FloatingPortal and shadowRoot

### ISSUE THREAD

**Issue by BATCOH** [floating-ui/floating-ui#1648]
In my project, part of the interface works inside shadowRoot.
I'm adding some components using Floating UI and encountered the following behavior:

`FloatingPortal` can't use an existing `div#floating-ui-root` on the page if it's inside a shadowRoot (`document.getElementById("floating-ui-root")` returns `null`).
`FloatingPortal` then creates a `div#floating-ui-root` and adds it to `document.body`.

I would like to be able to use a container inside the shadowRoot.
I understand that using floating components inside a shadowRoot is not a common scenario.
I understand that FloatingPortal can easily be re-implemented in a specific project with all the specifics in mind.

Does it make sense to think about a solution within @floating-ui/react-dom-interactions or is that out of scope?

[sandboxed example](https://codesandbox.io/s/floating-ui-floatingportal-shadowroot-4oqygg?file=/src/index.js)

**Comment by atomiks** [comment]
I think it should be supported yeah. Another thing is that `.contains()` is used throughout the package but that also doesn't handle Shadow DOM (but the positioning package has a util to handle that which could be copied over)

**Comment by atomiks** [comment]
`0.4.0`
