### ISSUE TITLE
Please just a little extra explanation in these docs, how to get the popper to be a child of body

### ISSUE THREAD

**Issue by FirstVertex** [floating-ui/floating-ui#1656]
Good day :)
In the docs [here](https://popper.js.org/docs/v2/performance/#attaching-elements-to-the-dom) it mentions:
> you may want to attach popper elements to the top of the DOM, such as `<body />`, this is of course supported as well

I cannot figure out any way to get this done.  All day yesterday and today I spent trying to understand any opportunity to change the parent to body or a div who is added directly to body.  I experimented with modifiers, and all available inputs.

Please if you can spare a moment to provide a small example, of how I can get my popper to be a child of body, it would save me a lot of time and frustration.  Thanks in advance.

**Comment by atomiks** [comment]
What are you struggling with? Are you creating the element with JS or is it just plain HTML? 

All it's saying is you can do this

```html
<body>
  <div>
    <div>
      <div>
        <!-- ... etc, nesting of unknown depth -->
        <div id="reference"></div>
      </div>
    </div>
  </div>

  <div id="popper-root">
    <div id="popper"></div>
  </div>
</body>
```

Querying these two elements and passing them `createPopper()` will work as normal
