### ISSUE TITLE
[React DOM Interactions] Tooltip: Follow Cursor feature

### ISSUE THREAD

**Issue by stefanzmf** [floating-ui/floating-ui#1659]
Hello,

I am trying to develop a React Tooltip component that could handle both static tooltip and follow cursor feature (based on a boolean prop `follow`). 

I was trying to develop an extra hook and toggle it based on the top-level prop follow.

```
  const { getReferenceProps, getFloatingProps } = useInteractions([
    useHover(context),
    useCursorFollow(context, {
      enabled: follow, /*top level boolean prop*/
    }),
  ]);
```

My approach does not look right since I do not know how to set a virtual element in the `reference` option from `useFloating` and also another reference for the DOM element that I have to listen to mouse events.

LE: Not really if this is the right approach but I am taking the DOM reference and as soon as the `mouseenter` event is triggered I am changing that reference to a virtual element. 

Demo here: https://codesandbox.io/s/still-smoke-mxznje?file=/src/App.js

**Comment by atomiks** [comment]
I think there should be some kind of hook that deals with the pointer position. This would be used for both "follow cursor" and context menus' initial position

**Comment by atomiks** [comment]
After experimenting there's definitely a piece missing from the hook that separates the DOM node (which listens for events like hover, etc.) and the position. 

In your hook you have to call `onOpenChange` because calling `reference()` changes the `refs.reference.current` value which all the other hooks expect to be a real DOM node, so it never closes after it opens.

To do this properly you need to two separate calls to `useFloating()`: one that handles the reference DOM node, and the other that handles the virtual reference position. 

You could pass the virtual call's `reference` as a prop to your custom hook and it should then work correctly.

```js
function Tooltip({children, label}) {
  // This handles the DOM node stuff
  const {
    reference: nodeReference,
    floating: nodeFloating,
    strategy,
    context,
    refs,
    update,
  } = useFloating({
    open,
    onOpenChange: setOpen,
  });

  // This handles the virtual position
  const {
    x,
    y,
    reference: virtualReference,
    floating: virtualFloating,
  } = useFloating({
    placement,
    middleware: [offset(5), flip(), shift({padding: 8})],
  });

  const {getReferenceProps, getFloatingProps} = useInteractions([
    useHover(context),
    useFocus(context),
    useRole(context, {role: 'tooltip'}),
    useDismiss(context),
  ]);


  const floatingRef = useMemo(
    () => mergeRefs([nodeFloating, virtualFloating]),
    [nodeFloating, virtualFloating]
  );

  return (
    <>
      {isValidElement(children) &&
        cloneElement(
          children,
          getReferenceProps({
            ref: nodeReference,
            // This is probably better on the document
            // if you have animations
            onMouseMove({clientX, clientY}) {
              virtualReference({
                getBoundingClientRect() {
                  return {
                    width: 0,
                    height: 0,
                    x: clientX,
                    y: clientY,
                    left: clientX,
                    right: clientX,
                    top: clientY,
                    bottom: clientY,
                  };
                },
              });
            },
          })
        )}
      {open && (
        <div
          {...getFloatingProps({
            ref: floatingRef,
            style: {
              position: strategy,
              top: y ?? '',
              left: x ?? '',
            },
          })}
        >
          {label}
        </div>
      )}
    </>
  );
}
```

Maybe we could come up with something to make this easier without needing to hook calls

**Comment by stefanzmf** [comment]
This is how I handle the following cursor feature on `react-popper`. I was hoping that we could make use of `useInteractions` to avoid duplicating `useFloating`
