### ISSUE TITLE
Best place to add onClose when clicking a dropdown menu item?

### ISSUE THREAD

**Issue by jacobsilver2** [floating-ui/floating-ui#1660]
Hi,

I've been going through this Dropdown example from the React DOM Interactions page:

https://codesandbox.io/s/admiring-lamport-5wt3yg?file=/src/DropdownMenu.tsx:0-16

Trying to implement a nested dropdown. It works great, but I'm unsure how to close the dropdown when a menu item (that is not disabled) is selected.
I've had some success adding it here (line 233 of `DropdownMenu.tsx`):
```
      <FloatingPortal>
        {open && (
          <FloatingFocusManager
            context={context}
            preventTabbing
            modal={!nested}
          >
            <div
              {...getFloatingProps({
                className: "Menu",
                ref: floating,
                onClick() {
                  setOpen(false)
                },
                style: {
                  position: strategy,
                  top: y ?? "",
                  left: x ?? ""
                }
              })}
            >
```

But this will apply the `onClose` whenever clicking anywhere in the dropdown. That's ok for most purposes, but if I wanted, for example, a menu item with a checkbox to NOT close the dropdown, this solution wouldn't work.

Another place I tried is here (line 253 of `DropdownMenu.tsx`):
```
              {Children.map(
                children,
                (child, index) =>
                  isValidElement(child) &&
                  cloneElement(
                    child,
                    getItemProps({
                      role: "menuitem",
                      className: "MenuItem",
                      ref(node: HTMLButtonElement) {
                        listItemsRef.current[index] = node;
                      },
                      onClick() {
                        setOpen(false);
                      },
```
But this will only close the nested dropdown, not the entire dropdown. Any tips?

**Comment by atomiks** [comment]
Hey good question! The event emitter is designed for this purpose and I updated the CodeSandbox 👍 

Emit the event in the `onClick` handler:
```js
onClick() {
  tree?.events.emit("click");
}
```

Listen inside an effect:
```js
useEffect(() => {
  function onTreeClick() {
    setOpen(false);
  }

  tree?.events.on("click", onTreeClick);
  return () => {
    tree?.events.off("click", onTreeClick);
  };
}, [tree]);

```

**Comment by jacobsilver2** [comment]
thank you!

**Comment by jacobsilver2** [comment]
I'm wondering about another thing (related to this issue, so I'm staying within this thread. Please let me know if you'd prefer I open another thread): 

If I use the code sandbox as an example, and add a simple `MenuItem2` component which only wraps the `MenuItem`, the closing functionality breaks. I have also tried using forwardRef, but that doesn't seem to help.

Here is a code sandbox with the example:
https://codesandbox.io/s/bitter-breeze-89xlv5?file=/src/App.tsx

Please let me know if there is a solution to this. Thank you!

**Comment by atomiks** [comment]
None of the props are being forwarded to it, including the ref.

```js
export const WrappedMenuItem = forwardRef<
  HTMLButtonElement,
  { label: string } & React.HTMLProps<HTMLButtonElement>
>(({ label, ...props }: { label: string }, ref) => {
  return <MenuItem label={label} {...props} ref={ref} />;
});
```

**Comment by jacobsilver2** [comment]
ha of course, thank you!
