### ISSUE TITLE
Latest version 0.4.5 as in documentation not available via skypack CDN

### ISSUE THREAD

**Issue by christianmartinnies** [floating-ui/floating-ui#1661]
First of all: Marvellous work, really love it very much! :)

It seems like the latest version 0.4.5 is not available via CDN.

**Steps to reproduce:**
Try to open https://cdn.skypack.dev/@floating-ui/dom@0.4.5 as documented at https://floating-ui.com/docs/getting-started#cdn

**Result:**
`
/*
 * [Package Error] "@floating-ui/dom@v0.4.5" could not be built. 
 *
 *   [1/5] Verifying package is valid…
 *   [2/5] Installing dependencies from npm…
 *   [3/5] Building package using esinstall…
 *   Running esinstall...
 *   Cannot find module '@floating-ui/dom/src/index.ts'
 *
 * How to fix:
 *   - If you believe this to be an error in Skypack, file an issue here: https://github.com/skypackjs/skypack-cdn/issues
 *   - If you believe this to be an issue in the package, share this URL with the package authors to help them debug & fix.
 *   - Use https://skypack.dev/ to find a web-friendly alternative to find another package.
 */

console.warn("[Package Error] \"@floating-ui/dom@v0.4.5\" could not be built. \n[1/5] Verifying package is valid…\n[2/5] Installing dependencies from npm…\n[3/5] Building package using esinstall…\nRunning esinstall...\nCannot find module '@floating-ui/dom/src/index.ts'");
throw new Error("[Package Error] \"@floating-ui/dom@v0.4.5\" could not be built. ");
export default null;
`

Best,
Christian

**Comment by atomiks** [comment]
`./src/index.ts` is for development purposes in the monorepo but has no relevance for consumers of the published package:

https://github.com/floating-ui/floating-ui/blob/a3299dc9c56a7c95183dfb3463f0542db4e945e2/packages/dom/package.json#L29

Not sure the easiest fix. Would be good if Skypack silently ignored for that type of case

**Comment by atomiks** [comment]
This is a bug in Skypack apparently. I've just removed it from the docs but you can make an issue at their CDN repo to get it fixed.

**Comment by christianmartinnies** [comment]
Well, THAT is, what i call response time and action…! :)
Thank you very much
