### ISSUE TITLE
[React DOM Interactions] Expose `useFloatingPortalNode` hook

### ISSUE THREAD

**Issue by mihkeleidast** [floating-ui/floating-ui#1668]
I'm working through some other dependencies that also do portaling (right now dealing specifically with [react-modal](https://reactcommunity.org/react-modal/)). I'd like to use the same portal container for all the different dependencies, but I can't use the FloatingPortal component itself directly, as those dependencies have their own portaling logic. However, some of them expose props to customize the portaling element.

I'd like to extract most of the FloatingPortal component code that deals with injecting the portal container to a custom hook. This way I could use the hook with other components that accept a reference to a node.

Example code of what I'd like to achieve with react-modal:
```jsx
const App = () => {
  const portalNode = useFloatingPortalNode();

  return <ReactModal parentSelector={() => portalNode}></ReactModal>;
};
```

Does this feature make sense? I can help with a PR, if necessary.

**Comment by atomiks** [comment]
Seems ok to me 👍
