### ISSUE TITLE
Cannot use CJS sources as transitive dependencies

### ISSUE THREAD

**Issue by Dolaanpls** [floating-ui/floating-ui#1676]
Hello,

I am in the same situation as the author of #1529. I am using @floating-ui/react-dom-interactions to build a context menu in one of our packages that combines multiple common use React components. When I am developing in said package, all is working fine.

The problem comes when I am trying to pull a generated version of this package, as the app will crash when I render the context menu with the generic error (Object(...) is not a function). This error comes from the fact that the loaded module through require returns the path and not a JS module/object.

I tried pulling the context menu from another package that we build using ESBuild (vs Webpack 5) and I have the same result.

Is this something that can be fixed ? Don't hesitate if you need more information, I'll try to answer the best I can while respecting confidentiality :)

Thanks in advance,

**Comment by Dolaanpls** [comment]
Sorry, I think I explained myself quite badly. We write our code in normal ES6 syntax, that is then transpiled to CJS (we use a fork of CRA 5 just to integrate scss modules). 

The require that fails is generated by Babel I guess, but it still works if the dependency is direct (as I'm developing with the CRA dev server), is it just a problem in the configuration then ? I raised an issue here because we've never had any problem with other packages and the app is quite large. e.g. we use popperJS in multiple places. 

My guess was that the conditional exports might have to do with it since it's the first time I saw that.

**Comment by atomiks** [comment]
As I said I don't know what the cause is because it works with a minimal webpack 5 setup. Something in your config is likely causing `.cjs` resolutions to break, maybe the file loader or something. This package is using modern `type` module which isn't that widespread so

**Comment by atomiks** [comment]
I was able to repro it in CRA 5

```js
const x = require('@floating-ui/react-dom')
// x points to a path
```

Their config does not include `cjs` as part of the processing https://github.com/facebook/create-react-app/blob/f99167c014a728ec856bda14f87181d90b050813/packages/react-scripts/config/webpack.config.js#L389-L418

**Comment by atomiks** [comment]
I think `zustand` might have the way to make it work everywhere: https://github.com/pmndrs/zustand/blob/ec90d993e182f2b668271473b7b7dac566bdbd51/package.json#L1-L18

I'll open a PR later and try to test it with a bunch of tools
