### ISSUE TITLE
[React DOM Interactions] restMs not working

### ISSUE THREAD

**Issue by natew** [floating-ui/floating-ui#1679]
On this sandbox:

https://codesandbox.io/s/cool-germain-ykbzfi?file=/src/AnimatedTooltip.tsx

When you continue to move your mouse over the button it shows no matter if you keep moving it.

**Comment by atomiks** [comment]
That's caused by

```js
delay: { open: 1000 },
```

If you remove that it will never open. The delay acts as a "fallback" value when specified

**Comment by natew** [comment]
Ah ok misread delay, almost seems like `limit`. Thanks.
