### ISSUE TITLE
[Popper 2] Change type of State.elements.reference from `Element | VirtualElement` to `HTMLElement | VirtualElement`?

### ISSUE THREAD

**Issue by DrJume** [floating-ui/floating-ui#1681]
I was trying out the `sameWidth` community wrapper (https://codesandbox.io/s/bitter-sky-pe3z9?file=/src/index.js) and using it in my TS Project this type error showed up: 

```
Property 'offsetWidth' does not exist on type 'Element | VirtualElement
  Property 'offsetWidth' does not exist on type 'Element'
```

But as it turns out, it works without problems, as the reference is an `HTMLElement`. So why is the type of `reference` `Element | VirtualElement`?

---

_types.d.ts:_
```ts
export declare type State = {
    elements: {
        reference: Element | VirtualElement;
        popper: HTMLElement;
        arrow?: HTMLElement;
    };
    ...
```

**Comment by atomiks** [comment]
Reference can be an `SVGElement`

**Comment by DrJume** [comment]
Oh, yeah, you are right.

Then would'nt it be better to type it `HTMLElement | SVGElement | VirtualElement`?

**Comment by DrJume** [comment]
Because Element is so less specific, as it stems from the old times of XML Elements.
