### ISSUE TITLE
Unncessary `return` keyword in React DOM docs

### ISSUE THREAD

**Issue by Mikilll94** [floating-ui/floating-ui#1682]
https://floating-ui.com/docs/react-dom#updating

<img width="629" alt="Screenshot 2022-05-06 at 17 09 09" src="https://user-images.githubusercontent.com/17653648/167160995-d131f8dc-ec37-4df7-84e1-308fd8412a7a.png">

`return` keyword before `autoUpdate()` function is not needed.

**Comment by atomiks** [comment]
It is because it returns a cleanup function..
