### ISSUE TITLE
React Native arrow throwing undefined is not an object (evaluating 'element.measure')

### ISSUE THREAD

**Issue by brycnguyen** [floating-ui/floating-ui#1684]
Hey there, I'm using this library but running into an issue with react native.

I'm referring to the documentation here:
https://floating-ui.com/docs/react-native#arrow,

Seems like this line: 
https://github.com/floating-ui/floating-ui/blob/d8a90be987a2479743e8e16c6319ca6c5b3c739e/packages/react-native/src/createPlatform.ts#L70, it is trying to de-structure element, but there is no element property.

A workaround I did was to set arrowRef.current = { element: node } when setting the ref on my Arrow Element.

I still can't seem to get the arrow to function properly as the element.measure call on that line seems to also be returning a single value rather then { width, height ... } even after I have called update() after setting the ref.

Is there an example of this library working somewhere for React Native?

**Comment by atomiks** [comment]
The React Native package really needs help from someone with RN experience to get it to a solid state. That's why it's still `Experimental` - that should be `(element)` not `({element})`. I'll try to get an arrow example working.

**Comment by brycnguyen** [comment]
You work fast! Thank you much! I have it working with your fixes.

**Comment by atomiks** [comment]
I'll release it later today, I need to merge a bunch of PRs first then all the packages will get released
