### ISSUE TITLE
Issues with using Floating-UI with Angular

### ISSUE THREAD

**Issue by Herbrandus** [floating-ui/floating-ui#1686]
I am using Angular together with Floating-UI and I am running into some issues. It may very well have something to do with the lifecycle hooks of Angular, but the arrow, as well as my tooltip itself aren't positioned correctly.
I made sure to use the latest lifecycle hook, so everything should be in position for Floating-UI to make its calculations.

Can I use Floating-UI like this at all? Or am I just missing something? I tried to follow the tutorial but my results are not the same.
Here is a demo link: https://codesandbox.io/s/herbrandus-floating-ui-angular-q8t3mn-q8t3mn

Also, I noticed in my IDE typescript having issues with a piece of code like: `const { x: arrowX, y: arrowY } = middlewareData.arrow;`
That's why I got around it with:
`const arrowX = middlewareData.arrow?.x;
  const arrowY = middlewareData.arrow?.y;`

I am also getting the typescript error on `[staticSide]: '-4px'` saying:
"TS2464: A computed property name must be of type 'string', 'number', 'symbol', or 'any'."
Is there something I could do about that? Or can I just ignore the whole `staticSide` part when I am not intending to use positions like 'top-start', etc.?

**Comment by atomiks** [comment]
You're computing the position when it has `display: none` and therefore can't be measured. It needs to be positioned when it's measurable/visible.

<img width="726" alt="Screen Shot 2022-05-09 at 11 58 36 pm" src="https://user-images.githubusercontent.com/22450188/167426478-e4b44399-973a-4e19-9c02-d9e121ca19de.png">

The TS errors are because `arrow` may or may not exist at runtime, only if you've put `arrow()` in the arrow. Probably should change that example to be better with TS usage.

**Comment by Herbrandus** [comment]
Oh right!
But how can it be that it does work in the tutorial? 
I see at the functionality part (https://floating-ui.com/docs/tutorial#functionality) that `display: none;` is added directly to the tooltip styling. Isn't that the same as what I am doing?
My alternative now is leaving it visible and setting `display: none;` to the tooltip in the `.then()` block, once the position is computed. Would that be the best solution in your opinion?

**Comment by atomiks** [comment]
>  Isn't that the same as what I am doing?

The `computePosition` call (which is inside `update`) is called **after** the `block` style has been added (so it can be measured). In your scenario you need to change `ngAfterContentInit` to `update` and then call `this.update()` at the end of the `show()` method. I did this and it works correctly.

**Comment by Herbrandus** [comment]
Thanks a lot! This helped me to understand Floating-UI much more!
