### ISSUE TITLE
[Core] Feature Request: Support for more CSS units (rem, em)

### ISSUE THREAD

**Issue by tgrelka** [floating-ui/floating-ui#1696]
I’m using Floating UI with responsive CSS, which is mostly based on `rem` and `em` CSS units instead of static `px`.

I’d like support for Floating UI to be able to use these units when configuring middleware, e.g. `shift`, `offset` or `arrow`.

One of the typical use-cases for this would be scaling the application with font-size, a standard accessibility feature.
With tooltips which have arrows, one would like to avoid the arrow moving over a rounded corner. This is implemented in the `arrow` middleware with the `padding` option. When styling tooltips responsively, with `border-radius: 0.25rem` for example, and the font size changes, the padding also needs to be adjusted, which is quite complex (re-initialising the whole `computePosition` stack).
So instead, I‘d like to pass a string containing CSS units, `padding: '0.25rem'`, and have Floating UI calculate how much that currently is in `px`.

**Comment by atomiks** [comment]
This will add too much size to the library, but can be done externally by measuring the root element's font size then converting it into pixels. 

In general think of Floating UI's API similar to `.getBoundingClientRect()` which also doesn't support `rem/em`

**Comment by atomiks** [comment]
Another thing is remaining agnostic to the DOM for platforms without a concept of `rem` / `em` (but all understand `px`)

Here's the converter btw: https://github.com/react-bootstrap/react-bootstrap/issues/5081#issuecomment-610291403

**Comment by tgrelka** [comment]
I see, thank you for your quick response.
It makes sense to me to have this feature externally, though I’d argue `.getBoundingClientRect()` does not support `rem`/`em` because you’re inquiring about information regarding what’s actually on the screen right now, while Floating UI is in the render stack before that and actively modifies what you see and how you see it, so I think the comparison is a bit off?
I totally see where you are coming from and thus will close this feature request.
Is there consideration for an `@floating-ui/extras` package which could provide useful helpers for these kind of tasks or even to the `@floating-ui/dom` package?

**Comment by tgrelka** [comment]
> Here's the converter btw: https://github.com/react-bootstrap/react-bootstrap/issues/5081#issuecomment-610291403
Thank you, the conversion is not difficult to implement, which is why I wondered if this could be a native feature of Floating UI.

**Comment by atomiks** [comment]
You mean like a utility function? I was thinking more alone the lines of parsing strings with units (which is where the cost would come from). A tree-shakeable utility function still feels like it's outside the scope of the project. I'm sure there's a package for it on npm 🤔

**Comment by stepanjakl** [comment]
+1 for offset em/rem units support
