### ISSUE TITLE
How to infer the flipped state of a floating element using flip()?

### ISSUE THREAD

**Issue by petercpwong** [floating-ui/floating-ui#1699]
What is the correct way to infer the flipped state of the floating element? One would assume the floating element is not flipped if the object returned by `flip()` is empty, but this doesn't seem to be the case when the floating element overflows the edge of the page (or containing element) as illustrated here: https://codesandbox.io/s/recursing-brattain-f8qbzy?file=/src/App.js

**Comment by atomiks** [comment]
You could do:

```js
const {placement} = useFloating({
  placement: 'top'
});

if (placement !== 'top') {
  console.log('flipped');
}
```

What's the use case for this tho?

**Comment by petercpwong** [comment]
Didn't realize `useFloating` also exposed the resolved `placement` of the floating element. Thanks!

> What's the use case for this tho?

Mainly to determine the placement of the arrow on the static axis

**Comment by atomiks** [comment]
Yeah I just updated the docs with that info a few hours ago, was definitely missing: https://floating-ui.com/docs/react-dom#arrow-styles
