### ISSUE TITLE
Support `aria-labelledby` attribute

### ISSUE THREAD

**Issue by Xin00163** [floating-ui/floating-ui#1704]
There are cases where a tooltip is serving as the label for an icon. In this case, the better attribute to use would be aria-labelledby, which is announced regardless of navigation method (tab key, arrow key, ...). Would be great if I had the choice to choose between aria-describedby and aria-labelledby.

**Comment by Xin00163** [comment]
Thank you. In this case, is there a way to omit `aria-describedby` ? This is what I have now. 

```
<button data-testid="button" type="button" aria-labelledby="floating-ui-7" aria-describedby="floating-ui-10" class="css-1fgc81t"><div class="css-bptyib"><div class="css-1yztr03"><span class="css-1v8h4au">right</span></div></div></button>
```

**Comment by atomiks** [comment]
Remove the `useRole` hook and add `role="tooltip"` to the floating element manually

**Comment by Xin00163** [comment]
Thank you!

**Comment by atomiks** [comment]
I wonder if `role: 'label'` makes sense (although `role="tooltip"` would remain). Basically acts like `aria-label` but the tooltip is the element being referenced.

**Comment by Xin00163** [comment]
Based on what I am reading [here](https://zoebijl.github.io/apg-tooltip/#tooltip-main-label), "_it makes a lot more sense to not use the tooltip role_" when used with `aria-labelledby`. What are your thoughts?

**Comment by atomiks** [comment]
It makes sense, so really you only need the code I provided above for it to work. Adding `label` to `useRole` would be a shortcut for it

**Comment by Xin00163** [comment]
Thanks for explaining. I will close this.
