### ISSUE TITLE
[Core] Add `relative` modifier

### ISSUE THREAD

**Issue by mishushakov** [floating-ui/floating-ui#1711]
Hey,
thanks for creating the library

I'm suggesting to add a `relative` modifier to the library, which let's you align tooltips relative to element from another context
The use-case for this is aligning tooltips within iframes or on canvas (where you know the relative coordinates upfront)

Here's the modifier code:

```js
const relative = {
  name: 'relative',
  fn: ({ x, y, element }) => {
    const rect = element.getBoundingClientRect()
    return {
      x: rect.left + x,
      y: rect.top + y
    }
  }
}
```

without `relative` modifier

https://user-images.githubusercontent.com/10400064/169694677-a8c88c8e-f263-47f7-9327-d2311df8731d.mov

with `relative` modifier

https://user-images.githubusercontent.com/10400064/169694680-fa4b3cb5-36ca-4f42-aaa8-bf0064b27a7f.mov

you can already achieve similar functionality by using virtual elements

**Comment by atomiks** [comment]
Is the floating element in the top-level document and it's being positioned to a reference element inside of an iframe?

I suppose #1594 is related?

**Comment by mishushakov** [comment]
yep, the tooltip is top-level but the target is inside of iframe
the modifier also works in combination with virtual elements (highlight inside of canvas with relative coordinates)

https://user-images.githubusercontent.com/10400064/169701710-efab6844-6fb4-4099-81af-14be4358f7a0.mov

**Comment by atomiks** [comment]
This kinda seems like something that should just work by default. If the ref element is not inside the same document as the floating element, then we add the iframe's offsets. Unfortunately it does mean extra size cost to the library, but it should also fix #1594. 

I'm assuming the reverse is impossible because you can't access a document in a higher-level

**Comment by mishushakov** [comment]
The functionality should not be only limited to iframe, but could also apply to virtual elements (such as in my example) where you know the relative position of the element but need to display the element inside of a wrapper div

so the feature should be more generic like a middleware, like i'm proposing, where you give an element (or boundary) as an argument and it adjusts the tooltip position accordingly

the example middleware i provided works for both of these cases

don't think the size is gonna be issue when you package it as optional module/middleware which can be tree-shaked

anyways, let's have a further discussion on that, as the use-case seems to be fairly common

**Comment by mishushakov** [comment]
or maybe even add a global boundary option, because right now i have to add the boundary argument each middleware i'm using

**Comment by talldan** [comment]
Just thought I'd mention that the project I work on had a very similar custom middleware solution for offsetting an iframe to the one shown in the issue description. 

A problem I encountered is that custom middleware that provides an offset doesn't seem compatible with floating ui's shift middleware. That seems to expect any offsets to be provided through middleware data:
https://github.com/floating-ui/floating-ui/blob/77c4b27a8096cafe06e58b2c7592317d6d3a3aea/packages/core/src/middleware/shift.ts#L203-L212

**Comment by atomiks** [comment]
@talldan is it enough to disable `crossAxis` checking in `limitShift`? If you aren't using `crossAxis: true` in the main `shift, it's fine

**Comment by talldan** [comment]
@atomiks I think we need cross axis for our use case.

I've managed to replace our custom middleware with the `offset` middleware, using the callback to determine the right mainAxis/crossAxis values. It looks a bit like this:
```js
offset( ( { placement } ) => {
	const isTopBottomPlacement = placement.includes( 'top' ) || placement.includes( 'bottom' );

	// The axes here seem to be opposite to what the floating-ui docs
	// state, but this seems to work.
	const mainAxis = isTopBottomPlacement ? 'y' : 'x';
	const crossAxis = mainAxis === 'x' ? 'y' : 'x';

	// When the popover is before the reference, subtract the offset,
	// of the main axis else add it.
	const hasBeforePlacement = placement.includes( 'top' ) || placement.includes( 'left' );
	const mainAxisModifier = hasBeforePlacement ? -1 : 1;

	return {
		mainAxis: frameOffset[ mainAxis ] * mainAxisModifier,
		crossAxis: frameOffset[ crossAxis ],
	};
} )
```

I was confused that the mainAxis/crossAxis were flipped from what's suggested in the docs, but maybe there's something I'm overlooking or I did something wrong!

**Comment by atomiks** [comment]
The main axis is the same as the docs suggest?

`const mainAxis = isTopBottomPlacement ? 'y' : 'x';`

[mainAxis](https://floating-ui.com/docs/offset#mainaxis)

```
Represents the distance (gutter or margin) between the floating element and the reference element.
```

For top/bottom, this is `y`.

**Comment by talldan** [comment]
I see. My mistake is that I didn't realise that some middleware (like flip) has a different definition of main/cross axis. Flip is the definition I saw first and I ran with that. 🤦 

I was finding it a bit confusing, but now it makes a lot more sense. Thanks for clarifying.
