### ISSUE TITLE
Mistake in docs regarding Bootstrap's usage of `floating-ui`

### ISSUE THREAD

**Issue by benmccann** [floating-ui/floating-ui#1718]
https://github.com/floating-ui/floating-ui/blob/master/website/pages/docs/tutorial.mdx#before-proceeding says:

> If you’re looking for something simple to set up, with pre-built interactions or styles out of the box for a tooltip or popover element, it is better to use a component library like Bootstrap, Chakra UI, MUI, and so on. All of the mentioned libraries use this library (formerly, Popper) under the hood.

It seems incorrect in stating that Bootstrap is using this library

https://github.com/twbs/bootstrap/search?q=popper - 26 results
https://github.com/twbs/bootstrap/search?q=floating-ui - 0 results

Maybe I'm missing something?

**Comment by atomiks** [comment]
Floating UI is the evolution of Popper and is under the same repo (and forks its code), it's essentially a new major but rebranded because it offers more packages

**Comment by drk-mtr** [comment]
Thanks for the wonderful library!

Bit confused about why this is closed. Maybe I've misunderstood but the documentation is still misleading for users in my view. I was thrown by the same thing hence ending up here. A few examples:

- As a user, I am currently using bootstrap. I see this comment and I think "great, I can use floating-ui without bringing in any new dependencies" - but I believe this is wrong?
- I believe the floating-ui package is the more modern version and is a smaller package size than popper v2. So as a user trying to minimise bundle size I might see this and think "ok, not much room for improvement here, I'll look elsewhere" - but I think this is wrong?
- When seeking to understand issues like this (https://github.com/twbs/bootstrap/issues/36518) I might think I should be looking at floating-ui source... but popper core might be more appropriate (I appreciate that what we're saying is there a lot of shared code, but still).
- I imagine threads like this wouldn't need to exist if it's already using floating-ui: https://github.com/twbs/bootstrap/issues/36497

**Comment by atomiks** [comment]
@drk-mtr I can see why it might be confusing. I tried to add “formerly Popper” to help indicate. 

There's nowhere really to guide vanilla users to something simpler to use (out of the box components) because there isn't a lib like Tippy/Bootstrap that uses it just yet. The only thing I could do is remove that message.

**Comment by drk-mtr** [comment]
Ha yeah I can see why it's tricky because your message makes perfect sense in that context. I guess I'd favour something like "All of the mentioned libraries use floating-ui or Popper (the precursor to this library) under the hood." but I appreciate it's subtle :)
