### ISSUE TITLE
[React DOM Interactions] Ref is insufficent to use a component as a reference/floating/item

### ISSUE THREAD

**Issue by Tiedye** [floating-ui/floating-ui#1720]
Component needs to forward on{Click, PointerDown, etc.} along with ref to be used as an reference or floating element.  If useInteractions could apply the event listeners using the ref it would allow a component that just uses forwardRef to be used as a reference/floating/item element if that makes sense.  Is this feasible?

**Comment by atomiks** [comment]
The prop getters should be spread onto the lowest leaf components/raw DOM node (if you're using styled components it's basically the same thing as spreading onto `styled.div`.). The component API you create should wrap the hooks rather than receive their logic externally as props.
