### ISSUE TITLE
Prevent hover events when using safePolygon

### ISSUE THREAD

**Issue by FelixRelli** [floating-ui/floating-ui#1722]
Hi, 

when using safePolygon and moving the cursor over another component with a tooltip, no hover events should pass.
Or there should be an option to prevent that behavoir. Alternative would be to only allow displaying one tooltip at a time. 

![image](https://user-images.githubusercontent.com/91951037/170279181-eba0eef1-1f82-4d36-8ad5-03a9d84c4aa4.png)

Example: 

[https://codesandbox.io/embed/nostalgic-violet-wiqkzt?fontsize=14&hidenavigation=1&theme=dark](https://codesandbox.io/embed/nostalgic-violet-wiqkzt?fontsize=14&hidenavigation=1&theme=dark)

**Comment by atomiks** [comment]
Alternative using `pointer-events`: https://codesandbox.io/s/laughing-smoke-ise9k0?file=/src/Tooltip.tsx. I guess this could be made a default when using `safePolygon` 🧐   actually, it should also simplify the nested `DropdownMenu` implementation where it blocks sibling list items' pointer-events

**Comment by FelixRelli** [comment]
Thanks for the fast response! Is it possible to only allow one tooltip to be open at the same time? Sometimes mouse-leave events are unreliable.

**Comment by atomiks** [comment]
> Sometimes mouse-leave events are unreliable.

In which cases? You'd need to use some global state to do that
