### ISSUE TITLE
[Safari/Firefox] Popper is not positioned correctly through shadow-dom when parent is position: relative

### ISSUE THREAD

**Issue by WestBrian** [floating-ui/floating-ui#1729]
When using `@popperjs/core` the popper is not positioned correctly if it is within the shadow-dom of a `position: relative` parent.

**This issue seems to only be prevalent in the latest Chrome version 102.**

In the picture below the top has a relative parent in the light-dom while the bottom is shadow-dom.

<img width="171" alt="Screen Shot 2022-05-26 at 6 49 21 PM" src="https://user-images.githubusercontent.com/11201644/170592186-12c054fb-7c83-489e-a5c4-d7f56734f4da.png">

[Codesandbox](https://codesandbox.io/s/busy-rumple-hm2oix)

**Comment by atomiks** [comment]
This seems like a bug in Chrome? `tooltip.offsetParent` is incorrectly returning `body`, not its actual `offsetParent` (the relative div)

**Comment by Dayvisson** [comment]
Apparently this is the chromium issue related with this bug : [Issue 1330819: Web component hover is no longer working](https://bugs.chromium.org/p/chromium/issues/detail?id=1330819)

**Comment by zengguirong** [comment]
Same problem in Safari 14.1.2 (16611.3.10.1.6).
Same problem in @floating-ui

**Comment by atomiks** [comment]
This is fixed in Chrome but was always broken in Safari (still is, on 15.4). I would recommend not using this DOM structure due to that. 

Otherwise, you need to patch `.offsetParent` on `HTMLElement.prototype` and traverse the nodes yourself which is another perf hit.

**Comment by atomiks** [comment]
Browsing around... it seems like the spec for `offsetParent` in shadow DOM was changed a while ago but Chrome didn't use that spec until this recent change? Which would explain why Safari and Firefox are currently broken.

https://github.com/PolymerElements/paper-tooltip/pull/156/files

That's a LOT of code just to handle this problem :\
