### ISSUE TITLE
[React DOM Interactions] Element open by default must be clicked twice to toggle it

### ISSUE THREAD

**Issue by JoaquinTrinanes** [floating-ui/floating-ui#1741]
The MWE can be found here: https://codesandbox.io/s/floating-ui-interactions-bug-uj5v12

Using the interactions package and the `useClick` and `useDismiss` listeners, when the initial open state is `true` the reference element must be clicked twice for it to toggle. Afterwards it works as expected.

Clicking outside and pressing escape work as expected.

**Comment by atomiks** [comment]
https://github.com/floating-ui/floating-ui/blob/84ecd57433ec9b4b788e4ed6f1ed6ef2c4b3aa28/packages/react-dom-interactions/src/hooks/useClick.ts#L83-L85

Seems this line relies on user interaction but in this case there was not an interaction
