### ISSUE TITLE
`tether` and `tetherOffset` in `@floating-ui/react-dom`

### ISSUE THREAD

**Issue by mariuslundgard** [floating-ui/floating-ui#1746]
Hello, I’m in the process of migrating [`@sanity/ui`](https://github.com/sanity-io/design) from `react-popper` to `@floating-ui/react-dom`.

I’m looking for the equivalent of `tether` and `tetherOffset`, but have not found it when browser through docs. Is this replaced by some new functionality? Or should I make my own middleware?

Cheers, & thanks for the great work!

**Comment by atomiks** [comment]
`limitShift` is the replacement
