### ISSUE TITLE
[React DOM Interactions - FloatingFocusManager] Unexpected page scroll when clicking from one popover trigger to another.

### ISSUE THREAD

**Issue by threehams** [floating-ui/floating-ui#1751]
When using `FloatingFocusManager` and `useDismiss` together:

If an open popover is off-screen, and a trigger is clicked to open a new one, the page will scroll back to the previous element and instantly close it, instead of opening the new popover.

![ZplCgrduAq](https://user-images.githubusercontent.com/1399894/174913405-b6e38396-9a27-42ce-a4a5-8719012653e9.gif)

Steps:
- Click on the first button on the page to open a popover.
- While the popover is still open, scroll down until the first is off the page, then click any other button.

Repro:
https://codesandbox.io/s/floating-ui-react-dom-visual-test-forked-rwogd6

**Comment by threehams** [comment]
I've been playing with this a bit more, and the force scroll happens from dismiss, so clicking anywhere outside the popover (or even pressing Escape) will snap back to the original trigger. Surprisingly, setting `returnFocus=false` doesn't change this - focus is correctly moved to the second element clicked, but the browser still snaps back to the first.

**Comment by atomiks** [comment]
https://github.com/floating-ui/floating-ui/blob/1589c1dec67669c6d43989b58c7203437c7515d5/packages/react-dom-interactions/src/hooks/useDismiss.ts#L89

Guess this shouldn't exist?

**Comment by threehams** [comment]
Agree on the `esc` key returning focus. I'll try out the fix on the much bigger project I found this on.
