### ISSUE TITLE
[React DOM Interactions - FloatingPortal] DOM Insert method option

### ISSUE THREAD

**Issue by needim** [floating-ui/floating-ui#1754]
Hello, first of all; thank you for this wonderful library.

It would be nice to have parameters like `insert: "append" | "prepend"` for FloatingPortal. Sometimes the order is essential for styling with CSS for stacking things (:nth-child())

https://github.com/floating-ui/floating-ui/blob/1589c1dec67669c6d43989b58c7203437c7515d5/packages/react-dom-interactions/src/FloatingPortal.tsx#L31

Also, I couldn't see any contribution guide. (I am not familiar with mono repositories)

**Comment by atomiks** [comment]
> Sometimes the order is essential for styling with CSS for stacking things (:nth-child())

Do you have an example? 

In this sort of scenario it might be better to add the node to the document yourself. Then it will select that, allowing you to place it anywhere.

**Comment by atomiks** [comment]
Closing as not planned for now since you can insert the node anywhere you want which is better than a single prepend option which can still have issues in certain cases
