### ISSUE TITLE
Centering is broken in some situations

### ISSUE THREAD

**Issue by gampleman** [floating-ui/floating-ui#1757]
I'm debugging an issue with arrow positioning in a table, but in trying to reproduce it I've encountered the following issue:

https://codesandbox.io/s/floating-ui-dom-template-forked-xh0y49?file=/index.html

If you notice, the tooltip is not centered above the `i` icon. This is regardless of any value to the `placement` property.

**Comment by atomiks** [comment]
you're passing the arrow not the bubble as the floating element

`computePosition(trigger, arrow, {` 

should be 

`computePosition(trigger, bubble, {`
