### ISSUE TITLE
Using a button trigger which sets its own ref in state causes an infinite loop.

### ISSUE THREAD

**Issue by threehams** [floating-ui/floating-ui#1760]
## Issue

If the trigger element for a tooltip/popover sets its own ref in internal state, the page locks up in an infinite loop.

## Reproduction

https://codesandbox.io/s/floating-ui-react-dom-infinite-loop-b8s1dh

## Expected

I'm not really sure which code is in the wrong here. React doesn't explicitly ban setting refs in state, and it's necessary for some patterns. That said, it's definitely not common. In this case, it was simple enough for me to take out the `setSelfRef` state, as it was part of an older render props API for the previous tooltip library.

That said, at wider scale, this may come up again, and this was difficult to track down.

**Comment by atomiks** [comment]
It may be possible to skip the update if we can check the node is the same

**Comment by atomiks** [comment]
Seems like it can't really be fixed with the `whileElementsMounted` prop due to React calling an unstable ref fn with `null` again. So currently memo'ing an unstable callback ref is the only solution
