### ISSUE TITLE
[Popper] Floating elements are attached to the wrong document

### ISSUE THREAD

**Issue by jdnarvaez** [floating-ui/floating-ui#1764]
When using `@popperjs/core` to show a floating element in a *child* window, the content is appended to the `global` `window` object. To function correctly, the anchor element's `ownerDocument` property should be used instead. I know this project is in maintenance mode and has been replaced, but if I submit a PR to fix this issue, would it be reviewed/accepted? thanks.

**Comment by atomiks** [comment]
What do you mean “attached”? Popper does not attach anything for you, you do it yourself. Owner documents are already handled

**Comment by jdnarvaez** [comment]
yep, I had misread and looked through dom utilities instead of the old popper branch, that is my mistake. it looks like the issue we are having is upstream in chakra, sorry about that.
