### ISSUE TITLE
`top` get computed to negative value with large tooltips when not setting max-height to dom immediately in `apply` fn

### ISSUE THREAD

**Issue by emattias** [floating-ui/floating-ui#1766]
If you dont update the dom immediately in your `apply` function in the `size` middleware the `top` value for the first render of the tooltip get calculated incorrectly  and the tooltip can even be positioned off screen.

Here's a codesandbox showing the bug. When you toggle the tooltip (only the first time) its not positioned at the top of the screen.  I emulated frameworks no updating immediately with a `setTimeout`. Try pressing the rightmost button to disable it and toggle the tooltip. It should now be calculated correctly.

https://codesandbox.io/s/floating-ui-dom-template-forked-yqiiws?file=/src/index.js

Frameworks often do not update the dom immediately. I see that [you can use `flushSync`](https://github.com/floating-ui/floating-ui/issues/1512#issuecomment-1094593531) with react to do it (or just update the dom directly, so bypassing react).

I think this should be noted clearly in the docs of `size` and `apply`.

I am using ember and I have found that just changing [this](https://github.com/floating-ui/floating-ui/blob/master/packages/core/src/middleware/size.ts#L87-L90) from:

```js
    apply?.({
      ...middlewareArguments,
      ...dimensions,
    });
```
to
```js
    await apply?.({
      ...middlewareArguments,
      ...dimensions,
    });
```

allows me to not have to bypass ember and update the dom directly by returning a promise from my apply function that resolves after ember has rendered, like this:

```js
apply({
  availableHeight,
  availableWidth,
  x,
  y,
}) {
  this.maxHeight = `${availableHeight}px`;
  this.maxWidth = `${availableWidth}px`;

  this.left = `${x}px`;
  this.top = `${y}px`;

  return new Promise((resolve) => {
    schedule('afterRender', this, resolve)
  })
```

I guess other frameworks also have ways to wait for a render to have been finished. 

If you want I can make a pr adding the await :)

**Comment by atomiks** [comment]
Seems fine but I think this reduced the updating perf a bit, mutating it directly was faster (in Chrome at least)
