### ISSUE TITLE
FloatingFocusManager does not honor outsidePointerDown from useDismiss

### ISSUE THREAD

**Issue by mihkeleidast** [floating-ui/floating-ui#1771]
In some scenarios I'd like to not close my popover on outside click, but would still like to use FloatingFocusManager for other focus handling.  It seemed like disabling `outsidePointerDown` in useDismiss should work for this as well, but no such luck - looks like the focusout event fires on outside click as well.

Sandbox: (forked from the official non-modal dialog example) https://codesandbox.io/s/laughing-resonance-n8xxnn?file=/src/Popover.tsx:1028-1046

**Comment by atomiks** [comment]
Isn't this just native blurring/focusout behavior? The pointer pressing down blurs it the same as with keyboard focus leaving it

**Comment by mihkeleidast** [comment]
Sure, I agree that this is native behavior. But it is still unexpected and conflicting and something that would be nice to control separately.

**Comment by atomiks** [comment]
Shouldn't (or can't) you be use a modal popover then? What does non-modal bring?

**Comment by mihkeleidast** [comment]
I don't think it is a modal popover, i.e. it does not look like a modal dialog, it does not cover the entire page content, other interactive elements are still accessible, etc. I'll talk with my team about dropping this functionality in our internal component, though, that would make this issue go away. I'll update when I can.

**Comment by mihkeleidast** [comment]
Do I understand correctly that for any kind of nested floating component structure, where one component is using FloatingFocusManager (for example Popover > Popover or Popover > Dropdown, etc), and some other is using FloatingPortal, the outermost floating component _must_ set `modal={true}` on FloatingFocusManager, otherwise the focusout / outside click issue comes into play? Seems a little bit complicated to be forced into some particular configuration like that.

Also, it seems like this behavior also sets `aria-hidden="true"` on the floating portal root node - I briefly tested with NVDA on Windows and it seemed to work okay, but has this been tested extensively on other combinations of screen readers / operating systems, to make sure it won't keep any portalled element content hidden from assistive tech?

**Comment by atomiks** [comment]
`modal={false}` adds the focusout/blur listeners, whereas `modal={true}` does not add it, regardless of nesting. 

`modal={true}` also adds `aria-hidden` to prevent outside content from being accessed by SR virtual cursors (which is required on top of focus trapping). I'm not sure what you're asking exactly tho

**Comment by mihkeleidast** [comment]
Take a look at this example: https://codesandbox.io/s/trusting-noether-ip0h2b?file=/src/Popover.tsx

It has a Popover w/ `<FloatingFocusManager modal={false}>`. I'd like the focus to be handled by this component, especially closing of the Popover in case the user tabs out of it. I do not think it is a modal, as the rest of the page content is accessible by non-keyboard users, so it should also be accessible by keyboard users.

There is a Tooltip w/ FloatingPortal. This is generally necessary for correctly rendering the Tooltip in case some parent element has `overflow: auto;` set. The Tooltip also uses `handleClose: safePolygon()`, so the contents of the tooltip could be selected/copied or there could be some little interactive content.

As an example, I put that Tooltip inside the Popover and added a link inside the Tooltip. When I go to click the link, this triggers focusout on the Popover, preventing the link from working, and closing the Popover.

I don't think these two components are something particularly complex, they seem quite ordinary usecases to me. But I don't understand why the outer floating element _must_ be functionally a modal for the clicks to work.

Same with the [nested DropdownMenu example](https://codesandbox.io/s/admiring-lamport-5wt3yg?file=/src/DropdownMenu.tsx) from the docs - in the case of a dropdown menu, why should the outermost menu be a modal to accommodate nesting (either nested dropdown menus or Tooltips on the menu items)?

**Comment by mihkeleidast** [comment]
In components where I've implemented this myself, I listen to Tab key presses and close it when the user is at the end and presses Tab key, and then move focus back to the correct element (next to reference). Virtual screen reader cursors are basically impossible to detect, in that scenario I would assume the user to know to close it with esc or otherwise it will be left open, yes. Outside click handlers take care of closing it in case anything else is clicked anywhere else.

> If a floating element gets rendered in a portal, it has to be modal otherwise the user's focus will get lost since it teleports to the end of the document not inline

Not sure I fully understand, if the focus is managed by JS, why does it have to be modal? The focus is not lost if managed correctly.

BTW, I don't think this _functionally modal_ behavior is actually setting `aria-modal="true"` on the elements that are modal. Is this deliberate or overlooked?

**Comment by atomiks** [comment]
Tab key works I guess

> Not sure I fully understand, if the focus is managed by JS, why does it have to be modal? The focus is not lost if managed correctly.

If the user tabs out of the popover, it has to focus the next element in the tab order after the reference element. How do you determine that reliably? Note that focus guards are used to ensure that "real focus movement" is retained as emulating it has issues.

> BTW, I don't think this functionally modal behavior is actually setting aria-modal="true" on the elements that are modal. Is this deliberate or overlooked?

`aria-modal` is a new-ish property and not really widely supported. It's unnecessary if you're polyfilling it using `aria-hidden` already.

**Comment by mihkeleidast** [comment]
I usually use [tabbable](https://www.npmjs.com/package/tabbable) or something similar, query the elements and focus the next from the reference element index.

> aria-modal is a new-ish property and not really widely supported. It's unnecessary if you're polyfilling it using aria-hidden already.

Gotcha, TIL 👍

**Comment by atomiks** [comment]
Btw your example can be fixed by using `FloatingTree`. It will know the tooltip is a child of the popover even though it's portalled outside of it: https://codesandbox.io/s/happy-brahmagupta-si6nen?file=/src/Popover.tsx

That said, I _can_ add something like `closeOnFocusOut: boolean` if it's really needed.

**Comment by mihkeleidast** [comment]
I did actually have FloatingTree around there, but had an issue with another component that was harder to debug.

My Dropdown component does not use useInteractions (yet, maybe i'll refactor it one day), so I have custom click and keyboard handlers, etc implemented. My DropdownButton (reference element) extends my default Button component, which allows async onClick callback. As such, currently the DropdownButton also allows onClick that can be async. This causes some sort of race condition inside floating-ui so the focusout triggers because it doesn't understand that the nested floating element is open. I could not allow the async onClick on DropdownButton (allowing it on Button is meant for different usecases), as that solves the floating-ui race condition, but maybe this is a bug that could be fixed instead?

Created a reproduction, sorry if there is a little too much code in there, but maybe it'll give some insight into what is going on: https://codesandbox.io/s/focused-dawn-spibiy?file=/src/dropdown_button.tsx

**Comment by atomiks** [comment]
`console.trace()` shows it's coming from your `handleOutsideClick` handler. `useDismiss` handles this internally but yours doesn't

<img width="352" alt="Screen Shot 2022-07-18 at 8 31 18 pm" src="https://user-images.githubusercontent.com/22450188/179493653-5b2a2f4c-bd99-40a7-99e4-d9ffff34ca37.png">

**Comment by atomiks** [comment]
Misunderstood the CodeSandbox, I see what you mean. From what I can tell, the `focusout` event is occurring because when you click the dropdown button, the `<body>` is getting focus before the list item of the menu gets focus.

In PopoverComponent:
```js
    onOpenChange: open => {
      console.log(document.activeElement);
      setOpen(open);
    },
```

**Comment by mihkeleidast** [comment]
I debugged this and traced to this filter in getChildren - it doesn't see that the child floating element is open: https://github.com/floating-ui/floating-ui/blob/master/packages/react-dom-interactions/src/utils/getChildren.ts#L8

**Comment by atomiks** [comment]
Yeah, the `focusout` event is occurring because the body is getting focus upon click when you add `async` before the click handler (no idea why? React event system or native DOM thing?)

The child dropdown isn't open because it hasn't been rendered at this stage, but that's not the root cause of the issue.

**Comment by atomiks** [comment]
Ah ok. It's because you have `disabled={}` set in your Button component (which removes the focus, causing the body to get focused, causing the `focusout` event) which is why that's happening.

**Comment by mihkeleidast** [comment]
Oh, interesting. That's probably because while the Button is awaiting the promise, it is disabled, that loses focus. Alright, that is understandable, I think then the correct move for this specific issue is to disallow the async onClick prop on DropdownButton (or maybe use aria-disabled instead of disabled on the Button for loading state).

Cheers, thanks for all the help! I think there isn't anything left to investigate here, I'll close this issue out.
