### ISSUE TITLE
Position issue with scroll-behavior smooth on Firefox

### ISSUE THREAD

**Issue by diegohaz** [floating-ui/floating-ui#1772]
On Firefox 102.0 (macOS), when the anchor element is inside a scrollable element with `scroll-behavior: smooth`, the floating element position is not consistent.

GIF in slow motion:

![Screencast of the issue described above](https://user-images.githubusercontent.com/3068563/178127331-0f2b0f38-dd06-46b6-9162-31b671e96b59.gif)

Repro: https://codesandbox.io/s/floating-ui-dom-template-forked-w72num?file=/src/index.js

This doesn't happen on other browsers.

**Comment by atomiks** [comment]
I think FF allows half pixels (based on the screen DPR) while animating the scroll which looks smoother, but if you're rounding the `x`/`y` outputs, it will cause that.

`left`/`right` can't be blurry and removing the rounding mostly fixes the problem in the example. (The floating element is measured in full pixels still, so I don't think it'd ever be fully perfect and snap to half pixels exactly though)

Otherwise, you probably need to round by DPR as the docs mention if continuing to use `translate`

**Comment by diegohaz** [comment]
The issue is still there if I don't round the value. It's just *half* evident.

Rounding by DPR seems to produce the same result.

If I use `Math.floor()` instead of `Math.round()`, it looks perfect, and `x` is consistent with other browsers, which makes me think that that additional `.5` shouldn't be there in the first place.

I can see that Firefox does include those `.5` in the DOMRect values, but not in the `scrollLeft` value. Maybe that's what makes Floating UI calculate it wrong?

**Comment by diegohaz** [comment]
The issue is that, in this example, `x` should be always `100` instead of varying between `100` and `100.5` (or `101` with `Math.round`).

**Comment by diegohaz** [comment]
For reference, here's another example in slow motion (without `Math.round()`). The issue is very noticeable at the end of the scroll:

![A sliding menu in slow motion](https://user-images.githubusercontent.com/3068563/178135885-f52a3a97-55f5-442e-8fc6-9fc569a789b3.gif)

**Comment by atomiks** [comment]
The `0.5` in its DOMRect would be causing it, as there's nothing special happening with the calculations, it's just raw unrounded math. Can't you just floor the values in this situation?

**Comment by diegohaz** [comment]
That's an example for Ariakit, so I'd like to keep the code as simple as possible. I'd rather fix this issue in Ariakit itself if I can find a "safe" solution. But I'm not sure if flooring the values by default is really safe. If it is, wouldn't it make more sense to fix it here?

**Comment by atomiks** [comment]
I feel like this is a good use case for the new API over Popper where you can choose how to round (or floor) the values it gives you which can help in edge cases like this. So in the case of this particular UI component, I'd just have a condition in your code that floors it instead of rounding it.
