### ISSUE TITLE
ResizeObserver is not defined

### ISSUE THREAD

**Issue by KutnerUri** [floating-ui/floating-ui#1774]
Getting this error during tests:

```
ReferenceError: ResizeObserver is not defined
```

Apparently popper is depending on the native implementation in AutoUpdate().
Now, I can easily mock it with `window.ResizeObserver ||= jest.fn().mockImplementation(...)`,
but I wonder if this isn't something that floating-ui should handle? 

I see `ResizeObserver` is available in most browsers since 2018-2020. That's not so old!
Maybe babel is supposed to automatically polyfill it?

**Comment by atomiks** [comment]
JSDOM doesn't support it is all

**Comment by KutnerUri** [comment]
is there a suggestion for using with Jest?
and are you not worried with support for slightly older browsers? (4 years old safari, etc)

**Comment by KutnerUri** [comment]
I circumvented it by checking:
```ts
useEffect(() => {
  if(!window.ResizeObserver) return;

  return autoUpdate(...);
});
```
