### ISSUE TITLE
`rect.floating.width` using `offsetWidth` instead of fractional `getBoundingClientRect` causes truncated text

### ISSUE THREAD

**Issue by emattias** [floating-ui/floating-ui#1778]
Because of this: https://github.com/floating-ui/floating-ui/blob/777c9377c5acfc1f252b58807eb076c30bad0ceb/packages/dom/src/utils/getDimensions.ts#L6-L11

where it uses `offsetWidth/Height` (which are rounded integers) instead of the fractional values you get from `getBoundingClientRect()` the width value cant be used to avoid the tooltip from shrinking (by setting that value as `tooltip.style.width`). (The use case is that the tooltip is a list of things and the user filters the list it should not get smaller, to avoid jumping)

I made a [codesandbox](https://codesandbox.io/s/floating-ui-dom-template-forked-4i5bnn?file=/src/index.js) showing this. 

### Using `rect.floating.width`:
(truncated because width becomes `257px` when it actually is `257.266px`)

<img width="424" alt="CleanShot 2022-07-13 at 19 11 28@2x" src="https://user-images.githubusercontent.com/351537/178791767-41227374-c8a8-49ab-879c-d7311bfaf389.png">

### Using `tooltip.getBoundingClientRect().width`:
<img width="438" alt="CleanShot 2022-07-13 at 19 11 40@2x" src="https://user-images.githubusercontent.com/351537/178791839-317e2b04-30ee-4d6a-b1b9-5c3d28c5acab.png">

Could the above linked if case just be removed so ´getBoundingClientRect´ is always used? I can make a PR if you want? (Or is there some benefit of using `offsetWidth/Height`?)

**Comment by atomiks** [comment]
I think there were problems with `transform: scale()` parents which impacts `.getBoundingClientRect` but not `.offsetWidth/Height`

**Comment by emattias** [comment]
Ok, maybe it could be an option that you send into `computePosition` or `size` middleware to use the other one?

Not sure if the correct `getBoundingClientRect` or `offsetWidth/Height` should be the default though? How common is the scale usage?

**Comment by emattias** [comment]
I need the floating element to not resize if the content changes because of user filtering the list, like in the video below. 

And when I added truncation of overflowing text we discovered this bug (and worked around it by getting the fractional value from `getBoundingClientRect` ourselves in our `apply` fun. I guess it would be better for the `reacts.floating.width` would be the fractional value instead of getting both `offsetWidth` and `getBoundingClientRect` every time, for possible performance gains.

https://user-images.githubusercontent.com/351537/178558491-30863101-a338-479d-ae7c-7089a6685869.mp4

**Comment by atomiks** [comment]
There are so many calls to DOM things during a single `computePosition` call, one extra `.getBoundingClientRect` will not make a difference so you can safely use that.

Maybe an alternative to `width` that continues to use the values would be:

```js
Object.assign(el.style, {
  minWidth: `${rects.floating.width}px`,
  maxWidth: `${rects.floating.width + 1}px`
});
```

**Comment by atomiks** [comment]
Re-opening, because I think we can use the computed `width`/`height` for the dimensions (as long as you're using `box-sizing: border-box`), which ignores scale but also returns fractional values.
