### ISSUE TITLE
[React DOM Interactions] Clicking a scrollbar closes a floating element when using `useDismiss` with `outsidePointerDown`.

### ISSUE THREAD

**Issue by threehams** [floating-ui/floating-ui#1779]
When using `useDismiss` with `outsidePointerDown`, a popover will close when using a scrollbar on a desktop browser. If a popover ends up off the page, this can prevent someone from scrolling it into view without having it disappear.
Tested with both MacOS and Windows.

Steps:
- Click "Pop Up"
- Scroll the page down by using the scrollbar.

https://codesandbox.io/s/floating-ui-react-dom-visual-test-forked-4e5krq

I'm not sure if this is reasonable to fix, as the browser doesn't appear to have anything built in for this, and it's been a problem in other libraries, but I thought it'd be worth knowing it happens. Here's a long Twitter discussion with some possible solutions, though some like `event.target.clientWidth` will also trigger relayout:

https://twitter.com/adamwathan/status/1530666459545931776

**Comment by atomiks** [comment]
I remember seeing that thread. I felt like the best solution is to make the dialog scrollable than the whole backdrop 🤷
