### ISSUE TITLE
Menu item losing focus as soon as menu is open

### ISSUE THREAD

**Issue by ally-bryand** [floating-ui/floating-ui#1780]
I'm running into an issue where I create a dropdown and set it to give focus to the first item, but it gives it focus and immediately takes it away. 

In order to see this behavior, use this sandbox: https://codesandbox.io/s/admiring-lamport-5wt3yg?file=/src/DropdownMenu.tsx and add `focusItemOnOpen: true` on line 107. 

I tried looking at the call stack in my own project, and this seems to be caused by a delayed call to `onMouseLeave`. For what it is worth, this happens without me moving my mouse after I click to open the dropdown. But I would still expect to be able to move the mouse from the trigger button to the options menu without losing focus since the documentation states that there should be a "safe cursor polygon" for exactly this.

**Comment by atomiks** [comment]
I guess it's caused by useClick's `pointerDown` causes it because the menu button receives focus on mouseup, which steals it after it opens
