### ISSUE TITLE
hide() middleware referenceHidden returning false for visibility:hidden

### ISSUE THREAD

**Issue by petey24** [floating-ui/floating-ui#1782]
Description: In the hide() middleware, [referenceHidden](https://floating-ui.com/docs/hide#referencehidden) is returning false when the reference element is hidden on the page with style _visibility:hidden_. Is this expected behavior? I have tested and it returns true for when the reference element is hidden with _display:none_ or _positioned outside_ of the viewport.

Example:
Please see example in the codepen. I have 3 hidden UL elements on the page.
1. Hidden with display:none
2. Hidden with visibility:hidden
3. Positioned outside of the viewport

You can switch the reference element on line 18 of the js file to see what referenceHidden returns for each element.
[https://codepen.io/Petey/pen/xxWVjwX](https://codepen.io/Petey/pen/xxWVjwX)

Happy to create a CodeSandBox example if required. Please reach out if you have any questions.

**Comment by atomiks** [comment]
It only checks if the ref element is positioned outside its viewport/is fully clipped. 

It's easy enough to check if the reference has `visibility: hidden` yourself, although, I _guess_ this could also be checked

**Comment by petey24** [comment]
Hi! thanks for the fast response and confirming.

That's right, at the moment we are checking for `visibility:hidden` ourselves. I just wanted to get your thoughts on the discrepancy between `display:none` and `visibility:hidden` as to me that meets the criteria from the doc below.

_Determines whether the reference element is currently not visible on screen for the user._

Happy to open a PR to include that check if you agree. Thanks!

**Comment by atomiks** [comment]
Since `hide` (part of the core) does not check for DOM stuff I don't think it will be feasible to implement. Maybe it should be renamed to `referenceClipped` or the doc wording changed.

**Comment by atomiks** [comment]
Changed doc wording

**Comment by petey24** [comment]
Got it. Thanks for looking at that.
