### ISSUE TITLE
[React DOM Interactions] SVG reference element breaks useDismiss when combined with useHover

### ISSUE THREAD

**Issue by nderscore** [floating-ui/floating-ui#1789]
# Demo

A minimal reproduction of the issue can be found here:
https://codesandbox.io/s/floating-ui-svg-reference-hover-dismiss-t1686i

# Steps to reproduce

* Have an `<svg>` reference element 
* Use `useHover` and `useDismiss` interactions
* Hover over the reference element to show the floating element
* Click on the floating element

# Expected result

* Nothing happens and text content inside the floating element is selectable.

# Actual result

* The floating element is dismissed upon click.

# Investigation

This is happening because `useHover` does not apply `pointer-events` styles to the reference element when it is an `SVGElement`. The `useHover` behavior skips setting pointer event styles when the reference element is not of type `HTMLElement`. Without the `pointer-events: auto` style applied to the reference and floating element, any click dismisses it.

# Possible resolution

I think `useHover` should apply the `pointer-events` styles for `SVGElement` references. Maybe the condition inside of `useHover` could be updated to check for `isHTMLElement()` _or_ `isSVGTag()`, where `isSVGTag()` is a function which checks if the element is an `<svg>` (and not some other inner-svg shape tag)

**Comment by atomiks** [comment]
https://github.com/floating-ui/floating-ui/blob/77c4b27a8096cafe06e58b2c7592317d6d3a3aea/packages/react-dom-interactions/src/hooks/useHover.ts#L276

I assume there's no issue if `isElement()` is used instead of `isHTMLElement` here?
