### ISSUE TITLE
[React] Consider exposing options prop types

### ISSUE THREAD

**Issue by jamesthomsondev** [floating-ui/floating-ui#1791]
I'm writing a wrapper component and would like to support the various options for the use hooks available when using '@floating-ui/react-dom-interactions'.

For example,

```
interface ITooltipProps {
  // ...
  clickOptions: <-- Something like UseClickOptions
  dismissOptions:  <-- Something like UseDismissOptions
  // etc.
  // ...
}

const Tooltip = ({ dismissOptions }: ITooltipProps) => {
// ...
  useClick(context, clickOptions),
  useDismiss(context, dismissOptions),
// etc.
// ...
}
```

**Comment by jamesthomsondev** [comment]
The issue exists for Middleware types as well

**Comment by atomiks** [comment]
You can extract them like this:

```js
type UseClickProps = NonNullable<Parameters<typeof useClick>[1]>
type UseDismissProps = NonNullable<Parameters<typeof useDismiss>[1]>
```

I think the middleware ones are exported but only under `@floating-ui/core` as `HideOptions`, `ShiftOptions`, etc., but you could do the same thing with those:

```js
type ShiftOptions = NonNullable<Parameters<typeof shift>[0]>
```

**Comment by jamesthomsondev** [comment]
The problem with that method is it doesn't give you anything useful in your IDE

Using Parameters<>:
![Screen Shot 2022-07-15 at 4 49 09 pm](https://user-images.githubusercontent.com/15789509/179167768-fe40e7df-c986-4ebc-9729-3c53dd83c687.png)

Using a properly exported type:
![Screen Shot 2022-07-15 at 4 49 15 pm](https://user-images.githubusercontent.com/15789509/179167887-f054a69c-d95c-4fe6-b853-38b2bcfc1b22.png)
