### ISSUE TITLE
Nested popover update position on parent scroll

### ISSUE THREAD

**Issue by AlexisVK** [floating-ui/floating-ui#1792]
Hello. I can't find if this issue is going to be fixed and the only [similar](https://github.com/floating-ui/floating-ui/issues/1267) issue was related to Popper-JS and was closed because of the new Floating-UI library.

Here you can find a [sandbox](https://codesandbox.io/s/friendly-mountain-2fs5zl) - it is forked from documentation and the only difference is a scrollable container style.

So the question is if this is going to be implemented on Floating-UI side or it should be handled manually with `update()` method?

**Comment by atomiks** [comment]
`animationFrame: true` in `autoUpdate` handles updating nested floating elements

**Comment by AlexisVK** [comment]
> `animationFrame: true` in `autoUpdate` handles updating nested floating elements

Thanks, it works! Closing this issue
