### ISSUE TITLE
Can't dismiss first popup after second

### ISSUE THREAD

**Issue by zhrk** [floating-ui/floating-ui#1795]
https://codesandbox.io/s/youthful-fire-e5uovd - it just [Nested Modal Popover](https://codesandbox.io/s/optimistic-jennings-jmpgfk?file=/src/NestedPopover.tsx) from docs and `useDismiss(context, { bubbles: false })`

Steps to reproduce:

1. Click "Click to open nested popover"
2. Click "More options..."
3. Click outside the second popup to close it
5. Click outside the first popup to close it

Expectation: 
The first popup was closed

Actually:
Nothing happened

Seems, after closing the second popup, the focus does not change to the first popup (`document.activeElement === document.body`)

**Comment by atomiks** [comment]
I guess the body steals focus from the reference as the pointer clicks there? You could manually focus the popover when the nested one closes then it should work.

**Comment by zhrk** [comment]
Yes, I can manually click the popup and then close it, but for example I want to implement a Dialog component that will support nested Dialogs

In this case, if user try to close Dialog by clicking outside of the content area, the UX will be broken because the user would normally expect the Dialog to close when the backdrop is clicked

https://codesandbox.io/s/funny-rhodes-i487jm?file=/src/App.tsx - example

**Comment by atomiks** [comment]
Got it, this seems to be a regression in `0.6.6` as it doesn't happen in `0.6.5`
