### ISSUE TITLE
[React DOM Interactions] stopPropagation in useClick

### ISSUE THREAD

**Issue by mjcampagna** [floating-ui/floating-ui#1800]
I'm using the `useClick` hook:

```js
  const { getFloatingProps, getReferenceProps } = useInteractions([
    useClick(context),
    useRole(context, { role: "tooltip" }),
    useDismiss(context),
  ]);
```

But I need to `stopPropagation` on the reference element, which `useClick` does not support.

My workaround feels very hacky:

```js
const referenceProps = useMemo(
  () =>
    getReferenceProps({
      ref: reference,
      ...children.props,
    }),
  [children.props, getReferenceProps, reference]
);
...
{
  ...referenceProps,
  onClick: (e: React.MouseEvent) => {
    e.stopPropagation();
    (
      referenceProps as Record<"onClick", React.MouseEventHandler>
    ).onClick(e);
  },
},
...
```

I believe this could be solved rather simply by adding a `stopPropagation` prop to the `useClick` hook, then using it as a condition within each of the hook's handlers, e.g.:

```js
onClick(event) {
  if (props.stopPropagation) {
    event.stopPropagation();
  }

  // etc. ...
```

**Comment by atomiks** [comment]
Should all of the open state changing hooks have that? `useHover` and `useFocus` as well

**Comment by atomiks** [comment]
Maybe it's better if there's a callback that gives you access to the event, then you can read stuff or call other methods as well.

```js
useClick(context, {
  onFire(event) {
    event.stopPropagation();
  },
});
```

**Comment by mjcampagna** [comment]
Thanks for the suggestion; that's a nice cleanup for my workaround.

I like the idea for the callback, though. That's much more flexible than making it a prop-based option.

**Comment by atomiks** [comment]
I think the prop getter technique makes more sense as you can specify it very granularly based on whatever event you like. I'll document this soon.

**Comment by tychenjiajun** [comment]
It seems that the prop getter technique doesn't fit `useHover`

**Comment by atomiks** [comment]
useHover doesn't use React events, maybe `event.nativeEvent.stopPropagation()` works?

**Comment by JasoonX** [comment]
Having the same issue

**Comment by atomiks** [comment]
@JasoonX can you describe what you're trying to do? Does the prop getter technique not work for you?

**Comment by adenisovgit** [comment]
@atomiks linked question.
Is it possible to call stopPropagation on outside click with useDismiss?
I have a clickable div, which opens some settings, and a button within that div which opens the popover. I would like on dismiss click just to close the popover, without entering settings.

**Comment by atomiks** [comment]
Is the pointer on the clickable div when dismissing? You can add a `<FloatingOverlay>` to block pointer-events and clicks behind the popover.

**Comment by adenisovgit** [comment]
Yes, I mean the situation, when the pointer on the clickable div.

**Comment by dan-son-optus** [comment]
Was there a solution for this? How do we stop propagation?

From what I can see, when you click on the reference element, it gets dismissed on mousedown, and the subsequent mouseup will activate the onClick in the element below... as if bubbling. 

I have tried this:
`
    useDismiss(context, {
      bubbles: false,
    }),
`

**Comment by atomiks** [comment]
@dan-son-optus do you have a codesandbox demo? You can call `stopPropagation` inside custom event handlers passed to the the prop getters seen in the last code block here: https://github.com/floating-ui/floating-ui/issues/1800#issuecomment-1192565224

**Comment by archit-p** [comment]
I'm using the `useClick` hook too, and faced the need to `stopPropagation()` after the click event. To do this (without support from the library), I wrapped the reference element with a new div, and stopped click propagation on that div. Code below:

```jsx
...
<div onClick={(e) => e.stopPropagation()}>
  <button ref={refs.setReference} {...getReferenceProps()}>
    Reference Element
  </button>
</div>
...
{isOpen &&
  <div ref={refs.setFloating} style={{ position: strategy, top: y ?? 0, left: x ?? 0 }} {...getFloatingProps()}>
    Floating Element
  </div>
}
```

**Comment by atomiks** [comment]
Does this not work? @archit-p

```js
<button 
  ref={refs.setReference} 
  {...getReferenceProps({ onClick: e => e.stopPropagation() })}
>
  Reference Element
</button>
```

**Comment by archit-p** [comment]
That works too! Don't need a workaround then. Thanks @atomiks!

**Comment by mmerezhko-hv** [comment]
Same problem but with onBlur. It works too!

> Does this not work? @archit-p
> 
> ```js
> <button 
>   ref={refs.setReference} 
>   {...getReferenceProps({ onClick: e => e.stopPropagation() })}
> >
>   Reference Element
> </button>
> ```

**Comment by KutnerUri** [comment]
I was just going to suggest it. I'm building a `<Dropdown>` component for my team, and I'd like to include the following props:
```tsx
type props = {
    // ..
    triggerOnHover?: boolean;
    triggerOnClick?: boolean;
    triggerOnClickAway?: boolean;
    triggerOnPopper?: boolean;
    triggerOnEsc?: boolean;

    onClick // <-- is regular onClick
    onHover // <-- just onMouseEnter / onMouseLeave
    onClickAway: MouseEvent => void;
    onPopperClick: MouseEvent => void;
    onEsc: KeyboardEvent => void;
```

It is possible I'd like to stop a toggle in the future, based on the source of the event.
It will be a nice feature to add :)

For example, I tried placing the floating inside the reference (it saves a `div`):
```tsx
<div ref={refs.setReference} {...getReferenceProps({ ...rest })}>
  {props.children}
  <div ref={refs.setFloating} {...getFloatingProps(popperProps)}>{pop}</div>
</div>
```

In this case, when triggerOnPopper={false} I'd like to ignore clicks when they come from the Floating.
@atomiks - WDYK?
