### ISSUE TITLE
ReferenceError: middlewareData is not defined

### ISSUE THREAD

**Issue by yelnyaface** [floating-ui/floating-ui#1803]
hi, what does `middlewareData` holds here?

```
    const {x, y, reference, floating, strategy, placement, middlewareData: {
        arrow: {x: arrowX, y: arrowY} = {

        }
    }} = useFloating({
        placement: 'right-start',
        middleware: [shift(), flip(), arrow({element: tooltipArrowRef})],
    });
```

when I do:
`console.log('middlewareData ----------> ' + JSON.stringify(middlewareData, null, 2));`

I get `ReferenceError: middlewareData is not defined`

**Comment by atomiks** [comment]
You're destructuring variables outside of `middlewareData`, not assigning it to a variable itself

```js
const {middlewareData} = useFloating();
const {x: arrowX, y: arrowY} = middlewareData;

console.log('middlewareData ----------> ' + JSON.stringify(middlewareData, null, 2));
```

**Comment by yelnyaface** [comment]
I see, thanks for clarifying!

but is the ` = {}` necessary from the `{arrow: {x: arrowX, y: arrowY} = {}}`?

**Comment by atomiks** [comment]
If you're using TypeScript, because it can potentially be undefined at runtime because it needs `arrow()` middleware in the array to exist inside the object.
