### ISSUE TITLE
CSS interface for using floating-ui

### ISSUE THREAD

**Issue by oluoluoxenfree** [floating-ui/floating-ui#1804]
Hi! 

Over at [Oddbird](https://www.oddbird.net/) we're working on a polyfill for CSS Anchor Positioning, and are going to use floating-ui to do a significant part of the heavy lifting as it seems to be the most comprehensive solution.

Is this something you'd be interested in? I'm going to fork the repo now to make changes to the tsconfig - concerns over browser compatibility with ES2020 - but would be great to be in conversation (or collaboration!) with you all whilst this is done.

Edit: no forking needed, apparently babel can do all of that for us!

Repo is very much at the beginning stages but is here: https://github.com/oddbird/css-anchor-positioning

**Comment by atomiks** [comment]
Hey, this sounds great. 

Is [this link](https://tabatkins.github.io/specs/css-anchor-position/) the latest spec that the implementation will follow? I am assuming since it's still an early draft it will be updated quite a bit (and so will the polyfill). 

What are your ideas for how the "CSS interface" will look like? Does it use `getComputedStyle()` to grab the properties specified in CSS and then transform them into something that Floating UI will understand?

**Comment by oluoluoxenfree** [comment]
Yes between this spec, [the explainer](https://github.com/MicrosoftEdge/MSEdgeExplainers/blob/main/CSSAnchoredPositioning/explainer.md) and ongoing conversations we have enough information to start, and as the spec is still very early as you said they may change syntax.

We're working iteratively so our implementation might affect the spec, as well as vice versa. We're on the polyfill train for the long haul in any case if there are significant changes. 😄 

We're using [stylis](https://github.com/thysultan/stylis) to generate an abstract syntax tree, which stylis can parse and find the relevant keywords and properties, which we can then hopefully use floating-ui to enact. Another person on our team used stylis to polyfill [CSS toggles](https://github.com/oddbird/css-toggles) so looks promising so far.

**Comment by atomiks** [comment]
So it looks like the [polyfill](https://github.com/oddbird/css-anchor-positioning) has been released 😄 

I'm going to close this now, and for discussion about CSS anchoring in general, I've converted https://github.com/floating-ui/floating-ui/issues/1952 into a discussion for anyone to add their thoughts in a better place.
