### ISSUE TITLE
Using safePolygon in useHover handleClose prevents clicks on outside elements from working

### ISSUE THREAD

**Issue by mihkeleidast** [floating-ui/floating-ui#1807]
When using safePolygon in the useHover hook to allow interactive contents in Tooltips, that will prevent the first outside click from working, as the hook adds `pointer-events: none;` to everything else. This is very evident when setting the close delay to a large time.

```
useHover(context, {
    handleClose: safePolygon(),
    delay: {
        close: 5000
    }
}),
```

Reproduction: https://codesandbox.io/s/epic-murdock-g3s412?file=/src/Tooltip.tsx

In there, hover over the button to show the Tooltip, then try to click the link below the button. The first click never works while the Tooltip is still open.

**Comment by atomiks** [comment]
pointer-events behind it are intentionally blocked while it's open https://github.com/floating-ui/floating-ui/issues/1722

**Comment by mihkeleidast** [comment]
I've read that issue and understand that the current solution solves that specific issue, but isn't this a bug if it breaks other usecases?

**Comment by atomiks** [comment]
I think it should block only while it's inside the safe polygon, so with large hide delays when it's outside it should clear the pointer-events style

**Comment by mihkeleidast** [comment]
That sounds good, yeah! One other thought: could there be a `<SafePolygon />` component exported by floating-ui that could be rendered inside the Tooltip and positioned correctly? It could render an actual SVG that would cover the safe area, then there wouldn't be a need for the pointer-events magic at all?

**Comment by atomiks** [comment]
In theory, but it's easier if the existing logic is kept here

**Comment by grantmagdanz** [comment]
I currently can't scroll when using `safePolygon` either. Will this fix that as well? The expected behavior is that if the cursor is outside the polygon scrolling should work as expected but inside it should not scroll.

**Comment by atomiks** [comment]
Does your layout have a scrolling element? The window/body scroll should still work normally.

Would you expect scrolling to work if the cursor is on the floating element or not for your case?

**Comment by grantmagdanz** [comment]
Yeah it's a scrolling element. Window / body scroll still works. But with `safePolygon` our scrolling component doesn't work.

It doesn't really matter what the behavior is when the cursor is on the floating element. If I had to choose, I'd say we'd prefer it to scroll.

**Comment by atomiks** [comment]
In your case, the browser behavior won't scroll the element if it's on the floating element when portalled, so I don't think that matters (works with window scroll though).

I think for your case, it also needs to clear the `pointer-events` style when the cursor lands back onto the reference (which keeps it open), that should scroll the element.

**Comment by atomiks** [comment]
Scrolling is also blocked when the cursor is over the reference, but I don't think it's that important, for now I will merge and release this fix. The real SVG polygon also has some problems to work out, if we decide to implement that

**Comment by grantmagdanz** [comment]
@atomiks let me know if it's better for me to open a new issue.

I pull the latest build with this change and, like you said, scrolling is disabled when the cursor is over the reference. Are there any workarounds to this? We're trying to implement a Slack / Discord style "reaction bar" on hover. This means a user is almost always hovering over a reference item when they want to scroll. I'll play around with it and see what I can find too.

**Comment by grantmagdanz** [comment]
This seems to be a hacky workaround but not sure what sort of behavior it breaks:

```
  useEffect(() => {
    if (isOpen && refs.floating.current) {
      const doc = refs.floating.current.ownerDocument ?? document
      doc.body.style.pointerEvents = 'auto'
    }
  }, [isOpen])
```

**Comment by atomiks** [comment]
You should be fine if there's nothing else that can be hovered (and open things) beneath the polygon area. This includes nested dropdown menus like in the CodeSandbox example.

**Comment by atomiks** [comment]
SafePolygon would solve all the issues yes, I think that's the best solution.

By disabling the check, you mean remove the test? You can add a `#root, #floating-ui-root { pointer-events: initial; }` on the React root/portaled roots for now. Or even `body { pointer-events: initial !important }` if you don't care about pointer-events when testing anywhere else.

**Comment by atomiks** [comment]
Yep we should track it. I also noticed macOS' auto-hiding scrollbars appear when a scrolling element has `pointer-events: none` put on it in Chrome (doesn't happen in FF/Safari). SafePolygon would have none of these unforseen side effects since it's local

**Comment by mjcampagna** [comment]
> Yep we should track it. I also noticed macOS' auto-hiding scrollbars appear when a scrolling element has `pointer-events: none` put on it in Chrome (doesn't happen in FF/Safari). SafePolygon would have none of these unforseen side effects since it's local

I came here looking for a solution to exactly this. When I use the `safePolygon` function, scrollbars appear in several scrollable columns of our app. It's unsightly. 

Is there a fix for this?

**Comment by mjcampagna** [comment]
Updating the package and using this seems to have it solved:

```
safePolygon({
  blockPointerEvents: false,
}
```

**Comment by atomiks** [comment]
The docs page has a workaround for that while preserving the option: https://floating-ui.com/docs/useHover#blockpointerevents (you could also use custom scrollbars). 

If we could solve the real polygon problem in Firefox, then that could be merged as a feature and used instead.
