### ISSUE TITLE
Floating misalignment

### ISSUE THREAD

**Issue by diegohaz** [floating-ui/floating-ui#1809]
![Screencast demonstrating the issue](https://user-images.githubusercontent.com/3068563/180518492-9cffd419-5e04-4a8b-b61b-bcd8646946a3.gif)

The floating element is initially misaligned under certain conditions:

- A wrapper div with `position: relative; display: flex; justify-content: flex-end;`.
- An intermediate div wrapping the reference and the floating elements.
- The floating element without a defined `width` using the absolute strategy.
- The floating element is positioned using [`transform: translate()`](https://floating-ui.com/docs/misc#subpixel-and-accelerated-positioning) instead of `top` and `left`.

Repro: https://codesandbox.io/s/floating-ui-dom-template-forked-btknl4?file=/src/index.js

Related: https://github.com/ariakit/ariakit/issues/1657

**Comment by atomiks** [comment]
Add `top: 0` and `left: 0` in the initial CSS (or prior to the call). The layout of the element prior to being positioned needs to have the final dimensions ready.

> Setting top and left to '0' initially minimizes layout interference with the dimensions of the element, so that its final dimensions are ready before being positioned.

More info: https://github.com/floating-ui/floating-ui/issues/1736

**Comment by diegohaz** [comment]
Thanks, @atomiks! I suggest updating the issue template with a CodeSandbox with those styles applied.
