### ISSUE TITLE
[React] Add a SafePolygon component to replace the current safePolygon close handler in useHover

### ISSUE THREAD

**Issue by mihkeleidast** [floating-ui/floating-ui#1811]
Split out from https://github.com/floating-ui/floating-ui/issues/1807

The current global solution for disabling pointer-events is flaky, some issues raised in that linked ticket:

> We are still running into issues in automated browser tests that don't actually move the cursor off the reference element, rather it tries to just click different elements in sequence. This fails because tools like playwright test before clicking an element if the element is clickable, and this check fails because of the global pointer-events: none;. 

> I also noticed macOS' auto-hiding scrollbars appear when a scrolling element has pointer-events: none put on it in Chrome (doesn't happen in FF/Safari). SafePolygon would have none of these unforseen side effects since it's local

> I pull the latest build with this change and, like you said, scrolling is disabled when the cursor is over the reference. Are there any workarounds to this? We're trying to implement a Slack / Discord style "reaction bar" on hover. This means a user is almost always hovering over a reference item when they want to scroll. I'll play around with it and see what I can find too.

All of these might be fixed by a more local solution.

There could be a <SafePolygon /> component exported by floating-ui that can be rendered inside the Tooltip and positioned correctly. It should render an actual SVG with the correct shape that would cover the safe area. Then there wouldn't be a need for disabling pointer-events globally.

**Comment by atomiks** [comment]
My current idea is to disable `pointer-events: none;` behavior in `useHover/safePolygon` by default. 

Users can opt-in to blocking pointer-events using the `SafePolygon` component. This is already largely implemented in the `DebugSafePolygon` file, the pointer-events would apply to the `<polygon>` only and the outer fixed svg would have `none`.

Right now a polygon isn't generated in certain situations in the `safePolygon` function (when a regular rect works better), but can be changed to always render a polygon with the right shape to block pointer-events.

**Comment by atomiks** [comment]
Also, the workaround for disabling the current global `pointer-events` behavior, added after the `useInteractions` hook in your component:

```js
useLayoutEffect(() => {
  if (open && refs.floating.current) {
    const doc = refs.floating.current.ownerDocument ?? document;
    doc.body.style.pointerEvents = '';
  }
}, [open]);
```

**Comment by mihkeleidast** [comment]
Would there be a need for the current handleClose/safePolygon at all? I'm thinking that if the SafePolygon component is rendered inside the floating element, hovering over that would prevent closing (I think there already are checks for preventing closing whyle the floating element is being hovered).

**Comment by atomiks** [comment]
No, because the polygon is dynamically generated.

I just implemented it, it will look like this.

```js
const [points, setPoints] = useState<Array<string | null>>([null, null]);

useHover(context, {
  handleClose: safePolygon({setPoints}),
}),

return (
  <>
    <SafePolygon points={points} />
  </>
);
```

There are actually two polygons being generated (one triangle-ish and one rect). The rect is so you can move the cursor back and forth between the rectangular trough area between the two elements without it closing (_slightly_ visually unappealing to me, not super important, but it's included for that reason)
