### ISSUE TITLE
Space key should not be ignored

### ISSUE THREAD

**Issue by what-is-a-crow** [floating-ui/floating-ui#1812]
## Description

The space key is being ignored in `useClick`, which breaks text input-based floating menus.

### Steps to reproduce
- Create a select-like component with `useListNavigation`, `useClick`, and a text input as the reference field
- Click into the text input
- Hit the space key

#### Expected behavior
The space key enters a space in the text input

#### Actual behavior
The space key is ignored

**Comment by what-is-a-crow** [comment]
My suggestion is to provide an `ignoreSpaceKey` property to `useClick` that defaults to true. If this feels like a safe addition, I can open a pull request.

**Comment by atomiks** [comment]
What version? This is checked for:

https://github.com/floating-ui/floating-ui/blob/22fcda255cbd2ca2464fa63ea8f5b45cef78c768/packages/react-dom-interactions/src/hooks/useClick.ts#L106-L109

**Comment by what-is-a-crow** [comment]
@atomiks apologies, I missed a key detail- `isSpaceIgnored()` returns false when the reference node is virtual, which mine must be in order to provide the dual-focus experience of a typeahead. We're using version 0.6.6 of `@floating-ui/react-dom-interactions`.

**Comment by atomiks** [comment]
I think `useFocus()` is much better than `useClick()` for something like that because it works more appropriately with keyboard focus.

But the check uses `refs.domReference.current` (real DOM node) not `refs.reference.current` (virtual element), which should be the input reference? Do you have a sandbox demo?

**Comment by what-is-a-crow** [comment]
`useFocus` may be a better candidate- I'll play around with that tomorrow to see if I can swap those out (it'll require at least minor surgery).

And you're right- I assumed it was an empty reference and didn't actually check, but `refs.domReference.current` is pointing to our container div, so it's not failing because it's not a real DOM node but rather because it _isn't_ a text input. We have two references, one for the container and one for the text input. It's a little convoluted but that's how we ended up achieving the set of desired behaviors. If swapping out the hooks (focus for click) is unsuccessful, I'll toss our source code into a sandbox.

**Comment by what-is-a-crow** [comment]
I was able to make the suggested change by applying `useClick` for button-type fields (standard select behavior) and `useFocus` for text input-type fields (combobox behavior). Had to tweak some other configuration to preserve the intended behavior but it was mostly straightforward. Thank you for your help.
