### ISSUE TITLE
[DOM] Wrong placement when an ancestor uses transform and translate when placed in shadow DOM

### ISSUE THREAD

**Issue by TomRauchenwaldUnifits** [floating-ui/floating-ui#1815]
When floating-ui is used in a webcomponent, and that webcomponent is placed in a container where an ancestor uses a CSS transformation (e.g. transform: translate(..)), the floating element is displaced.

This is a similar issue to #1488, I based the repro on the codepens found in the ticket.
The difference is that the positioning fails if the trigger/floating element is placed in a container, and that div is added to the shadowDom instead of the trigger/floating elements.

OK: https://codepen.io/TomRauchenwald/pen/GRxMMoo
Shadow DOM looks like this:
```html
<button>Trigger</button>
<div class="popper-container"></div>
```

![image](https://user-images.githubusercontent.com/98090196/181191660-574a50a5-84d2-4ec3-b478-b786fb77bfdc.png)

Not ok: https://codepen.io/TomRauchenwald/pen/VwXMzXg
Shadow DOM looks like this:
```html
<div>
<button>Trigger</button>
<div class="popper-container"></div>
</div>
```
![image](https://user-images.githubusercontent.com/98090196/181191754-290229e7-da12-4142-b7b8-950b397be955.png)

The placement is done like this:
```javascript
this.triggerElement.addEventListener("click", () => {
      computePosition(this.triggerElement, this.popperElement, {
        placement: "bottom-end",
        strategy: "fixed"
      }).then(({ x, y }) => {
        Object.assign(this.popperElement.style, {
          display: "block",
          left: `${x}px`,
          top: `${y}px`
        });
      });
    });
```

**Comment by atomiks** [comment]
Previous fix from the other issue for context, maybe something similar needs to be done for this:

https://github.com/floating-ui/floating-ui/blob/22fcda255cbd2ca2464fa63ea8f5b45cef78c768/packages/dom/src/utils/getOffsetParent.ts#L25-L27

**Comment by atomiks** [comment]
1.0.1
