### ISSUE TITLE
One reference, multiple floating components?

### ISSUE THREAD

**Issue by mjcampagna** [floating-ui/floating-ui#1821]
We want a button with these behaviors:

* on hover, displays its title in a tooltip;
* on click, opens an action menu.

So the button is a singular reference, triggered two different floating components -- a tooltip and a drop-down menu -- on its hover and click events, respectively.

Is this possible? Is there a best practice for this? Here's what I'm thinking -- in React -- but I'm also wondering whether there's a more efficient way to do this:

```js
const {
  context: hoverContext,
  floating: hoverFloating,
  reference: hoverReference,
} = useFloating({ ...hoverConfig });

const {
  getFloatingProps: hoverGetFloatingProps,
  getReferenceProps: hoverGetReferenceProps,
} = useInteractions([
  useHover(hoverContext),
]);

const {
  context: clickContext,
  floating: clickFloating,
  reference: clickReference,
} = useFloating({ ...clickConfig });

const {
  getFloatingProps: clickGetFloatingProps,
  getReferenceProps: clickGetReferenceProps,
} = useInteractions([
  useClick(clickContext),
  useDismiss(clickContext)
]);

return (
  <div {...hoverGetReferenceProps}>
    <button {...clickGetReferenceProps}>Title</button>
  </div>

  <Portal>
    <div {...hoverGetFloatingProps}> ... </div>
    <div {...clickGetFloatingProps}> ... </div>
  </Portal>
);
```

**Comment by atomiks** [comment]
You don't need wrapper tags: merge the refs on the reference and call the props inside the other prop getter. 

```js
const {
  context: hoverContext,
  floating: hoverFloating,
  reference: hoverReference,
} = useFloating({ ...hoverConfig });

const {
  getFloatingProps: hoverGetFloatingProps,
  getReferenceProps: hoverGetReferenceProps,
} = useInteractions([
  useHover(hoverContext),
]);

const {
  context: clickContext,
  floating: clickFloating,
  reference: clickReference,
} = useFloating({ ...clickConfig });

const {
  getFloatingProps: clickGetFloatingProps,
  getReferenceProps: clickGetReferenceProps,
} = useInteractions([
  useClick(clickContext),
  useDismiss(clickContext)
]);

return (
  <>
    <button 
      ref={mergeRefs([hoverReference, clickReference])} 
      {...hoverGetReferenceProps(clickGetReferenceProps())} 
    />
    {hoverOpen && <div ref={hoverFloating} {...hoverGetFloatingProps() />}
    {clickOpen && <div ref={clickFloating} {...clickGetFloatingProps() />}
  </>
);
```

**Comment by EvHaus** [comment]
@atomiks Sorry to revive this old thread, but I think there are still some issues with this. I took your original [CodeSandbox](https://codesandbox.io/s/trusting-mendeleev-49qn11?file=/src/App.tsx) that shows off how to make this work, and the only change I made was to break out the Menu and the Tooltip into separate components (which I imagine most users would want to do to allow for re-useability), which also required the use of `React.forwardRef`.

When doing this, I get strange behaviours:

- `<Tooltip><Menu><button /></Menu></Tooltip>` shows both tooltip and menu as expected 👍 
- `<Menu><Tooltip><button /></Tooltip></Menu>` only shows the tooltip 😢 

From what I can tell merging refs is working properly, but something in the merging of reference props isn't working correctly.

You can see the minimal repro here: https://codesandbox.io/s/silent-rgb-hcg8vo?file=/src/App.tsx

Any ideas?

**Comment by S-Ladros** [comment]
the same trouble when trying put Tooltip in Modal (both components got from the docs examples)

**Comment by atomiks** [comment]
@EvHaus  It's because you aren't forwarding all the props that the Menu passes to the Tooltip component into the prop getter.  Since it clones its child element, which for the Menu is the Tooltip, those props need to be forwarded down.

You may also need to merge the children.props with them.

<img width="626" alt="Screen Shot 2022-09-15 at 3 02 14 pm" src="https://user-images.githubusercontent.com/22450188/190318660-5d431581-76df-480c-afb6-463eb3136ff7.png">

**Comment by EvHaus** [comment]
Nice, that did the trick! Thank you.

Here's the updated sandbox with the fix in case others are running into the same problem: https://codesandbox.io/s/silent-rgb-hcg8vo?file=/src/App.tsx

**Comment by anand24816** [comment]
Hey Team, I am trying to open the menu (which has nested submenu) within tooltip pop-over which appears on hover in it's trigger component. 
but the moment focus go away from trigger popover to click on nested menu, the parent popover loses mouse and it goes away. Do you know, how to handle such scenario?
