### ISSUE TITLE
[bug] MacSelect demo: Safari overscroll scrolls body

### ISSUE THREAD

**Issue by natew** [floating-ui/floating-ui#1826]
Unfortuantely `overscroll-behavior: contain` not coming to Safari until next version. Small window height lets you scroll the body once you hit the end of the Select. Seems like `FloatingOverlay lockScroll` should ideally have a solution, but not sure if there is one.

**Comment by atomiks** [comment]
`lockScroll` is enabled for desktop Safari but iOS safari breaks the positioning behavior because of the technique used to ensure the body gets locked. `react-remove-scroll` is probably the best solution for x-browser scroll locking for this particular component `<FloatingOverlay lockScroll>` works best for regular modal dialogs.

**Comment by natew** [comment]
It doesn’t work on desktop Safari at least on my end. Just testing the MacSelect example you have, window sized small. 

Problem I had with react-remove-scroll are a few: scrolling outside a select makes sense, and could optionally clear the select viewport. And it has caused in some apps the body to scroll back to the top, though realizing now that seems like an edge case maybe as I imagine the whole point of the library is to preserve the scroll.

**Comment by atomiks** [comment]
Works for me on 15.4. [This demo does not work for you?](https://kp6479.csb.app) It uses `overflow: hidden` which works pretty standardly across desktop browsers, only iOS is annoying about it.

There are two main flaws with `react-remove-scroll` that I found:

- Pinch-zooming on trackpads doesn't work
- Elastic scrolling breaks sometimes

`react-aria` has something similar but also has issues

Wonder if it's worth putting energy into making a lock scrolling function that tries to solve everything 😅  If those problems are unsolvable I'd rather not :\

**Comment by atomiks** [comment]
Closing as stale, but if you have a demo video of the problem I can re-open. I'd need the version of desktop Safari it occurs on
