### ISSUE TITLE
[DOM] elements with overflow hidden but display inline or contents should not be an overflow ancestor

### ISSUE THREAD

**Issue by sventschui** [floating-ui/floating-ui#1831]
If I'm not mistaken, elements that have an overflow hidden (or auto, etc.) should not be taken into account when determining overflow ancestors as the following CSB shows browsers ignore the overflow property and the calculation of the `referenceHidden` flag of the `hide` middleware is wrong as the elements have a `clientHeight`/`clientWidth` of 0 (the middleware says the reference is always hidden, which is not true).

Note I originally detected this with custom elements (defaulting to `display: inline` and thus always being an overflow ancestor if a floating element is used in a custom element) but it seems it also applies to all other elements with `display: inline` (or `contents`).
 
https://codesandbox.io/s/floating-ui-custom-element-overflow-hslr9n?file=/src/index.tsx

**Comment by atomiks** [comment]
For some reason locally `display: inline` is clipping the reference.

`contents` doesn't though...

<img width="789" alt="Screen Shot 2022-08-05 at 5 26 53 pm" src="https://user-images.githubusercontent.com/22450188/183025035-94c3f514-28ec-4024-a3e9-63529c37ed8b.png">

**Comment by sventschui** [comment]
Do you have a CSB of this repro? I somehow can not reproduce this. For me all content of an inline element is **not** clipped
