### ISSUE TITLE
autoUpdate function Failed to execute 'getComputedStyle' on 'Window' vue 3

### ISSUE THREAD

**Issue by yurenklimbu** [floating-ui/floating-ui#1840]
Package : `@floating-ui/dom`
Package Version: `1.0.0`

Production Demo
https://codesandbox.io/s/zen-cannon-wvw5w4

I'm trying to use autoUpdate function for update position. It's working fine in regular ui but with vue v-if I got this error `Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.` 

Thanks!

**Comment by atomiks** [comment]
If you log the elements you're passing, both are `null` at the time `computePosition()` gets called, for whatever reason.

```js
 console.log(this.$refs.button, this.$refs.tooltip)
```
