### ISSUE TITLE
Element overflows the viewport

### ISSUE THREAD

**Issue by axelthat** [floating-ui/floating-ui#1844]
I have a context menu that I want to open and position on right click. This is the result,

https://user-images.githubusercontent.com/31353695/183277756-5d052f67-b163-41a6-b40d-bdb44535c803.mov

As you can see, the menu overflows the viewport.

Demo:  https://codesandbox.io/s/floating-ui-dom-template-forked-vu6jzr?file=/src/index.js

What am I doing wrong?

**Comment by atomiks** [comment]
The element cannot be measured when it has a `display: none` style at the time `computePosition` is called. The block display should be assigned prior.

<img width="465" alt="Screen Shot 2022-08-07 at 4 19 55 pm" src="https://user-images.githubusercontent.com/22450188/183278071-38bfd2d8-3874-4907-b7aa-0419ba12d24f.png">

**Comment by axelthat** [comment]
Oops lol. Thanks for your swift response.
