### ISSUE TITLE
Using `useFloating` with jest and testing-library

### ISSUE THREAD

**Issue by ling1726** [floating-ui/floating-ui#1845]
Sorry for not using the sandboxes provided, but this is a problem that happens on the `node` environment, so I created a stackblitz

https://stackblitz.com/edit/node-75er2t?file=index.jsx

You can see that when rendering the `<Floating />` component (code taken from docsite), there is immediately an error that states that something was not called in `act`. I think that this might be a consequence of `computePosition` being asynchronous.

It could be that I'm missing some kind of knowledge how to use floating-ui correctly in tests, but I keep getting this error even when try to use the least amount of code.

**Comment by atomiks** [comment]
Docs explain: https://floating-ui.com/docs/react-dom#testing (I made an issue about this on testing-lib repo, but it doesn't seem like they'll change the timing of the cleanup function)

**Comment by ling1726** [comment]
Ah I must have missed that from the docs, thx!

**Comment by ling1726** [comment]
Feel free to close this, but IMO it's quite a scary proposition for apps who do a lot of unit testing in their code... to bump to floating-ui from popper, every single test with any floating-ui usage needs to be updated.

I wonder why it wasn't an issue for v2 🤔🤔

**Comment by atomiks** [comment]
`react-popper` had the same warning message and needed the same technique to flush the queue as the first update was async, custom wrappers that don't use `setState` could avoid it though

**Comment by ling1726** [comment]
In our case we are actually using a wrapper without `setState`.

Howver, it seems that during the cleanup JSDOM is torn down and `document` no longer exists: https://github.com/microsoft/fluentui/blob/0aa4e377b127d0b032185919973d606d30e0eedd/packages/react-components/react-positioning/src/usePositioning.ts#L79. Then `computePosition` runs, which results in errors in node > 15

**Comment by atomiks** [comment]
I forgot to respond somehow, yes a new issue with a minimal repro of the problem would be good
