### ISSUE TITLE
getReferenceProps breaks props with "on" in the beginning of the propName

### ISSUE THREAD

**Issue by J4v4Scr1pt** [floating-ui/floating-ui#1860]
I just came across this creating our own tooltip replacing our old tippyTooltip.

We have a prop in one component that is onlyShowVotes.
After replacing the old tooltip we got this error:
Warning: Failed prop type: Invalid prop `onlyShowVotes` of type `function` supplied to `ForwardRef`, expected `boolean`.

Started to investigate it and found that after renaming the prop the warning went away.

And the only reason it became a function must be that the getReferenceProps translate it to a function becasue it starts with "on" because of the word only.

![image](https://user-images.githubusercontent.com/5929055/185061398-e2511761-9a68-47d1-b97f-656b524ed977.png)
![image](https://user-images.githubusercontent.com/5929055/185061446-0f5bf4b8-6284-4301-b5b6-7180b44f1cf2.png)

**Comment by atomiks** [comment]
I think the code at the bottom just needs to be moved into the `if` block

https://github.com/floating-ui/floating-ui/blob/15d1f49b966f9cf472141749f6ebdb4c75e62d5d/packages/react-dom-interactions/src/useInteractions.ts#L28-L34

As a workaround (without renaming your prop) you can just not pass it through the prop getter and add it as a normal prop in your JSX.

**Comment by J4v4Scr1pt** [comment]
Ahh ok thx! 

And keep up the great work! 😄
