### ISSUE TITLE
[dom] Add better support for cross-document elements

### ISSUE THREAD

**Issue by ciampo** [floating-ui/floating-ui#1869]
Currently, the library doesn't handle very well scenarios in which the reference and the floating elements are rendered in two different documents — for example, when the reference is inside an iframe, and the floating element is rendered outside of the iframe.

For more context, see conversation in #1868

**Comment by atomiks** [comment]
The [contributing](https://github.com/floating-ui/floating-ui#contributing) section should help you get started with the visual playground. You could add a new route with an iframe that has the reference element inside of it and the floating element outside of it. 

As for what exactly needs to be amended to support the cross-document elements properly I'm not sure. It was suggested in another issue that the `getBoundingClientRect` util can be modified to add offsets or something. Note that it also needs to work with the clipping rect detection as well.

**Comment by ciampo** [comment]
Hey @atomiks , I started working on this in https://github.com/floating-ui/floating-ui/pull/1884 and I was wondering if I could somehow collaborate with you and ask for some pointers, since I don't know the codebase very well.

Maybe you could join the [WordPress Slack community](https://make.wordpress.org/chat/) and ping me there? My username is `mciampini`. I would really appreciate it 🙏
