### ISSUE TITLE
[core] `limitShift`: add option to pass an offset amount that is always added to the min/max values

### ISSUE THREAD

**Issue by ciampo** [floating-ui/floating-ui#1870]
Currently, the `limitShift` function considers two types of "offsets" [when computing the min/max limits](https://github.com/floating-ui/floating-ui/blob/15d1f49b966f9cf472141749f6ebdb4c75e62d5d/packages/core/src/middleware/shift.ts#L176-L213) for the `shift` middleware:

- the offset from the `offset` middleware (added 
- the offset from the `offset` option (part of the `limitShift` arguments)

Both of these offsets are added arbitrarily, following a logic that depends on the axis and the popover's placement.

This logic comes as a limitation when the consumer of the library needs to add an offset to the popover that is always applied. In that case.

That's why I'm proposing that we add a new option for the `limitShift` function, in order to be able to pass an offset amount that gets always added when computing the min/max limits — not sure what the best name for this option would be.

For more context, see the conversation in #1868

**Comment by ciampo** [comment]
Hey @atomiks , let me know what you think about this proposal.

I'm happy to start working on this from next week, if you agree.

**Comment by atomiks** [comment]
Let's see if fixing cross-document element supports makes this unnecessary, otherwise if it's still necessary then consider it
