### ISSUE TITLE
[DOM] Is there a way to make the floating content automatically scroll the page to make it's contents visible?

### ISSUE THREAD

**Issue by LucasNovaes2016** [floating-ui/floating-ui#1871]
Using the _@floating-ui/react-dom-interactions_ library, let's say we have an input that triggers a dropdown that must always be placed on the bottom of it (therefore, the "flip()" property is not passed to useFloating()). If the input is too close to the bottom of the page (first screenshot), when you click on it to open the floating element, the floating content will not be visible due to insufficient space (second screenshot). Is there a way to make the page scroll "automatically" so the floating content is fully visible? (like in the screenshot 3) ? I looked for something like that in the documentation, but I couldn't find anything related. I know using "flip()" solves the issue by placing the floating element on the top of the input, but In this case, I would like the floating element to always be placed on the bottom, while still visible. 
 
sandbox: https://codesandbox.io/s/o9dmz3?file=/src/App.tsx

![1](https://user-images.githubusercontent.com/22013263/187048168-48bcf887-f6b5-4852-be6a-dad43d5593b4.png)
![2](https://user-images.githubusercontent.com/22013263/187048260-d42bea92-afac-4fec-822a-41660bc6f980.png)
![3](https://user-images.githubusercontent.com/22013263/187048261-5393f7fe-a825-4144-9c74-2b95a136f242.png)

**Comment by atomiks** [comment]
One solution is usually to use `size()` and allow the element itself to be scrolled, however if it always must remain at the bottom then it might only be like 10px tall if the input is right at the bottom of the screen.

 So in this case if you call `.focus()` on the floating element when it opens, the browser should scroll the page for you so it becomes fully visible. 

```js
  useLayoutEffect(() => {
    if (open) {
      // Wait for it to be positioned
      requestAnimationFrame(() => {
        // Make the browser scroll to make it all visible
        refs.floating.current?.focus();
        // Keep focus on the reference input element
        refs.reference.current?.focus();
      });
    }
  }, [open, refs]);
```

**Comment by LucasNovaes2016** [comment]
I used the code above, but for some reason when the floating element is focused, the scroll doesn't happen.

I got the expected behavior by scrolling directly to the element inside the floating content when it's open. I believe I will use this solution for now.

 
`
useLayoutEffect(() => {
    if (open) {
      document.getElementById("innerFloatingContentId")?.scrollIntoView({ behavior: "smooth" });
    }
  }, [open]);`

**Comment by atomiks** [comment]
Your method is way better yeah especially since you can smoothly animate it 👍
