### ISSUE TITLE
[DOM] Floating element flickers between different placements on smaller screen sizes

### ISSUE THREAD

**Issue by aliceHendicott** [floating-ui/floating-ui#1872]
On small screen sizes when using either the `flip` or `autoPlacement` middleware alongside `autoUpdate`, the floating element will flicker between different placements without ever settling on a position.

https://user-images.githubusercontent.com/40346716/187103206-2c44e093-d6c0-4837-93b5-45773c05d6d2.mov

I think potentially this could be happening because of the `ResizeObserver` observing the floating element (which is definitely important to keep). When the position is updated on a small screen like this, the floating element size also changes, causing another update moving it again, causing another resize update and so on.

## To reproduce

- Visit https://codesandbox.io/s/async-fire-1382wl?file=/src/App.js:327-337&resolutionWidth=399&resolutionHeight=416
- Scroll down
- The floating element (text) will flicker between top and left positions.

**Comment by atomiks** [comment]
It's not the `ResizeObserver` but the way the CSS layout acts upon the floating element when it changes placement/position coords.

The `<body>` element does not span the entire width of the container if you check DevTools, is the floating element's `offsetParent`, which is likely the root of the problem. 

Giving `position: relative` to the `width: "auto"` container removes the flicker, as the floating element's width can correctly adjust for different placements.

**Comment by atomiks** [comment]
Closing as in general this problem needs to be worked around by ensuring the floating element does not get resized due to the CSS layout when it changes placement. 

This can involve making an ancestor element its `offsetParent` by giving it `position: relative` or such
