### ISSUE TITLE
[React DOM Interactions] disabled button cause Tooltip to stay

### ISSUE THREAD

**Issue by Maetes** [floating-ui/floating-ui#1874]
Hi there, 

first of all sorry that I don't give a reproduceable sandbox. If you really want, I can create it, but I think a quick gif is enough since I know why this issue happens.

![button_issue](https://user-images.githubusercontent.com/46278653/187363348-a0433710-7173-4d5d-9289-d2f7183aefe9.gif)

I use Mantine UI which relies on Floaring-ui and the useHover hook. As you see when the button goes disabled the useHover hook don't fire the mouseleave event anymore, so that the Tooltip stays where it is. My suggestion is to just swawp the eventlistener in favor of the pointer events, which correctly fire the pointerleave even when the element is disabled. I'll create a pull request and you can choose. Hope that you will join my oppinion

**Comment by atomiks** [comment]
See the answer here: https://github.com/floating-ui/floating-ui/discussions/1865

**Comment by Maetes** [comment]
Sorry. Thanks @atomiks
