### ISSUE TITLE
[React DOM Interactions] useDismiss hook behavior

### ISSUE THREAD

**Issue by zhrk** [floating-ui/floating-ui#1879]
I have a Dropdown component, which in the mobile version (iPhone SE 375x667), when opened, instead of Popup, shows options from the bottom of the screen

https://codesandbox.io/s/magical-wilbur-bd9pqk?file=/src/Dropdown.tsx

The problem is that if these are nested Dropdowns, then closing the upper layers becomes problematic, because when clicking outside the floating element, it can immediately open another Dropdown and I can’t basically close it without a separate button or clicking on a non-interactive area

This behavior is only present on touch screens, is it possible to configure this to be the same as on the desktop?

**Comment by atomiks** [comment]
It sounds like you want to change this even to be `pointerup` for touch? I've been thinking of renaming the option to `outsidePress` and allowing configuration to decide which event to use.

https://github.com/floating-ui/floating-ui/blob/9eb72f2cc14f758011e9e207cf9f145da634c589/packages/react-dom-interactions/src/hooks/useDismiss.ts#L128

```js
outsidePress: 'pointerdown' | 'pointerup' // not sure if 'click' is also desirable
```

**Comment by zhrk** [comment]
Not sure about `pointerup`, I just tried using it but getting the same result. When using the `click` event, everything worked as expected

It would be great if I could choose which event to use

**Comment by atomiks** [comment]
Does `mousedown` work? That retains the behavior using a mouse, but could fix touch as well.

`mousedown` was previously used but it has different semantics to `pointer` on touch in that it acts more like `click`

**Comment by zhrk** [comment]
Yes, the `mousedown` event also works as expected
