### ISSUE TITLE
[React DOM Interactions] Position is off inside a scrolling flex container

### ISSUE THREAD

**Issue by feketegy** [floating-ui/floating-ui#1882]
When opening the floating div inside a scrolling flex container the position is not moving with the anchor element.

I don't think there's an easy solution to this, I had similar problems with my own implementation of a popup menu component.

https://codesandbox.io/s/floating-ui-incorrect-position-when-scrolling-iriquo?file=/src/App.js

If you look at the sandbox example above, the popup div element should scroll with the anchor div element.

**Comment by atomiks** [comment]
See https://floating-ui.com/docs/react-dom#updating
