### ISSUE TITLE
@floating-ui/core and @floating-ui/core   does not run in earlier browsers

### ISSUE THREAD

**Issue by gyf30827** [floating-ui/floating-ui#1888]
@floating-ui/core and @floating-ui/dom  is not transer es5  
in content has  const let...
![image](https://user-images.githubusercontent.com/22958382/190565203-1e0540a9-e403-48f3-bfb0-28e7b8c21a62.png)

**Comment by atomiks** [comment]
Only modern browsers are supported, no IE11, old mobile etc.

If you need their support, you can transpile the `node_modules` folder, and add any required polyfills.

**Comment by gyf30827** [comment]
I  transpile the node_modules folder ，But there's an error
![image](https://user-images.githubusercontent.com/22958382/190594686-0da55c29-37d0-40e5-bddc-2da8ecfb195d.png)
