### ISSUE TITLE
I  transpile the node_modules folder ，But there's an error  @atomiks

### ISSUE THREAD

**Issue by gyf30827** [floating-ui/floating-ui#1889]
I  transpile the node_modules folder ，But there's an error  @atomiks 
![image](https://user-images.githubusercontent.com/22958382/190594686-0da55c29-37d0-40e5-bddc-2da8ecfb195d.png)

_Originally posted by @gyf30827 in https://github.com/floating-ui/floating-ui/issues/1888#issuecomment-1249084595_

**Comment by FezVrasta** [comment]
@gyf30827 this doesn't look like a problem with Floating UI, something is wrong with your project configuration, you should try asking on StackOverflow.
