### ISSUE TITLE
Arrow gets positioned incorrectly first time if set immediately in. Works in rag

### ISSUE THREAD

**Issue by emattias** [floating-ui/floating-ui#1890]
I wanted to have a "hover bridge" between the button opening the tooltip and the tooltip that has an offset. I tried using the arrow middleware for this. It works, but only if I wrap the setting of the arrow elements style in a raf instead of doing it immediately. 

Interestingly it is only incorrect the first time. If I dont wrap with a raf it is incorrect on the first open but then when I close and open again it becomes correct. Seems like the `middlewareData.arrow.x` value is incorrectly calculated at first but then quickly updates to the correct value.

From sandbox below:

### without raf 
(on the first open the red arrow element is not positioned between the whole tooltip and button)

<img width="391" alt="CleanShot 2022-09-16 at 15 00 00@2x" src="https://user-images.githubusercontent.com/351537/190644765-b14e52c6-aede-422e-a8c8-223738c8e7fd.png">

### with raf
<img width="390" alt="CleanShot 2022-09-16 at 15 00 16@2x" src="https://user-images.githubusercontent.com/351537/190644951-c64a6526-fa7e-470b-bff0-b713ea5ff518.png">

Here's codesandbox: https://codesandbox.io/s/floating-ui-dom-template-forked-4i5bnn?file=/src/index.js

(maybe it would make sense to have a new "bridge" middleware or something for this but still I dont see why the raf should be needed for the value to be correct on the first render)

**Comment by atomiks** [comment]
If you remove the width assignment style to the tooltip, it's correct initially. Otherwise it re-runs the lifecycle and gives it the wrong value for some reason (idk why right now). I think the ordering of styles here is not right though, the arrow should have the width style applied to it before `arrow()` runs, without mutating it in `size` afterward, as it wasn't meant for that.

**Comment by emattias** [comment]
> the arrow should have the width style applied to it before `arrow()` runs, without mutating it in `size` afterward, as it wasn't meant for that.

Ok, how could the "hover bridge" be implemented in another way if not in size afterwards?

**Comment by atomiks** [comment]
I'm not sure how exactly although it's likely possible in some way. You can also write the logic for that in plain JS checking the mouse coordinates during `pointermove`, without needing to create an element (although it wouldn't block `pointer-events`/hover effects unerneath like an element would). 

Anyway, a [triangle polygon](https://floating-ui.com/docs/useHover#safepolygon) is usually better than a rectangle bridge shape like that

**Comment by emattias** [comment]
> Anyway, a [triangle polygon](https://floating-ui.com/docs/useHover#safepolygon) is usually better than a rectangle bridge shape like that

Yeah but how can I use `safePolygon` without react? More specifically in an ember project. Is there a vanilla js version of it? If not, what would have to be done to make the react version non react specific?

**Comment by atomiks** [comment]
It can be made non-React specific a bit easier than other parts of the React library - to do so it needs to accept all the [params it receives from the `context` object](https://github.com/floating-ui/floating-ui/blob/c422199d78b8a5c846043ab40cd9fa04213127bb/packages/react/src/safePolygon.ts#L77-L85) during the `mouseleave` listener. (But of course, setting up the `mouseleave` part is also a bit of work).
