### ISSUE TITLE
Using `useClick` and `useHover` together requires double click to toggle

### ISSUE THREAD

**Issue by EvHaus** [floating-ui/floating-ui#1893]
## Problem

When I use `useClick` and `useHover` interactions together I'm getting a behaviour I don't expect. What I would like:

- If I hover on an element, the floating element appears
- If (while hovered) I click on the element, the floating element disappears

## Actual

What actually happens right now is:

- ✅ If I hover on an element, the floating element appears
- ❌ If (while hovered) I click on the element, the floating element stays open
- If I click a second time, then the floating element disappears

## Note

The same problem occurs with the interaction of `useFocus` and `useClick`. I would expect that when I focus the element, the element appears, but if (while focused) I use the spacebar key to toggle the element -- it should disappear. But at the moment it requires a second keypress.

## Minimal repro

https://codesandbox.io/s/nervous-darwin-tktb4w?file=/src/Tooltip.tsx

**Comment by atomiks** [comment]
Are you looking for this behavior in this Sandbox? The current `useClick` + `useHover` behavior is like that intentionally

https://codesandbox.io/s/romantic-morning-pr2qnc?file=/src/Tooltip.tsx

**Comment by EvHaus** [comment]
Thanks for the fast reply. Yeah, so basically you're proposing `useDismiss(context, { referencePointerDown: true })` as the solution for that -- that works 🎉 for click/hover interactions!

Is it possible to get a similar behaviour for focus interactions too? My expectation is:

- If I focus on an element via the Tab key, the floating element appears
- If (while focused) I press `Spacebar` to activate the element, the floating element disappears

Why? I'm thinking of elements that have both a tooltip and a dropdown menu. I want the tooltip to disappear when the dropdown menu is shown so that tooltip doesn't cover the dropdown.

**Comment by atomiks** [comment]
You can just add an `onKeyDown` handler to the reference's prop getter and check for that pretty easily (`setOpen(false)`).

**Comment by EvHaus** [comment]
Indeed. That works. Thanks @atomiks!

Here's the sandbox with all the features enabled and working in case anyone runs into this issue: https://codesandbox.io/s/holy-violet-6xofit?file=/src/App.tsx
