### ISSUE TITLE
Attach to body

### ISSUE THREAD

**Issue by fredyagomez** [floating-ui/floating-ui#1895]
Seem like these are the docs for floating-ui (popper.js)?

Where is a sample of this approach ?  Appreciate your response.

https://popper.js.org/docs/v2/performance/#attaching-elements-to-the-dom

**Comment by atomiks** [comment]
It just means you write the markup for the element as a child of the `<body>`, instead of next to the reference element, which could be nested inside many containers, N levels deep.

In React, you'd use `createPortal()` to do that.
