### ISSUE TITLE
[react-dom-interactions] Cannot have a basic example to work

### ISSUE THREAD

**Issue by dackmin** [floating-ui/floating-ui#1902]
Hi there 👋 

Coming from popper I'm still figuring things out with floating-ui, but after trying with every version of react-dom-interactions out there I'm starting to think I probably missed something in the docs, or for my own sanity, something is not working as it should.

Here is a non-working very basic example: https://codesandbox.io/s/quirky-zhukovsky-ytpcy7?file=/src/App.js
It opens correctly, but the button never triggers a toggle, and dismiss doesn't work either.

It's almost a copy/paste from the docs (minus the middlewares and positioning) and I tried with every version from 0.10.1 to 0.0.1. Also tried with react & react-dom 18.2.0 to 17.0.2, with no luck.

Am I missing something? I'm running out of ideas and starting to question life itself.
Send help.

Much love, Ugo.

**Comment by atomiks** [comment]
You're passing `opened` to `useFloating`, should be `open: opened`
