### ISSUE TITLE
React tooltip example error on `mergeRefs` → This expression is not callable

### ISSUE THREAD

**Issue by StErMi** [floating-ui/floating-ui#1903]
This is the official example in the docs: https://codesandbox.io/s/winter-tree-wmmffl?file=/src/Tooltip.tsx:0-1458
If I freshly install both `@floating-ui/react-dom-interactions` and `react-merge-refs` I get an error on 

```
const ref = useMemo(() => mergeRefs([reference, (children as any).ref]), [reference, children]);
```

```
import mergeRefs
This expression is not callable.
  Type 'typeof import("/PROJECT_PATH/node_modules/react-merge-refs/dist/index")' has no call signatures.ts(2349)
```

Here are the version used

```
        "@floating-ui/react-dom": "^1.0.0",
        "@floating-ui/react-dom-interactions": "^0.10.1",
        "react-merge-refs": "^2.0.1",
```

**Comment by atomiks** [comment]
Docs use `v1` of that package but now it's v2, it's probably a default export problem. Though the releases do say both should work as of 2.0.1, try changing this:

Try `import { mergeRefs } from ...` instead of `import mergeRefs from ...`
