### ISSUE TITLE
[Question/Feature Request]  Is there a way to find out if flip middleware has been applied?

### ISSUE THREAD

**Issue by st-h** [floating-ui/floating-ui#1904]
I am using a border to make the element positioned by floating-ui look more nice:

<img width="226" alt="Screenshot 2022-09-26 at 18 04 49" src="https://user-images.githubusercontent.com/5768353/192326540-0a69e499-06e2-4947-8a8f-fbec7f24c543.png">

The downside is that I need to know if the flip middleware has been applied, so that I can make sure the arrow is also flipped. Otherwise it would show the arrow in the wrong direction: 

<img width="320" alt="Screenshot 2022-09-26 at 18 11 54" src="https://user-images.githubusercontent.com/5768353/192327338-c84413cc-387e-4b12-9cec-1fef16a015af.png">

I have been looking at the params provided by the middleware, but I could not find a way to reliably detect if flip has been applied. Is there currently a way to get that data?

Otherwise it might also be nice if the arrow middleware would be able to automatically flip the arrow when needed.

**Comment by atomiks** [comment]
You only need to check the `placement` that gets returned in the data. This allows you to style the arrow based on the side it's placed at.
