### ISSUE TITLE
Floating children sometimes gets (x,y) = (undefined,undefined) when the floating parent re-renders

### ISSUE THREAD

**Issue by rpelorosso-sv** [floating-ui/floating-ui#1905]
Hi! 

I have a custom component I created that opens a dropdown when a reference element is clicked.   This `ClickDropdown` component takes a render prop for the dropdown and a children, to which it adds the `onClick` listener via `React.cloneElement`. (Extract of the code below)

I'm having a weird issue that I can't duplicate reliably. I have a dropdown that includes another dropdown. Both dropdowns appear fine, but when the parent dropdown re-renders (the children can trigger that by changing information that the parent uses), some times the children dropdown gets re-rendered in the top left corner of the window. I've checked and `x,y` from `useFloating` come `undefined`. If I trigger a new render it fixes the issue, that may arise later.

I have no idea how to debug it or how to duplicate it reliably, but I was wondering if any of you have any idea of why (x,y) from `useFloating`  could come as undefined when the parent re-renders.

```
  const nodeId = useFloatingNodeId();
  
  const { x, y, reference, floating, strategy, context, refs } = useFloating<
    HTMLElement
  >({
    nodeId,
    open: isDropdownOpen,
    onOpenChange: toggleDropdown,
    placement,
    middleware: [
      size({
        apply({ rects }) {
          if (refs?.floating?.current && matchReferenceWidth) {
            Object.assign(refs.floating.current.style, {
              width: `${rects.reference.width}px`,
            });
          }
        },
      }),
      flip(),
      shift(),
    ],
  });

  const childWithProps = React.cloneElement(children as React.ReactElement, {
    ref: reference,
    onClick: toggleDropdown,
    onKeyDown,
    className: 'click-dropdown-target',
    onKeyUp,
    ...(id ? { id } : {}),
  });

  return (
    <>
      {childWithProps}
      {isDropdownOpen && (
        <FloatingNode id={nodeId}>
          <div
            onClick={handleDropdownClick}
            ref={floating}
            style={{
              position: strategy,
              top: y ?? 0,
              left: x ?? 0,
            }}
            className={`${styles.Popover} ${dropdownClassName}`}
          >
            {typeof dropdownRenderProp === 'function'
              ? dropdownRenderProp(hideDropdown)
              : dropdownRenderProp}
          </div>
        </FloatingNode>
      )}
    </>
  );```

Thank you so much!

**Comment by atomiks** [comment]
`x` and `y` can't ever be `undefined`, only `null` or `number`. Also once the first position/render has occurred, they shouldn't go back to `null` unless the component with the hook gets unmounted, the remounted. If you try `console.trace()`ing parts of the code, incl. node_modules, you may uncover the issue

**Comment by atomiks** [comment]
If you have a CodeSandbox or local repo demo demonstrating the issue, I can re-open. As the issue currently stands, it's not actionable unfortunately
