### ISSUE TITLE
Dynamic placement and autoUpdate conflict

### ISSUE THREAD

**Issue by AlexisVK** [floating-ui/floating-ui#1909]
Hello. Thanks for the hard work on this amazing project!

I have found an issue when Floating UI has a conflict between autoUpdate and dynamic placement.

Here I prepared a [codesandbox](https://codesandbox.io/s/hidden-architecture-8531iq?file=/src/App.tsx) so that you can check the issue (click on button will position floating with previous placement)

**Comment by atomiks** [comment]
The `autoUpdate` cleanup function is not being returned from `whileElementsMounted`. There's a comment about it when using it as an inlined function:


>  // Or, pass options. Ensure the cleanup function is returned.

https://floating-ui.com/docs/react-dom#updating
