### ISSUE TITLE
[React DOM Interactions] useHover open-close loop when floating element covers reference element

### ISSUE THREAD

**Issue by mattsenior** [floating-ui/floating-ui#1910]
Hi, I'm building an 'interactive' floating element that appears on hover (with `useHover`) and which completely covers the reference element. I'm using `handleClose: safePolygon()` to try to keep the floating element open while the mouse is interacting with it.

This works really well if the floating element is offset from the reference element, but if I overlap the reference element using a negative offset, I seem to run into trouble.

I'm finding that the floating element is closed immediately after appearing - I think it's registering that the mouse has left the reference element, but not yet registered that the mouse has entered the floating element, so it ends up looping:

![f6dfa1c5-20e0-4a8e-8a92-a292ac0ccffe](https://user-images.githubusercontent.com/84593/194033763-7989916e-eec7-46d0-b940-404f30857dc6.gif)

It seems I can work around it by adding a `delay: { close: 1 }` to `useHover`. I wondered whether there was a way to do this without needing the delay workaround? Please also let me know if this is user error! :) 

Here's a sandbox, based off the Tooltip tutorial example: https://codesandbox.io/s/agitated-sunset-tlqgxh?file=/src/App.tsx

Thanks so much

**Comment by atomiks** [comment]
Doesn't seem like user error, looks like a bug. 

Might be caused by this event handler:

https://github.com/floating-ui/floating-ui/blob/3dd6b42489b2beaeb97379769a6e4d63333ee171/packages/react-dom-interactions/src/hooks/useHover.ts#L234
