### ISSUE TITLE
Floating element doesn't reposition when reference is repositioned on page

### ISSUE THREAD

**Issue by hipstersmoothie** [floating-ui/floating-ui#1919]
So looking through the code it seems like a floating element will only repositions with autoUpdate when:

1. a scrolling/overflowing ancestor is scrolled or resized
2. when the reference element itself is is resized 

In the video below none of those are true. Things around the reference that aren't scrollable or boundaries in any way get resized, which repositions the reference, but does not trigger the floating element to update. I could use `animationFrame` but that seems really heavy for what seems like it should be default behavior

https://user-images.githubusercontent.com/1192452/195693045-2227865e-5e65-4015-a20d-56a0898d5c28.mp4

**Comment by hipstersmoothie** [comment]
Figured out a way to fix it on my side. Whenever something inside the grid is resized I fire:

```
 window.dispatchEvent(new Event('resize'));
```

Which triggers update functions

**Comment by atomiks** [comment]
The platform doesn't yet provide a way to know this scenario in an efficient way, you'd have to attach a bunch of `ResizeObserver`s to all parent containers. 

For transient elements that are open only for a short time, `animationFrame: true` is fine perf-wise, unless there'll be tons of them open.

> Figured out a way to fix it on my side. Whenever something inside the grid is resized I fire:

That's the same as calling the update function yourself manually when the user is resizing:

```js
autoUpdate(reference, floating, update);

const onPaneResize = () => {
  update();
};
```

**Comment by hipstersmoothie** [comment]
True. Not directly using the library though so I can't directly access that function

**Comment by hipstersmoothie** [comment]
Thanks!
