### ISSUE TITLE
Documentation for Arrow-Placement has a broken example (out of date?)

### ISSUE THREAD

**Issue by leopoldkristjansson** [floating-ui/floating-ui#1924]
On these pages:

- https://floating-ui.com/docs/tutorial#arrow-middleware
- https://floating-ui.com/docs/arrow

We have examples of fetching the X and Y coordinates for an arrow like so:

`const {x: arrowX, y: arrowY} = middlewareData.arrow;`

and 

`const {x, y} = middlewareData.arrow;`

![Screenshot 2022-10-19 at 13 52 29](https://user-images.githubusercontent.com/2579324/196683379-713a2432-d6d7-4115-80bd-48ed6a1c07ad.png)

TS is however pointing out to me that:

`Property 'x' does not exist on type '(Partial<Coords> & { centerOffset: number; }) | undefined'.`

and 

`Property 'y' does not exist on type '(Partial<Coords> & { centerOffset: number; }) | undefined'.`

The TS errors seem correct, given that the object returned looks like this (only `x` or `y`, never both):

`{ x: Number, centerOffset: Number }`

or 

`{ y: Number, centerOffset: Number }`

**Comment by atomiks** [comment]
When using TS, you just need to ensure the object itself is not `undefined`:

```
middlewareData.arrow ?? {};
```

or

```
if (middlewareData.arrow) {

}
```
