### ISSUE TITLE
issue with popper in my node modules

### ISSUE THREAD

**Issue by Kevin-Terblanche** [floating-ui/floating-ui#1929]
Hi im getting this error from my node modules when trying to build my app is there any solution to this im using angular 
![image](https://user-images.githubusercontent.com/108672217/198629942-1d8e891e-5aa7-4fe6-a4f6-b66ed1b90ded.png)

**Comment by atomiks** [comment]
We have now released [Floating UI v1](https://floating-ui.com/docs/motivation), the successor to Popper.

Don't worry, Popper 2 will continue to receive new releases with bug/security fixes provided by external contributors, but development of new features is not continuing at this point. We are also closing bugs related to it as us maintainers are focusing our energy on tracking issues with Floating UI, however you are welcome to create new pull requests to fix bugs in Popper, which we will review and merge, as many packages (such as MUI, Bootstrap, etc) still rely on it. 

Thanks!
