### ISSUE TITLE
useDismiss + ancestorScroll: dismiss only when reference is scrolled out of ancestor visible viewport

### ISSUE THREAD

**Issue by mihkeleidast** [floating-ui/floating-ui#1941]
Example: https://codesandbox.io/s/lively-sunset-kyohtw?file=/src/Select.tsx

I modified the Select example from the docs site a bit to try to showcase what I'd like to achieve. I'm trying to set up a reasonable behavior for a Select floating menu in a scrollable area (which can also be a floating element). The Select menu is portaled, so it is essentially detached from the Select control button.

Essentially, the issue is that `ancestorScroll: true` option in `useDismiss` hook dismisses the floating element immediately. This however can be quite annoying to users, as they can open the Select, then accidentally trigger a scroll, which will immediately close the menu. I do not wish to use a scroll locking mechanism to be honest, because at times the select menu height can be quite small, so would like to allow users to scroll to top or bottom to increase the visible item count (this small height issue is not very well visible in the linked example).

I would like the floating element to not dismiss immediately, like ancestorScroll currently does, rather when the reference element is scrolled out of the ancestor viewport, i.e. when the reference and floating element get "detached" from each other due to portaling. 

Any thoughts, is this reasonable to support in floating-ui directly, or should this be implemented in userland?

**Comment by mihkeleidast** [comment]
Duh, I must be getting old, 5 minutes after filing this I read through the docs again and found the `hide()` middleware, which should be just for this, so I shouldn't use ancestorScroll at all? But I'm not entirely sure how to use the hide middleware, it does not seem to trigger `onOpenChange`.  Does it need to be handled manually from the returned middleware data? Shouldn't it trigger `onOpenChange` when used?

**Comment by atomiks** [comment]
`hide()` is part of the positioning library so it doesn't have any hooks to the interactions package. It will remain rendered while scrolling out of view, but you use it to visually hide it using a CSS style.

To un-render it when that value becomes true just requires an effect like this:

```js
useEffect(() => {
  if (middlewareData.hide?.referenceHidden) {
    setOpen(false);
  }
}, [middlewareData.hide?.referenceHidden]);
```

**Comment by mihkeleidast** [comment]
I added that to the sandbox: https://codesandbox.io/s/lively-sunset-kyohtw?file=/src/Select.tsx

Weirdly, when it decides to hide the menu, the parent component scroll position jumps so that the select button is centered. Is this some sort of a bug?

**Comment by atomiks** [comment]
I guess it's focus returning to the reference element causing it to scroll

**Comment by mihkeleidast** [comment]
Yeah, that makes sense - I guess this is only feasible to use with a virtual focus, then it should not scroll. Thanks for the help!
