### ISSUE TITLE
Calculating clippingRect is off when a floating element is inside another floating element

### ISSUE THREAD

**Issue by nicolechung** [floating-ui/floating-ui#1944]
## Examples

Popper
https://codesandbox.io/s/ancient-wind-o4bm96?file=/src/index.js

Floating UI:
https://codesandbox.io/s/floating-ui-dom-template-forked-gn3qb4?file=/src/styles.css

In both examples, the `popover` should show that contains a `button` that should display a tooltip above the button.

The tooltip is rendered into a portal.

The issue comes from the popover originating in a container with:
1. display: grid
2. overflow: scroll

I think the issue might be related to this: https://github.com/floating-ui/floating-ui/blob/master/packages/dom/src/utils/getClippingRect.ts#L42

The clipping Rect calculation excludes `absolute` and `fixed` positioned items, but then does not account for items with `translate` applied. Then `data-popper-reference-hidden` is applied to elements that aren't actually hidden.

In these examples, the tooltip thinks the button is hidden when it is not.

**Comment by atomiks** [comment]
This particular case was fixed by https://github.com/floating-ui/floating-ui/pull/1923

It doesn't handle every scenario yet though, but is being tracked here already https://github.com/floating-ui/floating-ui/issues/1867
