### ISSUE TITLE
[React DOM Interactions / FloatingPortal] A moving portal node moves floating elements away from their reference

### ISSUE THREAD

**Issue by sambrannon** [floating-ui/floating-ui#1945]
I stumbled across what I think is a bit of an edge case, but couldn't find the guidance in the docs to answer which direction I should take... Not sure if this would be considered a bug, a gap in documentation, or a "hey internet stranger this is just too much of an edge case but thanks anyway" sort of thing.

**TL;DR: Changing a portal node's vertical position can sometimes "push" or "pull" the floating element away from it's reference in unexpected ways.**

[Here's a Code Sandbox demo I put together.](https://codesandbox.io/s/peaceful-ramanujan-74n4t2)

https://user-images.githubusercontent.com/7304891/200130271-62704f8d-6e7f-4393-a3db-0b001268d11d.mov

### Reproduction steps:

1. Create a floating UI of some kind
2. Insert it into a `FloatingPortal` _that exists at the bottom of the DOM_
3. Add `position: relative` (or similar) to that portal node
4. Change the height of the content _outside of a React render cycle_ (at least, I think it needs to be outside of React... I tried to replicate the weirdness via `useEffect` + `setTimeout` and it seemed to behave appropriately).

From what I can tell, once you `position: relative` the portal node, the floating element's `top` value becomes relative to that portal node. When that node changes it's vertical position (via some outside-of-React event), it shifts down, but the floating element's `top` value doesn't recalculate thus "pulling" the floating element down.

Admittedly this feels a lot like an edge case, but my team stumbled on it a bit and wanted to surface in case it could help anyone else down the line. We have a complex data fetching system that doesn't always live inside React. Once the data loaded, our content would jump around.

### Identified "fixes":

- `position: absolute; top: 0; left: 0;` on the portal node to ensure the portal reference is at the top of the page and never moves
- Remove any position styles from the portal node (this feels like the most-right answer potentially?)
- Put the portal node at the top of the DOM instead

**Comment by atomiks** [comment]
This type of thing can also happen if you inserted the content above the reference, it would detach (since it doesn't update the position as necessary). In both of these scenarios, [autoUpdate#animationFrame](https://floating-ui.com/docs/autoUpdate#animationframe) fixes it, as it can handle arbitrary layout changes.

But I'd say #/2 is the best/simplest option indeed. Not sure what purpose `position: relative` has other than cause the issue described. For #/1, using `position: fixed` sounds like it would handle some more edge cases but would also work.

> Admittedly this feels a lot like an edge case

Yeah there's nothing really to do here, but it's helpful for Google search results anyway 👍

**Comment by sambrannon** [comment]
>In both of these scenarios, [autoUpdate#animationFrame](https://floating-ui.com/docs/autoUpdate#animationframe) fixes it, as it can handle arbitrary layout changes.

This actually how I started to fix it, but it didn't work for me. Since I'm using `react-dom-interactions` I changed

```
  const { ... } = useFloating({
    ...
    whileElementsMounted: autoUpdate
  });
```

to


```
  const { ... } = useFloating({
    ...
    whileElementsMounted: (reference, floating, update) => {
      return autoUpdate(reference, floating, update, {
        animationFrame: true,
      });
    },
  });
```

based on [this example](https://floating-ui.com/docs/react-dom#updating). Just updated [my sandbox](https://codesandbox.io/s/peaceful-ramanujan-74n4t2) to use that and it too doesn't update as expected.

I figured it's because of the mixed-React implementation but not sure. Either way, thanks for the sanity check @atomiks.

**Comment by atomiks** [comment]
@sambrannon yeah sorry, I realized shortly after posting that it wouldn't work because animationFrame-based updating is dependent on the reference's rect changing, which doesn't change in this case. So manually updating after the content loads is the "solution", but you already listed better ones 😄
