### ISSUE TITLE
wrong position in electron 21

### ISSUE THREAD

**Issue by dragos-boisteanu** [floating-ui/floating-ui#1951]
![image](https://user-images.githubusercontent.com/38045539/201111270-4e037e54-59d7-422d-8485-95920755adb7.png)

The first image is from Edge and the second is from Electron 21. It seems that the values for X and Y are NaN on electron. I am suing a library based on floating-ui, https://github.com/Akryum/vue-mention and after some research I got to the conclusion that the problem is from floating-ui
My guess is the problem could be from computePosition method from @floating-ui/dom.

The NaN values affects the positioning of the element like this: 

Electron:
https://user-images.githubusercontent.com/38045539/195864190-83547351-7f18-481b-82c8-3caab668c875.png

Edge:
https://user-images.githubusercontent.com/38045539/195864283-690959d9-08f8-4e09-8c1c-29ce47452e94.png

**Comment by atomiks** [comment]
`floating-vue` is using an old version of this lib: `"@floating-ui/dom": "^0.1.10"`, the issue with Electron was fixed in [`0.4.2` in March](https://github.com/floating-ui/floating-ui/releases/tag/%40floating-ui%2Fdom%400.4.2)
