### ISSUE TITLE
@floating-ui/dom@1.0.3 Introduced a code that is not compatible with ie11

### ISSUE THREAD

**Issue by 1593292349** [floating-ui/floating-ui#1963]
![image](https://user-images.githubusercontent.com/48791868/202331817-419efe11-3799-40b2-8c55-a4704ff89b6c.png)
The code, as shown in the figure, does not support ie11

**Comment by FezVrasta** [comment]
Floating UI doesn't support IE11

**Comment by 1593292349** [comment]
@FezVrasta This is very frustrating, many frameworks need to support ie, this is a common requirement

**Comment by atomiks** [comment]
@1593292349 I'm sorry that it's frustrating, but supporting IE11 is even more frustrating. It was officially announced retired mid-2022, so there is no reason to support it anymore from this library's perspective. All major libraries have dropped support for it, e.g. React 18. 

Even if you were polyfilling all the required methods before, and transpiling the syntax, there were specific checks that were made that Popper was doing that were also removed - so it could've been breaking in subtle ways already. 

Plus, we might add a new array method that it doesn't support, requiring a new polyfill for it, so it'd break if you blindly updated in that case.

So, if you need to support IE11:

- Use Popper 2 instead, with the required polyfills.
- Use Floating UI but lock the version, and use `patch-package` to fix checks where it breaks if you need to update, like in this case.

Supporting IE11 is extra effort so if you need to support it, you'll need to take some extra effort to ensure that.
