### ISSUE TITLE
[React Native] Y coordinate returns NaN

### ISSUE THREAD

**Issue by piechoo** [floating-ui/floating-ui#1964]
Unfortunately I React-Native version of this library is not usable, at least for me, even example code from https://floating-ui.com/docs/react-native is not working properly, y value returned by useFloating hook is always NaN, what causes app crash. 
Im using:  
"react": "18.1.0",
 "react-native": "0.70.3",
 "@floating-ui/react-native": "0.8.1",

![image](https://user-images.githubusercontent.com/61754826/202428601-af28cc28-8702-4831-9a11-f1a39856389d.png)

**Comment by atomiks** [comment]
Hey @piechoo I can't reproduce this on a fresh project, with iOS. What platform is being targeted?

```shell
npx create-expo-app floating-native
cd floating-native
npm i @floating-ui/react-native
npm run ios
```

App.js

```js
import { StatusBar } from "expo-status-bar";
import { StyleSheet, Text, View } from "react-native";
import { useFloating, shift } from "@floating-ui/react-native";

export default function App() {
  const { x, y, reference, floating } = useFloating({
    placement: "bottom",
    middleware: [shift()],
  });

  return (
    <View>
      <View
        ref={reference}
        style={{
          margin: 100,
          width: 200,
          height: 200,
          backgroundColor: "yellow",
        }}
      >
        <Text>Reference</Text>
      </View>
      <View
        ref={floating}
        style={{
          position: "absolute",
          top: y ?? 0,
          left: x ?? 0,
          backgroundColor: "pink",
        }}
      >
        <Text>Floating</Text>
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
  },
});

```

**Comment by piechoo** [comment]
I've tried it on Windows, targeting android, not using expo but `npx react-native init`

**Comment by atomiks** [comment]
My guess is there is something not being passed correctly to `createPlatform`. Without Expo it looks like it takes a while to setup, so I'll need some help. Can you please try editing your `node_modules/@floating-ui/react-native/dist/floating-ui.react-native.js` file 

Look for `createPlatform` and log out all the values being passed into the `getElementRects` method (`x`, `y`, `width`, `height` being passed into the measure functions — both the `floating` and `reference` rects).

https://github.com/floating-ui/floating-ui/blob/e115340c6b18a0adedf3b50c08d16366e9646854/packages/react-native/src/createPlatform.ts#L18-L48

If one of the values is invalid that would explain why `NaN` is being returned.

**Comment by piechoo** [comment]
Unfortunately all of the values are invalid :( 
Edited code in node modules:
![image](https://user-images.githubusercontent.com/61754826/203774589-e7b932fa-efdb-4d28-9bd5-cc4b8c4797cc.png)
Result:
![image](https://user-images.githubusercontent.com/61754826/203774552-69ded40e-2593-4d28-a205-ac7f1ed581f4.png)

**Comment by atomiks** [comment]
This issue? https://github.com/facebook/react-native/issues/29712

Does adding `collapsable={false}` work?

**Comment by piechoo** [comment]
Yes, this workoround solves problem :)
