### ISSUE TITLE
[React DOM Interactions] useFocus overrides outside click handling

### ISSUE THREAD

**Issue by ConcernedHobbit** [floating-ui/floating-ui#1970]
When using the `useFocus` hook, clicking outside of the trigger element always closes the tooltip.

Example sandbox: https://codesandbox.io/s/quirky-stitch-sw9cru?file=/src/App.tsx

The problem can be recreated by commenting out the `focus` interaction from the array passed to `useInteractions`.

Expected behavior: setting focus to `keyboardOnly` (especially with `outsidePress` set to `false` in `dismiss`) makes the tooltip not close when clicking outside of the trigger element

Current behavior: the tooltip closes when clicking outside of the trigger element

If this is intended behavior, is there an example of using custom logic or hook props to ensure the tooltip stays open, while still retaining focus handling (for a11y reasons)?

**Comment by atomiks** [comment]
The browser blurs the element in this case which acts similarly to "outsidePress". Why would you want it to stay open if it's no longer focused?

**Comment by ConcernedHobbit** [comment]
Might be an odd use case but I'd like to keep the tooltip open if alt-tabbing.

**Comment by atomiks** [comment]
I'm not sure how to really handle this, maybe just don't use the `useFocus` hook and make your own one? Or if you have a solution, feel free to make a PR.
