### ISSUE TITLE
escapeKey does not close a tooltip

### ISSUE THREAD

**Issue by mlenser** [floating-ui/floating-ui#1971]
Hi,

Firstly thanks for making this great library.

**Issue:** the `escapeKey` on `useDismiss` does not seem to close a tooltip.

**Sandbox:** https://codesandbox.io/s/ancient-frog-u1i8el?file=/src/Tooltip.tsx

**Reproduction steps:**
1. Hover a button
2. Click escape
3. Tooltip does not close

Please let me know if I have missed some config or if something else is wrong.
Thank you

**Comment by atomiks** [comment]
It's because you have not focused the iframe in the CodeSandbox itself, so the keydown events are firing in the parent document/window – it's not possible for the library to listen to events in the parent document

**Comment by mlenser** [comment]
Ahh, if I open it at https://u1i8el.csb.app/ it works. Thank you!
