### ISSUE TITLE
Utilizing useListNavigation in child elements of floating element

### ISSUE THREAD

**Issue by hornta** [floating-ui/floating-ui#1974]
I'm making a multi select combobox and I would want to place my input element inside the floating element just above the listbox element but this means I can't use the useListNavigation hook since it adds attributes and event listeners to the root floating element. Would it be possible to somehow pass it along to a child element of the floating element?

**Comment by atomiks** [comment]
You can call `useInteractions` multiple times and have different prop getters to spread. 

The [emoji picker](https://codesandbox.io/s/nameless-glade-kz3pfc?file=/src/App.tsx) demo does that

<img width="800" alt="Screenshot 2022-11-25 at 11 40 21 am" src="https://user-images.githubusercontent.com/22450188/203878758-38063020-c3d3-4f38-8c1d-fc948b280512.png">

**Comment by hornta** [comment]
Thanks, that's just what I'm looking for.
