### ISSUE TITLE
Bug in virtual select example

### ISSUE THREAD

**Issue by clarknova** [floating-ui/floating-ui#1978]
Hello,
Keyboard Navigation inside the virtual select example is broken:
https://codesandbox.io/s/l10rjs?file=/src/App.tsx

For Example just press up a few times after it loops around. 

I think this is a bug inside the virtualisation hook but I am not 100% sure.

Anyway the example does not work correctly in any case.

**Comment by hornta** [comment]
Yes there is indeed something wrong when using the up arrow key
![Animation (2)](https://user-images.githubusercontent.com/4553604/204162298-bc79ced4-f142-433c-91dd-a6a0500c9ff3.gif)

**Comment by atomiks** [comment]
Thanks for the report, not sure if an upgrade to `react-virtual` in the Sandbox caused it or something else but deleting this line in the layout effect fixes the issue:

```js
      if (selectedIndex === null) {
        rowVirtualizer.scrollToIndex(0, {
          smoothScroll: false
        });
      }
```

(the line was necessary for something else, though)
