### ISSUE TITLE
Unhandled Runtime Error ReferenceError: Cannot access 'placement' before initialization

### ISSUE THREAD

**Issue by yelnyafacee** [floating-ui/floating-ui#1979]
I moved and extracted my `floating-ui/react-dom` code from one project to another project and now I am getting: `Unhandled Runtime Error ReferenceError: Cannot access 'placement' before initialization`

I do not understand why, the code is identical

here is my sandbox:
@floating-ui/react-dom: https://codesandbox.io/p/sandbox/polished-waterfall-ilc51b?file=%2Fpackage.json [ This --> `https://ilc51b-3000.preview.csb.app/users/1` the sandbox page URL ]

I am using: `"@floating-ui/react-dom": "^0.6.2"`

**Comment by atomiks** [comment]
I don't know where to look in the Sandbox but this has nothing to do with the library, it's a JS runtime error, take a look here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Cant_access_lexical_declaration_before_init
