### ISSUE TITLE
floating-ui/react-dom: How to prevent tooltip pup-up from relocating based on spacing and window size?

### ISSUE THREAD

**Issue by yelnyafacee** [floating-ui/floating-ui#1980]
How do I make the position of the `floating-ui/react-dom` tooltip pop-up `static` [ `always next to the trigger element, either left or right based on horizontal space` ]:

https://i.stack.imgur.com/jXoGc.png

Currently my tooltip pop-up position keeps changing vertically based on the vertical space, how do I stop it and make it fixed?

https://i.stack.imgur.com/KsIRv.gif

Here is my sandbox code:
https://codesandbox.io/p/sandbox/polished-waterfall-ilc51b

**Comment by atomiks** [comment]
It looks like you have `shift()` inside the middleware array but should remove it in this case.

**Comment by yelnyafacee** [comment]
hi, I tried removing `shift()` totally but it make no differences, seems `flip()` is still causing it to reposition the tooltip as well, If I removed both `shift()` and `flip()` the repositioning is gone, but the `left` and `right` `flipping` of the tooltip is gone, how can I keep the `left` and `right` flipping but remove the `top` and `bottom` repositioning?

**Comment by atomiks** [comment]
Maybe you want to disable [`flipAlignment`](https://floating-ui.com/docs/flip#flipalignment) or if that fails, manually set `fallbackPlacements` to something like `['right-start', 'left-start']` depending what you need.
