### ISSUE TITLE
[React DOM Interactions] FloatingOverlay passes touch events through itself

### ISSUE THREAD

**Issue by Santehnikua** [floating-ui/floating-ui#1984]
When using FloatingOverlay touch events are passed through it instead of just calling the close event.
This causes the buttons and links below the overlay to fire when the user wanted to close the modal.
![ezgif-3-032f79bdd5](https://user-images.githubusercontent.com/104627137/204681511-020c8fd4-1391-40c3-964a-9af1a040c67a.gif)

Steps to reproduce:
1) Open on any touch device (or device emulation in Chrome/Firefox DevTools) sandbox from docs: https://codesandbox.io/s/wandering-dream-qwe6dj?file=/src/App.tsx
2) Click "Open dialog" button
3) When modal dialog active - click again on area where "Open dialog" button located
4) Instead of just closing, a close event and a button click will occur.

Version:
- @floating-ui/react-dom-interactions 0.12

**Comment by atomiks** [comment]
It's due to [`pointerdown` event](https://floating-ui.com/docs/useDismiss#outsidepressevent) being used, rather than `mousedown` (or `click`). Probably a good idea to use `mousedown` when an overlay is active and/or always for modal dialogs. I've updated the Sandbox to use `mousedown` instead.
