### ISSUE TITLE
Floating element closes when tabbing from reference to content if it is opened by useFocus

### ISSUE THREAD

**Issue by mihkeleidast** [floating-ui/floating-ui#1987]
Hey again! I'm trying to set up the following scenario, but am a bit lost as to why things are not working as expected:
- Floating element opens on reference focus
- Floating element is non-modal
- FloatingFocusManager should move the focus from the reference into the floating element

I made a small reproduction as well, nuked the Menu demo a bit to approximate what I'm trying to do:  https://codesandbox.io/s/bold-pare-wlboy4?file=/src/App.tsx

There, you can see that FloatingFocusManager does try to move the focus to a child of the floating element. But it seems like the blur event on the reference element is fired, which closes the floating element, and moves focus back to the reference. At least that's where I tracked the close event to: https://github.com/floating-ui/floating-ui/blob/master/packages/react-dom-interactions/src/hooks/useFocus.ts#L126

Is this something that should work or could be supported? Anything wrong with my hook/component setup?

**Comment by atomiks** [comment]
This PR improves non-modal focus management with portals (and focus handling in many other places): https://github.com/floating-ui/floating-ui/pull/1985 - I have some additional fixes locally that I need to push though

Testing locally the Sandbox works with the changes

**Comment by mihkeleidast** [comment]
Oh, interesting! I'll wait for that to be released then!
