### ISSUE TITLE
[Question] How to set placement to 'overlap'?

### ISSUE THREAD

**Issue by jun2077681** [floating-ui/floating-ui#1988]
![image](https://user-images.githubusercontent.com/20516642/205212837-56520a23-dc28-4da9-8d0c-d11248263256.png)

I want 'Floating UI' to cover 'Ref'.

How do I set up a layout like the one pictured above using flip middleware? (top and bottom are the same flip)

**Comment by atomiks** [comment]
If the placement is either `top-start` or `top-end`, use `offset`:

```js
computePosition(a, b, {
  placement: 'top-start',
  middleware: [
   offset(({rects}) => -rects.floating.height),
    flip({
      fallbackPlacements: ['top-end'],
    }),
  ]
});
```

If it can go on the `bottom-*` side, then you'd use the ref's rect height instead

**Comment by atomiks** [comment]
Demo: https://codesandbox.io/s/lucid-snow-bsowd4?file=/src/index.js
