### ISSUE TITLE
(question) Add an arrow to react 'Reusable tooltip component' example

### ISSUE THREAD

**Issue by rory-ferguson** [floating-ui/floating-ui#1989]
The example component can be found here: [Reusable tooltip component](https://codesandbox.io/s/xenodochial-grass-js3bo9?file=/src/App.tsx)

Documentation for said component is here: https://floating-ui.com/docs/tooltip#reusable-tooltip-component

**Comment by rory-ferguson** [comment]
Just to add, here is my example with as far as I have got: [Codesandbox](https://codesandbox.io/s/floating-ui-tooltip-forked-mho1bf?file=/src/Tooltip.js)

Where I access arrow coords from `state.context.middlewareData.arrow` or `state.middlewareData.arrow` arrow is always `{}`

**Comment by atomiks** [comment]
You need to pass it to the return value, the context currently has it as undefined:

<img width="506" alt="Screenshot 2022-12-02 at 9 14 14 pm" src="https://user-images.githubusercontent.com/22450188/205269630-f97b765c-6457-4321-8ba3-d032c52a403a.png">

But yes, this should be documented (https://github.com/floating-ui/floating-ui/issues/1969 had the same issue lol)

**Comment by rory-ferguson** [comment]
Thank you for the fast response!

**Comment by rory-ferguson** [comment]
Working reuseable react component for anyone stumbling across this: [codesandbox](https://codesandbox.io/s/floating-ui-reusable-tooltip-component-with-arrow-46i10k?file=/src/Tooltip.tsx)
