### ISSUE TITLE
[React] Virtual element doesn't work with some interactive elements

### ISSUE THREAD

**Issue by EliteUser** [floating-ui/floating-ui#1991]
Hello!
I faced an issue with virtual element and stuck. 
Here is an example - https://codesandbox.io/s/musing-rgb-n8pv6z - it is modified [Reusable tooltip component](https://codesandbox.io/s/xenodochial-grass-js3bo9?file=/src/App.tsx) from docs.
I am trying to implement the tooltip with cursor position - tooltip will open at cursor and its position won't change until mouseleave.
So, with simple button it works almost fine (need to add animations and arrow).
In my project we use [antd](https://ant.design/) library and its Button component, but with antd button tooltip doesn't work.
On mouseMove event i'm logging `refs.reference.current`. When I use html button it logs an object with getBoundingClientRect as expected, but with antd Button it logs a button DOM node, so I'm getting the wrong behavior and tooltip stays at the default position, but it should be under my cursor.

with `<button>`
![image](https://user-images.githubusercontent.com/31800794/205299663-b1307ef1-0ab9-47c3-a0be-11728810ab74.png)

with antd `<Button/>`
![image](https://user-images.githubusercontent.com/31800794/205299732-f264e4dc-d6b8-45bb-ade1-53319632ab6a.png)

How to fix it?

**Comment by atomiks** [comment]
I think that antd is not memoing the Button's `ref` value, so when it re-renders, it gets called with `null` and then the Button's ref again, overriding the virtual element you passed in

You can reproduce it with the native HTML button by removing the memo

```js
const ref = mergeRefs([state.reference, propRef, childrenRef])
```

I think you can get around this by only merging `state.reference` into the element `ref` when `state.open` changes, then removing it.

Might cause some other issues
```js
mergeRefs([state.open ? null : state.reference, propRef, childrenRef])
```

**Comment by atomiks** [comment]
I got it working with a hack: https://codesandbox.io/s/amazing-estrela-6zllpi

Maybe we need a better API to pass in virtual elements :\

**Comment by EliteUser** [comment]
Oh, thanks!
It works and it looks like that's enough for me now 😃

Yep, would be nice to have better API with more examples of usage (like this one)

And it would be great to have a out-of-the-box support for cursor position of tooltip. Like in yours [tippy.js](https://atomiks.github.io/tippyjs/#follow-cursor)
