### ISSUE TITLE
[React DOM Interactions] useListNavigation onNavigate not called in production builds

### ISSUE THREAD

**Issue by erictaylor** [floating-ui/floating-ui#1993]
We came across a bug in our application that uses `@floating-ui/react-dom-interactions@0.11.0` and the `useListNavigation` hook not calling the provided `onNavigate` callback function but _only_ in production builds.

Our application is bundled/built with Vite.

We found in production builds that keyboard events were no longer working for lists created by `useListNavigation`. I spent hours debugging our production builds attempting to find the culprit.

It appears to be something related to the usage of the `useEvent` hook. I'm not _exactly_ sure what it is about that hook that is causing the problem, but the conditional `useInsertionEffect` and the check for the existence of that hook look suspicious at first glance.

We ended up patching `useListNavigation` in our app as follows which clears the issue up and gets things working again:

```diff
--- a/dist/floating-ui.react-dom-interactions.esm.js
+++ b/dist/floating-ui.react-dom-interactions.esm.js
@@ -2286,8 +2286,8 @@ const useListNavigation = function (_ref, _temp2) {
   const parentId = useFloatingParentNodeId();
   const tree = useFloatingTree();
   const previousOpen = usePrevious(open);
-  const onNavigate = useEvent(unstable_onNavigate);
-  const previousOnNavigate = useEvent(usePrevious(unstable_onNavigate));
+  const onNavigate = unstable_onNavigate;
+  const previousOnNavigate = usePrevious(unstable_onNavigate);
   const focusItemOnOpenRef = React.useRef(focusItemOnOpen);
   const indexRef = React.useRef(selectedIndex != null ? selectedIndex : -1);
   const keyRef = React.useRef(null);
```

I'd happily provide a PR to refactor the `useEvent` usage, but it's not clear to me why this hook exists in the first place. It seems to me to be unnecessary. It's not clear why `useInsertionEffect` would even be necessary at any point (at first glance anyways).

**Comment by erictaylor** [comment]
`0.12.0` has the same problem.

`useEvent` gets built into:
```ts
const useIsomorphicLayoutEffect$3 = canUseDOM
  ? react.exports.useLayoutEffect
  : react.exports.useEffect;
function useEvent$1(mn) {
  const Cn = react.exports.useRef(mn);
  return (
    useIsomorphicLayoutEffect$3(() => {
      Cn.current = mn;
    }),
    react.exports.useCallback(function (...Pn) {
      return Cn.current == null ? void 0 : Cn.current(...Pn);
    }, [])
  );
}
```

Stepping through the debugger our provided `onNavigate` callback is never called, and the callback returned via `useEvent` is, but I suspect the reference function that is ultimately called is the initial one (with the conditional throw error that gets removed in production builds) and so nothing happens (ie nothing gets thrown, nothing errors, nothing occurs).

**Comment by atomiks** [comment]
Interestingly, I just made a minimal demo with both Vite 2 and Vite 3, built both and the list navigation worked with `v0.11.0`. I suppose there is some kind of Rollup bug where the minification is breaking something in a particular location in a larger app 😕 

Maybe try updating Vite and the React plugin and/or all versions of packages you're using?

Also why is it using a layout effect rather than the insertion effect? I'm not sure it'd make a difference here but it seems to be compiling to something different and not the one in this library. Is it from a different library?

Repro:
<details>

```shell
npm create vite@latest my-react-app -- --template react
```

```js
import { useState, useRef } from "react";
import "./App.css";
import {
  useFloating,
  useInteractions,
  useListNavigation,
  useDismiss,
  useClick,
  FloatingFocusManager,
} from "@floating-ui/react-dom-interactions";

function App() {
  const [open, setOpen] = useState(false);
  const [activeIndex, setActiveIndex] = useState(null);

  const { x, y, reference, floating, context } = useFloating({
    open,
    onOpenChange: setOpen,
  });

  const listRef = useRef([]);

  const { getFloatingProps, getReferenceProps, getItemProps } = useInteractions(
    [
      useListNavigation(context, {
        listRef,
        activeIndex,
        onNavigate: setActiveIndex,
      }),
      useDismiss(context),
      useClick(context),
    ]
  );

  return (
    <>
      <button ref={reference} {...getReferenceProps()}>
        Open
      </button>
      {open && (
        <FloatingFocusManager context={context}>
          <div
            ref={floating}
            style={{
              position: "absolute",
              left: x ?? 0,
              top: y ?? 0,
            }}
            {...getFloatingProps()}
          >
            {Array.from({ length: 10 }).map((_, index) => (
              <div
                key={index}
                tabIndex={-1}
                ref={(node) => {
                  listRef.current[index] = node;
                }}
                style={{
                  backgroundColor: activeIndex === index ? "red" : "white",
                }}
                {...getItemProps()}
              >
                {index}
              </div>
            ))}
          </div>
        </FloatingFocusManager>
      )}
    </>
  );
}

export default App;
```
</details>

**Comment by erictaylor** [comment]
> I suppose there is some kind of Rollup bug where the minification is breaking something in a particular location in a larger app 😕

I share the same suspicion. 😔

I'll keep digging and debug some of our build setup and see if I can get a different result and will report back.

**Comment by erictaylor** [comment]
To clarify a point of confusion. I found that the `useEvent` function in my comment above was actually the wrong one. Some other library has a similarly named function, so the actual reference was:

```ts
const useInsertionEffect = React$m['useInsertionEffect'.toString()];
function useEvent(mn) {
  const Cn = react.exports.useRef(() => {});
  return (
    useInsertionEffect || (Cn.current = mn),
    react.exports.useCallback(function () {
      for (var Pn = arguments.length, Rn = new Array(Pn), On = 0; On < Pn; On++)
        Rn[On] = arguments[On];
      return Cn.current == null ? void 0 : Cn.current(...Rn);
    }, [])
  );
}
```

**Comment by atomiks** [comment]
Well that looks like the culprit: `useInsertionEffect` is not being called and thus the `.current` property is never updated, so your function won't be called... weird bug of the minidifer but I'll try to work around that.

**Comment by erictaylor** [comment]
> It should work, right?
I don't see why not. Though the question is how to get it to minify down to that.

**Comment by atomiks** [comment]
Let's see if this works: https://github.com/floating-ui/floating-ui/pull/1995

**Comment by erictaylor** [comment]
Been playing with updating Rollup to the latest version on our side to see if I can get a different minified result, but no luck.

**Comment by erictaylor** [comment]
Trying that change now locally and verified the minified production version comes out right.

```ts
const useInsertionEffect = React$m['useInsertionEffect'.toString()],
  useSafeInsertionEffect = useInsertionEffect || ((mn) => mn());
function useEvent(mn) {
  const Cn = react.exports.useRef(() => {});
  return (
    useSafeInsertionEffect(() => {
      Cn.current = mn;
    }),
    react.exports.useCallback(function () {
      for (var Pn = arguments.length, Rn = new Array(Pn), On = 0; On < Pn; On++)
        Rn[On] = arguments[On];
      return Cn.current == null ? void 0 : Cn.current(...Rn);
    }, [])
  );
}
```

**Comment by erictaylor** [comment]
I assume this will be going out as `0.12.1`?

**Comment by atomiks** [comment]
`0.13.0` — there is a small breaking change, but it only requires a 1 prop change. It's preparing for release now
