### ISSUE TITLE
Strange behaviour with transform: scale(...)

### ISSUE THREAD

**Issue by blnvdanil** [floating-ui/floating-ui#2003]
Hello! I have some problems implementing my project, the project is simple -- there is absolute positioned rectangles with `contentEditable="true"`, so I want to show slash menu whenever user enters `/`. There is one small detail, rectangles could be scaled by applying `transform: scale(...)`, and because of that position of slash menu is wrong-calculated, specifically `flip` middleware flips slash-menu when there is no reason to flip. I concluded that there is a problem with a root boundary.

![image](https://user-images.githubusercontent.com/61459199/205631310-88783d34-0af4-4d8f-b9cc-d90c8bde4daf.png)

As you can see on the screenshot, slash-menu is positioned wrong whenever it is far from top left corner of the screen. Top left  is the right one. 

There is as codesandbox where you can check out the actual code: https://codesandbox.io/s/infallible-villani-dhlvzm

If you will set `scale` variable to 1, everything works as expected.

**Comment by atomiks** [comment]
Maybe related:

- https://github.com/IDuxFE/idux/issues/1325 (related to clipping)
- https://github.com/floating-ui/floating-ui/pull/1763 (doesn't seem related to clipping)

> I concluded that there is a problem with a root boundary.

In Floating UI's `getClippingRect` function, what is the rect returning? I have a suspicion that the floating element is overflowing in _layout_ but not visually (after compositing with the transform, so the final result).

**Comment by blnvdanil** [comment]
`getClippingRect` returns the same rect as if there was no scale at all.
```            console.log(platform.getClippingRect({
                element: document.getElementById("element")!,
                strategy: "absolute",
                boundary: document.getElementById("boundary")!,
                rootBoundary: "viewport"
            }));
```
I ran this code when slash menu is open (on the last of my rectangles), slash-menu has `id="element"`, and parent of slash-menu has `id="boundary"`
And the result is
```
height: 400
width: 399.5
x: 900.5
y: 100.5
```

**Comment by blnvdanil** [comment]
Well, I have just noticed that `boundary` could be equal to `"clippingAncestors"`, and I ran this code 
```
console.log(platform.getClippingRect({
    element: document.getElementById("element")!,
    strategy: "absolute",
    boundary: "clippingAncestors",
    rootBoundary: "viewport"
}));
```
The result is 
```
height: 979
width: 1920
x: 0
y: 0
```

Does it say something useful?

**Comment by blnvdanil** [comment]
That's sad. I've been struggling with another problem before that. If you noticed, I'm correcting coordinates of reference with scale here
![image](https://user-images.githubusercontent.com/61459199/205666776-669981ca-45ad-4cbe-bdae-6adfcb6acd9f.png)

Other way it just setting wrong position of floating element, can you explain why does this happen?
![image](https://user-images.githubusercontent.com/61459199/205667306-5bc5eb6f-d45f-456e-a1c7-8f6dfa2cf37c.png)

**Comment by blnvdanil** [comment]
I have strong feeling, that because of `transform: scale(...)` every parent was scaled in computePosition

**Comment by atomiks** [comment]
That second issue is maybe a repro of https://github.com/floating-ui/floating-ui/pull/1763, seems like it should be easier to fix than correcting the clipping rect

**Comment by atomiks** [comment]
So I've done some digging... for the clipping issue, I think it may be the result of passing in the wrong boolean when convering the offsetParent-relative rect to a viewport-relative rect

In `convertOffsetParentRelativeRectToViewportRelativeRect`:
Does changing the boolean from `true` to `false` help?

```js
      const offsetRect = getBoundingClientRect(offsetParent, false);
```

I'm still investigating here but I think the scale negation is incorrect

**Comment by atomiks** [comment]
I'm temporarily reopening this to figure out if we can do anything about that manual `scaleRect` function we have (which could maybe also fix #1763, although maybe these issues are related)

**Comment by atomiks** [comment]
Ok so it's related to virtual elements not being detectable as scaled: 

https://github.com/floating-ui/floating-ui/blob/b049e160fe9b299b5c07bdd7d9f9c097e16383b7/packages/dom/src/utils/getBoundingClientRect.ts#L16

I think a good solution to this is check if the virtual element has a `contextElement` attached, and check that instead.

**Comment by atomiks** [comment]
Yeah as it still detects clipping via layout boxes, not visual boxes:

> Detection of clipping is also done via layout (which now works properly with scaling — but if the element is transformed it may appear to detect the overflow at the wrong point because detection is done via layout boxes, not accounting for transforms. This may be tricky to handle but please open a PR if you get a solution).

I'm not sure how hard it is to support for feel to make a PR if you can.

I think in the meantime as a workaround, you need to use `padding` in `flip`/`shift` that is negative for scale < 1 and positive for > 1 to account for this.

**Comment by blnvdanil** [comment]
Oh that what you wrote before, I'm sorry for reading too superficially.

So if element is transformed, that there could be some problems, but is there a way to set scale to element without transform? Now it seems for me that if I use scale, than it will detectOverflow incorrectly anyway :(

**Comment by atomiks** [comment]
Yeah but now the workaround works 😄 

It works something like this, idk the exact math but:

```js
const [padding, setPadding] = useState(0);

const { x, y, reference, floating, strategy, refs } = useFloating({
  placement: "bottom-start",
  middleware: [shift({ crossAxis: true, padding })]
});

// Only detects width... you'd need height too
// And maybe account for the aspect ratio if it's not a square
useLayoutEffect(() => {
  if (props.isOpen && refs.floating.current) {
    const width = refs.floating.current.offsetWidth;
    const value = width - (width * scale);
    setPadding(scale > 1 ? value : -value)
  }
}, [props.isOpen, scale, refs])
```

**Comment by atomiks** [comment]
I'm asking ChatGPT to help and maybe this works LOL:

https://chat.openai.com/chat - try chatting to it?

<img width="658" alt="Screenshot 2022-12-06 at 10 05 24 pm" src="https://user-images.githubusercontent.com/22450188/205895091-d158bd8b-b4f8-4a07-8194-5d7434257922.png">

<img width="677" alt="Screenshot 2022-12-06 at 10 05 34 pm" src="https://user-images.githubusercontent.com/22450188/205895129-230cef1e-98f5-4d11-95a8-2ae18b13d1de.png">

**Comment by blnvdanil** [comment]
Seems that yours and ChatGPT's formula is correct :) But I still have a problem with padding, I tried to set padding, and it works wrong. I made another slash-menu that is appended to body and not scaled, and with this slash menu padding works, but with mine -- nope :(

**Comment by atomiks** [comment]
I'm going to open an issue to track considering transforms when detecting clipping. I don't think this should be on by default, but can be an option like `layout: boolean` passed as an option to flip/shift/etc (so a `detectOverflow` option).

**Comment by atomiks** [comment]
Issue: https://github.com/floating-ui/floating-ui/issues/2009 (I wonder if that formula is correct, seems like it works for that layout.)
