### ISSUE TITLE
[useDismiss] using arrow function for outsidePress breaks ancestorScroll

### ISSUE THREAD

**Issue by Mario-Eis** [floating-ui/floating-ui#2008]
As the title says, using an arrow function like illustrated in the docs breaks the ancestorScroll dismiss functionality.

```
useDismiss(context, {
  // Same as `true`, but with a custom guard check.
  outsidePress: (event) => !event.target.closest('.toast'),
});
```

I figured out, that the following fixed this issue:

Outside of the component define:
`const outsidePressGuard = (event: MouseEvent) => !event.target.closest('.annotation-popup');`
And in the component do
`useDismiss(popupContext, {ancestorScroll: true, outsidePress: outsidePressGuard})`

Maybe using useCallback would also work here.

I think this should be fixed or corrected in the docs.

**Comment by atomiks** [comment]
Yeah it should be memoized by `useDismiss` using the `useLatestRef` hook, right now you do need to memo it yourself than pass it inline, but this should be handled by the library 😕
