### ISSUE TITLE
Consider transforms when detecting clipping

### ISSUE THREAD

**Issue by atomiks** [floating-ui/floating-ui#2009]
Continuing #2003

Right now detection of clipping is done via layout, so if your floating element is scaled, the detectOverflow logic either happens too early or too late depending on the scale transform, as the detection is based on its layout not visual box.

Since this interferes with common animation use cases, it'll be off by default, but configurable with an option like `layout: boolean` to `detectOverflow` which middleware like `flip` and `shift` can configure as they accept all of its options.

As a workaround, you can set the `padding` option to be positive if the scale is > 1, or negative if the scale is < 1. It looks like this may be difficult in some situations, but here's an example: https://codesandbox.io/s/billowing-cdn-5bfzil?file=/src/App.tsx

**Comment by atomiks** [comment]
I've mostly got this working, but there's a few edge cases to resolve, should have a PR tonight @blnvdanil

**Comment by blnvdanil** [comment]
That's finally works in my project! Thank you very much, I am very grateful to you! :)
