### ISSUE TITLE
useHover's delay and restMs do not work on some Linux machines

### ISSUE THREAD

**Issue by Slapbox** [floating-ui/floating-ui#2015]
These issues were discovered while working on https://github.com/mantinedev/mantine/issues/2569

Myself and another user were experiencing `mouseOnly` would not work on our machines. Once I discovered this and fixed it, I immediately noticed that tooltip delays were not being honored.

I tried `restMs` as well, but the outcome is the same.

The `closeDelay` works on the elements, but only if the page remains focused. If the button is hovered while the page is not focused, then the `closeDelay` also has no effect.

I believe this is because of the way Linux is handling mouse input, though I'm not sure how exactly.

So of course, I don't really expect `mouseOnly` to be fixed, but certainly the delays should work as intended?

Here's a CodeSandbox derived from the [tooltip docs](https://floating-ui.com/docs/tooltip): 

- https://codesandbox.io/s/awesome-lehmann-if4106?file=/src/App.js

I believe this issue can be reproduced on any machine by using VMWare - although that is an untested assumption. **Importantly, this issue does not _only_ affect VMWare - it just seems the best way to reproduce the problem.**

> Assuming that VMWare on any machine can produce the issue, one  could try a [ready-made Kubuntu image via VMDK file](https://www.osboxes.org/kubuntu/#kubuntu-21-10-vmware) with [VMWare Workstation Player](https://www.vmware.com/products/workstation-player.html)

If there's any more useful information I can provide, please let me know.

Tested with versions `0.10.2` to `0.13.2`

Thanks for all of your hard work!

**Comment by atomiks** [comment]
I know that this particular function has caused weird issues, and works differently on React 17 vs 18, especially if using pointer events vs. mouse events:

https://github.com/floating-ui/floating-ui/blob/1e0ce82a88828e2c016dbb0880925e63f3c1429a/packages/react-dom-interactions/src/hooks/useHover.ts#L234

I think that only is relevant for `safePolygon()` though. Does early-returning that so it never runs fix anything?

Aside from that, it's pretty hard for me to debug so I recommend debugging/logging out everything inside that hook on the problem machine, especially with the delay logic, the problem should surface itself somewhere.

**Comment by atomiks** [comment]
Actually since you mentioned an issue with `mouseOnly`, maybe the `pointerType` is not returning `"mouse"`?

https://github.com/floating-ui/floating-ui/blob/1e0ce82a88828e2c016dbb0880925e63f3c1429a/packages/react-dom-interactions/src/hooks/useHover.ts#L175

**Comment by Slapbox** [comment]
Thanks so much for your reply @atomiks! Surprisingly `pointerType` was equal to `mouse` - but then on every subsequent test I did it returns `pen` - so I guess that makes sense - but why it returned `mouse` the first time, I'm not sure at all.

It seems that `onScrollMouseLeave` never fires, so I've not tried early returning it as it seems not to be a factor.

I wonder if the fact that it's recognized as `pen` makes reproducing this on your end any more plausible?

**Comment by atomiks** [comment]
If it's recognized as `pen` then that definitely is gonna break the logic as it needs to be `mouse` 😆 uhmm I guess `touch` is more important to be ignored for than `pen` so maybe we can check for both

**Comment by atomiks** [comment]
This is the other place:

https://github.com/floating-ui/floating-ui/blob/1e0ce82a88828e2c016dbb0880925e63f3c1429a/packages/react-dom-interactions/src/hooks/useHover.ts#L32

I think `['mouse', 'pen'].includes(pointerTypeRef.current)` works for both (that line isn't a ref though).

**Comment by Slapbox** [comment]
Hmm. I guess I can't just `patch-package` the change because npm/yarn downloads the transpiled code, not the source - but I'll make the changes on my end, test, and then submit a PR to do the same.

**Comment by atomiks** [comment]
https://github.com/floating-ui/floating-ui/pull/2016
