### ISSUE TITLE
FloatingFocusManager focusout handler - closes when clicking another button, does not close on outside click

### ISSUE THREAD

**Issue by mihkeleidast** [floating-ui/floating-ui#2017]
I created a small reproduction in a branch in my fork: https://github.com/mihkeleidast/floating-ui/commit/c5b92d4b029d8902e5b5a3178cb4cb4b3072ad37

Ran across an inconsistency in how the focusout handler works. Two different scenarios at play here:

Scenario 1
1. Open Popover from the button
2. Click outside of the Popover, observe that it does not close
3. Click the "Second button", observe that the Popover remains open

Scenario 2
1. Open Popover from the button
2. Click the "Second button" observe that the Popover closes

As far as I debugged, the focusout handler fires in both cases when clicking outside of the floating element, but in scenario 1, when clicking the background, `relatedTarget` is `null`, so it does not fire the open change event.

It is kind of an edge case, but would be good if the behavior was consistent, to know what I should expect, as from the users perspective a random click outside should not change anything. 

Some additional info: in my real usecase, I do not have such Popovers, rather it is a drawer-like component (ex https://shoelace.style/components/drawer) that can be configured to not render on top of other content, rather it would render aside the main page. In this context, I have floating-ui configured to not close the floating element on outside click, but this issue means it still does in some cases. I can create a more realistic sandbox, if necessary, though I think the above describes the issue in enough detail.

**Comment by atomiks** [comment]
I feel like a drawer component should have modal focus management? If it has a backdrop

**Comment by mihkeleidast** [comment]
I know we talked about a similar thing in https://github.com/floating-ui/floating-ui/issues/1771. In there, you said about a potential option to disable the focusout behavior:

> I guess the issue is, if there was an option to remove the focusout/blur listeners, how does a tabbing keyboard user have it close for them when navigating out of it? Or it's okay that it gets left open?
> 
> If a floating element gets rendered in a portal, it has to be modal otherwise the user's focus will get lost since it teleports to the end of the document not inline


I think the second part is not relevant anymore, as floating-ui now does allow non-modal portaling.

For the first part, I think it would be OK (or even preferred) at least for my scenario that it would remain open. (though the next focused element should be the next from the reference still).

**Comment by mihkeleidast** [comment]
> I feel like a drawer component should have modal focus management? If it has a backdrop

Yeah, agree with that, but as I mentioned, my Drawer can be configured to render aside the main page, not on top of it, so it's more like "split screen" view, there is no backdrop covering the main page.

**Comment by atomiks** [comment]
So I guess we have two options:

- Add a prop that allows the user to disable `focusout` behavior.
- Detect if a `pointerdown` event occurred on the related target right before the focusout occurred, if so prevent closing. Keeps keyboard/virtual cursor closing working.

**Comment by mihkeleidast** [comment]
I would go with the first, to allow disabling the focusout behavior, for my usecase this solves more problems actually - I'll try to put a PR together with a testable example, if that sounds good?

**Comment by adamborowski** [comment]
Hey, did you manage to get it working properly, when the only difference is that instead of popover we have nested dropdown menu (FloatingTree and FloatingNode)?
