### ISSUE TITLE
Incorrect placement on Tooltip Example

### ISSUE THREAD

**Issue by rory-ferguson** [floating-ui/floating-ui#2018]
I've just used the reuseable component example for the tooltip

Can be found here https://codesandbox.io/s/awesome-leftpad-ks567l?file=/src/Tooltip.tsx

I've made the trigger 100% width and added a `placement="left"

There isn't any room for the tooltip on the left hand side but it doesn't correct itself

<img width="514" alt="image" src="https://user-images.githubusercontent.com/13840040/206418063-3a1201a5-80c8-4f1d-912a-e8c7d52cad20.png">

**Comment by atomiks** [comment]
`flip()` by default does not change the axis of placement. But can be easily done:

```js
flip({
  fallbackPlacements: ['bottom', 'left', 'right']
});
```

https://floating-ui.com/docs/flip#fallbackplacements
