### ISSUE TITLE
[Core] Specifying arrow padding cause tooltip to stuck at the center of ref when scrolling

### ISSUE THREAD

**Issue by EliteUser** [floating-ui/floating-ui#2020]
Hello!

Looks like I found a bug when tried to use tooltip with an arrow.
I created a repro [here](https://codesandbox.io/s/clever-voice-v669mx?file=/src/styles.css).
Zooming in codesandbox doesnt work, so I gave .App width = 5000px, so just scroll :D

When tooltip is wider than trigger element and arrow padding is specified (> 0), tooltip with arrow do not shift, it stops at the center when you scroll, but it should move till the edge of the trigger element (as limitShift is specified)

![bad](https://user-images.githubusercontent.com/31800794/206645607-ffc2fad2-703e-4bdb-8250-608301ed8751.gif)

If tooltip width < ref width and padding specified - everything works
If tooltip width > ref width but padding is 0 - everything works

![good](https://user-images.githubusercontent.com/31800794/206645679-1633d494-75d2-4e10-a704-6c018477e3f1.gif)

**Comment by atomiks** [comment]
This behavior was changed as part of https://github.com/floating-ui/floating-ui/pull/1496

To get around it you can call `shift()` again (a second time) after `arrow()` in the array. (I think that `arrow` should have an option to disable shifting itself tbh).

**Comment by EliteUser** [comment]
Thank you so much!

As I understand, it is expected behavior. 
I'm glad that there is a WA, so I can implement it the way I need.

**Comment by atomiks** [comment]
I feel like it can be smarter so you don't need to workaround it, nor an option to disable it. It should handle both of the cases (that PR, and this issue) desirably
