### ISSUE TITLE
useDismiss outsidePress is not reactive

### ISSUE THREAD

**Issue by mihkeleidast** [floating-ui/floating-ui#2021]
This is an issue that was introduced in https://github.com/floating-ui/floating-ui/pull/2010.

My usecase is that on large screens, the floating element is rendered inline, i.e. it is not actually floating. On smaller screens, it transforms to a floating element, rendered like a modal. This is controlled by reactive resize handlers (we use react-responsive library, but that's not too relevant). This means that the `outsidePress` value might change while the floating element is open, but currently this does not update the outside press event listeners, so one of two issues can happen:

1. When resizing the window from large to small (i.e. component changes from non-floating to floating), outside press does not work as expected.
2. When resizing the window from small to large (component changes from floating to non-floating), outside press handlers stay attached, meaning a click outside will close the floating element, even though it is not expected.

It's configured like this:
```
export const useDrawer = () => {
  const [open, setOpen] = React.useState(false);
  const { variables } = useTheme();
  const isLargeScreen = useMediaQuery({ query: variables.media.width.xlarge.min });
  const isModal = !isLargeScreen;

  const data = useFloating({
    open,
    onOpenChange: setOpen,
  });

  const context = data.context;
  const click = useClick(context);
  const dismiss = useDismiss(context, {
    outsidePress: !isLargeScreen,
    outsidePressEvent: "mousedown",
  });
  const role = useRole(context);

  const interactions = useInteractions([click, dismiss, role]);

  return React.useMemo(
    () => ({
      open,
      setOpen,
      modal: isModal,
      ...interactions,
      ...data,
    }),
    [open, setOpen, isModal, interactions, data],
  );
};
```

Any way that change could be reverted or made smarter in this regard, i.e. keep the boolean value reactive?

**Comment by atomiks** [comment]
"Doubt this matters." LOL, well.... 😭
