### ISSUE TITLE
Portaled element in a non-portaled element closes unexpectedly

### ISSUE THREAD

**Issue by mihkeleidast** [floating-ui/floating-ui#2039]
Reproduction: https://codesandbox.io/s/peaceful-wave-6cizwo?file=/src/Popover.tsx

This is a slightly modified version of the official Popover example. I modified it in three ways:
- Added a `portal` prop, to allow turning of portaling on a per-instance basis
- Added FloatingTree and FloatingNode setup
- Added `order={["reference", "content"]}` to `<FloatingFocusManager>`

To reproduce:
1. Tab to "My trigger".
2. Tab inside the first level Popover to "Nested trigger".
3. Tab inside the second level Popover to "Close".
4. Observe that the first level Popover suddenly closes.

I've discovered several possible workarounds:
- I could enable portaling on the first level Popover. Note that in my real code, the first level floating element is a separate component that uses fixed positioning, so I don't necessarily need portaling there, which is why I'd rather not turn it on. But this is a viable workaround for now.
- I could turn on modal mode for the first level Popover. While this would also work, in my real code there are some parts of the page that are interactive while this is open, so I would rather not do that either.
- I could remove `order={["reference", "content"]}` from `<FloatingFocusManager>`. This sort of works when floating-ui itself moves focus inside the second level Popover, but when tabbing out of it to the reference and back in, the bug surfaces again.

Anyway, while the portaling workaround works for now, thought I'd better report this, seems like an unhandled edgecase in that very complex condition: https://github.com/floating-ui/floating-ui/blob/master/packages/react/src/components/FloatingFocusManager.tsx#L198

**Comment by atomiks** [comment]
Is setting `closeOnFocusOut={false}` viable? Seems like it fixes it (btw the Sandbox doesn't have the `order={...}` prop).

**Comment by mihkeleidast** [comment]
As a temporary workaround, maybe, but I'd rather have it close if the user tabs out of it to the rest of the page. Portaling is a better workaround in this case, as that does not affect the rest of the focus management logic.

**Comment by atomiks** [comment]
So from what I can see, focus is moving to the non-portalled Popover's "inside" focus guard node, which then moves to the portalled Popover's first "outside" focus guard node, which is not inside the tree (because it's outside the Popover node). 

That's what the `portalNode` contains check handles, because it bails if it finds a child portal, but that only works if the root is also portalled (as you mentioned). And the tree check doesn't work in this case because the guard node is outside of it. I guess we could check if the Popover in the tree is the `nextElementSibling` of the focus guard node.

**Comment by mihkeleidast** [comment]
I think adding special handling for the guard nodes makes sense. One thing that I noticed as well was that another floating component that does use portaling worked correctly, but that is because that component does not use FloatingFocusManager (yet...), it has a custom keyboard behavior.
