### ISSUE TITLE
Is there any way to get the event, in the onOpenChange function?

### ISSUE THREAD

**Issue by aromanchev** [floating-ui/floating-ui#2047]
The problem is that when onOpenChange is triggered, only the open/closed state of dropdown comes. Is there any way to get an event how dropdown opens(keyboard, mouse, etc) when onOpenChange is triggered?
```typescript
...
const { x, y, reference, floating, refs, strategy, context } = useFloating({
	...
	onOpenChange: (opened, event?) => {
          ...
	},
        ...
});
```

**Comment by atomiks** [comment]
`context.dataRef.current.openEvent` contains the event that caused the floating element to open.

**Comment by aromanchev** [comment]
@atomiks but if you try to open in first time you get undefined from context.dataRef.current.openEvent

**Comment by atomiks** [comment]
When are you accessing it? You need to wait for the event to have fired for it to be written to the ref

**Comment by alexandredepape** [comment]
Hi, i have the same issue, i'm having a debug point in my code:

```js
onOpenChange: (open) => {
            const event = context.dataRef.current.openEvent;
            debugger;
},
```

But when looking in the dev tools, the event is undefined even though the event got fired since the onOpenchange was called ?
