### ISSUE TITLE
PreventOverflow from popperjs v.1 in floating-ui

### ISSUE THREAD

**Issue by bennymeier** [floating-ui/floating-ui#2048]
Hi,

I have just read the documentation for the [detectOverflow](https://floating-ui.com/docs/detectOverflow) middleware. But how can I use it like in v.1 from popperjs? 

I switched in a big project from popperjs' first version to floating-ui and it seems hard to re-implement the old preventOverflow setting, e.g. my old popperjs preventOvervlow setting:
```
 preventOverflow: {
                    boundariesElement: 'viewport',
                    enabled: true,
                    padding: 0,
                },
```

How to implement 
```
const middleware = {
  name: 'middleware',
  async fn(middlewareArguments) {
    const overflow = await detectOverflow(middlewareArguments);
    return {};
  },
};
```
in `computePosition`? I can't find any example how to implement this own modifier/middleware into the middleware array.

**Comment by atomiks** [comment]
That's now [`shift()`](https://floating-ui.com/docs/shift), just a different name

**Comment by bennymeier** [comment]
Thank you!!

**Comment by Grandizer** [comment]
This is great and all, but you do have the `detectOverflow` function. I put code in there with a boundary and it seems to work great in detecting when the tooltip is in an overflow state. But I cannot see how to use that data from the middleware. Your docs do not show how to implement this into the following:

    export function setupPopovers() {
      const triggers = document.querySelectorAll("[id^='my-trigger-']");
      const body = document.getElementById("the-body");

      triggers.forEach((triggerElement) => {
        const trigsPopId = triggerElement.getAttribute("popup-id");
        const arrowId = triggerElement.getAttribute("arrow-id");

        if (trigsPopId) {
          const popoverElement = document.getElementById(trigsPopId);
          const arrowElement = document.getElementById(arrowId);

          if (popoverElement) {
            const middlewareDO = {
              name: 'middleware',
              async fn(state) {
                const overflow = await detectOverflow(state, {
                  boundary: body,
                });
                console.log('should flip:', overflow.top >= 0); // This is the boolean I want
                return {}; // have tried returning overflow.top >= 0 but nothing shows
              },
            };

            function updatePosition(trigger, popover) {
              computePosition(trigger, popover, {
                placement: triggerElement.getAttribute("my-arrow-position"),
                middleware: [
                  offset(8),
                  middlewareDO,
                  flip({ crossAxis: true }),
                  shift({ padding: 5 }),
                  arrow({ element: arrowElement }),
                ],
              })
              .then(({ x, y, placement, middlewareData }) => {
                Object.assign(popover.style, {
                  left: `${x}px`,
                  top: `${y}px`,
                });

                console.log('middleware:', middlewareData);

                const { x: arrowX, y: arrowY } = middlewareData.arrow;
                const staticSide = {
                  top: 'bottom',
                  right: 'left',
                  bottom: 'top',
                  left: 'right',
                }[placement.split('-')[0]];

                Object.assign(arrowElement.style, {
                  left: arrowX != null ? `${arrowX}px` : '',
                  top: arrowY != null ? `${arrowY}px` : '',
                  right: '',
                  bottom: '',
                  [staticSide]: '-4px',
                });
              });
            }

            triggerElement.addEventListener('mouseenter', () => {
              updatePosition(triggerElement, popoverElement);
              popoverElement.style.display = 'block';
            });
            triggerElement.addEventListener('mouseleave', () => {
              popoverElement.style.display = 'none';
            });
          }
        }
      });
    }


In a situation where it does not need to flip this is the log: 

    overflow: {top: -3, bottom: -422.046875, left: -273.42949999999996, right: -740.4295}
    should flip: false
    middleware: 
      arrow: {x: 166.5, centerOffset: 0}
      flip: {}
      middleware: {}
      offset: {x: 0, y: -8}
      shift: {x: 0, y: 0}

And in the situation where it should flip I see this in the log:

    overflow: {top: 22, bottom: -447.046875, left: -273.42949999999996, right: -740.4295}
    should flip: true
    middleware: 
      arrow: {x: 166.5, centerOffset: 0}
      flip: {}
      middleware: {}
      offset: {x: 0, y: -8}
      shift: {x: 0, y: 0}

So how can I get the value from the `detectOverflow` into the `middlewareData` or somewhere accessible?
