### ISSUE TITLE
[React] `FloatingFocusManager` negative `initialFocus` breaks modality?

### ISSUE THREAD

**Issue by KenjiTakahashi** [floating-ui/floating-ui#2052]
Modified "Basic Popover" example: https://codesandbox.io/s/frosty-lamport-u2z5pt.

What we're trying to achieve is a modal with no initial focus that circles over elements in the list after user starts "Tabing".
Thought that setting `initialFocus={-1}` is going to do it, but it seems that it makes the modal lose focus and get closed instead.

**Comment by atomiks** [comment]
In this case, the `order` prop does what you want instead of `initialFocus`:

`order={['reference', 'content']}`

**Comment by KenjiTakahashi** [comment]
Thanks, we have tried that already, but it's not ideal as well.

Firstly, it adds the button that opened the modal to the "focus list", which is not sth we want.
Secondly, and more importantly, it seems to be having problem doing the initial focus. I.e. when I Tab once, there's no focus visible, when I Tab twice, the focus is visible already on the second item.

Also, on Safari only, `reference` seems to work the same as `floating` for some reason. (Focus on Safari works weird in general, though, not sure what can be done about it.)

**Comment by atomiks** [comment]
So there's an easier solution than that ^ — set `initialFocus` to the floating ref:

```js
const {refs} = useFloating();

<FloatingFocusManager initialFocus={refs.floating}>
  {/* ... */}
</FloatingFocusManager>
```

`initialFocus={-1}` means focus isn't moved at all, so in the case of modal focus management, the focus doesn't get trapped which causes the issue you see. It needs to be set inside the focus trap, so we can use the floating element itself as the initial point of focus.

This needs to be documented which I'll do shortly.

**Comment by KenjiTakahashi** [comment]
Thanks @atomiks and sorry for a late response, holiday time ;-). It does indeed work as expected, except on Safari as mentioned. Now we'll have to look into the issue with Safari, but that's probably separate problem.

One point to note, current TS definitions do not allow for this usage. Had to cast to `any` to make it pass.

**Comment by atomiks** [comment]
What version of the library are you on? On Safari 16, the trap works and so does focus with and without this option enabled:

<img width="454" alt="Screenshot 2023-01-03 at 3 24 03 pm" src="https://user-images.githubusercontent.com/22450188/210299911-40acba85-70a9-4f84-a347-917ea2faa89e.png">

The types also don't complain on latest either

**Comment by KenjiTakahashi** [comment]
We're on `0.15.1`, which is the latest AFAICT?

The trap works on Safari, but tabbing doesn't. It might have to do with the contents of the popover. In our real code, we have a list (`dl`/`dd`) inside and it seems that Safari defaults to focusing the list itself instead of the items.

For TS, this is the error we're getting (it's TS `4.9.4`):
```typescript
43     <FloatingFocusManager context={context} initialFocus={floating}>
                                               ~~~~~~~~~~~~

  node_modules/@floating-ui/react/src/components/FloatingFocusManager.d.ts:7:5
    7     initialFocus?: number | React.MutableRefObject<HTMLElement | null>;
          ~~~~~~~~~~~~
    The expected type comes from property 'initialFocus' which is declared here on type 'IntrinsicAttributes & Props<ReferenceType>'
```

**Comment by atomiks** [comment]
That's because you are assigning the callback ref `floating`, not `refs.floating`

**Comment by KenjiTakahashi** [comment]
Ah, you're right! Interestingly, it effectively works the same either way.

Forgot to mention, Safari also works fine if I switch the switch you mentioned. So it's just Safari thing, I think.

Thanks a lot for your help!
