### ISSUE TITLE
[DOM] Use `IntersectionObserver` in `autoUpdate`

### ISSUE THREAD

**Issue by idevelop** [floating-ui/floating-ui#2053]
In our usage of `floating-ui` we came across a scenario where the floating element's position isn't getting updated, because neither `ancestorScroll`, `ancestorResize`, nor `elementResize` would catch what's changing in the document. Enabling `animationFrame` fixes the issue, however we're concerned about the performance impact this would have.

Looking into the implementation of `autoUpdate` with `animationFrame: true`, I noticed that you're comparing the result of `getBoundingClientRect` on every frame.

I was curious if this approach ever came up on your radar: https://toruskit.com/blog/how-to-get-element-bounds-without-reflow/

Here's a proposal that I haven't tested yet, but just to illustrate what I think this would look like: https://github.com/idevelop/floating-ui/commit/7ab6b5dd356e94a3f2252a0ec78c8587d6e5ca5a

**Comment by atomiks** [comment]
With the async approach, it's possible for certain frames to be wrong - anything layout related should be sync. For example, with 6x CPU slowdown, there can be stale positions like this (this is visible for 1 frame, but could be longer in more complex layouts):

<img width="665" alt="Screenshot 2022-12-21 at 11 45 02 pm" src="https://user-images.githubusercontent.com/22450188/208908480-808e9996-5125-48be-b097-c33f6f831246.png">

**Comment by idevelop** [comment]
Yeah that's a good point. I wonder if there's an argument for giving developers the choice, given that each approach has pros and cons:
- the sync approach guarantees layout updates happen in sync, with no frames missed, with the downside of unnecessary calls to `getBoundingClientRect` on every animation frame that will affect performance
- the async approach should have much less performance impact, with the downside of the risk of missing frames on slower CPUs / complex pages

Completely agree that the risk of dropping frames exists in async, I'm not sure what the 6x CPU slowdown maps to in practice. Do we have any way of knowing what class of computers are that slow, and what % of internet users would that be?

**Comment by FezVrasta** [comment]
Could it be exposed as a separate utility maybe?

**Comment by idevelop** [comment]
> Could it be exposed as a separate utility maybe?

That's an interesting idea, I could see this being a separate `intersectionObserverAutoUpdate` function exported by your package, that could be used by itself to replace `autoUpdate` since it would cover every case (option) handled currently by `autoUpdate`.

**Comment by atomiks** [comment]
`async: true` would be most ergonomic, disabling everything else and switching to this technique, with the downside of tree-shaking

**Comment by atomiks** [comment]
I wonder if this should be enabled by default and only disabled when `animationFrame: true`? I know it also has to run in a loop, but presumably it's optimized enough to use as a default given its async nature.

**Comment by atomiks** [comment]
cc @sanajaved7 @oluoluoxenfree @jgerigmeyer: do you think this would be a good default to add for `autoUpdate`? Since it would handle arbitrary layout changes, it makes it far more reliable. Any perf implications?

**Comment by jgerigmeyer** [comment]
> do you think this would be a good default to add for `autoUpdate`? Since it would handle arbitrary layout changes, it makes it far more reliable.

Yes, I'd support making this the default -- especially if users can opt out by enabling `animationFrame`. It covers more use cases, with few/minor downsides as far as I can tell.

> Any perf implications?

Hard to say without testing out a PR, but theoretically they should be minimal. 🤷

**Comment by atomiks** [comment]
I'm thinking we make `animationFrame` do this, which keeps backwards-compatibility:

- `undefined` = use the async version (on by default)
- `true` = use the sync version
- `false` = disable both versions

I'll make a PR for this shortly

**Comment by atomiks** [comment]
Here are the results where a floating element is sitting idley on the screen for 5 seconds (M1 Mac)

Seems to be actually much worse for performance, possibly because we're creating a new observer on every frame? 

## Sync
 
<img width="335" alt="84ms scripting time out of 4.8 seconds" src="https://user-images.githubusercontent.com/22450188/211814379-76d4f450-8591-45ae-ae7f-756af8aa0904.png">


## Async

<img width="329" alt="1253ms scripting time out of 4.8 seconds" src="https://user-images.githubusercontent.com/22450188/211814301-e9d32ac8-8eb5-48ff-b31e-90c5e02864ed.png">

**Comment by atomiks** [comment]
I'm going to close this issue as it seems to perform worse than the sync method, but if you have any evidence that it's worthwhile I can re-open the issue. I think the sync method is fine to use if you aren't noticing any performance issues, especially for transient elements that aren't open all the time (which most floating elements are).
