### ISSUE TITLE
Build error when using react-scripts

### ISSUE THREAD

**Issue by sam159** [floating-ui/floating-ui#2062]
I've ran into a build issue when using this in a project created with create-react-project.

```
# npm run build
> react-scripts build  

Creating an optimized production build...
Failed to compile.

TypeError: C:\Users\Sam\WebstormProjects\untitled1\node_modules\@floating-ui\core\dist\floating-ui.core.browser.min.mjs: Cannot read properties of undefined (reading 'constantViolations')
    at transformFile.next (<anonymous>)
    at run.next (<anonymous>)
    at transform.next (<anonymous>)
```

The same error doesn't occour if I repoint it to use the non-minified mjs file.

Reproduction steps (node 18 or 16)

1) start new project `npx create-react-app test-bug`
2) install the react-dom package `npm install @floating-ui/react-dom`
3) update src/App.js to reference package (example below)
4) do `npm run build`

```javascript
import {useFloating} from "@floating-ui/react-dom";
import './App.css';

function App() {
  const {x, y, reference, floating, strategy} = useFloating();

  return (
      <>
        <button ref={reference}>Button</button>
        <div
            ref={floating}
            style={{
              position: strategy,
              top: y ?? 0,
              left: x ?? 0,
              width: 'max-content',
            }}
        >
          Tooltip
        </div>
      </>
  );
}
export default App;
```

**Comment by atomiks** [comment]
Have you tried updating your Babel config? https://github.com/babel/babel/issues/13907

**Comment by atomiks** [comment]
Yeah I see, might have to submit a bug to Babel because it looks like it can't parse(?) or transform that minified file probably even though it's valid.

**Comment by atomiks** [comment]
Actually, I just updated some Babel deps locally, re-built, pasted it in the repro `node_modules` and now it builds properly. So the old deps might cause a problem with new versions of Babel or such...

**Comment by atomiks** [comment]
There may be a bit of a delay in releasing this fix (will be within the next ~1 week though), so in the meantime anyone encountering this issue, install [`patch-package`](https://www.npmjs.com/package/patch-package) and edit `node_modules/@floating-ui/core/package.json` by removing the `min` from the `"browser"` default field (so it uses the unminified file, it'll still get minified). This will make your builds work until the patch gets released.

**Comment by atomiks** [comment]
Well it looks like Babel has a fix for it, it seems like a new issue: https://github.com/babel/babel/issues/15300

**Comment by atomiks** [comment]
https://github.com/babel/babel/pull/15301#issuecomment-1363014495

Fixed in [@babel/plugin-transform-block-scoping@7.20.8](https://www.npmjs.com/package/@babel/plugin-transform-block-scoping/v/7.20.8)

**Comment by reesscot** [comment]
I know this isn't directly related to your code, but for others following this ticket I'm seeing a new build error with 7.20.8:
```
TypeError: /home/runner/work/amplify-ui/amplify-ui/canary/apps/react/cra/node_modules/@floating-ui/core/dist/floating-ui.core.browser.min.mjs: Cannot set properties of undefined (setting 'kind')
```

**Comment by reesscot** [comment]
I'll open a bug on babel
