### ISSUE TITLE
autoPlacement config: allowedPlacement values  *-start and *-end do not work unless an alignment is also explicitly specified

### ISSUE THREAD

**Issue by dancingbug** [floating-ui/floating-ui#2072]
* Expected behavior:
    `allowedPlacements: ['top-start']` causes the floating element to be positioned above the reference. with the floating element and the reference horizontally aligned on their left edges.

* Actual:
    unless `alignment:'start'` or `alignment:'end'` is also specified, the floating element is placed in bottom center placement, or the placement given by the `placement` config option if it was specified

This is true also of the other *-start and *-end placements. the regular left/right top/bottom placements appear to work

* Example:
    https://codesandbox.io/s/floating-ui-dom-template-forked-dhh69v?file=/src/index.js

I suggest modifying your linked codesandboxes to position the reference element away from the upper left corner, so that placement bugs will be more noticeable

**Comment by atomiks** [comment]
It does document this in the code, maybe not on the docs (haven't checked). But maybe there's an improvement to be made with how the options work.

<img width="618" alt="Screenshot 2022-12-26 at 3 22 33 pm" src="https://user-images.githubusercontent.com/22450188/209499556-a375b1c8-932e-4d7d-a0e6-e9316c67a592.png">

**Comment by atomiks** [comment]
Made a PR for this: https://github.com/floating-ui/floating-ui/pull/2073 (I think this will greatly reduce confusion and should be how it works to begin with)
