### ISSUE TITLE
[Vue] Use `ComputedRef` alongside `Ref` in `MaybeReadonlyRef`

### ISSUE THREAD

**Issue by enkot** [floating-ui/floating-ui#2075]
If use the `middleware` as `computed` FloatingUI complains about types. Example: 
```ts
const { x, y, placement, strategy, middlewareData } = useFloating(
  initiator,
  floating,
  {
    middleware: computed(() => []),
  }
);
```
I guess `MaybeReadonlyRef` should accept `ComputedRef` as well:
```ts
export declare type MaybeReadonlyRef<T> = T | Readonly<Ref<T> | ComputedRef<T>>;
```

**Comment by lozinsky** [comment]
[`ComputedRef` is subtype of `WritableComputedRef`](https://github.com/vuejs/core/blob/8dcb6c7bbdd2905469e2bb11dfff27b58cc784b2/packages/reactivity/src/computed.ts#L9-L12) [which is subtype of `Ref`](https://github.com/vuejs/core/blob/8dcb6c7bbdd2905469e2bb11dfff27b58cc784b2/packages/reactivity/src/computed.ts#L14-L16). This means that [assignment of `ComputedRef` type to `Ref` type](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzjAnmApnASugZgGjgGMJwBXGdAEzgF85cpS4AiANzPRYG4AoXkgDsAzvEqiAXNjwAeUVGCCA5gD44AXmKkwFagAo9ASg1qA5KcN8gA) is valid. But maybe it depends on typescript configuration. Can you please show an error message?

**Comment by atomiks** [comment]
I'm going to close this as it seems like the type already works as expected as above, and there's no reproduction to look into
