### ISSUE TITLE
Export more useful utilities to simplify usage

### ISSUE THREAD

**Issue by atomiks** [floating-ui/floating-ui#2078]
There are utilities like `autoUpdate`, but the library is missing many more that could be useful. Of course, the library still gives full control, but common use cases should be handled more easily. This issue applies to most of the packages, although the React package added several utilities recently.

## Virtual elements

A point reference is the most common one:

```js
createVirtualElement({
  width: 0,
  height: 0,
  x: clientX,
  y: clientY,
});
```

I think range selections and modifying/deriving `getBoundingClientRect` on a real element are already simple enough?

## Arrows

These are by far the biggest pain — we should simplify both applying arrow styles and creating an actual arrow element in the first place.  We should export function(s)/components that either generate an SVG or provide data to generate one. 

SVGs are less limited than the most basic CSS styles, as they can:

- Have a border
- Allow the floating element to be partially transparent (no overlapping problem)
- Are flexible when it comes to roundedness, shape, etc.

Options could include:

- type (isosceles or right-angle)
- angle
- size
- roundness
- color
- border

Since `offset.mainAxis` usually needs to equal the hypotenuse length of the arrow, a utility for that could also be included.

## Other

If you have ideas, please comment!

**Comment by mihkeleidast** [comment]
From the [testing docs](https://floating-ui.com/docs/react#testing), the `waitForPosition` testing utility would perhaps be useful to export.

**Comment by atomiks** [comment]
For arrows, I'm not actually sure if this should be part of the library code, but rather, just some generator thing on the docs. 

I have no idea how to generate unique rounded shapes like this programmatically in code (made this in Figma):

<img width="805" alt="Screenshot of rounded arrows on the four sides" src="https://user-images.githubusercontent.com/22450188/211826931-f29987ed-d9ca-4089-90c7-1885eca48dd2.png">

The docs could maybe just have a bunch of copy & pasteable SVG shapes with some CodeSandbox links showing how to use each one of them.
