### ISSUE TITLE
Tooltip triggered by default when using it inside a popover

### ISSUE THREAD

**Issue by sajadevo** [floating-ui/floating-ui#2085]
Hey @atomiks,

I'm using a Tooltip component inside a Popover and when I open the Popover the Tooltip open by default, here is a codesandbox link related to this issue: [https://codesandbox.io/s/tender-rgb-8wzhew?file=/src/App.tsx](https://codesandbox.io/s/tender-rgb-8wzhew?file=/src/App.tsx)

Cheers,
Sajad

**Comment by atomiks** [comment]
This is because the button is the first element in the content order to receive focus, which triggers the tooltip. [Details about `initialFocus` can be found here](https://floating-ui.com/docs/FloatingFocusManager#initialfocus).

**Comment by sajadevo** [comment]
@atomiks thanks for the response got right answer 🙏🏻
