### ISSUE TITLE
Handling transitions

### ISSUE THREAD

**Issue by mihkeleidast** [floating-ui/floating-ui#2088]
## Goal

I'm attempting to implement in-out transitions on a Tooltip component. I'd like to understand if there is some preferred library for implementing such transitions, or if it would be feasible to support this directly in floating-ui.

Sort of a discussion really - I did find https://github.com/floating-ui/floating-ui/discussions/1873, but that is also not solved.

## Current state

Example implementation I currently have: https://codesandbox.io/s/beautiful-jennings-zm83g8?file=/src/Tooltip.tsx

It uses the [react-transition-state](https://github.com/szhsin/react-transition-state) library that provides a hook that handles the animation. To be fair, I'm not too happy with that lib, but I haven't found any better hook-based libraries either. I suppose I could try out [react-transition-group](https://github.com/reactjs/react-transition-group) as well, though I do not like that component-based approach at all in 2023.

So, the Tooltip component allows both "auto" placement and some specific placement. If a specific placement is set, the positioning and transitions work fine. With the auto placement, however, the first transition is always with `placement="bottom"`, as the auto placement needs time to calculate the final placement. So this takes the transition and actual placement out of sync - the Tooltip is placed on the right, but the transition is for bottom. I assume that flip can also have this issue, whenever it actually needs to flip to some alternative placement.

I do know that there is now the `isPositioned` boolean returned from the hook that is true only when the final placement is calculated. So I attempted to make the transition state dependent on that: https://codesandbox.io/s/gracious-sound-9c52jf?file=/src/Tooltip.tsx

This version does not have the "in" transition for some reason. It might have something to do with the library I'm using for handling the transition, I don't really know. Either way it's quite cumbersome to mix'n'match these different libraries, it turns into a state variable conditional hell pretty quickly.

## Feature request?

I would assume that such transition and animation needs are quite common to be implemented together with different floating elements - at least in my memory this is usually the number 1 feature request from UI designers that I have to implement. So, it would be nice if we could provide some guidance and/or examples how these could be implemented - i.e. which hook/component would be a good match to use together with floating-ui for this.

Perhaps, if there is no good match out there, it could also be a new hook that lives inside floating-ui? As the positioning logic has to be quite tightly tied to the animation and mounting states, this might be a good approach?

```
const { isMounted, transitionState } = useFloatingTransition({
  open,
  placement,
  isPositioned,
  timeoutMs: 100,
});
```

**Comment by atomiks** [comment]
`framer-motion` and `react-spring` handle this well, but they aren't small so I guess some hooks for handling pure CSS animations would be nice to add.

**Comment by atomiks** [comment]
So to implement placement-aware animations (currently), you can do the following: 

https://codesandbox.io/s/reverent-shannon-dp1byq?file=/src/Tooltip.tsx

`react-transition-group` is used only for the unmounting timeout.

- Inside an effect, apply the "out" styles unconditionally;
- Then, inside a `rAF`, apply the transition style and the "in" styles when `state.open === true`. It immediately cleans up the logic that would start the animation from the false initial placement, so it never runs, only running the logic for the real placement.

`isPositioned` doesn't appear suitable because it won't wait for the unmounting animation.
