### ISSUE TITLE
[React] Configure keyboard events in `useListNavigation` hook

### ISSUE THREAD

**Issue by maxmalov** [floating-ui/floating-ui#2090]
# Motivation

The hardcoded navigation configuration (arrow keys, Home, and End) is great and covers a lot of cases. But sometimes it makes it hard to use different keyboard events for navigation. E.g. I'd like to navigate in the list using Tab and Shift+Tab. It is possible, but requires a lot of work, since I have to respect `loop`, `allowEscape` options manually.

On the other hand, the default preset makes it impossible to move cursor in a reference `input` element with `Home` and `End` buttons when focus is virtual.

# Suggestion

I was thinking, it would be awesome to have a new optional configuration field that would map navigation actions to the keyboard events, e.g

```js
type EventMatcher = string | (event: KeydownEvent) => boolean
type NavigationMap = {
  start?: EventMatcher,
  end?: EventMatcher,
  previous?: EventMatcher,
  next?: EventMatcher,
}

// usage

useListNavigation({
  ...currentOptions,
  navigationMap: {
    start: undefined, // disable navigation to the start
    end: undefined, // disable navigation to the end
    previous: (event) => event.key === 'Tab' && event.shiftKey,
    next: 'Tab'
  }
})
```

What do you think about the motivation and the proposed suggestion? If is okay I'd like to make a PR with the changes.

**Comment by atomiks** [comment]
>  E.g. I'd like to navigate in the list using Tab and Shift+Tab. It is possible, but requires a lot of work, since I have to respect loop, allowEscape options manually.

You don't need the `useListNavigation` hook then, the natural tab order with `FloatingFocusManager` will handle it. Or do you have another edge case in mind also?

**Comment by atomiks** [comment]
> My usecases require a virtual focus to be enabled

Oh I see, sorry for missing that.

I'm curious what type of component allows using Tab + Arrow keys simultaneously?

**Comment by maxmalov** [comment]
That's a custom autocomplete integrated into xterm. The arrows navigation is for users with IDE experience and the Tab navigation is for users with terminal experience.

**Comment by maxmalov** [comment]
I've played around with implementation and noticed that workarounds are easier to implement rather having this functionality in the library code 😅. I'm going to close this issue
