### ISSUE TITLE
[React] Define the root node for `FloatingPortal` instead of the portal subroot node

### ISSUE THREAD

**Issue by mihkeleidast** [floating-ui/floating-ui#2094]
Not sure what to call this, maybe some observation / feedback / question on a recent change.

From https://github.com/floating-ui/floating-ui/pull/1985:

> refactor(FloatingPortal): portal content by default no longer injects itself into a single root node with a default id of floating-ui-root. Instead the portals have a unique id and get removed from the DOM when the FloatingPortal’s host component unmounts — when specifying an id this logic can be bypassed however as it is assumed the node is static or controlled elsewhere. This better supports the new focus management system. (https://github.com/floating-ui/floating-ui/pull/1985)

Previously, the logic was that there was a single root node with id `floating-ui-root`. The portals themselves did not have subroots, i.e. they just forwarded children to the root.

```html
<body>
  <div id="floating-ui-root">
    <div class="my-component"></div>
    <div class="my-component"></div>
  </div>
</body>
```

When one specified a custom id to FloatingPortal, it made it possible to change the root node, but otherwise the structure would be the same i.e. the result would have been:

```html
<body>
  <div>
    <!-- custom root can be deep inside the rest of the app structure: https://github.com/floating-ui/floating-ui/blob/master/packages/react/test/visual/components/Drawer.tsx#L112 -->
    <div id="custom-root">
      <div class="my-component"></div>
      <div class="my-component"></div>
    </div>
  <div>
</body>
```

Now, it seems that there is no specific root node (it defaults to document.body), and the portals themselves are rendered into their own subroots, that are rendered into the root node.

```html
<body>
  <div id="subroot-1">
    <div class="my-component"></div>
  </div>
  <div id="subroot-2">
    <div class="my-component"></div>
  </div>
</body>
```

If I specify a custom ID to a component's FloatingPortal, it renders all of mu components to the same subroot, which results in a different HTML structure when viewed from the perspective of the subroot - there can be multiple focus guards in the same subroot in this case, which seems a bit weird? Also, there is no specific "root" in this case, really - it's whatever the parent node of the specified subroot is.

```html
<body>
  <div>
    <!-- custom root can be deep inside the rest of the app structure: https://github.com/floating-ui/floating-ui/blob/master/packages/react/test/visual/components/Drawer.tsx#L112 -->
    <div id="custom-root">
      <div class="my-component"></div>
      <div class="my-component"></div>
    </div>
  <div>
</body>
```

## Question / proposal

Wouldn't make more sense to keep the one-subroot-for-portal behavior, and instead of specifying the id of a specific portal, allow specifiying the root id / node? So the default output would be:

```html
<body>
  <div id="floating-ui-root">
    <div id="subroot-1">
      <div class="my-component"></div>
    </div>
    <div id="subroot-2">
      <div class="my-component"></div>
    </div>
  </div>
</body>
```

And with a custom root:

```html
<body>
  <div>
    <!-- custom root can be deep inside the rest of the app structure: https://github.com/floating-ui/floating-ui/blob/master/packages/react/test/visual/components/Drawer.tsx#L112 -->
    <div id="custom-root">
      <div id="subroot-1">
        <div class="my-component"></div>
      </div>
      <div id="subroot-2">
        <div class="my-component"></div>
      </div>
    </div>
  </div>
</body>
```

This would ensure that each of the portals with their focus guards are still rendered into their own nodes, which I assume was the reason for the change in the first place. But it would still allow specifying a custom root node that should keep all the portals injected into there.

All that said, I'm not even sure if this (i.e. multiple portals rendered into a single subroot) is even a problem - but you probably know the specifics of the focus management change, so perhaps can tell if it is not relevant.

The Drawer component I added in the HTML comment is a good example, I think, of a component where the current system feels a bit weird - in order for me to get the expected output of what looks more correct in my mind, I can't use the FloatinPortal at all? Or I should inject the subroots into my own root myself, which is sort of duplicating the code.

---------

This article came up as well, I know we've discussed it before already, but not sure if it should be considered or not - there is definitely more stuff being appended to body right now than there were before: https://atfzl.com/don-t-attach-tooltips-to-document-body

**Comment by atomiks** [comment]
The new portal system is largely taken from Ariakit, which also just injects each portal node into the `<body>`. Each node needs a unique id for the `aria-owns` attribute for non-modal + Portal focus management. 

It looks messy but shouldn't be a perf concern because there's no layout or positioning calculations being performed with a `children`-less (initially) `<div>` being inserted into the body, unlike with a tooltip being positioned as in the article. The concern is appending the children directly into `<body>`, but when they get rendered, they are within the portal node, so the perf problem doesn't exist

**Comment by mihkeleidast** [comment]
Yeah, the perf thing was mostly an aside, not a real concern.

> The new portal system is largely taken from Ariakit, which also just injects each portal node into the `<body>`. Each node needs a unique id for the `aria-owns` attribute for non-modal + Portal focus management.

So it is an issue, when a component that can be rendered n times specifies a static ID (like in the linked Drawer example), it should always be unique?

**Comment by atomiks** [comment]
> It's just a lot of portal nodes appended to body when a page has lots of tooltips and I kind of want to clean up my devtools :D

Actually for tooltips I recommend a static string id since they don't care about focus management and are far more numerous, for anything that uses focus management you should omit it

> So it is an issue, when a component that can be rendered n times specifies a static ID (like in the linked Drawer example), it should always be unique?

Depends if it's rendered multiple times, would be an issue for nested ones, but not discrete separate components where two can't be open simultaneously. In any case it'd be unreliable compared to the dynamic/unique id.

**Comment by mihkeleidast** [comment]
> Actually for tooltips I recommend a static string id since they don't care about focus management and are far more numerous, for anything that uses focus management you should omit it

That's a good point! Though, won't that cause z-index issues, for example when a modal is rendered to it's own subroot, and there's a tooltip in there - if that tooltip in modal is then rendered into some pre-existing root, it can render below the modal?

> Depends if it's rendered multiple times, would be an issue for nested ones, but not discrete separate components where two can't be open simultaneously.

Yes and no - it's relevant to the transition topic as well - two drawers are open at the same time when switching from one to the other, and both are transitioning. But this is only my example component, I'm not sure what other wild things are being done or could be done with this library.

> In any case it'd be unreliable compared to the dynamic/unique id.

That's what I assumed, hence the issue. The issue is - if I just get a new unique id from `useId` and use it on FloatingPortal, it will append it to the default root document.body, if the element does not already exist in the DOM. So, if I want to use it in a custom root (`drawer-root`), which is deep in the app structure (necessary for other layout needs), I would have to create and append the custom subroot element myself and append it to my custom root? Which would duplicate a lot of what FloatingPortal already does?

**Comment by mihkeleidast** [comment]
I think the easiest and most correct way to use it for the Drawer example would be to allow changing [this default value here](https://github.com/floating-ui/floating-ui/blob/master/packages/react/src/components/FloatingPortal.tsx#L54), but that does not seem possible without duplicating a lot else as well.

Can we add something like `fallbackRootId` and`fallbackRootNode` to FloatingPortal to allow this?

**Comment by atomiks** [comment]
> That's a good point! Though, won't that cause z-index issues, for example when a modal is rendered to it's own subroot, and there's a tooltip in there - if that tooltip in modal is then rendered into some pre-existing root, it can render below the modal?

Yeah this is a good point, right now `FloatingPortal` avoids z-index wars if each floating element has the same z-index, as DOM insertion order means later ones take priority (best way to avoid `z-index` wars imo?)

So essentially the main concern here for you is that there's tons of nodes in the DOM tree which looks messy in DevTools? And that by default, you want all the nodes to be portalled into one single common root node? In this way, there's still many portal nodes, but they're all nested/neatly hidden within a single root `<div>`.

**Comment by atomiks** [comment]
Any chance you can set up a PR for what you're describing? Kind of confused what you mean 😅
