### ISSUE TITLE
Upgrading from @floating-ui/react-dom 1.0.0 to 1.1.1 breaks positioning

### ISSUE THREAD

**Issue by akinnee** [floating-ui/floating-ui#2096]
Followup from comments here: https://github.com/floating-ui/floating-ui/issues/2091

I'm using a library which depends on @floating-ui/react-dom `^1.0.0`. When I upgraded packages, it installed `1.1.1` which broke the positioning of the popup as shown in the screenshots below.

I'm unable to share the specific library that depends on floating-ui since it's internal. The authors will update their usage to work with 1.1.x, but others may run into this problem so I'll post it here anyway.

1.1.x version:
![Screen Shot 2023-01-05 at 7 52 49 PM](https://user-images.githubusercontent.com/3019562/211064315-c8434827-f0cb-4651-8e24-d27456e964d8.png)

1.0.x version after package.json overrides:

![Screen Shot 2023-01-05 at 8 05 17 PM](https://user-images.githubusercontent.com/3019562/211064654-1280c169-029c-4400-a879-3fe053936cb9.png)

If anyone else runs into this, I was able to fix it for now with overrides in package.json:

```
"overrides": {
    "dependency-that-uses-floating-ui-1.x": {
      "@floating-ui/react-dom": "1.0.0"
    }
  },
  ```
  
@atomiks asked [here](https://github.com/floating-ui/floating-ui/issues/2091#issuecomment-1373452918) to check if the issue happens in 1.1.0 or 1.1.1 or both of `@floating-ui/react-dom`.
  
I looked at my package-lock.json in the commit where it originally broke, and it contained this combination of dependencies:

Affected library had `@floating-ui/react-dom@1.1.1` which had `@floating-ui/dom@1.1.0` which had `@floating-ui/core@1.1.0`.

The library author told me installing `@floating-ui/react-dom@1.1.1` fixed the problem, so maybe you've already fixed this in one of the sub-dependencies.

**Comment by atomiks** [comment]
Based on your overrides, the latest `core` and `dom` packages (`v1.1.0`) are not the problem, only `react-dom v1.1.1`, right?

It's hard to understand what the problem is without an actual reproduction, but if you try testing each of `react-dom@1.1.0` and `react-dom@1.1.1` in your overrides key (and re-installing) to see if which one is the issue, that would help

> Affected library had @floating-ui/react-dom@1.1.1 which had @floating-ui/dom@1.1.0 which had @floating-ui/core@1.1.0.

> The library author told me installing @floating-ui/react-dom@1.1.1 fixed the problem, so maybe you've already fixed this in one of the sub-dependencies.

I don't see how it would be fixed suddenly though, given `core` and `dom` are unchanged

**Comment by atomiks** [comment]
Unfortunately it's not :\

The dual sync technique works fine in `v1.1.1`: https://codesandbox.io/s/floating-ui-react-dom-template-forked-ccujnq?file=/src/App.js, including when updating either of the nodes as seen in the demo, and resizing the window to indicate `autoUpdate` is active.

**Comment by akinnee** [comment]
Ok, I think we can just close this. If anyone else runs into the problem hopefully they'll find this thread useful. Thanks!
