### ISSUE TITLE
[React] Make `useRole` more useful

### ISSUE THREAD

**Issue by atomiks** [floating-ui/floating-ui#2099]
Right now, `useRole` accepts the `role` of the floating element and using that, adds props to the floating element and reference elements to add screen reader support. 

## Problem

- Roles aren't specified for `item`s so they need to be manually added if needed.
- `listbox` shouldn't necessarily add `role="combobox"` to the reference element, e.g. for a select button rather than an input — sometimes there are bugs like with VoiceOver in Safari, so you need to add `role={undefined}` after the prop getters spread.
- Some additional props must be added based on the type of component which is more involved than is known from the role of the floating element, e.g. `aria-autocomplete`.
- There are some nuances around tooltips with `role="tooltip"`, e.g. using `aria-labelledby` instead of `aria-describedby` and omitting that role entirely for certain types of tooltips which has been discussed here previously.

## Solution

Configuration could be based on the component rather than the base floating role, such as:

- `type: 'tooltip'`
- `type: 'label'`
- `type: 'autocomplete'`
- `type: 'select'`
- `type: 'multiselect'`
- etc

`role` option could continue to exist for uncommon components to still enable custom configs where the base props that add `aria-expanded`/`aria-controls` are very useful, but this `type` option should help simplify things and ensure good defaults in the majority of use cases

**Comment by ayushi0809** [comment]
HI @atomiks  can I work on this feature?

**Comment by atomiks** [comment]
Sure, [this is the hook](https://github.com/floating-ui/floating-ui/blob/master/packages/react/src/hooks/useRole.ts)
