### ISSUE TITLE
Fix typescript 4.9.4 error

### ISSUE THREAD

**Issue by nikage** [floating-ui/floating-ui#2106]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Here is an error I got:
```
  node_modules/tippy.js/node_modules/@popperjs/core/lib/types.d.ts:117:36
    117 export declare type Modifier<Name, Options> = {
                                           ~~~~~~~
    This type parameter might need an `extends Obj` constraint.
```

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `@popperjs/core@2.10.2` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/tippy.js/node_modules/@popperjs/core/lib/types.d.ts b/node_modules/tippy.js/node_modules/@popperjs/core/lib/types.d.ts
index 11f9219..1aed7b2 100644
--- a/node_modules/tippy.js/node_modules/@popperjs/core/lib/types.d.ts
+++ b/node_modules/tippy.js/node_modules/@popperjs/core/lib/types.d.ts
@@ -114,7 +114,7 @@ export declare type ModifierArguments<Options extends Obj> = {
     options: Partial<Options>;
     name: string;
 };
-export declare type Modifier<Name, Options> = {
+export declare type Modifier<Name, Options extends Obj> = {
     name: Name;
     enabled: boolean;
     phase: ModifierPhases;
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by atomiks** [comment]
This was fixed in April 2022, you can uninstall then reinstall `tippy.js` to get the latest `@popperjs/core` version

**Comment by nikage** [comment]
@atomiks thanks for the quick response! That is very helpful. It seems like  patch-package   created an issue in the wrong repo.
