### ISSUE TITLE
[React] Focus floating element in `useListNavigation` when item loses focus

### ISSUE THREAD

**Issue by nzaytsev** [floating-ui/floating-ui#2107]
[preview](https://codesandbox.io/s/issue-for-floating-ui-sq0lhw)

when focus is on an dissappearing/disabling item the focus is lost

steps to reproduce:

- configure useNavigation hook on list
- make one or more items removable on click
- click on removable item by keyboard

real use case: multiselect dropdown with `clear button` which disappears on click

**Comment by nzaytsev** [comment]
> In this case, calling `refs.floating.current?.focus()` after the clear button disappears would be better rather than falling back to an item index I think.
> 
> [Example](https://codesandbox.io/s/determined-turing-9cty66?file=/src/ContextMenu.tsx)

good point, I'll try, thanks

**Comment by atomiks** [comment]
Might consider doing this inside the `useListNavigation` hook automatically, unless it has other unintended side effects. I'll mark it as a bug for now
