### ISSUE TITLE
@floating-ui/dom 1.0.7 regression with async tests

### ISSUE THREAD

**Issue by EvHaus** [floating-ui/floating-ui#2115]
## Description

After upgrading my project from `@floating-ui/react-dom-interactions@0.13.3` to `@floating-ui/react@0.14.0` I noticed that some of my unit tests which test my components started to fail. After several hours of debugging and trying to isolate the problem, I think I finally tracked it down to a change between `@floating-ui/dom` version 1.0.7 and 1.0.6.

## Steps to reproduce

I was able to create a minimal repro case here: https://stackblitz.com/edit/jest-example-ybnzzn?file=index.test.jsx If you run that `npm run test` you'll see the test passes but throw an error in the console with: 

```
Cannot log after tests are done. Did you forget to wait for something async in your test?
```

If you take the exact same code, but with `@floating-ui/react-dom-interactions@0.13.3` and `@floating-ui/dom@1.0.6` (which I've done here: https://stackblitz.com/edit/jest-example-zyswxh?file=index.test.jsx) -- everything passes without any errors.

I suspect some change in `@floating-ui/dom@1.0.7` is causing resizing events to fire after the component has unmounted, and because `@testing-library/react` and Jest catch that behaviour -- it throws an exception. In my minimal repro, all I'm doing is print a console.log so the tests still passes and maybe it's not a big deal. But in my actual app, the code that runs is more complex -- so having it run outside of the React mount cycle is causing various problems that cause tests to fail.

Can you think of what change in `@floating-ui` could have caused this regression and what possible corrections I could make to my code to address it? Or maybe it's a bug in `@floating-ui` itself.

**Comment by atomiks** [comment]
I'm not sure why they're failing now, as this was always required and documented: https://floating-ui.com/docs/react#testing

**Comment by EvHaus** [comment]
Hmm. Yes. Adding:

```
await act(async () => {}); // Flush microtasks.
```

fixes the tests.

I wonder why this behaviour changed with that particular version.
