### ISSUE TITLE
Bug in examples of React Context Menu

### ISSUE THREAD

**Issue by krutoo** [floating-ui/floating-ui#2121]
#### Example

<img width="296" alt="изображение" src="https://user-images.githubusercontent.com/13140130/212660273-55680264-661d-45f2-9036-96bc683ff47a.png">

#### How to reproduce

1. Open https://codesandbox.io/s/admiring-lamport-5wt3yg?file=/src/DropdownMenu.tsx
2. open menu by click "Edit" button
3. Fast move mouse between "copy as" and "share" buttons
4. Fast move mouse on context sub menu

**Comment by atomiks** [comment]
Can't reproduce on Mac Chrome or Firefox. 

Does removing this `onMouseEnter` sync part fix it for you?

<img width="613" alt="Screenshot 2023-01-17 at 1 37 49 am" src="https://user-images.githubusercontent.com/22450188/212703443-25378f0e-953e-48fd-8679-9a2d1f5c8bbb.png">

**Comment by atomiks** [comment]
I've updated the example so this shouldn't happen (can you confirm?), but I believe that it could be caused by a bug I've filed here: https://github.com/floating-ui/floating-ui/issues/2124 which I'm not sure how to solve properly.

**Comment by krutoo** [comment]
> I've updated the example so this shouldn't happen (can you confirm?), but I believe that it could be caused by a bug I've filed here: #2124 which I'm not sure how to solve properly.

Looks like it worked properly now, thanks
