### ISSUE TITLE
How to use React bindings?

### ISSUE THREAD

**Issue by krutoo** [floating-ui/floating-ui#2122]
Hi. Looking at the [documentation](https://floating-ui.com/docs/useHover) it is not clear how to use React bindings correctly:

<details>
  <summary>Docs screenshot</summary>
  <img width="753" alt="изображение" src="https://user-images.githubusercontent.com/13140130/212665819-997e31a1-d8fb-446f-b1bd-150eae14d301.png">
</details>

- What should be in JSX?
- Which props are returned from functions getReferenceProps/getFloatingProps? (now unknown type)
- What does `context.open` property mean? 
- Should i use `context.open` for condition to render floating element?

**Comment by atomiks** [comment]
You need to read the [Interactions](https://floating-ui.com/docs/react#interactions) section first to understand how to use that part of the library. How can we better surface that as prerequisite reading?

**Comment by krutoo** [comment]
is it hard to show a full use case on the `onHover` docs page? Including simple JSX usage example?

**Comment by atomiks** [comment]
@krutoo yeah I'll add that
