### ISSUE TITLE
[React] Hover events possible for 1 tick after `safePolygon` element is injected to body

### ISSUE THREAD

**Issue by atomiks** [floating-ui/floating-ui#2124]
Before `v0.15.0`, a "global" holes strategy with `pointer-events: none` on the `<body>` and `pointer-events: auto` on elements was used for `blockPointerEvents: true`, but this caused unwanted side-effects in various scenarios.

Since then, it now injects a real `<polygon>` element to the body on `mouseleave` to block pointer events, but it seems to leave hover events possible for 1 tick before the browser will consider it blocking other content.  This means hover events e.g. `onMouseEnter` can now fire while trying to traverse the polygon.

A workaround is to ensure elements underneath that can be affected have a short open delay.

I can't really think of a good solution to this as the polygon needs to be generated only on mouseleave, but it seems like it needs to be generated just before? I don't want to return to the previous solution either due to the side-effects.

**Comment by mihkeleidast** [comment]
> I can't really think of a good solution to this as the polygon needs to be generated only on mouseleave, but it seems like it needs to be generated just before?

I've understoof that one feature of `safePolygon` is that it's generated is "as-needed", depending on the direction of the moving cursor, etc, right? Could we, if we don't yet know the exact shape needed, render a "basic" polygon that just covers some of the space between reference and floating element? It likely won't cover all the edge cases, but might catch that one tick, before the RealSafePolygon is rendered?

**Comment by atomiks** [comment]
> I've understoof that one feature of safePolygon is that it's generated is "as-needed", depending on the direction of the moving cursor, etc, right?

Yeah the video demonstrates it: https://floating-ui.com/safe-polygon.mp4

> Could we, if we don't yet know the exact shape needed, render a "basic" polygon that just covers some of the space between reference and floating element?

The question is what shape do we render?

I was thinking of having the polygon injected on `mousemove` but with `pointer-events: none`, then on `mouseleave` put it to `pointer-events: auto` — it's possible the browser will consider it blocked immediately vs. appending it to the body in that scenario. 

Or if that fails, manually do mouseleave detection on mousemove to fire it earlier by 1px or something, but that might fail if the cursor is moving fast.

**Comment by mihkeleidast** [comment]
True, choosing the correct shape is not very straightforward. We could do the "safest" polygon, i.e. connect the farthest corners? From the video, instead of starting from the bottom middle (which we'll know a bit later), we could start from the bottom left corner? Not sure if disabling the mouseleave for that one tick, until we know the real safe polygon, will bring other buggy edgecases?

**Comment by atomiks** [comment]
@mihkeleidast I found a solution and your comment there gave me an idea 😛 

The idea is to generate a mask created by four separate elements emanating from the reference element on `mouseenter` of it, spanning the whole viewport from the reference element's location on the screen. The entire page's pointer-events are then blocked for the frame:

<img width="1728" alt="Screenshot 2023-01-21 at 4 48 02 pm" src="https://user-images.githubusercontent.com/22450188/213845620-9889d979-c788-434c-9d6d-3c222d071168.png">

On `mouseleave`, they get destroyed (replaced with the polygon), but it's enough to prevent that 1 tick problem.

**Comment by atomiks** [comment]
I'm going to go back to the old technique because there seem to be infinite edge cases with this. But I have some ideas to improve it to prevent the side-effects as much as possible for users.
