### ISSUE TITLE
[React] `useTooltip` hook breaks after upgrading `@floating-ui/react` to `v0.17.0`

### ISSUE THREAD

**Issue by rileyjshaw** [floating-ui/floating-ui#2129]
I wrote a custom `useTooltip` hook based on the [Tooltip examples](https://floating-ui.com/docs/tooltip) in the docs. It’s been working well for a few months.

When updating `@floating-ui/react` `v0.16.0 -> v0.17.0`, I noticed that my app was crashing whenever a tooltip opened. The app is entering an infinite render loop.

[I made a minimal reproduction in CodeSandbox here.](https://codesandbox.io/s/angry-cherry-eejht0?file=/src/useTooltip.js) If you upgrade the `@floating-ui/react` version from `v0.16.0 -> v0.17.0` then hover the preview frame, the app will crash with the error:

> Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.

I imagine that this is because of the [new refs APIs](https://github.com/floating-ui/floating-ui/pull/2101) mentioned in the [0.17.0 release notes.](https://github.com/floating-ui/floating-ui/releases/tag/%40floating-ui%2Freact%400.17.0) The changes are listed as “non breaking”, so I thought it would be worthwhile to provide a counterexample here.

**Comment by atomiks** [comment]
If you upgrade to `@floating-ui/react-dom@latest` in the CodeSandbox, there's still no infinite loop, so it seems like it's related to placing the elements in the dependency array internally in `@floating-ui/react` from. `v0.17.0`+. This means it's not breaking for the v1 package.

This was done to support more use cases and to simplify logic internally. From first glance the `interactions.getFloatingProps` is likely changing on every render now causing the problem.

**Comment by rileyjshaw** [comment]
Thanks @atomiks! The latest version is working great 👍
