### ISSUE TITLE
is there any way to get event from tree.events.on('click)?

### ISSUE THREAD

**Issue by aromanchev** [floating-ui/floating-ui#2136]
Is it possible to get an event by clicking on a tree?
```typescript
tree?.events.on('click', event => event?);
```

**Comment by atomiks** [comment]
I'm assuming you're referring to the DropdownMenu example — yes, because the example itself emits the event and passes the data in the `onClick` in the `getItemProps(...)` getter: `tree?.events.emit('click', data)`

**Comment by aromanchev** [comment]
@atomiks thanks that make sense
