### ISSUE TITLE
FloatingPortal: ability to set empty id attribute

### ISSUE THREAD

**Issue by krutoo** [floating-ui/floating-ui#2140]
Hi, i trying to set empty id for floating portal root element and its still has id attribute.

Example:
https://codesandbox.io/s/floating-ui-react-dom-template-forked-zsns4z?file=/src/App.js

How can i unset default id value?

**Comment by atomiks** [comment]
Why do you need to remove the id attribute?

**Comment by krutoo** [comment]
> Why do you need to remove the id attribute?

its not needed and its a little confusing when passing an empty string in the output id is specified not empty

**Comment by atomiks** [comment]
It's needed in certain cases and doesn't pose any conflict issues as it uses React's id hook, so there's no need to remove it. An empty string is interpreted as falsy internally, the same as undefined

**Comment by krutoo** [comment]
Thanks for explaining

> It's needed in certain cases

can I somehow delete it if I don't use these cases?

> An empty string is interpreted as falsy

a little confusing since the using id attribute in React for html elements gives a different result
