### ISSUE TITLE
Interactive tooltip

### ISSUE THREAD

**Issue by sshh0** [floating-ui/floating-ui#2152]
How can I make a tooltip interactive? So that it can be hovered over and clicked inside?
What I'm looking for is exactly this: https://atomiks.github.io/tippyjs/v6/all-props/#interactive but for floating-ui

**Comment by atomiks** [comment]
So you're using the vanilla package, not React? The vanilla package only offers positioning, so you'd have to implement that yourself.

**Comment by guitarhero17** [comment]
Hi @atomiks , I'd like to second this question. I am using `@floating-ui/react` but I can't seem to find the right property to turn on. I've tried using `handleClose: safePolygon()` but that doesn't seem to work.

What's the current way of implementing an interactive tooltip like the one from Tippy.js?

Thanks!
