### ISSUE TITLE
Should `strategy: fixed` be contained by elements with `transform: ...`?

### ISSUE THREAD

**Issue by Westbrook** [floating-ui/floating-ui#2167]
As seen in https://github.com/floating-ui/floating-ui/blob/db4b7ad129b3f79b85184c3c30f352daab824cc3/packages/dom/src/utils/is.ts#L49-L74 an element is considered containing whenever is has been given a `transform` rule that does not equal `none`. This makes sense for `strategy: "absolute"` positioned content, but when `strategy: "fixed"` is used this can errantly contain the `fixed` content to an ancestor with `overflow` rules when an interceding element has a `transform` rule. While https://developer.mozilla.org/en-US/docs/Web/CSS/Containing_block#identifying_the_containing_block does say that an element with a `transform` rule _"MAY"_ form a containing block, I'm not so sure that is actually does for our purposes when using `strategy: "fixed"`.

Repro: https://codesandbox.io/s/magical-sky-vbbnqk?file=/index.html

Do you think that `strategy` could/should be taken into account when gathering whether an element is a containing block? Or do you think there is some other reasonable API that could be leveraged to ignore content of this type as being a containing block? It seems that [`getClippingRect`](https://github.com/floating-ui/floating-ui/blob/master/packages/dom/src/utils/getClippingRect.ts#L149-L152) is incorrectly calculated without one of these two options being available to consumers.

Happy to submit a PR if we can work out an acceptable path forward for this.

**Comment by atomiks** [comment]
I'm not sure I understand the demo - it gets clipped by the blue element so it can't be positioned next to the button? It seems like the existing behavior is correct.

**Comment by FezVrasta** [comment]
Agree with @atomiks, containing blocks work the same for absolute or fixed children elements. They always clip their content.

**Comment by Westbrook** [comment]
I’m not quite sure how to hack floating ui in that context, but if you take those element out of the clipping ancestors array the overlay works just as expected. The elements don’t actually clip, just as outlined by the description of the fixed strategy in the documentation site.

**Comment by atomiks** [comment]
`boundary: []` in each of the visibility optimizer middleware will only consider the `rootBoundary` and ignore element ancestors. 

But the demo you have clips the element, so it sounds like whatever behavior you want to demonstrate is not being represented by the demo, so I don't know what to do

**Comment by Westbrook** [comment]
Thanks for the push, I didn't realize I was missing part of the repro. Here there's a `positioned: fixed` item between the "containing block" and the element that this block makes a "clipping ancestor", but because of the `position: fixed` the ancestor no longer clips: https://codesandbox.io/s/youthful-wiles-dc6oy4?file=/index.html

**Comment by Westbrook** [comment]
It's possible in https://github.com/floating-ui/floating-ui/blob/master/packages/dom/src/utils/getClippingRect.ts#L108-L115 that `currentContainingBlockComputedStyle` should be _unset_ when we encounter a `position: fixed` ancestor?

**Comment by atomiks** [comment]
Yeah looks like a missed edge case 👍

**Comment by atomiks** [comment]
Looks good, feel free to make the PR
