### ISSUE TITLE
Floating not closing upon selecting an item

### ISSUE THREAD

**Issue by hornta** [floating-ui/floating-ui#2168]
I've made a `<FilterWithinSelect>` component which is basically a regular `<Select>` but with an inline `<input>` inside of the floating element. To achieve this I'm calling `useInteractions()` two times in my component, the first call is to get the `getReferenceProps` for my outer reference, the button, and the second call is to get the `getReferenceProps` for my inner reference, the input field.

I slightly followed the example here: https://github.com/floating-ui/floating-ui/issues/1974

I thought I got it working until I found out I wanted dropdown to open upon focusing the outer reference, so I added the `useFocus()` to the button reference. By doing it triggered this very problem. If I were to leave out the `useFocus` then the floating is closing upon selecting an item.

I'm thinking this may be a very specific case and not so normal to use two `userInteractions` so I may have to resort to the `useCustomLogic` to make the floating element open upon focus and close upon selection an item but I rather not since I may very well loose out on something.

https://codesandbox.io/s/floating-ui-react-dom-template-forked-49byds?file=/src/SelectFilterWithin.js

GIF Floating not closing upon selection an item:
![Animation (2)](https://user-images.githubusercontent.com/4553604/217269887-ccd96fa7-61e1-429a-b55b-c4ede41f5e59.gif)

**Comment by saltire** [comment]
> The problem is that `FloatingFocusManager` is returning focus to the button, which just immediately re-opens the floating element because it opens on focus. So you'd have to set `returnFocus={false}` and decide somewhere else to place the focus.

Or you can remove `useFocus()`, so the dropdown doesn't automatically pop open whenever the button gets focus.
