### ISSUE TITLE
Change the arrow position when the tooltip is fliped

### ISSUE THREAD

**Issue by nucliweb** [floating-ui/floating-ui#2185]
With the flip middleware, and with the arrow, when the tooltip is flipped, the arrow position doesn't change to point to the button

<img width="261" alt="image" src="https://user-images.githubusercontent.com/1307927/219511862-6a84ff80-89b6-42ca-876c-29fd8b1e7fdb.png">

[Codesandbox sample](https://codesandbox.io/s/floating-ui-dom-template-forked-00kwrj?file=/index.html)

**Comment by atomiks** [comment]
You've set `top: -4px` to the arrow as the static side offset, but it needs to be dynamic based on the placement returned from `computePosition`. This explains it: https://codesandbox.io/s/mystifying-kare-ee3hmh?file=/src/index.js
