### ISSUE TITLE
Floating Item behaves strangely when used with React state

### ISSUE THREAD

**Issue by SpookyJelly** [floating-ui/floating-ui#2186]
Reproduction Link : https://codesandbox.io/s/floating-ui-react-dom-template-forked-oinr8c?file=/src/App.js

I'm building a tooltip component that changes text based on a change in a state value.
As you can see, clicking the button changes the state, and the text inside changes. However, It acts weirdly when I clicked a left side of button. but clicking right or center does exactly what it's supposed to do.

I figured out that I could fix the the problem by set width of floating Items with static or set middleware offset value a lot, but this doesn't seems a smooth solution.

It's not in the reproduction, but in my development enviroment, the tooltip disappears entirely when I click on it.

I'm having a really hard time cause of this. Is it a just bug, or is my code at fault?

please give me a help. Thanks.

**Comment by atomiks** [comment]
I don't understand the repro, clicking anywhere on the button, including the left side works fine. It might be that your arrow element is overlapping the button, preventing events from firing. You can make it inert by adding `pointerEvents: 'none'` style to the arrow.

**Comment by atomiks** [comment]
If you provide a sandbox that actually reproduces the issue, I can re-open. As it stands this isn't actionable as the issue described isn't present.
