### ISSUE TITLE
How to position an item in a grid layout.

### ISSUE THREAD

**Issue by jgerigmeyer** [floating-ui/floating-ui#2187]
I'm not sure if this is more of a CSS question or a floating-ui question... 😕 Or it's probably out of the scope of floating-ui?

When an element is positioned in a CSS Grid Layout using `grid-column` and `grid-row`, is there a good way to account for that positioning when using floating-ui to anchor it to another element? The `x` and `y` values that `computePosition` returns are relative to the containing box, but `grid-column`/`grid-row` mean that `left`/`top` positions will be applied relative to the grid.

Demo: https://codesandbox.io/s/floating-ui-grid-4qgqwh

Feel free to close if this is out of scope -- and thanks for any suggestions/feedback!

**Comment by FezVrasta** [comment]
Is there any reason to set the grid properties on the popup element? If you remove them everything works correctly.

**Comment by jgerigmeyer** [comment]
@FezVrasta You're completely right, and maybe that's a good enough solution -- just auto-remove any `grid-column`/`grid-row` styles. 👍 

For context, I'm using floating-ui (more specifically, `getElementRects`) as part of a [polyfill for CSS Anchor Positioning](https://github.com/oddbird/css-anchor-positioning). So I don't have full control over the styles applied to a given popup element, but as much as possible we're trying to resolve `anchor()` functions into calculated pixel values that position it appropriately. One of the [Web Platform Tests](https://github.com/web-platform-tests/wpt/blob/master/css/css-anchor-position/position-fallback-grid-001.html) uses grid layout, which is how I discovered this edge case.

Thanks for your help!

**Comment by FezVrasta** [comment]
Great, I'll go ahead and close this issue then.
