### ISSUE TITLE
Possible to achieve: autoPlacement() horizontally, flip() vertically?

### ISSUE THREAD

**Issue by YamiOdymel** [floating-ui/floating-ui#2188]
I'd like to use `autoPlacement()` to align the dropdown horizontally, but vertically I want it work as `flip()`.

with the options below, the Dropdown adjusting itself horizontally, great! But it won't `flip()` to `top` if there's no more space.

```js
window.FloatingUIDOM.autoPlacement({
    crossAxis: true,
    allowedPlacements: ["bottom-start", "bottom-end"],
})
```

with the options below, the Dropdown now appearing on top but it's based on the "most space strategy" of `autoPlacement()`.

```js
window.FloatingUIDOM.autoPlacement({
    crossAxis: true,
    allowedPlacements: ["top-start", "top-end", "bottom-start", "bottom-end"],
})
```

Since I'm making a Dropdown, I hope it preferred `bottom-x` so users can having the same User Experience without guessing which direction the Dropdown will open, and only choose `top-x` instead if there's no space for `bottom-x`.

I wonder what methods should I use? Or it's not possible?

---

May related:

1. #1636
2. #2155
3. #2159

**Comment by atomiks** [comment]
Not possible with the default middleware but you can write your own custom one to achieve it.

**Comment by YamiOdymel** [comment]
Indeed, seems awrkward to asking for something between `flip()` and `autoPlacement()`. Maybe one day we will separate the options for each `Axis` instead. And not based on the two existing middlewares and doing `crossAxis: true` and `mainAxis: false` things.

**Comment by atomiks** [comment]
@YamiOdymel I did have thoughts a while ago about how to unify the two APIs into one, where you can choose a strategy of `most space` or `no space` depending on the axis, but couldn't come up with a good API. I'm not opposed to it though.
