### ISSUE TITLE
Floating element never opens

### ISSUE THREAD

**Issue by bensampaio** [floating-ui/floating-ui#2189]
I am using `floating-ui` to render dialogs with the help of `FloatingPortal` and `FloatingFocusManager`. This works well for the majority of dialogs in my application except one case.

I have an `<a>` element inside a `<label>` element which when pressed should open a dialog. However, it never opens anything and instead shows this error in the console:

<img width="504" alt="Screenshot 2023-02-20 at 17 04 12" src="https://user-images.githubusercontent.com/1700178/220164948-bc4f08b4-50c9-4936-8e95-093c12dbe4ae.png">

I think this is something related to the `FloatingFocusManager` and maybe the combination with the `<label>` element but so far I couldn't find the reason and how to prevent it. I also didn't manage to reproduce this issue. I am posting this here in the hope someone could give me more information about what causes this error and how to reproduce it or fix it.

**Comment by atomiks** [comment]
That means the `<article>` element is not actually rendered into the document/body, or is being rendered outside of it somehow and is therefore hidden. Doesn't seem like a bug with the lib, but I can re-open with a reproduction to work from.

**Comment by bensampaio** [comment]
@atomiks that's strange because if I change `<FloatingPortal id="dialog-root">` to `<FloatingPortal>` then everything works as expected. It is not the first time I come across issues with the `id` of `FloatingPortal`. Is this expected behavior?

**Comment by atomiks** [comment]
Are you conditionally rendering `FloatingPortal` based on the open state? It's not possible to say what the cause is without a repro

**Comment by bensampaio** [comment]
No, I'm rendering in this order in my `Dialog` component:

```
<FloatingNode id={nodeId}>
      <FloatingPortal id="dialog-root">
        {open && (
          <FloatingFocusManager context={context}>
            <FloatingOverlay>
              <article ... />
```

I have multiple `Dialog` components being rendered on the page. When they first render the portal gets mounted but then something causes the portal to be removed from the DOM (I'm still trying to figure out what could cause this to happen). Since the portal is no longer in the DOM when I press to open a `Dialog` it gives me the error I showed in my first message.

**Comment by atomiks** [comment]
The portal container does get removed from the DOM here:

https://github.com/floating-ui/floating-ui/blob/ed68d4daf3cc7f06edf43bb7adc33015a3489aae/packages/react/src/components/FloatingPortal.tsx#L60-L62

This can happen if `uniqueId` changes from the `useId` hook, which causes it to re-mount. This can happen if something is being conditionally rendered. A similar issue happened here: https://github.com/floating-ui/floating-ui/pull/2130#issuecomment-1396377165
