### ISSUE TITLE
[React] useInsertionEffect within useEvent throws SSR error

### ISSUE THREAD

**Issue by Abyrd9** [floating-ui/floating-ui#2190]
Hello, I'm using `@floating-ui/react` in a Nextjs project and recently upgraded to Nextjs 13. With latest Nextjs and latest floating-ui I've been running into an SSR error:
`useInsertionEffect only works in Client Components. Add the "use client" directive at the top of the file to use it.`

"[use client](https://beta.nextjs.org/docs/rendering/server-and-client-components#convention)" does not work in [`pages` directory](https://nextjs.org/docs/basic-features/pages), which I'm using. And adding my own check for `window` was giving hydration errors. I figured since [useInsertionEffect](https://beta.reactjs.org/reference/react/useInsertionEffect) is client-only anyway, adding a check for window in the package would be a simple fix.

While locally linking the package I was able to create the fix by adding a window check in the useEvent hook [here](https://github.com/floating-ui/floating-ui/blob/master/packages/react/src/hooks/utils/useEvent.ts#L10).
Just a simple window check:

**Before**:
```
const useSafeInsertionEffect = useInsertionEffect || ((fn) => fn());
```
**After**:
```
const useSafeInsertionEffect =
  typeof window !== 'undefined' && useInsertionEffect
    ? useInsertionEffect
    : ((fn: () => void) => fn());
```

This worked for me, seems too simple though 👀 wasn't sure if this would be the correct fix.

**Comment by atomiks** [comment]
The docs website for this library uses Next.js 13, the `pages` directory, and `@floating-ui/react` but I don't see that error, and it seems like a Next.js bug.

**Comment by Abyrd9** [comment]
Ah okay, must be something on my end then. I will keep investigating, thanks.
