### ISSUE TITLE
[React] useFloating returns differents values based on my screen (DPI)

### ISSUE THREAD

**Issue by adrijere** [floating-ui/floating-ui#2193]
Hi team 👋 

Thanks for your hard work on this library!!

I've a weird issue with `@floating-ui/react-dom-interactions": "^0.13.3"`.
I have a textarea. When the user clicks on the text, a floating toolbar appears so the user can edit the text and the format at the same time.

I'm running my page locally on my macbook screen (14-inch) and my floating box is well displayed :
<img width="1064" alt="Capture d’écran 2023-02-22 à 16 20 59" src="https://user-images.githubusercontent.com/7966737/220668034-6a377680-f298-4768-adf6-08a4abd350de.png">

But if I'm running the same page on my Samsung monitor (27-inch), the floating toolbar is rendered on my text and it's hard to edit my text if I can't see it:
![Capture d’écran 2023-02-22 à 16 20 13](https://user-images.githubusercontent.com/7966737/220669134-13dbd2fd-6891-4dee-afa1-3e97f939c81e.png)

Both screenshots are on the same browser with the same code, nothing (except the size of the monitor) is different.

The current code looks like:
```js
const { x, y, reference, floating, strategy } = useFloating({
    placement: 'top',
    middleware: [
      shift({
        boundary: editorRef.current, // this is a ref to the textarea element
      }),
      offset(12),
      inline(),
      hide(),
    ],
    whileElementsMounted: autoUpdate,
  });
  ```
  
  I've the issue on my Chrome browser version `110.0.5481.100` and on Arc browser version `0.90.0` (which uses Chromium Engine Version `110.0.5481.100`).
  
  Any idea how to fix this problem or any workaround for now? I've found nothing for now in the closed issues.
  
  Thanks!

**Comment by adrijere** [comment]
Thank you for your fast answer! The current version installed is the `'@floating-ui/dom': 1.2.1`

**Comment by atomiks** [comment]
What are the values of the reference element's `getBoundingClientRect()` and the floating element's `getBoundingClientRect()` on each screen? If you were to manually position the floating element to the reference element using those values, are they correct for the 27-inch screen?

**Comment by adrijere** [comment]
Hi @atomiks ! Sorry for the delay! After investigation, I found that `useFloating` is not the problem but the lib I'm using to define the position of the selected text to show the floating menu just above. I'm closing the issue, sorry for the inconvenience and thanks a lot for your reactivity, really appreciated 🙌
