### ISSUE TITLE
Latest release not working with downshift

### ISSUE THREAD

**Issue by rvetere** [floating-ui/floating-ui#2202]
I stumbled upon the code sandbox for "floating-ui-downshift" and started to implement that in our project. I was wondering why `x` and `y` always staying on value null and, yeah as one could thinkg with those values remaining "null" - it doesn't work.

After a while i realized that the versions are all different and after updating the code sandbox to the latest releases of downshift and floating-ui, it breaks now too:

https://codesandbox.io/s/floating-ui-downshift-forked-8p35xv?file=/src/App.js

Check out the console log - the vlaues `x` and `y` always stays on "null", the autoUpdate is not working too (but this seams to be a "known issue", well i could fix it with a useLayoutEffect but still...)

Expected behavior: The codesandbox example should just work, "out of the box"

**Comment by atomiks** [comment]
The `refs.reference` and `refs.floating` values should be `refs.setReference` and `refs.setFloating` respectively. I think there was an infinite loop problem before but hasn't been an issue for a while.

**Comment by rvetere** [comment]
Woa, this fixes everything, thank you! <3
