### ISSUE TITLE
🤔 How to use arrow in vue package when using `useFloating` composable

### ISSUE THREAD

**Issue by jd-solanki** [floating-ui/floating-ui#2208]
Hi 👋🏻 

I'm glad to let you know that I'm using floating UI in my Vue component lib - [Anu](https://anu-vue.netlify.app/).

I already used this in [Menu](https://anu-vue.netlify.app/guide/components/menu.html) component and want to use floating-ui in the tooltip as well.

However, in the tooltip I want to show the arrow but unfortunately, I'm unable to understand the docs correctly for `useFloating` composable & arrow [docs](https://floating-ui.com/docs/vue#arrow). Docs raises questions like:
- Will useFloating will handle arrow position by itself as we passed arrow ref?
- Does it require position absolute or that will also get added?

Thanks for this amazing lib 🌟 

Out of the context, I wanted to ask, Can you can more composables to floating UI just like you added in react, specifically that useHover that has `safepolygon` 😍 ?

Regards.

**Comment by atomiks** [comment]
Here's an example of how to use it: https://github.com/floating-ui/floating-ui/discussions/2103#discussioncomment-4633661 If you have some suggestions for the docs feel free to make a PR to help make it clearer for people
