### ISSUE TITLE
Incorrect position with inline middleware

### ISSUE THREAD

**Issue by joaom00** [floating-ui/floating-ui#2219]
I'm positioning a floating element based on a range selection and when I use the `inline` middleware it seems that it's not possible to position correctly if the text has an element inside like `strong` or `em` for example. The floating element must be positioned at the center of the range selection.

https://codesandbox.io/s/floating-ui-react-range-selection-forked-gx1bwd

https://user-images.githubusercontent.com/48808846/224442724-4269ca9e-1bac-48fb-a672-cd94207cfe6b.mp4

**Comment by atomiks** [comment]
Interesting, if you log `console.log(range.getClientRects())` it's returning 3 different rects when you partially highlight an inner node.

You could workaround it by only sending in the relevant rects to `getClientRects` in the virtual element, but wonder if `inline` needs to handle this.

<img width="659" alt="Screenshot 2023-03-11 at 4 59 55 pm" src="https://user-images.githubusercontent.com/22450188/224467906-f1dac9d9-d5f6-4477-b078-8ded3c2ee61d.png">

**Comment by atomiks** [comment]
It seems this isn't fully fixed yet
