### ISSUE TITLE
[React] Reduce hooks number

### ISSUE THREAD

**Issue by cangSDARM** [floating-ui/floating-ui#2225]
In order to implement a `Popover`, for now to complete require at least three or more hooks. Hope to change hooks such as `useClick`/`useDismiss`/`useHover/useRole` etc. into simpler util functions to easier use.

for the more, may they can change into like this:

```js
import { click, dismiss, hover, mergeRefs, role } from '@floating-ui/react/utils';

function Popover(props) {
  const data = useFloating(props.config);
  const context = data.context;
  const interactions = useInteractions(context, [click, hover, dismiss, role]);
 
  // this is dummy
  return <div ref={mergeRefs([context.refs.setReference, propRef, childrenRef])}>{props.children}</div> 
}
```

**Comment by cangSDARM** [comment]
may relavent: https://github.com/floating-ui/floating-ui/issues/2100

**Comment by atomiks** [comment]
Yeah, #2100 is about reducing configuration necessary. However in the proposal given, it's not clear how you can configure each of the hooks' behavior. How do you pass options?

In its current state, the JavaScript of the library works a lot like CSS, where things are progressively added as you need them. This allows you to compose pieces of functionality common to different floating elements in a way that can create unique or different interactions without duplicating anything. (This also applies to the positioning part of the library.)

The hooks work a bit like Tailwind's CSS utilities. For example, to style a popover, you might have this

```js
<div className="bg-white p-3 shadow rounded" />
```

In a way these utilities are like the interaction hooks:

```js
const click = useClick(context);
const dismiss = useDismiss(context);
const role = useRole(context);

const interactions = useInteractions([click, dismiss, role]);
```

Fundamentally, it's about composition and giving you full flexibility. This has the tradeoff/cost of more code to setup, but I feel like copy/pasting the reusable examples and working from them gives you the best baseline to jump off. 

I'm open to ideas about how to make this better/easier without sacrificing the goals of the library. What do you think? /cc: @mihkeleidast

**Comment by mihkeleidast** [comment]
To me the proposal is not too much simpler - you still have to import all of the util functions and pass them to interactions hook. Does it matter if they are prefixed with `use` or (not) called when passing them to `useInteractions`?

One thing I do like about this proposal is moving the context passing to `useInteractions`, not to every interaction separately. Maybe this would also open up a way for an options param on that hook, which could hold that common `enabled` prop I wanted a while back (see #2125)?

It does look a bit simpler to me.

```js
useInteractions([useClick(context), useDismiss(context), useRole(context)]);
useInteractions(context, [useClick(), useDismiss(), useRole()], opts);
```

**Comment by FezVrasta** [comment]
react-table handles this nicely

**Comment by cangSDARM** [comment]
> To me the proposal is not too much simpler - you still have to import all of the util functions and pass them to interactions hook. Does it matter if they are prefixed with `use` or (not) called when passing them to `useInteractions`?
> 
> One thing I do like about this proposal is moving the context passing to `useInteractions`, not to every interaction separately. Maybe this would also open up a way for an options param on that hook, which could hold that common `enabled` prop I wanted a while back (see #2125)?
> 
> It does look a bit simpler to me.
> 
> ```js
> useInteractions([useClick(context), useDismiss(context), useRole(context)]);
> useInteractions(context, [useClick(), useDismiss(), useRole()], opts);
> ```

This is indeed not simple to write, but it can be integrated into other functions that are conditionally judged.

Hooks restrict their use to certain circumstances.


For example, to implement a `Popover` that allows dynamic modification of the trigger type, the use of hooks must be divided into `ClickPopover` and `HoverPopover` to make the hooks work correctly (I think we know that they will look similar except for a few hooks), but if not hook, it can be much simpler

**Comment by cangSDARM** [comment]
For api usebility and fixbility, i think [unified's plugins systeam](https://www.npmjs.com/package/unified) is a good sample

**Comment by mihkeleidast** [comment]
All of the interaction hooks have a `enabled` option, which you can toggle based on some external condition like the trigger type:

```js
const click = useClick(context, {
  enabled: trigger === 'click',
});
const hover = useClick(context, {
  enabled: trigger === "hover",
});
const interactions = useInteractions([click, hover]);
```

What's the benefit of conditionally passing utils to `useInteractions` instead of conditionally enabling them?

If you want to reuse some of that logic in multiple places, you can wrap it in your own hook:

```ts
const useMyInteractions = ({
  context,
  trigger = 'click',
}: {
  context: FloatingContext<ReferenceType>;
  trigger?: 'click' | 'hover';
}) => {
  const click = useClick(context, {
    enabled: trigger === 'click',
  });
  const hover = useClick(context, {
    enabled: trigger === "hover",
  });
  
  return useInteractions([click, hover]);
};
```

**Comment by FezVrasta** [comment]
It may be worth waiting for the new "use" hook that should be introduced soon into React. It should allow for a more ergonomic API

**Comment by jakobvase** [comment]
I can't help but think that if you want simpler hooks, you could just create a library that composes several of the hooks of this library in they way that you want. I really like the composability of floating-ui.

**Comment by atomiks** [comment]
Going to close this due to some problems with the proposals, but any suggestions can still go in #2100.
