### ISSUE TITLE
[react] hover open was triggered when`useHover` was not passing into`useInteractions`

### ISSUE THREAD

**Issue by mashirozx** [floating-ui/floating-ui#2230]
Should not trigger `onOpenChange` event when `useInteractions` was set to be empty: 

```js
const { getReferenceProps, getFloatingProps } = useInteractions([]);
```

Demo: https://codesandbox.io/s/small-field-1lcxwv?file=/src/App.tsx

**Comment by atomiks** [comment]
This is is because the hover listeners are registered inside an effect rather than returning event props since there were some bugs with `onMouseEnter/onMouseLeave` (which are `onMouseOver`/`onMouseOut` in the browser).

**Comment by MattisAbrahamsson** [comment]
We ran into this same issue when implementing a flexible popover component which allows the interactions to be configured via props. This doesn't seem like it should be the expected behaviour

**Comment by atomiks** [comment]
The `enabled` prop on each interaction hook serves the purpose of conditionally enabling/disabling it (same as conditionally passing it in the array).
