### ISSUE TITLE
[React] Wrong position of nested floating element when open on initial render, react 17, autoUpdate

### ISSUE THREAD

**Issue by piecyk** [floating-ui/floating-ui#2231]
Noticed a bug when using floating with react 17 and autoUpdate, as in title opening nested floating element that is initially open has wrong position. Looks like those two elements are rendered in same time, as we skip the initial callback of ResizeObserver https://github.com/floating-ui/floating-ui/blob/master/packages/dom/src/autoUpdate.ts#L80 second content is not placed correctly. 

I think more bulletproof would be to to remove this `initialUpdate` optimization and run the callback always as gains are not that significant and elements can change between sync render and update. 

Steps to reproduce

- click on `My button 1`
https://codesandbox.io/s/floating-ui-react-dom-template-forked-gbhr85?file=/src/App.js

<img width="329" alt="Zrzut ekranu 2023-03-15 o 11 08 18" src="https://user-images.githubusercontent.com/82964/225279157-acde9bd5-b198-45af-9012-b6bd392cc679.png">

expected positon 
<img width="407" alt="Zrzut ekranu 2023-03-15 o 11 08 27" src="https://user-images.githubusercontent.com/82964/225279154-40f2bbf5-7fd4-4621-a231-93afe2f8e733.png">

**Comment by atomiks** [comment]
I think that's this issue: https://github.com/floating-ui/floating-ui/issues/1531

I don't think it's related to `autoUpdate`, rather React's down-up initialization of effects (whereas it needs to be top-down because the parent needs to be positioned first).

**Comment by piecyk** [comment]
> I don't think it's related to autoUpdate, rather React's down-up initialization of effects (whereas it needs to be top-down because the parent needs to be positioned first).

hmm thanks will check it, but if we remove the `initialUpdate` in autoUpdate check in RO callback, it's position correctly 🤔 Just saying that skipping this has not that big impact on performance, or has it?

**Comment by atomiks** [comment]
Oh ok interesting, does removing the check work if there's 3+ nested children?

**Comment by piecyk** [comment]
> Oh ok interesting, does removing the check work if there's 3+ nested children?

yes it will, checkout this https://codesandbox.io/s/floating-ui-react-dom-template-forked-e9w54p?file=/src/App.js using custom autoUpdate just wrapping over ResizeObserver and running update for every callback

**Comment by atomiks** [comment]
In case `elementResize` is disabled or `autoUpdate` isn't in use, this is also a workaround:

```js
React.useLayoutEffect(() => {
  isOpen && requestAnimationFrame(update);
}, [isOpen, update]);
```
