### ISSUE TITLE
Leverage `scrollend` event for better performance

### ISSUE THREAD

**Issue by kripod** [floating-ui/floating-ui#2233]
Recently, [a new API has been released](https://developer.chrome.com/blog/scrollend-a-new-javascript-event/) for tracking completed scrolls.

As it stands today, [the `scroll` event is being used within the codebase](https://github.com/search?q=repo%3Afloating-ui%2Ffloating-ui+addEventListener%28%27scroll&type=code). Most of these occurrences could possibly be replaced with `scrollend`, perhaps making it opt-in so that browser compatibility is retained. Developers could be asked to ship [a polyfill](https://github.com/argyleink/scrollyfills) on their own if necessary.

**Comment by FezVrasta** [comment]
Most of the time we need to react to every single scroll event so that the tooltip is repositioned in real time. This new event would make the tooltip lag behind

**Comment by atomiks** [comment]
As @FezVrasta said, `scrollend` doesn't work for anchoring, which needs to be 1:1 with layout. 

Plus, scroll events are already passive so they don't cause performance issues in the first place (even if the main thread is busy, scrolling is still smooth).
