### ISSUE TITLE
Clicking on outside *inline* element doesn't close the popover 

### ISSUE THREAD

**Issue by clbn** [floating-ui/floating-ui#2237]
While implementing a popover using floating-ui I found an issue that I can't explain right away. My popover hides when I click outside of the floating element (as it should), **_unless_** I click on a piece of text wrapped in a `span`. Further, I found that clicking on any element with `display: inline` style doesn't trigger the outside click, so the popover wouldn't hide. 

Luckily, I managed to reproduce it with [the Popover component from the docs](https://floating-ui.com/docs/popover) as well. Here's my sandbox, which is forked from the original Popover example, and I only added lines 17-27 in App.tsx:

- https://codesandbox.io/s/nifty-mopsa-gox18g?file=/src/App.tsx:290-572

Why is this happening, and how could I fix it?

**Comment by atomiks** [comment]
Thanks for the report. It looks like it only happens in Firefox, not Chromium/Safari.

My first guess is something here is being calculated incorrectly, which prevents the floating element from closing when clicking on the scrollbar:

https://github.com/floating-ui/floating-ui/blob/cfe8e3851eda4b8dff98b9e9e99c13517317f407/packages/react/src/hooks/useDismiss.ts#L161-L184

**Comment by clbn** [comment]
Whoa, that was fast! 🚀 Thank you for the fix!
