### ISSUE TITLE
[React] `useHover` on mobile doesn't dismiss when touching reference element

### ISSUE THREAD

**Issue by kamilmccabe** [floating-ui/floating-ui#2241]
### Description
When using `useHover` on mobile the reference element doesn't close the popover.
Because on mobile there is no hover behaviour it works by touching the reference element. If it is used then touching the reference element should close the popover. Currently you have to touch somewhere off the reference and popover to dismiss it.

### Expected Behaviour
On mobile when using `useHover`, touching the reference element should open and dismiss the popover.

### Steps to replicate
1. Create a popover element that uses `useHover`
2. On mobile, open the popover by clicking the reference and then try closing it again the same way

Sandox [here](https://codesandbox.io/s/floating-ui-react-dom-template-forked-oywfg1)

**Comment by atomiks** [comment]
The sandbox doesn't contain the code as described?

In Chrome DevTools touch emulation mode, tapping reference element a second time also doesn't close it without `safePolygon` (on iOS too, I think). Seems device/browser-dependent.

**Comment by kamilmccabe** [comment]
Apologies, I've updated it to the correct link https://codesandbox.io/s/floating-ui-react-dom-template-forked-oywfg1

**Comment by kamilmccabe** [comment]
And yes I have just realised that the reason I thought it was `safePolygon` was because in my code it was overlapping the reference element slightly, so when `safePolygon` wasn't used it counted as touching the popover which dismissed it. I will update the description.

I still believe that when touching the reference element again it should dismiss the popover?

**Comment by atomiks** [comment]
I don't think pressing it again should dismiss it because no `mouseleave` event is fired by browsers intentionally. I think you want to combine `useClick` and `useHover` together in this scenario, enabling `mouseOnly: true` for `useHover`.

**Comment by kamilmccabe** [comment]
Okay I see now what you mean. Annoyingly I have a specific use case that has an iframe on the page (which is why this solution didn't appear to work for me previously). It seems that on mobile touching inside the iframe doesn't dismiss it with this solution, but it does if you just use `useHover`. 

To replicate:
Add `useHover` with default options and don't use `useClick` - this will dismiss the popover when touched anywhere outside of it but not if the reference element is touched.
Add `useHover` with `mouseOnly: true` and use `useClick` - this will dismiss the popover when the reference element is touched but not when outside of it is touched in an iframe.

Sandbox with iframe https://codesandbox.io/s/floating-ui-react-dom-template-forked-oywfg1?file=/src/App.js

I know this is a fairly niche case, however I would expect that touching anywhere outside of it (even if it's an iframe) OR touching the reference element would dismiss it.

**Comment by atomiks** [comment]
Does "press outside" typically work when clicking into another document (as with an iframe) in other libs? If so, would be a bug, otherwise maybe it can't be handled

**Comment by kamilmccabe** [comment]
I haven't found a library that does it, but it does work with `useHover` here (which basically behaves like `useClick` on mobile) so maybe there would be a way to use that logic for it?

**Comment by atomiks** [comment]
Hmm, then maybe using default `useHover` works (without `mouseOnly: true`), or worst case, you can detect if the iframe was tapped and manually call `setIsOpen(false)`

**Comment by kamilmccabe** [comment]
Unfortunately it doesn't work with both `useHover` and `useClick`. If this isn't something that can be fixed in this library then I will look at detecting an iframe check like you suggested or conditionally changing the behaviour based on device.

**Comment by man-trackunit** [comment]
I have the same issue with `outsidePress` from `useDismiss()`—which is unfortunate since the web app I'm working on has a decent amount of iFrames in it. Even embedding a Google Maps component (which comes in an iFrame) means that useDismiss() doesn't work correctly. What solution did you end on @kamilmccabe?

**Comment by kamilmccabe** [comment]
@man-trackunit been a while since I looked at this but we decided to skip the functionality of clicking on the reference item for dismissing the popover. So using `useHover` works perfectly fine on desktop, and then on mobile if you tap anywhere outside of the element (including the iframe) then it gets dismissed. It only doesn't work if you tap the item used to open the popover again, but we've decided that's okay.

**Comment by man-trackunit** [comment]
Thanks for getting back to me. I am no longer sure my issue strictly had to do with iFrames but rather `FloatingFocusManager` `closeOnFocusOut: true` (default) clashing with useDismiss `outsidePress: false`. Still unsure if user or lib error.
