### ISSUE TITLE
scrollItemIntoView doesn't work if rendered in a react-virtuoso list

### ISSUE THREAD

**Issue by hornta** [floating-ui/floating-ui#2247]
We are rendering a select dropdown in a floating element. We can have around 10.000 items to select from and therefore we need to use windowing/virtualization. 

I've tried to use react-virtuoso which works OK but the only thing that's missing is that floating-ui is unable to scroll to the selected item upon opening the dropdown. I think it's because floating-ui uses `scrollIntoView`. I think I need to use some method from here to scroll to the selected item: https://virtuoso.dev/virtuoso-api-reference/#methods

Would it be possible to extend the API with a custom scrollIntoView method that overrides the default behaviour?

**Comment by atomiks** [comment]
[There's an example with `react-virtual` here](https://codesandbox.io/s/l10rjs?file=/src/App.tsx), where you maintain your own effect, maybe this'd be convenient to be able to extend

**Comment by hornta** [comment]
I've yet to test react-virtual. I was going to close this but I saw you added the Feature label so do you plan on making an API change?
