### ISSUE TITLE
scrollbar ui issue in docs page sidemenu

### ISSUE THREAD

**Issue by joeshajan** [floating-ui/floating-ui#2256]
### Issue
The top half of the scrollbar is hidden inside the top component.

https://floating-ui.com/docs/shift

https://user-images.githubusercontent.com/69904519/227794104-e456982c-5bc8-4803-aac9-176e3218623a.mp4

**Comment by atomiks** [comment]
Thanks, didn't see that with overlay scrollbars when developing it, will be fixed shortly

**Comment by atomiks** [comment]
Side-note: the middle section looks quite narrow for you, Tailwind typography uses the `ch` char but maybe should just use `rem` here...
