### ISSUE TITLE
Consistent way to disable middleware

### ISSUE THREAD

**Issue by valtism** [floating-ui/floating-ui#2257]
I would like to make a generic `<Popover>` component that can take options for middleware to allow full control by the calling component.

My interface for the `<Popover>` is:

```ts
interface PopoverOptions {
  ...
  offsetOptions?: Parameters<typeof offset>[0];
  flipOptions?: Parameters<typeof flip>[0];
  shiftOptions?: Parameters<typeof shift>[0];
}
```

I was playing around with disabling these, and noticed that I could disable the `offset` and `flip` middleware by passing `false` to the options. For `shift`, however, I have to pass `null` as `false` does not disable it.

I think it would be nice to have a consistent way to disable middleware, either by passing `null` or `false` to support this use-case

**Comment by atomiks** [comment]
So you're saying this worked: `flip(false)`, or something else? 

Ycan pass `false`, `null`, or `undefined` to the `middleware: []` array, and it won't run the logic at all for the given calculation.

This works consistently for all of them, is there a CodeSandbox demonstrating otherwise?
```js
middleware: [
  null && shift(),
  false && shift(),
  undefined && shift()
]
```

**Comment by valtism** [comment]
Oh yeah, I guess I can actually conditionally apply the middleware. I thought because I was initializing with a default that it would be overwritten, but that would actually only happen if it was `undefined`, not `null` or `false`.
