### ISSUE TITLE
Warning when using Floating UI on Firefox

### ISSUE THREAD

**Issue by Ericlm** [floating-ui/floating-ui#2272]
**Describe the bug**
When going through the Floating UI examples (like [shift](https://floating-ui.com/docs/shift)), Firefox produces a warning saying the following:
`This site appears to use a scroll-linked positioning effect. This may not work well with asynchronous panning; see https://firefox-source-docs.mozilla.org/performance/scroll-linked_effects.html
 for further details and to join the discussion on related tools and features!`

**To Reproduce**
Simply open the [shift example](https://floating-ui.com/docs/shift) from the floating UI docs on Firefox.

**Expected behavior**
No warning should be triggered.

**Context:**
 - OS: macOS 13.2.1 (22D68)
 - Browser: Firefox 13.2.1 (22D68)
 - Version: `@floating-ui/vue` 0.2.1

**Comment by atomiks** [comment]
Firefox has emitted this warning for years now, but it's not a problem and the scroll linked effect (updating the position on scroll) is required for anchoring to work correctly.

**Comment by Ericlm** [comment]
@atomiks thank you for your response! Do you know a way to disable this warning or to hide it ?
