### ISSUE TITLE
[React] Should `useTypeahead` take disabled items into account?

### ISSUE THREAD

**Issue by pierreburel** [floating-ui/floating-ui#2273]
It is currently possible to focus a disabled item with the keyboard using `useTypeahead`, but should it be?

Demo: https://codesandbox.io/s/floating-ui-use-typeahead-disabled-ich3zy?file=/src/App.tsx

Notice how pressing "o", "p" or "m" set `setActiveIndex` and thus focus the disabled items. Selection can still be prevented by testing if item is disabled, but maybe it would make sense to have the same behaviour as `useListNavigation` (and even have a `disabledIndices` prop too, that could be shared)?

For example, [Adobe’s React Aria](https://react-spectrum.adobe.com/react-aria/useListBox.html#disabled-items) and [Headless UI](https://headlessui.com/react/listbox#disabling-an-option) prevent focus completely when item is disabled.

**Comment by atomiks** [comment]
In native macOS menus it's possible to focus a disabled item with typeahead. Not sure if this should be an option or not and if the web recommends something else.

<img width="244" alt="Chrome > Tab > disabled item highlighted" src="https://user-images.githubusercontent.com/22450188/229537203-019965d0-d652-474b-90fa-9070f0d873a2.png">

**Comment by pierreburel** [comment]
Oh, interesting, i cannot do it on my side (pressing "c" focus "Case" and not "Create Link" here in Figma for example):

![image](https://user-images.githubusercontent.com/37228/229542556-b568352f-5ffc-4e18-a6ab-02b81f77e1c1.png)

Same on a native Select element (pressed "d"):

![image](https://user-images.githubusercontent.com/37228/229543408-3ab2a56f-aeee-4c49-a302-778acba38b95.png)

**Comment by atomiks** [comment]
From what I see, if there are no other items that start with the letter in the list, it focuses something random first, then typing another letter then focuses the disabled item

**Comment by pierreburel** [comment]
Wow good call, it's not random but it seems to be the closest next letter, i never noticed 😳 like on my first example : "b" focus "Case", "d" focus "Spell Check"… and "t" to "z" focus "Text Direction". But i still cannot focus disabled items, whatever i do, weird.

Anyway, Adobe (or [MUI](https://codesandbox.io/s/cool-diffie-6eqftx)) don't seem to try to replicate exactly macOS (and Windows? i didn't test) behaviour, but still prevent items to have focus tho.

**Comment by atomiks** [comment]
Marking it as a bug since the behavior isn't matching regardless. Not sure if it's worth trying to focus the nearest letter if nothing is found though 🤔

**Comment by atomiks** [comment]
I just realised in some examples I've made, that you should pass `null` for the index if it's disabled in the strings array. This will skip it for you. Since the node is decoupled from the label, this `null` check is how something is determined as disabled:

```js
listRef.current[index] = isDisabled ? null : node?.textContent
```
