### ISSUE TITLE
[data-popper-reference-hidden] attribute is added even when the element is visible

### ISSUE THREAD

**Issue by leandro-fenoglio-ca** [floating-ui/floating-ui#2276]
**Describe the bug**
The `[data-popper-reference-hidden]` attribute is being added even when the reference element is visible. What happens is that the wrapper has `overflow: hidden;`, but the reference element is inside a wrapper with `position: fixed;`, so it is visible but the `tooltip` is not added. 

**To Reproduce**

I created an example in jsfiddle reproducing the problem:

https://jsfiddle.net/vo7xbqze/2/

The tooltip is displayed when you hover over items 1 and 2, but it does not work on item 3, as it goes beyond the area of the parent element.

**Expected behavior**
I believe that since the element is visible, the `[data-popper-reference-hidden]` attribute should not be added

**Screenshots**
![Apr-05-2023 15-29-51](https://user-images.githubusercontent.com/82389520/230172197-f80635d7-8328-4894-836c-c870e4398c48.gif)

**Context:**
 - OS: macOS Monterey 12.1
 - Browser: Google Chrome
 - Version: 112.0.5615.49

**Additional context**
I'm using @popperjs/core@2

**Comment by atomiks** [comment]
We have now released [Floating UI v1](https://floating-ui.com/docs/motivation), the successor to Popper.

Don't worry, Popper 2 will **continue to receive new releases** with bug/security fixes provided by external contributors, but development of new features is not continuing at this point. We are also closing bugs related to it as us maintainers are focusing our energy on tracking issues with Floating UI, however you are welcome to create new pull requests to fix bugs in Popper, which we will review and merge, as many packages (such as MUI, Bootstrap, etc) still rely on it. 

Thanks!

**Comment by Ashwin-Mothilal** [comment]
@atomiks Is this a bug from popper side? Could you please confirm? Or do we have any workarounds you aware of, other than migrating to Floating UI?
