### ISSUE TITLE
The hide middleware hides the floating element when the referenced element has fixed position

### ISSUE THREAD

**Issue by leandro-fenoglio-ca** [floating-ui/floating-ui#2278]
**Describe the bug**
The [hide middleware](https://floating-ui.com/docs/hide) hides the floating element when the referenced element has `position: fixed;` and it's inside an element with `overflow: hidden;`.

**To Reproduce**

https://codesandbox.io/s/upbeat-mclaren-s9q0n0

Note that button 1 with fixed position does not display the tooltip, but button 2 with absolute position does.

**Expected behavior**
The tooltip must be displayed as long as the referenced element is also visible.

**Screenshots**
![image](https://user-images.githubusercontent.com/82389520/230486237-0ff28105-b3b4-42d0-ac84-14f5eaf7dbd8.png)

A real example to exemplify our use case:
![real-example](https://user-images.githubusercontent.com/82389520/230486317-18eaf88e-92c2-433d-9c61-e990519f458c.gif)

**Context:**
 - OS: OS: macOS Monterey 12.1
 - Browser: Google Chrome
 - Version: 112.0.5615.49

**Additional context**

**Comment by atomiks** [comment]
Seems to be caused by https://github.com/floating-ui/floating-ui/pull/2170; works in `1.2.0`

**Comment by jcfranco** [comment]
Maybe I'm missing something, but it appears this is still an issue in 1.2.6.

![floating-ui-ref-hidden-issue](https://user-images.githubusercontent.com/197440/231920422-fadcaf5d-ea42-4559-8acb-e86b4ce3976c.gif)

**Comment by atomiks** [comment]
The original sandbox got updated, it fixed the first (this) issue but seems there's another one which has been opened :')

**Comment by jcfranco** [comment]
Thanks for clarifying. I'll keep an eye on the [proper one](https://github.com/floating-ui/floating-ui/issues/2288). 👀
