### ISSUE TITLE
Antd Dropdown is incompatible with Floating-Ui

### ISSUE THREAD

**Issue by CarryOnHxy** [floating-ui/floating-ui#2282]
**Describe the bug**

Hi, this is my first time to report an issue, i was developing a pop-confirm component with Floating-UI and Antd, and used the popover demo from the [docs example](https://floating-ui.com/docs/popover) which contains dropdown component from antd
as children, and then an abnormal situation, the floating container was anchor to the top-left of the page.

![image](https://user-images.githubusercontent.com/41328326/230607922-3918411d-913e-49d5-a0f0-5c36d162551c.png)

And the console throw an error information:

![image](https://user-images.githubusercontent.com/41328326/230609019-6cce8e8d-ff5e-4811-b8c9-6e8e805d0428.png)

It seems like Floatin-UI can not get the ref from Antd Dropdown. I am new to this, hoping get your helps and some suggestions, thank!!! 
**To Reproduce**

https://codesandbox.io/s/busy-sid-fr597o?file=/src/App.tsx

Just move your curson and click the text, you can see the question. The popover in the demo i used from docs example above.

**Expected behavior**

![image](https://user-images.githubusercontent.com/41328326/230608402-390fa752-3661-4ab3-abf7-c1122a8f10c3.png)

The floating container should be near the clicked area.

**Screenshots**

![image](https://user-images.githubusercontent.com/41328326/230608618-29cc761c-922f-4699-bda0-2e705de91a15.png)

**Context:**
 - OS: [e.g. iOS] Win10
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] Antd@4.24.8 Floating-ui@0.21.0

**Comment by atomiks** [comment]
It means `Dropdown` doesn't accept a `ref` (doesn't forward it to any DOM node). So, in this scenario, it needs to be attached to `children.props.children`:

```js
cloneElement(children, {
  children: cloneElement(children.props.children, {
    ref: refs.setReference
  }),
})
```

**Comment by CarryOnHxy** [comment]
> It means `Dropdown` doesn't accept a `ref` (doesn't forward it to any DOM node). So, in this scenario, it needs to be attached to `children.props.children`:
> 
> ```js
> cloneElement(children, {
>   children: cloneElement(children.props.children, {
>     ref: refs.setReference
>   }),
> })
> ```

So efficient!!!  Thank you!
