### ISSUE TITLE
The hide middleware hides the floating element when the referenced element is visible

### ISSUE THREAD

**Issue by leandro-fenoglio-ca** [floating-ui/floating-ui#2288]
**Describe the bug**
The [hide middleware](https://floating-ui.com/docs/hide) hides the floating element when the referenced element has `position: fixed;` and it's inside an element with `overflow: hidden;`.

**To Reproduce**

https://codesandbox.io/s/hungry-saha-5fzzb5

Hovering over the item "Option 5 (Hover me)" will not display the tooltip.

1. Add `position: static;` on `<div class="select">` will work

or

1. Remove `overflow: hidden;` form `<div class="wrapper-with-overflow">` will work

**Expected behavior**
I believe that as a reference element is visible, the tooltip should also be.

**Screenshots**
![floating-ui](https://user-images.githubusercontent.com/82389520/231872230-107590d3-17ef-4469-b75c-f5e84ea53b3b.gif)

**Context:**
- OS: OS: macOS Monterey 12.1
- Browser: Google Chrome
- Version: 112.0.5615.49

**Additional context**
-

**Comment by atomiks** [comment]
This would be another incorrect calculation of the clipping rect. Looks like it's been broken forever (including before v1) and fails on this structure:

```
div.overflow:hidden
  div.position:relative
    div.position:fixed
      div.reference (visible out of overflow hidden wrapper)
```

**Comment by sallerli1** [comment]
we encountered the same issue in @idux/components

from what I read from the codes, when one overflow ancestor's position is fixed, following ancestors are not included only when position is static。

since fixed positioning is only relative to viewport，I an wondering if position has to be 'static' to be droped from clipping ancestors when its descendants have fixed positioning

because I cannot ensure that every ancestor is  `position: static`, dont know how to avoid this issue

**Comment by atomiks** [comment]
@sallerli1 fixed positioning is relative to the nearest containing block, which is the viewport by default, but not always.

Below is where the clipping ancestors are determined. In this case, the `overflow: hidden` wrapper should be dropped but isn't. 

When I tried changing various things in this function it ended up breaking some other case.  Robustly knowing which ones can be dropped or shouldn't be dropped is a bit tricky, and there are many tests for this at `Hide.tsx`, which helps know other structures break as a result. There may be a much better and more straightforward algorithm 🤷 cc: @gavinxgu  

https://github.com/floating-ui/floating-ui/blob/09a3ce259fc35d9c936ad469051ab6ea602a1249/packages/dom/src/utils/getClippingRect.ts#L94-L130
