### ISSUE TITLE
Wrong `FloatingArrow` size

### ISSUE THREAD

**Issue by Profesor08** [floating-ui/floating-ui#2292]
**Describe the bug**
Height is same as width

**To Reproduce**

1. Create `FloatingArrow` with custom shape
2. Assign `width`, `height` attributes

**Expected behavior**
Arrow to be same size as `width`, `height` attributes

**Screenshots**
![image](https://user-images.githubusercontent.com/8218016/233047281-0710192c-d827-45c2-9715-a156d60f4e31.png)

![image](https://user-images.githubusercontent.com/8218016/233047449-bf449cf2-7b2b-4bef-ac20-7e725bae15ed.png)

**Bug is there**
https://github.com/floating-ui/floating-ui/blob/09a3ce259fc35d9c936ad469051ab6ea602a1249/packages/react/src/components/FloatingArrow.tsx#L127-L129

**Suggestion**

```
const svgWidth = isCustomShape ? width : width + strokeWidth;
const svgHeight = isCustomShape ? height : height + strokeWidth;

width={svgWidth} 
height={svgHeight}
viewBox={`0 0 ${svgWidth} ${svgHeight}`}
```

**Comment by atomiks** [comment]
The docs mention the SVG needs to be square in dimensions, with the inner path being able to have any aspect ratio:

<img width="787" alt="Screenshot 2023-04-19 at 9 13 39 pm" src="https://user-images.githubusercontent.com/22450188/233057892-72a10edf-2551-44a4-b189-bac9816f66a5.png">

The square is how the other shapes are built:
<img width="675" alt="Screenshot 2023-04-19 at 9 17 11 pm" src="https://user-images.githubusercontent.com/22450188/233058819-11f7534a-37f4-4ebb-83a8-5c6d4c9e9eac.png">

**Comment by Profesor08** [comment]
> The docs mention the SVG needs to be square in dimensions, with the inner path being able to have any aspect ratio:

It is weird behavior. Because it is realy easy to support normal svg with any `width` and `height`, and to align, and rotate it, any way you want.

**Comment by atomiks** [comment]
The reason it's like that is because when the axis of placement changes (e.g. `top` -> `right`), a size other than a square causes an incorrect position of the arrow for the first update since it's not known beforehand. A square ensures the axis change doesn't affect the measurement. I think it was also easier to create the logic in general with that constraint.

**Comment by Profesor08** [comment]
There is simple logic, set `transform-origin: bottom center` and to rotate arrow around this point depending on placement. Also you will need `width` to shift the arrow. Other calcuations, required to position the arrow relative to popup, depends on popup rect. The `height` really doesn't matter.
