### ISSUE TITLE
Firefox right click triggers a mouseOut event

### ISSUE THREAD

**Issue by AlexKDawson** [floating-ui/floating-ui#2299]
**Describe the bug**
While using firefox, if you right click a tooltip it triggers a mouseout event which causes the tool tip close, even when using an interactive tooltip via safePolygon();

**To Reproduce**
[Sandbox](https://codesandbox.io/s/floating-ui-react-dom-template-forked-voew0m?file=/src/App.js:0-965)
I switched the lib from @floating-ui/react-dom to @floating-ui/react (I hope this is ok)

1. Mouse over the Reference Element
2. Move the mouse to the floating element
3. Highlight the text, and right click
4. The floating ui will disappear in Firefox

**Expected behavior**
The context menu should open, but the floating element should remain visible

**Context:**
 - OS: MacOS Ventura
 - Browser Firefox
 - Version 111.0

**Additional context**
This isn't an issue specific to this library, I have seen it happen with other tooltips which rely upon mouseout. But I'm wondering if there is a mechanism in this library to avoid this issue, or a recommended workaround for an implementation of a tooltip using floatingUI

**Comment by atomiks** [comment]
Something like this on the floating/reference element seems to work, but then the floating element doesn't close if you weren't hovering over it when closing the context menu:

```js
onPointerDown={() => {
  setHoverEnabled(false);
  setTimeout(() => setHoverEnabled(true), 100);
}}
```

File a bugzilla ticket?

**Comment by AlexKDawson** [comment]
Thanks for the feedback! I was able to get something similar tooling around with in on my end, but ran into the same issue where now you need some way of closing the tooltip since the close trigger was ignored... filing a bugzilla ticket seems like the right approach to me! Will do.

**Comment by AlexKDawson** [comment]
For visibility: https://bugzilla.mozilla.org/show_bug.cgi?id=1829500
