### ISSUE TITLE
Floating pane with border and floatingArrow have no easy way to preserve pane border contiguity

### ISSUE THREAD

**Issue by klepas** [floating-ui/floating-ui#2302]
## Is your feature request related to a problem? Please describe.

AFAIK, yes? I haven’t found a direct solution for this pedantic design problem.

TL;DR: no easy means to having border contiguity when a pane has a border and using floatingArrow’s SVG (with a stroke).

If the floating pane has a border, when using the floatingArrow (despite the many excellent options for modifying the ‘arrow’ SVG) I don’t have an easy means to avoid a border cutting across the arrow — it’s either the pane’s border or the stroke of the arrow that cuts across.

Visual eg:

![Screenshot 2023-04-26 at 16 48 14](https://user-images.githubusercontent.com/52766/234499321-61fb55c9-1006-411a-9fbe-09a296b51402.png)

## My current solution

My current solution is to provide my own `d='…'` path definition, with a hand-crafted SVG triangle.

The dimensions of this triangle go into the negative on the Y axis. I do this to work with the floatingArrow positioning setup (touching the bottom of the 14×7 viewBox) and going into the negative means the stroke of the arrow path is now outside of the viewBox. Now I ensure it paints above my pane’s border so it cuts across it and I get border contiguity.

The problem with my solution is I must provide my own custom `d` path definition and therefore can’t use and extend the default SVG with the many awesome options already provided.

Screenshot with border contiguity:

<img width="162" alt="Screenshot 2023-04-26 at 17 17 07" src="https://user-images.githubusercontent.com/52766/234499660-a7031769-a675-40dd-9877-e3e92aea85ff.png">

## Describe the solution you'd like

As a fan of floatingArrow’s `staticOffset`, maybe another similarly-named prop to offset on the other axis?

This would allow me to use the default SVG and the many neat options for it.

## Describe alternatives you've considered

1. Write a fair bit more code and use [arrow](https://floating-ui.com/docs/arrow) and then draw the shape myself (eg. via a custom-crafted SVG or the CSS border triangle method).
2. Faking a border using an additional CSS `drop-shadow()` filter? :S

There might be others I haven’t thought of (hopefully nothing too obvious)? 😃 

***

Thanks for floating-ui. 🙏

**Comment by atomiks** [comment]
I made a Sandbox if you want to edit it to reproduce your issue: https://codesandbox.io/s/quirky-torvalds-mriduv?file=/src/App.tsx

Though I don't see the issues, especially if you're rounding `x` and `y` coords. I can re-open with a reproduction of the issue — and there's the above workaround in any case.
