### ISSUE TITLE
Migration documentation not linked

### ISSUE THREAD

**Issue by Flachdachs** [floating-ui/floating-ui#2310]
When you open the [documentation for Floating-UI](https://floating-ui.com/docs/getting-started) there is no Migration guide visible in the menu at the left side. But you can find one when using the search function. Is this intended?

It is also not linked in Getting Started. This would make sense for me, when I want to start with Floating UI but have already knowledge about Popper.

Finally there is a link in the Motivation page. That's not the place where I would search it at first.

Suggestion: Give the Migration page a place in the menu and also mention it in Getting Started.

**Comment by atomiks** [comment]
Thank you, added to nav and getting started page

**Comment by Flachdachs** [comment]
Is it intended that Motivation is now unlinked?

**Comment by atomiks** [comment]
I inverted the linking as I figured migration should take precedence, and don't want to make the nav too long
