### ISSUE TITLE
Clipping calculations of reference element inside iframes are incorrect

### ISSUE THREAD

**Issue by chrishoyle** [floating-ui/floating-ui#2313]
The hide() middleware (or other uses of detectOverflow) doesn't properly calculate clippingRects of iframes.

Minimal reproduction showing reference detected as hidden when it is visible: https://stackblitz.com/edit/react-ts-floating-ui-iframe-clipping?file=App.tsx

**Comment by atomiks** [comment]
Workaround here: https://github.com/floating-ui/floating-ui/issues/2174
