### ISSUE TITLE
Infinite loop on getNearestOverflowAncestor causing a RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by jvlobo** [floating-ui/floating-ui#2317]
Hello!

I'm using this library and it is working great. I had a few tests in place using Jest, and they were all working fine too using Node 14.
Now I've updated to Node 18, and somehow the tests that involve floating-ui started failing 🤔

This is the error I get:

```
Node.js v18.16.0
project/node_modules/.pnpm/@floating-ui+dom@1.2.7/node_modules/@floating-ui/dom/dist/floating-ui.dom.umd.js:296
  function getParentNode(node) {
                        ^

RangeError: Maximum call stack size exceeded
    at getParentNode (project/node_modules/.pnpm/@floating-ui+dom@1.2.7/node_modules/@floating-ui/dom/dist/floating-ui.dom.umd.js:296:25)
    at getNearestOverflowAncestor (project/node_modules/.pnpm/@floating-ui+dom@1.2.7/node_modules/@floating-ui/dom/dist/floating-ui.dom.umd.js:313:24)
    at getNearestOverflowAncestor (project/node_modules/.pnpm/@floating-ui+dom@1.2.7/node_modules/@floating-ui/dom/dist/floating-ui.dom.umd.js:322:12)
    at getNearestOverflowAncestor (project/node_modules/.pnpm/@floating-ui+dom@1.2.7/node_modules/@floating-ui/dom/dist/floating-ui.dom.umd.js:322:12)
    at getNearestOverflowAncestor (project/node_modules/.pnpm/@floating-ui+dom@1.2.7/node_modules/@floating-ui/dom/dist/floating-ui.dom.umd.js:322:12)
    at getNearestOverflowAncestor (project/node_modules/.pnpm/@floating-ui+dom@1.2.7/node_modules/@floating-ui/dom/dist/floating-ui.dom.umd.js:322:12)
    at getNearestOverflowAncestor (project/node_modules/.pnpm/@floating-ui+dom@1.2.7/node_modules/@floating-ui/dom/dist/floating-ui.dom.umd.js:322:12)
    at getNearestOverflowAncestor (project/node_modules/.pnpm/@floating-ui+dom@1.2.7/node_modules/@floating-ui/dom/dist/floating-ui.dom.umd.js:322:12)
    at getNearestOverflowAncestor (project/node_modules/.pnpm/@floating-ui+dom@1.2.7/node_modules/@floating-ui/dom/dist/floating-ui.dom.umd.js:322:12)
    at getNearestOverflowAncestor (project/node_modules/.pnpm/@floating-ui+dom@1.2.7/node_modules/@floating-ui/dom/dist/floating-ui.dom.umd.js:322:12)
```

I've been doing a bit of debugging, and it seems that the `getNearestOverflowAncestor` function gets into an infinite loop. The `parentNode` const is being assigned to the same node in every run.

Any ideas? What can I try? Not sure why this was not failing on the previous version of Node and it is failing on this one.

Thanks.

**Comment by atomiks** [comment]
If you log out `parentNode`, what is it before this branch?

https://github.com/floating-ui/floating-ui/blob/b8d1fd5854333b688ddc9ee2a171f6453fcdbcab/packages/dom/src/utils/getNearestOverflowAncestor.ts#L7-L11

This is where the function should stop recursing, so it's likely the node is not what is expected in the new Node/jsdom version or whatever

**Comment by jvlobo** [comment]
I recorded a quick video while debugging and checking the content of `parentNode` and I forgot to post it

https://user-images.githubusercontent.com/5671420/236202096-2da6a5a1-1c98-4012-a458-e64d0733ef4c.mov

Basically it seems like the content of `parentNode` goes "back and forth" between two values, resulting in an infinite loop.
If you need more information please let me know.

**Comment by atomiks** [comment]
That must mean `isLastTraversableNode(...)` is failing, because `#document` is one of the strings that is checked for, and it should break the loop. What's `getNodeName(parentNode)`?

**Comment by jvlobo** [comment]
`getNodeName(node)` is returning empty string inside the `isLastTraversableNode` function:

![Screenshot 2023-05-04 at 13 30 36](https://user-images.githubusercontent.com/5671420/236204646-52e599b1-f095-466c-9ed0-1a32248cca40.png)

**Comment by atomiks** [comment]
yeah that'd do it 🫠

**Comment by jvlobo** [comment]
Is that what you were asking for or is there something else I can provide?
Thanks for the help :)

**Comment by atomiks** [comment]
The empty string is why it's running into an infinite loop. 

> Also, it seems like the node is of type MockHTMLElement

My guess is `isNode()` is returning `false` then, which is why it's empty

```ts
export function getNodeName(node: Node | Window): string {
  return isNode(node) ? (node.nodeName || '').toLowerCase() : '';
}
```

**Comment by jvlobo** [comment]
Correct, `isNode()` is returning `false`

![Screenshot 2023-05-04 at 13 38 59](https://user-images.githubusercontent.com/5671420/236206859-70f6aed5-a514-4f99-85a5-cba66a50e4cd.png)

It seems like it gets a bit confuse with all those `mock` types from Jest 🤔

**Comment by jvlobo** [comment]
> An alternative method is checking if `node.nodeName` is of type `string` instead, assuming that `.nodeName` property on that node is `#document` or `html`.

That definitely works. I did something like this just to test:

```
function isStr(value) {
    return typeof value === 'string' || value instanceof String;
  }

  function getNodeName(node) {
    return isNode(node) || isStr(node.nodeName) ? (node.nodeName || '').toLowerCase() : '';
  }
```

And it runs with no issues. Is this something that can be added on the library itself and release in a future version?

Thanks.

**Comment by atomiks** [comment]
Yeah that's fine if you want to make a PR. The only problem is if someone has `window.nodeName = 'body'` or such, then things may break. So a better check may be needed...

**Comment by FezVrasta** [comment]
@atomiks does it make sense to change how the library work so that a quirky DOM implementation works? Wouldn't it make more sense to fix the problem on, I guess, jsdom?

**Comment by atomiks** [comment]
@FezVrasta kind of agree, I'm not even sure how this is happening considering this lib is used in a lot of projects and no one has made an issue until now. I also can't reproduce it on Node 18 with latest `jest` and `jest-environment-jsdom`.  
Seems like it could be an environment problem on your end @jvlobo, try creating a minimal repro?

**Comment by atomiks** [comment]
@jvlobo I'm not against changing the code to adapt to this scenario, as long as it doesn't have any downsides in other cases, like the one I mentioned. Given that it seems to be env-specific, maybe with a custom Jest setup causing an issue, I'm going to close as not reproducible. But you can make a PR if you want anyway to fix it.

**Comment by jvlobo** [comment]
Thanks @atomiks 
I forgot to reply to your last comment as I was planning on trying to get a min repro but I haven't had the time this week.
I'll report back with any news I have regarding the issue.

Thank you.

**Comment by jvlobo** [comment]
Hello again @atomiks 
Sorry for the delay but I finally got around creating a minimal repo where you can reproduce the issue: https://github.com/jvlobo/floating-ui-issue

It has the minimum of the stack I'm having the issue with: StencilJS (3.0.0), Storybook (7.0.21).
To reproduce the issue you just need to install the dependencies and run the `test:unit` script. It throws the same error I reported at the beginning of the issue:

![Screenshot 2023-06-16 at 11 51 22](https://github.com/floating-ui/floating-ui/assets/5671420/086e5b61-a0d0-40ae-832b-610b70522416)

I'm using Node `18.16.0`, NPM `9.5.1` and PNPM `8.6.2`.

The repo basically has only one componente `my-component` that you can see inside `src/components` and it has the StencilJS code for the component itself and the `my-component.spec.ts` file that is running the test.

I hope this can help on finding a good solution.

If you believe the solution is what we previously talked about I'm happy to do a PR. I haven't done it because it can have other side-effects that I'm not aware of.

Thanks a lot :)
