### ISSUE TITLE
Stable floating-ui-id for TEST environments in jest - RTL

### ISSUE THREAD

**Issue by smellai** [floating-ui/floating-ui#2319]
**Is your feature request related to a problem? Please describe.**
At the moment my snapshots get outdated at each test run because of random ids generation

**Describe the solution you'd like**
I think other libraries like [MUI](https://github.com/mui/material-ui/issues/21293) implement some mechanism to keep stable IDs on test environments

**Describe alternatives you've considered**
I tried to mock `useId` hook exposed by floating-ui/react, but no luck to date.

**Additional context**

![Screenshot 2023-05-09 alle 18 13 01](https://github.com/floating-ui/floating-ui/assets/1763268/da6c5a74-c445-4c7e-a41f-799bba2d68bb)

**Comment by atomiks** [comment]
```js
jest.mock("@floating-ui/react", () => {
  const originalModule = jest.requireActual("@floating-ui/react");
  return {
    __esModule: true,
    ...originalModule,
    useId: jest.fn(() => "mocked-id"),
  };
});
```

https://jestjs.io/docs/jest-object#jestrequireactualmodulename

**Comment by smellai** [comment]
I tried that and any variant of that (using spy etc), but it didn't have any effect, I suspect because I'm not using `useId` in my code directly.

**Comment by atomiks** [comment]
Snapshot tests like that are generally a bad idea because you're testing internals which are subject to change. Instead assert only the public parts that are necessary to check for. 

Otherwise, if you upgrade to React 18, it will use the built-in hook instead, which I think may be stable.
