### ISSUE TITLE
safePolygon doesn't seem to work as expected

### ISSUE THREAD

**Issue by luin** [floating-ui/floating-ui#2321]
**Describe the bug**

First I want to say thanks for the great library. I just migrated from PopperJS and found the new API is much fun to work with 👍

For my issue:
I'm under the impression that the safe area created by `safePolygon` should be a triangle as demonstrated in the screencast of the documentation: https://floating-ui.com/docs/useHover#safepolygon.

However, in practice, I found the safe area seems to be a rectangle in the following case:

https://github.com/floating-ui/floating-ui/assets/635902/f50f810f-2d90-472b-bf06-59b535f7c3fc

https://codesandbox.io/s/floating-ui-react-dom-template-forked-ec5tyy?file=/src/App.js

Not sure if that's the expected behavior but I think the area is too large and counterintuitive.

**To Reproduce**

https://codesandbox.io/s/floating-ui-react-dom-template-forked-ec5tyy?file=/src/App.js

1. Hover over "Hover Me"
2. Move the mouse to the upper right corner as shown in the video.

**Expected behavior**
The popover should be closed.

**Screenshots**
The popover remains open.

**Context:**
 - OS: macOS
 - Browser Chrome
 - Version 107

**Comment by atomiks** [comment]
Well usually the rectangle bridge offset is not huge like that, which doesn't seem realistic. Is that a realistic scenario to be concerned about? The triangle on the other hand can block many other elements, especially nearby reference elements, which is why it has different handling.

**Comment by luin** [comment]
Hey @atomiks 👋. Yeah it's a real use case at slab.com where there is a big offset (40% of the viewport width) between the reference and the popover.

And in our case the triangle will not block other references so that's not an issue for us. I'm not familiar with the codebase and  all the options that `safePolygon` provides so not sure if a new option can be added to customize the behavior.

**Comment by atomiks** [comment]
What can be done instead, is measuring the bridge from the smaller element's dimension. i.e. `Math.min(referenceLen, floatingLen)`

**Comment by luin** [comment]
Sounds good! This should solve the issue perfectly for us 👍
