### ISSUE TITLE
```@floating-ui/react@0.24.1``` is using wrong version of ```@floating-ui/dom``` after package update

### ISSUE THREAD

**Issue by meruyert93** [floating-ui/floating-ui#2331]
**Describe the bug**

After updating the package, we had an issue related to the versions of packages, I decided to report it here and I hope it will be useful for someone.

We were also experiencing this bug https://github.com/floating-ui/floating-ui/issues/2311 and after this PR https://github.com/floating-ui/floating-ui/pull/2326  is merged. I have updated the packages but the bug was still persisting. 

It took us some quite time until we realised that `@floating-ui/react@0.24.1` requires `@floating-ui/dom@1.2.8` and our dependency versions did not look correct and it were not automatically updated. So my dependency versions of the packages looked like this: 
```
"@floating-ui/dom@^1.2.7":
  version "1.2.7"
  resolved "https://registry.yarnpkg.com/@floating-ui/dom/-/dom-1.2.7.tgz#c123e4db014b07b97e996cd459245fa217049c6b"
  integrity sha512-DyqylONj1ZaBnzj+uBnVfzdjjCkFCL2aA9ESHLyUOGSqb03RpbLMImP1ekIQXYs4KLk9jAjJfZAU8hXfWSahEg==
  dependencies:
    "@floating-ui/core" "^1.2.6"

"@floating-ui/react-dom@^2.0.0":
  version "2.0.0"
  resolved "https://registry.yarnpkg.com/@floating-ui/react-dom/-/react-dom-2.0.0.tgz#7514baac526c818892bbcc84e1c3115008c029f9"
  integrity sha512-Ke0oU3SeuABC2C4OFu2mSAwHIP5WUiV98O9YWoHV4Q5aT6E9k06DV0Khi5uYspR8xmmBk08t8ZDcz3TR3ARkEg==
  dependencies:
    "@floating-ui/dom" "^1.2.7"
    
"@floating-ui/react@0.24.1":
  version "0.24.1"
  resolved "https://registry.yarnpkg.com/@floating-ui/react/-/react-0.24.1.tgz#9ef81c78045c4b88ac062755826a3daf7cbe23d6"
  integrity sha512-qjCKUZDEz/4bnJmu4gn66TqsoX912/re8JGEi3pXazsphmyh327l0UpTgpBAT3WkNbnzAH7Adt3wKlLMNtfupw==
  dependencies:
    "@floating-ui/react-dom" "^2.0.0"
    aria-hidden "^1.1.3"
    tabbable "^6.0.1" 
```

Since `@floating-ui/react` is not directly using `@floating-ui/dom` but it is like this `@floating-ui/react` --> `@floating-ui/react-dom` --> `@floating-ui/dom`  and since based on rolling versions here https://github.com/floating-ui/floating-ui/pull/2326#issuecomment-1546026895 only `@floating-ui/react` and `@floating-ui/dom` were released, `@floating-ui/dom` was not automatically updated for us because `@floating-ui/react-dom` were still the same and using old version of  `@floating-ui/dom`

So, we just deleted all versions for the entire `floating-ui` dependency tree, so it will just install everything again and now it is just working because `^` versioning. 

Nevertheless, I think you should change rolling version configurations that it will update `@floating-ui/react-dom` to use new version of `@floating-ui/dom` as well because an update of the packages are happening based on dependency sequences of the packages and package manager doesn't update the packages if it does not have direct dependency :)

**Comment by atomiks** [comment]
Well `@floating-ui/react` doesn't require `@floating-ui/dom@1.2.8`, it's optional. (But fixes that issue). The `^` versioning and `@floating-ui/react-dom` not being updated is fine in this case.

Re-installing the package to get all deps to latest seems fine to me - new installations will get the latest version.

**Comment by atomiks** [comment]
Going to close since this release cycle is expected. Re-installing for latest everything is the recommended strategy
