### ISSUE TITLE
Request: An autoUpdate solution intended for text editors, or otherwise a way to manually invoke updates

### ISSUE THREAD

**Issue by Slapbox** [floating-ui/floating-ui#2332]
**Is your feature request related to a problem? Please describe.**
When positioning `floating` elements inside of a text editor there seems to be no alternative to `animationFrame: true` to keep the floaters in their correct positions in the event that a user adds a paragraph to the editor above the `floating` element's reference - except this hacky workaround which affects global event listeners: `window.dispatchEvent(new Event('resize'));`

**Describe the solution you'd like**

One of:

1. A cleaner way to manually force position updates
2. An autoUpdate option specifically intended for text editor projects (possibly via comparing the previous/next number of children of the parent of the reference element)
3. A debounced alternative to `animationFrame: true` (probably not realistic)

**Describe alternatives you've considered**
Dispatching `window.dispatchEvent(new Event('resize'))`, but it's hacky, not self-documenting, and affects global event listeners. I also considered `animationFrame: true` but it raises CPU usage ten-fold and I'm only even positioning a single element so I can't imagine using it in production for persistent `floating` elements

**Additional context**

**Comment by atomiks** [comment]
https://floating-ui.com/docs/react#manual-updating?

**Comment by Slapbox** [comment]
Thanks for your reply @atomiks. Correct me if I'm wrong, but that `update` method is only available when using React or equivalent, right? 

What about if you can't use React - is there a vanilla option to achieve that?

**Comment by atomiks** [comment]
Oh ok, well I thought it was obvious — you already control the update function. Just call it yourself whenever:

```js
import {computePosition, autoUpdate} from '@floating-ui/dom';
 
// You control this, just call it
function updatePosition() {
  computePosition(referenceEl, floatingEl).then(({x, y}) => {
    // ...
  });
}
 
const cleanup = autoUpdate(referenceEl, floatingEl, updatePosition);
```

**Comment by Slapbox** [comment]
Thanks again for your reply @atomiks. I shouldn't have overlooked that, but it can become easy to overthink when code gets complex. I feel there's room for API improvement here.

We're creating a bunch of floating elements at once but we only need to update them in a single place, and it seems like our only option is to accumulate the updater for every individual floating element in the collection and then update each one individually - but in practice it's quite onerous to keep an up to date array of the updater functions since this is a text editor. The resulting logic is tough to read and reason about.

It would be _really_ nice if `autoUpdate` could handle this situation because it's rather painful currently.

Do you have any thoughts regarding adding a potential option for `autoUpdate` for this use case? My idea was:

> An autoUpdate option specifically intended for text editor projects (possibly via comparing the previous/next number of children of the parent of the reference element)

Having worked with several text editor libraries I feel this would be a general purpose and helpful option which shouldn't harm performance and could be opt-in only like `animationFrame` is. It would be similar to the existing `ancestorResize`. Admittedly I am not familiar with how the existing options are implemented, and while I'm sure it wouldn't cover 100% of text editor cases, it would probably cover 99%.

**Comment by Slapbox** [comment]
@atomiks I still think an option for rich text editors would be invaluable. Again I face a circumstance where `animationFrame` is our only option, but if we could do something like `referenceEl.parentElement.childElementCount !== previousChildElementCount` it would spare us literally hundreds of operations per second. This time manually invoking updates is not viable.

When a user inserts a new node above the `referenceEl` in the editor, `autoUpdate` cannot detect that and display in the correct location.

So we're stuck with `animationFrame` for possible dozens of elements. Is there any reason this couldn't be supported?

**Comment by atomiks** [comment]
There's an open PR for a new option that should handle it

**Comment by Slapbox** [comment]
For future readers, it would appear that PR is: #2373 (which I am very excited about!)
