### ISSUE TITLE
Allow an offset for FloatingArrow to align with rounded tooltips

### ISSUE THREAD

**Issue by mcongrove** [floating-ui/floating-ui#2337]
**Is your feature request related to a problem? Please describe.**
When using rounded corners on a tooltip, the FloatingArrow becomes visually disconnected as the tooltip scrolls out of view.

![Screen Shot 2023-05-22 at 10 31 58 PM](https://github.com/floating-ui/floating-ui/assets/442433/472241f4-1e33-4b94-b4dd-ce1b98f35468)

You can see it live here: [https://codesandbox.io/s/fervent-lake-bhcodk](https://codesandbox.io/s/fervent-lake-bhcodk)

**Describe the solution you'd like**
Add a setting which determines the minimum offset from the edge of the tooltip that the FloatingArrow can appear; generally, if you have 4px rounded borders, this value would be at minimum set to 4px.

**Describe alternatives you've considered**
I had this working using the old method of manually creating and positioning the arrows, but FloatingArrow is awesome, and I want to use it! :)

**Comment by atomiks** [comment]
The [`padding` option for `arrow`](https://floating-ui.com/docs/arrow#padding) is for this purpose: 

https://codesandbox.io/s/great-bas-2l8kdr?file=/src/App.tsx

**Comment by mcongrove** [comment]
Well, guess I didn't doc hard enough. Thanks!
