### ISSUE TITLE
[React] Large values of FloatingArrow padding makes arrow and tooltip positions incorrect

### ISSUE THREAD

**Issue by EliteUser** [floating-ui/floating-ui#2349]
Hello!

Stuck with a problem with the tooltip arrow... again 😄 

Reproduction example - [reproduction](https://codesandbox.io/p/sandbox/tooltip-arrow-positioning-45hdkq?file=%2Fsrc%2FApp.tsx) 

As a continuation of [this](https://github.com/floating-ui/floating-ui/discussions/2307) discussion (which is unanswered 😢) - when padding value is large the arrow is not positioned correctly. 

E.g - for placement=left, if tooltip height is 36px, and padding value is also 36px - looks like this:

![image](https://github.com/floating-ui/floating-ui/assets/31800794/fd7cd23a-3882-4aaf-855b-2bf955b5612e)

But should look like this: 

![image](https://github.com/floating-ui/floating-ui/assets/31800794/aff508b5-0c31-4a0f-959d-0f165a3ef067)

The problem is that the padding is just a number that only takes into account one side, even though the documentation says - "stop 5px from the edges of the floating element". It doesn't take into account the placement of the tooltip, its size, or the size of the trigger element.

In my case - I want arrow to be centered on tooltip, if large padding value makes arrow "disconnected" from tooltip. So I think that some improvements in arrow middleware will help - like callback argument in offset mw, which can provide info about rects.

There are also a lot of other cases I tried to describe in the [discussion](https://github.com/floating-ui/floating-ui/discussions/2307), but I think the main thing is the padding

Any ideas how to fix it? 
Thx in advance!

**Comment by atomiks** [comment]
What is the use case for such a large padding value? It's only really necessary to be as large as the `border-radius` causes it to overflow the corners. A value of `36` means it has to be _at least_ 36 pixels from one of the edges, causing that result

**Comment by EliteUser** [comment]
I have following tooltip design

![image](https://github.com/floating-ui/floating-ui/assets/31800794/71d9ac13-19d0-45a6-95ac-152c6de150a8)

This is left-top placement. So here I have 5px border-radius and 14px offset from the top edge to the arrow (the padding I want to set). The arrow itself is 18x8px. So when tooltip will only have title (and in this case its height will be 36px - minimum height possible) the padding will be very large, even if it not-aligned-placement. I have these cases in reproduction. 
So by design, if tooltip is small, I want to center the arrow - set padding to another value, depending on the tooltip or trigger element size

**Comment by atomiks** [comment]
In that case, I would just use a static offset under a certain condition (i.e. it's too small): 

```js
<FloatingArrow 
  // ...
  staticOffset={isTooSmall ? `calc(50% - ${arrowWidth / 2}px)` : null}
/>

**Comment by atomiks** [comment]
So if the padding causes it to be less than the padding from the two edges on the relevant axis, the `arrow` middleware should force-center itself to prevent needing to do it manually? @EliteUser would this be enough, or there still needs to be something else checked?

**Comment by domidomi** [comment]
> So if the padding results in the arrow being _less than_ the padding from one of the two edges on the relevant axis, the `arrow` middleware should force-center itself to prevent needing to do it manually? @EliteUser would this be enough, or there still needs to be something else checked?

Simply centering the arrow wouldn't work for `-end` and `-start` positions. Actually, the padding shouldn't cause arrow to not point at the middle of the ref element.

**Comment by EliteUser** [comment]
> 

Agreed. I think it would be more flexible, if arrow middleware will provide control over padding value. 
E.g I want to set another padding value, when tooltip is small 
So, like I said before - something like 
`padding: ({rect}) => {
 /* some conditions based on ref and tooltip sizes */
 return paddingValue}
 }
 `
 will help

**Comment by atomiks** [comment]
> Simply centering the arrow wouldn't work for -end and -start positions.

Are you referring to centering inside the floating element, or centering relative to the reference element? When I said "force-center", I mean the center of the reference element, not floating element

> padding: ({rect}) => { /* some conditions based on ref and tooltip sizes */ return paddingValue} } 

Seems simple enough to add.

**Comment by domidomi** [comment]
>When I said "force-center", I mean the center of the reference element, not floating element

Ok, now I get it! This is exactly what I meant
