### ISSUE TITLE
useHover + restMs option doesn't show tooltip when reference is a forwardRef cloned element

### ISSUE THREAD

**Issue by saadflow** [floating-ui/floating-ui#2350]
**Describe the bug**
The setup is as follows:
- A Generic Tooltip component receives a single child as a prop.
- The component clones the child and renders it with the ref `useFloating(...).refs.setReference` as well as `...getReferenceProps()` from `useInteractions()`.
- It also renders the floating element with all the necessary props and refs.
- In order for this to work, the child component must have been creating using `forwardRef`, and must have passed the ref to one of its child jsx elements.
- When using the component with a native jsx element such as <button>, everything works as expected.
- When the element is a functional component, it works too ...
- ... **until** the `restMs` option is set. The tooltip never appears

**To Reproduce**

https://codesandbox.io/s/floating-ui-react-dom-template-forked-9idkst

1. Hover over the three buttons.

**Expected behavior**
The third buttons's tooltip should appear after 300ms of cursor rest

**Screenshots**

**Context:**
 - OS: OSX 13.1
 - Browser: Chrome
 - Version: 113.0.5672.126

**Comment by atomiks** [comment]
You aren't forwarding the props to the button, this works:

```js
export const Button = forwardRef(({ label, ...props }, ref) => {
  return (
    <div>
      <button ref={ref} {...props}>{label}</button>
    </div>
  );
});
```

Native event listeners are used for regular hover behavior due to some bugs with the event delegation system in React, which is why it works without that. In any case, the props should always be forwarded to the element to prevent issues with the underlying implementation if it changes in the future.

**Comment by saadflow** [comment]
Thanks!
