### ISSUE TITLE
Floating-ui doesn't fully support ESM when building with esbuild

### ISSUE THREAD

**Issue by maxbogus** [floating-ui/floating-ui#2355]
**Describe the bug**
When we bundle application with @popperjs/core into ESM with Esbuild it incorrectly transforms JS. Unfortunately, Esbuild bundles JS into global space. And one of the properties of this library overwrites browser property top and then browser replaces it with its own Window object.

**To Reproduce**
- @esbuild:0.17.19 : https://github.com/evanw/esbuild

1. Set package to ESM in package.json: `"type": "module"`
2. Bundle project to esm for browser:
`const devConfiguration = {
  bundle: true,
  jsx: 'automatic',
  loader: {
    '.js': 'jsx',
    '.png': 'file',
    '.ts': 'ts',
    '.tsx': 'tsx',
    '.svg': 'text',
    '.woff': 'file',
    '.translations': 'file'
  },
  format: "esm",
  target: ['chrome60', 'edge79'],
  platform: 'browser'
}`
5. Serve bundle into the browser
6. Go to console

**Expected behavior**
One of the ways to fix this issue is to update package.json and replace `"module": "lib/index.js"` with `"module": "dist/cjs/popper.js"`.

**Screenshots**
<img width="1218" alt="Screenshot 2023-05-31 at 11 01 49" src="https://github.com/floating-ui/floating-ui/assets/521205/50c2bf86-6fff-4877-ab0d-3567960a3c62">
<img width="549" alt="Screenshot 2023-05-31 at 11 09 40" src="https://github.com/floating-ui/floating-ui/assets/521205/1a48da7c-9ee6-4c2c-8b5c-ca6c1dc3a015">

**Comment by atomiks** [comment]
You need `type="module"` on your `<script>` tag

**Comment by maxbogus** [comment]
@atomiks , thank you very much!
That worked!
