### ISSUE TITLE
[React] Nested FloatingPortal doesn't obey root prop

### ISSUE THREAD

**Issue by sverps** [floating-ui/floating-ui#2356]
When having nested `FloatingPortal` elements, the inner portals don't respect their `root` prop and are set on the parent portal node. Cause: ([code](https://github.com/floating-ui/floating-ui/blob/b8990250568043b876e1c8fe42358fe337847ede/packages/react/src/components/FloatingPortal.tsx#L72))

This leads to issues in more complex scenario's, e.g. a modal component with a child scroll wrapper that then has popover elements.

```jsx
const ref = useRef();

...

<FloatingPortal>
  <ScrollWrapper ref={ref}>
    <FloatingPortal root={ref?.current} />
  </ScrollWrapper>
</FloatingPortal>
```

In the pseudo-code example above, when the inner portal is open, the element will scroll with the parent portal, rather than within the scroll wrapper.

Potential fix is to change the priority and use the provided root element if defined:

```diff
-let container = portalContext?.portalNode || root || document.body;
+let container = root || portalContext?.portalNode || document.body;
```

**Comment by atomiks** [comment]
Seems valid to me. 

Side note: you're reading the `ref` in render, but that's not allowed by React - I think we can accept a `ref` as well as an `element` for the `root` prop to reduce that type of usage.
