### ISSUE TITLE
Add type for `context` property

### ISSUE THREAD

**Issue by ashtraysoap** [floating-ui/floating-ui#2361]
I have an application in TypeScript with custom popover logic built on the `@floating-ui/react` API which combines `useFloating`, `useInteractions` and some other hooks from the package. The Floating UI `context` property is passed around a lot. It would be easier to refactor / write wrappers around it, if the `context` property had a concise type.

Suggested solution:

Create a type alias such as `FloatingContext` for the current
```
{
    placement: Placement;
    strategy: Strategy;
    x: number;
    y: number;
    middlewareData: MiddlewareData;
    update: () => void;
    isPositioned: boolean;
    floatingStyles: React.CSSProperties;
    ... 7 more ...;
    elements: ExtendedElements<...>;
}
```

**Comment by atomiks** [comment]
`FloatingContext` is already exported and that is the type, you're seeing a prettified expanded version in your IDE.

**Comment by ashtraysoap** [comment]
Aha, thanks for clearing it out.

Great work with the poject!
