### ISSUE TITLE
arrow middleware does not return correct x and y on rtl

### ISSUE THREAD

**Issue by jd1378** [floating-ui/floating-ui#2374]
**Describe the bug**
as title says

**To Reproduce**
https://codesandbox.io/s/morning-framework-624tp7?file=/index.html

I have set html direction to rtl right now, so it's buggy when you open it
setting to nothing or ltr is the default behavior that works, but when it's changed to rtl it breaks

**Expected behavior**
add a `direction` prop to arrow middleware ? so we can let it know that it should calculate position from right I guess ?

**Comment by atomiks** [comment]
I would recommend just using `top`/`left` as the docs say, but this isn't a bug - it's because you need to set `top` and `left` layout to `0` so the transform works from top-left when positioning.

https://codesandbox.io/s/elegant-david-ghc855?file=/src/index.js:972-1349

Layout:

```js
transform: "rotate(45deg)",
// Ensure the static side gets unset when
// flipping to other placements' axes.
left: y != null ? `${x}px` : "",
top: y != null ? `${y}px` : "",
```

Transform:

```js
left: 0,
top: 0,
// The ordering here also matters - translate must come first
transform: `translate(${x}px, ${y}px) rotate(45deg)`,
```

**Comment by jd1378** [comment]
is this what you suggested ? it doesn't work
https://codesandbox.io/s/affectionate-gianmarco-sjc2gp
```js
Object.assign(arrowEl.style, {
        left: 0,
        top: 0,
        transform: `translate(${x}px, ${y}px) rotate(45deg)`
      });
```

**Comment by jd1378** [comment]
also the example with layout only works when it's placement is bottom, for example 'top' is buggy @atomiks :
https://codesandbox.io/s/dark-tree-tvwqrd

**Comment by atomiks** [comment]
You shouldn't set `x = 0, y = 0` when destructuring, then the `null` checks don't work.

**Comment by jd1378** [comment]
I see, in layout yes, but I can't still figure out the transform (I was using transform in my code, so using defaults in destruct made sense)

**Comment by jd1378** [comment]
doesn't matter, I'll use the layout (transform causes blurry text somehow, even rounded values of x/y)
thanks a lot
