### ISSUE TITLE
Floating UI in a sticky header doesn't stay with the reference element

### ISSUE THREAD

**Issue by jquense** [floating-ui/floating-ui#2380]
**Describe the bug**

Floating UI in a sticky header doesn't stay with the reference element. `strategy: fixed` is a workaround, but that can cause scroll jank when the sticky element isn't stuck. Ideally i think this case should work out of the box? 

**To Reproduce**

https://codesandbox.io/s/floating-ui-react-dom-template-forked-4yvkfm?file=/src/App.js

1. Scroll the preview window

**Expected behavior**

Tooltip makes an effort to stay positioned to the reference element

**Screenshots**

**Context:**

**Additional context**

**Comment by atomiks** [comment]
> strategy: fixed is a workaround, but that can cause scroll jank when the sticky element isn't stuck. Ideally i think this case should work out of the box?

Scroll jank would occur without `fixed` when it is stuck though and is more noticeable than the other way around imo. Using fixed strategy is better in this scenario.

**Comment by jquense** [comment]
Yeah I made an attempt at toggling between fixed/absolute using an intersection observer to detect when the container is stuck but the hook didn't adapt smoothly when toggled so I tabled it till I have more time to dig into why
