### ISSUE TITLE
Uncaught RangeError: Failed to construct 'IntersectionObserver': Threshold values must be numbers between 0 and 1

### ISSUE THREAD

**Issue by HuanEragon** [floating-ui/floating-ui#2389]
**Describe the bug**
![image](https://github.com/floating-ui/floating-ui/assets/129071336/bdd8acda-fd07-4f41-a70e-ec007034b3b0)

antd-mobile popover import [floating-ui](https://github.com/floating-ui/floating-ui)

![image](https://github.com/floating-ui/floating-ui/assets/129071336/9143aef7-1712-43c3-a991-f4918c8cf1ca)
antd-mobile-5.31.1  code

![image](https://github.com/floating-ui/floating-ui/assets/129071336/d32a4ab9-9e35-4feb-a823-9d64c311d468)
too much error about ':Uncaught RangeError: Failed to construct 'IntersectionObserver': Threshold values must be numbers between 0 and 1' generated here

**Comment by atomiks** [comment]
Are these errors appearing in your error reporting system? What browser are they coming from? Never saw these while adding this, but we can add safety checks to make sure this can't happen.

For now if you override `@floating-ui/dom` installation to `1.3.0` instead of `1.4.1` the error will disappear

**Comment by HuanEragon** [comment]
It‘s from our  error reporting system. All in  android from 9 - 12. here is some eg：

Rajax/1 OPPO/PEGM10 Android/12 Display/PEGM10_11_C.19 Napos/10.5.6 ID/cb7cba96-ebff-37d2-9dbb-7301f37a14cd; KERNEL_VERSION:4.19.157-perf+ API_Level:31 Channel:ele AliApp(NAPOS/10.5.6) ; Needle EleEnv(release) Mozilla/5.0 (Linux; U; Android 12; zh-CN; PEGM10 Build/RKQ1.211103.002) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/69.0.3497.100 UWS/3.22.1.238 Mobile Safari/537.36 AliApp(NAPOS/10.5.6) UCBS/2.11.1.1 TTID/hybrid@windvane_android_8.5.0 WindVane/8.5.0 UT4Aplus/ltracker-0.2.30.38 Needle/3.0.0.42-SNAPSHOT;utdid=YN2/iH4Az/MDAHyEKm5QP050;webank/h5face;webank/1.0;netType:NETWORK_WIFI;appVersion:103356;packageName:me.ele.napos

Rajax/1 samsung/SM-G9730 Android/12 Display/SP1A.210812.016.G9730ZCU8HVL2 Napos/8.6.8 ID/c749ba58-010b-3224-a339-7f6f101fedd8; KERNEL_VERSION:4.14.190-23725627-abG9730ZCU8HVL2 API_Level:31 Channel:huawei AliApp(NAPOS/8.6.8) ; Needle EleEnv(release) Mozilla/5.0 (Linux; U; Android 12; zh-CN; SM-G9730 Build/SP1A.210812.016) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/69.0.3497.100 UWS/3.21.0.103 Mobile Safari/537.36 AliApp(NAPOS/8.6.8) UCBS/2.11.1.1 TTID/hybrid@windvane_android_8.5.0 WindVane/8.5.0 Needle/2.2.27;webank/h5face;webank/1.0;netType:NETWORK_WIFI;appVersion:102942;packageName:me.ele.napos

I can’t repeat the

**Comment by atomiks** [comment]
Fix is releasing shortly. Please let me know if there are other issues - I'll have to hack something with try/catch in the worst case, but it _should_ fix it

**Comment by HuanEragon** [comment]
thx to fix it~
