### ISSUE TITLE
Arrow middleware appears to not be doing anything

### ISSUE THREAD

**Issue by wathhr** [floating-ui/floating-ui#2392]
**Describe the bug**
Arrow middleware doesn't appear to be doing anything

**To Reproduce**
https://codesandbox.io/s/confident-poincare-zjym5s

1. Append a child to the tooltip element
2. Use the child as the "element" option on the arrow middleware
3. Notice how the child does nothing

**Expected behavior**
The element specified gets positioned correctly

**Screenshots**
![image](https://github.com/floating-ui/floating-ui/assets/72303904/84b8e094-300a-4e10-91ff-550d86b6168d)

**Context**
 - OS: Windows
 - Browser: Firefox
 - Version: 114.0.2

**Comment by atomiks** [comment]
The arrow middleware provides data to apply the arrow's positioning styles yourself, the same as `computePosition`'s main coordinates. The [usage docs](https://floating-ui.com/docs/arrow#usage) are quite clear about this.

**Comment by wathhr** [comment]
Sorry I completely overlooked that, thanks for pointing that out!
