### ISSUE TITLE
Export more internal utils from react package

### ISSUE THREAD

**Issue by mihkeleidast** [floating-ui/floating-ui#2396]
**Is your feature request related to a problem? Please describe.**
The composable nature of the hooks system in `@floating-ui/react` makes it fairly easy to replace a hook with custom implementation, be the reason just for debugging or some functional need. Doing this is a bit complex right now, since most of the hooks use a bunch of internal utility functions and hooks. Copying `useListNavigation` to my codebase to debug/test some changes, for example, also necessitates copy-pasting [12 utility functions](https://github.com/floating-ui/floating-ui/blob/master/packages/react/src/hooks/useListNavigation.ts#L9-L22) from different files.

**Describe the solution you'd like**
Make it easier to copy a hook to consumer codebase without all the utility functions (those can be copied and modified separately, if necessary!) by exporting the utilities from the library, as just replacing the imports is much easier than copying all of the source:

```
import { activeElement, contains, ... } from '@floating-ui/react';
```

**Describe alternatives you've considered**

Exporting the internal utilities from the main library entrypoint may not be wanted, since I would say they are in a gray area in terms of semver - as they are mostly for internal use, you likely do not want to do major releases just to overhaul some utility functions.

Alternatives would be:
1. Add a separate entrypoint for the internal utils, e.g. `import { activeElement, contains, ... } from '@floating-ui/react/internal';`. This could then be clearly documented that this entrypoint does not necessarily follow semver.
2. Move the internal utils to a separate package, e.g. `import { activeElement, contains, ... } from '@floating-ui/react-internal';`. A separate package could stay on 0.x forever, meaning it can always introduce breaking changes.

**Additional context**
None.

**Comment by atomiks** [comment]
There are a few places where functions in dependencies need to be re-used by the dependants, but can't and need to be copied. I think a `0.0.x` versioned `@floating-ui/utils` package is a good idea.

**Comment by atomiks** [comment]
`@floating-ui/react@0.25.0` splits most utils into `@floating-ui/utils` package, non-useful internal ones aren't exported though
