### ISSUE TITLE
Incorrect positioning when reference has `display: contents`

### ISSUE THREAD

**Issue by cpsievert** [floating-ui/floating-ui#2403]
**Describe the bug**

When a reference element has `display: contents`, positioning for the floating element is incorrect. 

**To Reproduce**

https://codesandbox.io/s/little-https-zcnjnv?file=/src/styles.css

**Expected behavior**

In the example above, I'd expect the same result as [the canonical placement example](https://codesandbox.io/s/lively-waterfall-rbc1pi?file=/src/index.js) (i.e.,  "Tooltip" should appear above the empty box)

Note that all I changed from the codepen above is to move the reference styles to it's child element and put a `display: contents` on the reference.

**Screenshots**

<img width="1293" alt="Screenshot 2023-06-29 at 5 26 33 PM" src="https://github.com/floating-ui/floating-ui/assets/1365941/e0eb8953-ef0c-4ca1-9788-c61bbd606b92">

**Comment by atomiks** [comment]
Elements with `display: contents` don't have a bounding box and can't be measured. This is a browser limitation and not a bug

**Comment by KutnerUri** [comment]
That disappointing to learn. Thanks for addressing this limitation.

**Comment by silverwind** [comment]
Wonder if there are any workarounds as `display: contents` is the most non-invasive method of introducing a wrapper element and I would much prefer to use it instead of fiddling with the styling of the wrapper to make it work in all situations.
