### ISSUE TITLE
Floating UI not closing on second click of reference when using closed Shadow DOM

### ISSUE THREAD

**Issue by sampotts** [floating-ui/floating-ui#2420]
**Describe the bug**
When using a _closed_ Shadow DOM, the select does not close on the second click of the reference. This seems to effect the Select example too so I've included an edited codesandbox to demonstrate the issue. 

**To Reproduce**

1. Go to https://codesandbox.io/s/floating-ui-react-18-shadow-dom-8r6pyy
2. Click on 'Select...' to open
3. Click again to close and observe it doesn't close as it does in the other [Select example](https://codesandbox.io/s/gallant-sea-rcg43b?file=/src/Select.tsx). When logging `event.target` in useDismiss you'll notice it logs the root element, rather than the button/reference:
```ts
const dismiss = useDismiss(context, {
  outsidePress: (event: MouseEvent) => {
    console.log(event.target);
    return true;
  }
});
```

**Expected behavior**
The select menu should close when you click the button/reference the second time. 

**Context:**
 - OS: macOS 13.4.1
 - Browser: Arc
 - Version: 0.110.1 (39837) Chromium Engine Version 114.0.5735.198

**Additional context**
Seems to be unrelated to the browser used and more of an issue with the closed Shadow DOM.

**Comment by atomiks** [comment]
The event is a regular `MouseEvent`/`PointerEvent` from `document.addEventListener('pointerdown', e => ...)` - you can test this in the Sandbox, so there's nothing special there.

It seems to work with an `open` shadow mode rather than `closed`

**Comment by sampotts** [comment]
> The event is a regular `MouseEvent`/`PointerEvent` from `document.addEventListener('pointerdown', e => ...)` - you can test this in the Sandbox, so there's nothing special there.

Yeah, I only mention it as it's getting the wrong event.target. You'll notice it logs the root element instead. Without React 18/Shadow DOM, it returns the button/reference as expected. I assume that's related to why the select does not close as expected on second click. 

> It seems to work with an `open` shadow mode rather than `closed`

Unfortunately, we need closed.

**Comment by atomiks** [comment]
It's not related to React 18 but probably how the browser exposes elements inside closed shadow DOMs. You can replicate it with vanilla JS:

```js
const rootElement = document.getElementById("root");
const shadowRoot = rootElement!.attachShadow({ mode: "closed" });

const btn = document.createElement("div");
btn.textContent = "Button";
shadowRoot.appendChild(btn);

document.addEventListener("pointerdown", e => {
  console.log(e.target);
});
```

Not familiar enough with this to know if there's a workaround or if it's an inherent limitation.

**Comment by sampotts** [comment]
Yeah, wasn't sure re: React 18. I've removed the reference. I didn't have time to try the different React versions, I just knew we're using 18. 

I'll see if I can find a workaround. It's not a critical bug.

**Comment by atomiks** [comment]
Best solution is likely to use `FloatingOverlay` and detect clicks on it rather than `outsidePress` in `useDismiss`.

**Comment by sampotts** [comment]
Thanks! Adding a `FloatingOverlay` fixed it 👍🏼

**Comment by ivancuric** [comment]
Bumping this as it seems to happen even when using an open shadow root. Reproduced in https://github.com/floating-ui/floating-ui/issues/2420
