### ISSUE TITLE
[React] `useHover` does not work with `window.open` rendered component 

### ISSUE THREAD

**Issue by Mgrdich** [floating-ui/floating-ui#2421]
**Describe the bug**

i am opening a new window with `window.open` that i am rendering with portal and that component has some floating elements in it , after i create all the necessary template for that new document with the element id and the styling it is still not working.

https://david-gilbertson.medium.com/using-a-react-16-portal-to-do-something-cool-2a2d627b0202. the implementation and the motivation is close to this one but it has some floating elements in it. but i am making sure i create the correct div elements with `id` and the correct `ownerDocument`. 

**To Reproduce**

* implement the code from the article.
* create new element div with the correct `id` and `ownerDocument`.
* put a floating element with FloatingPortal with `id` in it.

**Expected behavior**

**Screenshots**

**Context:**
 - OS: MacOs
 - Browser Chrome
 - Version` react: "18.2.0"` , `"@floating-ui/react": "0.24.3"`

**Additional context**
i think i know the problem because the FloatingPortal that uses this hook just uses `document` instead of using

 https://github.com/floating-ui/floating-ui/blob/af9065552f52f1300d274ee4980e58cd1a7cda08/packages/react/src/utils/getDocument.ts#L1

and In this one

https://github.com/floating-ui/floating-ui/blob/af9065552f52f1300d274ee4980e58cd1a7cda08/packages/react/src/components/FloatingPortal.tsx#L64

it uses the document directly instead of using `getDocument` which i think is what causing the problem, but the whole `useFloatingPortalNode` is written with Document instead of `getDocument` i think we need to address this.

**Comment by atomiks** [comment]
Instead of an `id`, you can pass `root` which refers to an element inside the external window's document

**Comment by atomiks** [comment]
Closing since there's no element to reference when using an `id` this seems expected - the `root` prop allows you to specify any element regardless and should work.

**Comment by Mgrdich** [comment]
but are the `React` element reference that gets created linked to the correct `document` ?

**Comment by Mgrdich** [comment]
> Closing since there's no element to reference when using an `id` this seems expected - the `root` prop allows you to specify any element regardless and should work.

https://github.com/floating-ui/floating-ui/blob/d51e5bdc8bf892383e11f64cfdcd12c319bfeeb9/packages/react/src/hooks/useHover.ts#L296

, in the useHover is returning false and that is not actually putting the event listenner `onmouseenter` and `onmouseleave` on my floating container which i checked it is picking up the correct root node now.

**Comment by atomiks** [comment]
A repro would help

**Comment by Mgrdich** [comment]
@atomiks  hey thanks in advanced , i created a repo and i noticed that it works on FireFox but it does not on Chrome and Chromium browser the Event handlers are not there.

https://codesandbox.io/s/dawn-https-n6vm8w

here this is a minor `codesandbox` implementation , since i am using an `Electron` application for all of this , and it uses `Chromium` under the the hood so i have to make sure it does works on `Chromium` browser.

**Comment by Mgrdich** [comment]
> A repro would help

This is a zip of the video , where i demonstrate on the same sandbox example how the tooltip is not working. 

[demo of the video.zip](https://github.com/floating-ui/floating-ui/files/12011575/demo.of.the.video.zip)

**Comment by solteszm** [comment]
Hi @atomiks, I faced very similar issues when tried to used floating elements in a separate window. Any update on this would be really useful. Thanks 🙏

**Comment by Mgrdich** [comment]
This might help us out

<img width="551" alt="Screen Shot 2023-07-11 at 14 20 13" src="https://github.com/floating-ui/floating-ui/assets/46796009/9675a700-3920-4776-b5b1-5d31b7a0bc24">
<img width="425" alt="Screen Shot 2023-07-11 at 14 20 27" src="https://github.com/floating-ui/floating-ui/assets/46796009/7dad94fe-63c9-448d-8841-01c8e1377e07">

**Comment by atomiks** [comment]
So essentially, the default behavior of `FloatingPortal` is expected. The `id` query selects the main `document`, so you need to use a `root` element (which I see has been added to the Sandbox). What's not expected is `useHover` not working — hooks that use React's event handlers work fine, but `useHover` registers event listeners on the element directly:

https://codesandbox.io/s/silent-glade-qkq3c5?file=/src/components/Tooltip.js

Therefore it seems to just be a bug with the `isElement` etc guard functions checks as pointed out by @Mgrdich, rather than `FloatingPortal` since the `root` prop works fine.

**Comment by Mgrdich** [comment]
it works Thanks 💯 .
