### ISSUE TITLE
Flip middleware does not work properly when content is changed

### ISSUE THREAD

**Issue by IsaacAbrahamson** [floating-ui/floating-ui#2424]
**Describe the bug**
Flip middleware does not flip when there is more room above when the content is changed. The flip middleware correctly flips large content to the top if there is more room. However, if the content inside is made smaller and it flips back to bottom, the content will not flip back to the top when content is made large again.

**To Reproduce**
https://codesandbox.io/s/floating-ui-react-dom-template-forked-g2r6qk
1. Click button to open popover
2. See that flip correctly places content above activator
3. Press button inside modal to make content small
4. See that flip correctly places content below activator
5. Press button inside modal to make content large again
6. See that flip middleware doesn't flip content back to top

**Expected behavior**

The flip middleware should flip the content to the top like it did when initially rendered.

**Screenshots**

I made a simple example in CodeSandbox as well as I could, but here is how it looks in actual app:

![ezgif com-video-to-gif (35)](https://github.com/floating-ui/floating-ui/assets/17521691/6b207de8-a134-45f4-bb6d-62d92d4a471f)

**Context:**
 - OS: 2022 Macbook Pro (M1)
 - Browser: Chrome
 - Version: 114

**Comment by atomiks** [comment]
The problem here is that the `maxHeight` style doesn't get unset (to measure its true size / natural `scrollHeight`). One solution is to unset it when content changes: 

```js
<button
  onClick={() => {
    floating.refs.floating.current.style.maxHeight = "";
    setLarge(!large);
  }}
>
  Toggle Large
</button>
```

Although flipping on content changes feels a bit disorientating anyway, imo

**Comment by IsaacAbrahamson** [comment]
> The problem here is that the maxHeight style doesn't get unset (to measure its true size / natural scrollHeight). One solution is to unset it when content changes:

@atomiks Thanks for helping out. That's good to know that there is a manual fix to the problem. Shouldn't the max height be updated automatically when the floating element's size changes? I'm using the `autoUpdate` middleware which should give `size` middleware the correct `availableHeight`, or do I need to manually reset the max height in the `autoUpdate` function?

> Although flipping on content changes feels a bit disorientating anyway, imo

That's a good point.

**Comment by atomiks** [comment]
The `availableHeight` on the bottom is ~200px compared to the ~500px on the top placement. This means when content gets added, it simply overflows with the scrollbar rather than flip, because it doesn't stretch to its natural `scrollHeight` and therefore doesn't overflow the boundary.

**Comment by IsaacAbrahamson** [comment]
@atomiks That makes sense, thanks for the help. I'll just change to using `initialPlacement` for this then as you're right it shouldn't be flipping between views anyway.
