### ISSUE TITLE
There is a problem with the vertical position calculation when the keyboard is opened on the ios mobile terminal

### ISSUE THREAD

**Issue by liu-jin-yi** [floating-ui/floating-ui#2433]
**Describe the bug**
When I open the keyboard in IM, the view will be squeezed up, and there is a problem with the calculation of y at this time.

https://github.com/floating-ui/floating-ui/assets/45869971/665a5462-7312-4b90-8984-9d22106c6ab8

**Comment by liu-jin-yi** [comment]
My temporary solution is to use: y - window.visualViewport.offsetTop + floating.height + reference.height

**Comment by liu-jin-yi** [comment]
I think the compatibility scheme should be considered for the code below：

https://github.com/floating-ui/floating-ui/blob/073da89da80577565a69cebd786430e11ea9e3bc/packages/dom/src/utils/getRectRelativeToOffsetParent.ts#L48

**Comment by FezVrasta** [comment]
Without a minimal reproduction example we can't help you. I'm sorry

**Comment by atomiks** [comment]
@liu-jin-yi what version of `@floating-ui/dom` is installed? Make sure it's 1.4.4+
