### ISSUE TITLE
[React] tooltip use `shift` middleware with `crossAxis: true` option might results in tooltip flashing 

### ISSUE THREAD

**Issue by wulftn** [floating-ui/floating-ui#2435]
**Describe the bug**
when using `shift` middleware with `crossAxis: true` option, if the tooltip content is too large,
the tooltip keeps flashing.

**To Reproduce**
https://codesandbox.io/s/eloquent-breeze-2n9y59?file=/src/App.tsx
It is modified from floating-ui React's "Basic tooltip" example with the following changes:
1. large size tooltip content.
2. use `shift` middleware with `crossAxis: true` option.
3. use `useHover` with `delay: 200`.

1. Go to the codesanbox.
2. Hover the trigger button.

**Expected behavior**
The tooltip should stay open since we now hover the tooltip.

**Context:**
 - OS: [Windows10]
 - Browser [Chrome]
 - Version [@floating-ui/react 0.24]

**Comment by atomiks** [comment]
This can be fixed with `safePolygon`:

```js
import { useHover, safePolygon } from '@floating-ui/react';

useHover(context, { handleClose: safePolygon() });
```
