### ISSUE TITLE
 Cannot read properties of undefined (reading 'documentElement')

### ISSUE THREAD

**Issue by EduardoDevOlmedo** [floating-ui/floating-ui#2437]
**Describe the bug**
This error is happening when using Jest and React. This happens when testing the radix-ui `Dropdown` component and might be happening in other components as well.

```
node_modules/@floating-ui/dom/dist/floating-ui.dom.umd.js:199
    return ((isNode(node) ? node.ownerDocument : node.document) || window.document).documentElement;
```

**To Reproduce**
  In order to reproduce you only need to test the `Dropdown.Item` subcomponent. You will get this error no matter what you do, just by rendering it. 

**Expected behavior**
This line should use the optional chaining operator to check if `window.document` is already defined.

**Context:**
 - OS: MacOS
  - "jest": "^29.4.2",
    "jest-environment-jsdom": "^29.4.2",
 - Node 16.18.0
 
**Additional context**
This could be fixed by adding the '?' optional chaining operator. This should not have any impact on the code or produce any bugfixes. Adding ?.documentElement after window.document in code will not introduce any bugs. The ? operator ensures that the code gracefully handles cases where window.document is null or undefined.

If window.document is null or undefined, the optional chaining operator will short-circuit the expression and return undefined, preventing any potential errors that could occur when trying to access the documentElement property.

In essence, the updated code will wait for node.ownerDocument or node.document to be defined and then access the documentElement property, or it will check if window.document is defined and access its documentElement property. If none of these conditions are met and the values are null or undefined, it will return undefined.

I fixed this locally by changing the getDocumentElement fn:

```
function getDocumentElement(node) {
    return ((isNode(node) ? node.ownerDocument : node.document) || window.document)?.documentElement;
 }
```

If you agree with the changes please let me know to make a PR with these small changes that would save lots of peoples time. This issue has also been mentioned here: [issue](https://github.com/floating-ui/floating-ui/issues/1908) but nothing there helped to fix the issue, only by changing the `getDocumentElement` function.

**Comment by atomiks** [comment]
So does adding the `?.` operator fix the tests with no other issues? The main issue with this was that the types expect it not to be nullish elsewhere, which means it could error in other areas - but if this works then I don't see a problem with adding it.

**Comment by EduardoDevOlmedo** [comment]
> So does adding the `?.` operator fix the tests with no other issues? The main issue with this was that the types expect it not to be nullish elsewhere, which means it could error in other areas - but if this works then I don't see a problem with adding it.

Yes, this fixes it, I did it locally and it does fix it. I will send the PR today then.
