### ISSUE TITLE
Ability to delay FloatingFocusManager until open transition is complete

### ISSUE THREAD

**Issue by maladr0it** [floating-ui/floating-ui#2442]
**Is your feature request related to a problem? Please describe.**

When using FloatingFocusManager, the floating element immediately receives focus. This causes visual glitches if the floating element has an opening transition, eg sliding into view.

A reproduction of the issue is here:
https://codesandbox.io/p/sandbox/shy-night-cyzx29

Notice how the entry animation does not play correctly in various browsers, but if you remove the FloatingFocusManager there is no issue.

**Describe the solution you'd like**

There should be some way to delay floatingFocusManager from activating until the transition is complete, a simple way could be to have a `disabled` prop, which could be used as so:

`<FloatingFocusManager disabled={transition.status !== "open"}>`

Let me know if you need more information or have an appropriate workaround. For now I am just using conditional rendering to include the FloatingFocusManager, but this hurts readability.

**Comment by atomiks** [comment]
> For now I am just using conditional rendering to include the FloatingFocusManager, but this hurts readability.

Just wondering what value are you conditionally rendering on? I think you need to manually use `onTransitionEnd={() => {}}` and check if the transition completed? I guess a timeout fallback would usually work too.

**Comment by maladr0it** [comment]
Hi, thanks for the quick response. I'm really sorry but as you pointed out, I overlooked something. I don't actually have a way of knowing whether the entrance transition is completed. This could be a rather large breaking change, but I wonder if it would be possible to offer a more granular description of the transition state, as something like react-transition-group does.

For example, "opening", "opened", "closing", "closed"

I would really like some way of knowing the transition has completed without having to set up a listener and update some local state of my own, as I'm working on a relatively low-level library where performance is a consideration.

**Comment by atomiks** [comment]
It's possible to know the exit transition via `isMounted` but not the enter one. You can setup a timeout when `isMounted` changes to `true` to conditionally set the `disabled` prop for now. The same would be done need to be done by this library anyway.
