### ISSUE TITLE
[React] `useHover` and `useClick` no longer play nice in >= 0.24.3

### ISSUE THREAD

**Issue by briefone** [floating-ui/floating-ui#2443]
`useHover` and `useClick`, no longer behave like they used to. Clicking on the button doesn't keep the popover opened after hovering off.

Works as expect with 0.24.2:
https://codesandbox.io/s/serverless-flower-f3p7yv?file=/src/Popover.tsx

Doesn't work as expected with  0.24.7:
https://codesandbox.io/s/tender-sid-gyflqh?file=/src/Popover.tsx

`ignoreMouse` doesn't seem to do anything: https://floating-ui.com/docs/useClick#ignoremouse

1. Hover the button
2. Click it
3. Hover off

**Expected behavior**
After clicking, the popover should remain open, even after hovering off.

**Context:**
 - OS: Windows 11
 - Browser: Chrome 
 - Version: 114.0.5735.199

**Comment by atomiks** [comment]
Looks like it's caused by #2362 which moved the `dataRef.current.openEvent` assignment to be in `onOpenChange`, so the value only changes on open state changes, and not whenever the event fires (which is necessary in this case).

**Comment by atomiks** [comment]
Fixed in `0.24.8` (releasing now)

Side note: if you want it to not close after mouseleave after click-toggling it as well (e.g. triple-click) then `move: false` should be set in `useHover`.

**Comment by briefone** [comment]
@atomiks awesome, thank you.
