### ISSUE TITLE
[idea, useHover] Option to persist nested floating UIs on mouseLeave

### ISSUE THREAD

**Issue by tryggvigy** [floating-ui/floating-ui#2446]
Hello folks! I love this library I'm spiking trying to use it as a new foundation for our floating UI stack.
We are running into scaling issues with Tippy and I picked @floating-ui  precisely because it's so low-level and flexible.

I have a feature in mind that i'm curious if you think would be a good idea for this library. Taking inspiration from native MacOS context menus, the feature is essentially this: 

persisting nested floating UIs when the pointer paths outside of the floating element.
Here is how `useHover` is capable of today in nested floating uis:
1. ✅ open nested floating element when hovering over it's reference element
2. ✅ closing the nested floating element when the pointer paths outside of the reference element, but is still within the root floating ui
3. ✅ persist the nested floating element when pointer is pathing straight between the reference element and the floating element
4. ✅ persist the nested floating element when pointer is pathing towards the reference element in a reasonable way (safePolygon)
5. ❌ persist the nested floating element if the pointer paths from within the nested floating element to anywhere outside in the surrounding UI
  5.1 ❌ close the nested floating element if the pointer paths into the parent floating element

We could even add an extra behaviour that MacOS doesn't have but probably should:
6. ❌ Starting from state 5., persist the nested floating element if the pointer paths into the parent floating element but enters over the nested floating ui reference element

Here is a video showcasing how MacOS does this 

https://github.com/floating-ui/floating-ui/assets/2373958/386c4188-3a22-4ef2-b194-74e1508e01b5

Shows behaviour 5. and 5.1. As you can see, in state 6. MacOS flickers the nested floating ui closed and open. Not great! I guess it's because the reference element doesn't stretch all the way to the edge of the root floating element so maybe it's not their stacks fault really._

I'm not really sure where a behaviour like this should live in @floating/ui. useHover? safePolygon? both?

Looking forward to hearing your thoughts on this! I think it would be a great feature. It's a nice default for context menus at least. Especially if the nested menu has small width and the margin of error for the user, when they are entering the submenu, to accidentally move their mouse too far and exit the menu (thereby causing it to close when they dont want to) are higher.

**Comment by atomiks** [comment]
This is already possible by changing `useHover` `enabled` prop to `false` on mouseenter

**Comment by tounsoo** [comment]
For those who are also looking for the same thing, I made a [code sandbox](https://codesandbox.io/s/dropdownmenu-floating-ui-zl8lp4) with the full code.

_Originally posted by @tounsoo in https://github.com/floating-ui/floating-ui/discussions/2461#discussioncomment-6532804_

**Comment by atomiks** [comment]
There's an edge case there when hovering back into the menu on an item which doesn't have a submenu attached - the menu won't close. 

Something like this works:
```js
onMouseEnter(e) {
  setHoverEnabled(true)
  if (!refs.domReference.current?.contains(e.target)) {
    setIsOpen(false)
  }
}
```
