### ISSUE TITLE
[React] Support `width` in floatingStyles, and make default with the width of the reference element

### ISSUE THREAD

**Issue by loveholly** [floating-ui/floating-ui#2448]
https://github.com/floating-ui/floating-ui/blob/eb6c042e42faae7567e717fe10afdd1953375e14/packages/react-dom/src/useFloating.ts#L156-L160

Can we change it to:
```ts
const referenceRect = referenceEl?.getBoundingClientRect();
const initialStyles = { 
   position: strategy, 
   left: 0, 
   top: 0,
   width: referenceRect?.width,
 }; 
```

**Comment by atomiks** [comment]
Popovers and tooltips (most common floating elements) don't match the width of the reference element, so this is not an appropriate default.

Aside from that technique, there is also documentation here for `size`: https://floating-ui.com/docs/size#match-reference-width

**Comment by loveholly** [comment]
thx
