### ISSUE TITLE
[Vue] ArrowOptions.element type is too narrow

### ISSUE THREAD

**Issue by benkroeger** [floating-ui/floating-ui#2451]
**Describe the bug**
using arrow middleware in vue requires `options.element` to be of type `MaybeElement<HTMLElement>` although all interfaces in `dom` would be satisfied with `MaybeElement<Element>`

This narrow type requirement makes assigning a [template ref via function](https://vuejs.org/guide/essentials/template-refs.html#function-refs) from within a slot unnecessarily complicated to satisfy the typescript compiler.

FloatingUi component

```vue
<script setup type="ts">
    const arrowRef = ref<MaybeElement<HTMLElement>>();
    function setArrowElement(ref: Element | ComponentPublicInstance | null): void {
      arrowRef.value = ref as HTMLElement | ComponentPublicInstance | null;
    }
</script>
<template>
    <slot name="arrow" :set-arrow-element="setArrowElement" :arrow-style="arrowStyles"></slot>
</template>
```

in the consumer:

```vue
<template>
    <FloatingUi>
        <template #arrow="{ setArrowElement, arrowStyle }">
          <div :ref="setArrowElement" :style="arrowStyle"></div>
        </template>
    <FloatingUi>
</template>
```

**Expected behavior**
Would be nice if the FloatingUi component could look like this instead which makes `setArrowElement` compatible with vue's type for `HTMLAttributes['ref']`

```vue
<script setup type="ts">
    const arrowRef = ref<MaybeElement<Element>>();
    function setArrowElement(ref: Element | ComponentPublicInstance | null): void {
      arrowRef.value = ref;
    }
</script>
<template>
    <slot name="arrow" :set-arrow-element="setArrowElement" :arrow-style="arrowStyles"></slot>
</template>
```

**Additional context**
This is purely a type issue.

**Comment by atomiks** [comment]
Releasing in `@floating-ui/vue@1.0.2`
