### ISSUE TITLE
[React] `FloatingPortal` does not work inside `Suspense`

### ISSUE THREAD

**Issue by bug-brain** [floating-ui/floating-ui#2454]
**Describe the bug**
After the `FloatingPortal` comes out of suspense mode the floating element is gone.

**To Reproduce**
https://codesandbox.io/s/magical-sid-tt5z3h

1. open the sandbox
2. check that tooltip works by clicking “trigger”
3. click on “suspend” and wait one second
4. check that tooltip will no longer open

**Expected behavior**
`FloatingPortal` should be usable inside `Suspense`.

**Additional context**
As shown in the sandbox layout effects are executed again when a component is comes out of suspense mode. Because of that, [this layout effect](https://github.com/floating-ui/floating-ui/blob/master/packages/react/src/components/FloatingPortal.tsx#L51) will remove the element from the DOM but it not be re-initialized because of [this check](https://github.com/floating-ui/floating-ui/blob/master/packages/react/src/components/FloatingPortal.tsx#L58).

**Comment by atomiks** [comment]
The portal cleanup strategy there was adjusted after there were some problems in Strict Mode with conditionally rendered portals. 

It seems that allowing the portal to be conditionally rendered on `open` state changes fixes the issue, but causes a problem with it not being conditional.

`if (!context.open) return null`

```js
export const PopoverContent = React.forwardRef<
  HTMLDivElement,
  React.HTMLProps<HTMLDivElement>
>(function PopoverContent({ style, ...props }, propRef) {
  const { context: floatingContext, ...context } = usePopoverContext();
  const ref = useMergeRefs([context.refs.setFloating, propRef]);

  if (!context.open) return null;

  return (
    <FloatingPortal>
      <FloatingFocusManager context={floatingContext} modal={context.modal}>
        <div
          ref={ref}
          style={{ ...context.floatingStyles, ...style }}
          aria-labelledby={context.labelId}
          aria-describedby={context.descriptionId}
          {...context.getFloatingProps(props)}
        >
          {props.children}
        </div>
      </FloatingFocusManager>
    </FloatingPortal>
  );
});
```

**Comment by pedrojfds** [comment]
Will a fix for this be deployed soon?

**Comment by skypyxis** [comment]
Will a fix for this issue be available soon? 

The workaround is to create the PopoverContent  on our code with the upper mentioned code?

Thank you!

**Comment by atomiks** [comment]
The workaround is to make `FloatingPortal` be conditionally rendered based on the `open` state rather than always rendered.

**Comment by hornta** [comment]
Ah right, I had implementation the transitions incorrectly. It does work now.
