### ISSUE TITLE
[Vue]: Create Composables for Vue package (similar to React hook)

### ISSUE THREAD

**Issue by zernonia** [floating-ui/floating-ui#2455]
**Is your feature request related to a problem? Please describe.**
In https://github.com/radix-vue/radix-vue/ we are using Floating UI heavily, and we absolutely love it!
However, we wanted to implement the safePolygon feature (similar to useHover in React), but we can't find the same for Vue.

**Describe the solution you'd like**
Create `useHover` composables for Vue package

**Additional context**
Related issue: https://github.com/radix-vue/radix-vue/issues/169

**Comment by VividLemon** [comment]
You can find that utility method in vueuse

**Comment by zernonia** [comment]
> You can find that utility method in vueuse

could you direct me with a link? I cant seems to fine it.
Furthermore, I'm looking into safePolygon feature

**Comment by VividLemon** [comment]
https://vueuse.org/core/useElementHover/

**Comment by zernonia** [comment]
> https://vueuse.org/core/useElementHover/

Thanks for the link. But that is not what I'm looking for. If you look at the `useHover` hook for React.. it is quite extensible, and also include the feature I'm after (safePolygon)

**Comment by atomiks** [comment]
Ideally the interaction pieces would be framework-agnostic so there can just be bindings to hook into any framework. That was the original plan when first making the package, but the implementation was too buggy, so I went with React-only for the time being. It's possible of course, but since I am not very familiar with Vue, it needs another maintainer and an effort to decouple the logic from React.

**Comment by zernonia** [comment]
Thanks for the insight @atomiks ! I will try to implement the composable at locally at https://github.com/radix-vue/radix-vue/issues/169. Once it's up perhaps I can create a PR to floating-ui 😁

**Comment by atomiks** [comment]
Realistically, there isn't enough maintainer support for this to ever happen. Interactions will stay React-only for the foreseeable future, so I'm going to close this.

**Comment by ZWkang** [comment]
@atomiks would you accept vue composable hook pr?
