### ISSUE TITLE
@floating-ui/vue "MaybeReadonlyRef" => MaybeRefOrGetter

### ISSUE THREAD

**Issue by VividLemon** [floating-ui/floating-ui#2456]
I apologize for neglecting the bug report template. I'm on my phone making this and things are a bit tough.

The instance if the issue that I'm seeing is

```ts
useFloating(ref, ref, {
strategy: () => props.strategy
})
```
This synatx is available in Vue 3.3. The only way to make strategy reactive correctly is to create an intermediate ref like so (assuming the composable accepts reactivity, which I'm sure you are correctly doing this)
```ts
useFloating(ref, ref, {
strategy: toRef(props, 'strategy')
})
```

This isn't necessarily a bad thing, but can have performance benefits by not creating intermediate refs. In addition, the getter syntax is more straightforward. It would be nice if this was supported globally. I'm not necessarily sure if "Read-only" is required as a typing 

I suppose this is a feature request more than a bug report. I could submit a PR in a few days if needed

**Comment by VividLemon** [comment]
I am planning on building a PR sometime next week. So no worries

**Comment by atomiks** [comment]
@lozinsky can you take a look at this and the PR?

**Comment by VividLemon** [comment]
Requires a breaking change. `toValue` is not supported by Vue 2 or @vue/composition-api

**Comment by atomiks** [comment]
Ok, we can revisit once Vue 2 is officially EOL.

**Comment by VividLemon** [comment]
> Ok, we can revisit once Vue 2 is officially EOL.

Perhaps a BREAKING_CHANGE label may help it so this issue doesn't get lost in the void
