### ISSUE TITLE
[React] useHover floating element unexpectedly appears after the reference element is removed from the DOM

### ISSUE THREAD

**Issue by vveisard** [floating-ui/floating-ui#2463]
**Describe the bug**
useHover floating element unexpectedly appears after the reference element is removed from the DOM.  

**To Reproduce**
https://stackblitz.com/edit/stackblitz-starters-ynswwy

1. Go to linked StackBlitz
2. Enter text into input element
3. Observe a new X reference element has appeared to the right of the input element
4. Click the X reference element before the hover timeout completes
5. Observe a floating element (tooltip) appears unexpectedly

**Expected behavior**
I expect removing the reference element from the DOM to prevent the floating element to appear.

Alternatively, I expect the useHover hook to return an Api which allows you to clear the timeout yourself (which is preferable to me...)

**Context:**
 - OS: Manjaro Linux
 - Browser: Chromium
 - Version: 115.0.5790.98
 
 **Additional context**
 The only workaround is a onOpenChange function which checks if the element still exists.

**Comment by atomiks** [comment]
> The only workaround is a onOpenChange function which checks if the element still exists.

`useDismiss` `referencePress: true` option is another workaround
