### ISSUE TITLE
Generate `.d.mts` types for imports

### ISSUE THREAD

**Issue by fourdim** [floating-ui/floating-ui#2472]
**Describe the bug**

Upgrading @floating-ui/dom from version 1.2.9 to 1.50 will give following errors:

```
src/index.ts:6:42 - error TS7031: Binding element 'x' implicitly has an 'any' type.

6 computePosition(button, tooltip).then(({ x, y }) => {
                                           ~

src/index.ts:6:45 - error TS7031: Binding element 'y' implicitly has an 'any' type.

6 computePosition(button, tooltip).then(({ x, y }) => {
```

**To Reproduce**
https://codesandbox.io/p/sandbox/fancy-moon-t5p4ps?file=%2Fpackage.json%3A12%2C1-12%2C31

1. Run `yarn build`
2. See error

**Expected behavior**
No errors.

**Screenshots**

![image](https://github.com/floating-ui/floating-ui/assets/59462000/c5f7c148-f78b-4000-bdb2-07c78cfcee79)

**Context:**
 - Version 1.5.0

**Comment by atomiks** [comment]
In v1.5.0 the exports changed to put the `types` field below `import` and use the `.mts` extension to fix the [Masquerading as CJS](https://github.com/arethetypeswrong/arethetypeswrong.github.io/blob/main/docs/problems/FalseCJS.md) issue:

**From:**

```json
  "types": "./src/types.d.ts",
  "exports": {
    "./package.json": "./package.json",
    ".": {
      "types": "./src/types.d.ts",
      "import":  "./dist/floating-ui.core.mjs",
      "module": "./dist/floating-ui.core.esm.js",
      "default": "./dist/floating-ui.core.umd.js"
    }
  },
```

**To:**

```json
  "types": "./src/types.d.ts",
  "exports": {
    "./package.json": "./package.json",
    ".": {
      "import": {
        "types": "./src/types.d.mts",
        "default": "./dist/floating-ui.core.mjs"
      },
      "types": "./src/types.d.ts",
      "module": "./dist/floating-ui.core.esm.js",
      "default": "./dist/floating-ui.core.umd.js"
    }
  },
```

Which `publint` marks as "All good". 

However, it looks like [Are the types wrong?](https://arethetypeswrong.github.io/?p=%40floating-ui%2Fdom%401.5.0) fails to resolve the types from ESM.

I don't really understand how to fix this correctly.

**Comment by atomiks** [comment]
Seems like the issue is the `.d.mts` declaration files require an extension which is currently missing.

**Comment by atomiks** [comment]
Ok so I think adding the extensions to the `.d.mts` files is going to require a bit of work where every internal module in the project needs to add `.js`/`.ts` when importing, then a build step to rewrite the `.d.mts` files to add the `m` prefix to any imports.

For now, I'll simply revert the `.d.mts` declarations since "masquerading as CJS" is not really that bad, and keep this issue open to track getting them to work correctly.

**Comment by fourdim** [comment]
In my point of view, maybe you need to first tsc with `emitDeclarationOnly: false` and then use the generated js as the input of rollup. It is much easier to configure it if you use vite build system for the whole project ( as it will automatically do it for you by plugins ).

**Comment by fourdim** [comment]
I'm working on a pull request to replace rollup with vite.

**Comment by bsunderhus** [comment]
Just to confirm here @atomiks, this would be the ideal, so we gotta build `.d.ts` and `.d.mts` files?

```json
  "types": "./src/types.d.ts",
  "exports": {
    "./package.json": "./package.json",
    ".": {
      "import": {
        "types": "./src/types.d.mts",
        "default": "./dist/floating-ui.core.mjs"
      },
      "types": "./src/types.d.ts",
      "module": "./dist/floating-ui.core.esm.js",
      "default": "./dist/floating-ui.core.umd.js"
    }
  },
```

Seems like the generation of `.d.mts` files are identical to the on of `.d.ts` files, so why not just having a ctrl-c + ctrl-v task to copy `"./src/types.d.ts"` to `"./src/types.d.mts"? am I missing something here?

**Comment by atomiks** [comment]
I did do that originally, but that's what led to this exact error in this issue :D Specifically: https://github.com/floating-ui/floating-ui/issues/2472#issuecomment-1657125662

The CJS type defs don't need extensions in imports (and are compiled from the source without them), but ESM ones do. `import type {X} from './types.mjs';`

**Comment by bsunderhus** [comment]
And would it be ok if we only had the `.d.mts` types instead of the `.d.ts`? Like this:

```json
  "types": "./src/types.d.mts",
  "exports": {
    "./package.json": "./package.json",
    ".": {
      "import": {
        "types": "./src/types.d.mts",
        "default": "./dist/floating-ui.core.mjs"
      },
      "types": "./src/types.d.mts",
      "module": "./dist/floating-ui.core.esm.js",
      "default": "./dist/floating-ui.core.umd.js"
    }
  }
```

**Comment by bsunderhus** [comment]
I think I got a possible solution actually, if we flatten the types into a single file using something like [api-extractor](https://api-extractor.com/) then there will be no relative import to worry about this: `import type {X} from './types.mjs';` vs `import type {X} from './types';`, since those imprts will be sliced out of the flat `.d.ts` file, in that case I guess there would be no difference between a `.d.ts` and `.d.mts` 🤔
