### ISSUE TITLE
"ReferenceError: ResizeObserver is not defined" in lower Android devices(Android 9, Android 5.1, Android 7.1.1, Android 8.1.0)

### ISSUE THREAD

**Issue by sky-gg** [floating-ui/floating-ui#2485]
https://github.com/floating-ui/floating-ui/blob/6b12fdef95d7b09f276816ce9aead601be55204d/packages/dom/src/autoUpdate.ts#L168

some browser don't support "ResizeObserver" API, so we need to add `if( window.ResizeObserver){ // do something }`

**Comment by atomiks** [comment]
Already fixed since `dom@1.4.3`
