### ISSUE TITLE
Missing git tag for popperjs/core v2.11.8

### ISSUE THREAD

**Issue by jayaddison** [floating-ui/floating-ui#2486]
**Describe the bug**
Version v2.11.7 of popperjs/core is tagged in this repository, but v2.11.8 doesn't appear to be at the moment.  The tag could be useful for inter-version comparison and to match NPM releases against the code history here.

The v2.11.8 release was derived from commit 92195083958c9496988ed4526b82b75b7256b5a4 I think.

(later bug template sections omitted since hopefully the above includes enough of the relevant details)

**Comment by atomiks** [comment]
This version only removed the `__DEV__` / `process.env` access code. @FezVrasta are you able to create a new release tag for that commit?

**Comment by FezVrasta** [comment]
https://github.com/floating-ui/floating-ui/releases/tag/v2.11.8

**Comment by jayaddison** [comment]
Thanks @FezVrasta!
