### ISSUE TITLE
FloatingFocusManager issue with react-testing-library

### ISSUE THREAD

**Issue by konsalex** [floating-ui/floating-ui#2488]
**Describe the bug**

There is an issue with `<FloatingFocusManager/>` while testing with RTL, and I am not able to pinpoint why this is happening, while the functionality is correct in the application.

**To Reproduce**

Reproduction Repo:  https://github.com/konsalex/floating-focus-repro

Just install packages and run the tests

```bash
yarn
yarn test
```

**Expected behavior**

The tests should pass, as we expect when the tooltip is closed to re-focus on the trigger button. Instead of this the `<body/>` is taking focus

```bash
Expected element with focus:
  <button
  data-testid="trigger"
>
  Open Tip
</button>
Received element with focus:
  <body>
  <div>
    <div>
      <h1>
        Vite + React
      </h1>
      <div
        class="card"
      >
        <button
          data-testid="trigger"
        >
          Open Tip
        </button>
      </div>
    </div>
  </div>
</body>
```

**Screenshots**

The behaviour we want to test can be seen in the short video

https://github.com/floating-ui/floating-ui/assets/12672541/395b4de1-3c57-4ee2-bda2-045b03652d15

**Comment by atomiks** [comment]
Focus calls are wrapped in rAF, so making it sync for the test will fix it

**Comment by atomiks** [comment]
Yes:

https://github.com/floating-ui/floating-ui/blob/6b12fdef95d7b09f276816ce9aead601be55204d/packages/react/test/unit/setupTests.ts#L10-L15

**Comment by konsalex** [comment]
@atomiks Spying and mocking `requestAnimationFrame` still gives the same result. Pushed the change to the reproduction repo 🤔  Something else that may be missing?

**Comment by atomiks** [comment]
Sorry for taking so long to look at the repo.

Looks like you should use `fireEvent` instead of `userEvent` here instead, as the latter does things with focus and might be "stealing" it incorrectly in the testing environment.

```js
// Close the tooltip again
fireEvent.click(screen.getByTestId("test"));
```

Either way though, I think this is an implementation detail that you shouldn't test. It's this library's job to make sure these details work, which are tested (not perfectly thoroughly, but still.)

**Comment by atomiks** [comment]
Not sure if it's that, actually. This test passes in this repo but fails in yours. Tried to install the same versions of the test packages and the same setup file. Not sure why, but I don't think testing this implementation detail is needed by you anyway.

```js
test.only('test', async () => {
  function App() {
    const [isOpen, setIsOpen] = useState(false);
    const {refs, context} = useFloating({
      open: isOpen,
      onOpenChange: setIsOpen,
    });

    const click = useClick(context);
    const {getReferenceProps, getFloatingProps} = useInteractions([click]);

    return (
      <>
        <button
          data-testid="reference"
          ref={refs.setReference}
          {...getReferenceProps()}
        />
        {isOpen && (
          <FloatingFocusManager context={context}>
            <div
              ref={refs.setFloating}
              data-testid="floating"
              {...getFloatingProps()}
            >
              <button data-testid="close" onClick={() => setIsOpen(false)}>
                Close
              </button>
            </div>
          </FloatingFocusManager>
        )}
      </>
    );
  }

  render(<App />);

  await act(async () => {});

  await userEvent.click(screen.getByTestId('reference'));
  expect(screen.getByTestId('close')).toHaveFocus();
  await userEvent.click(screen.getByTestId('close'));
  expect(screen.queryByTestId('floating')).not.toBeInTheDocument();
  expect(screen.getByTestId('reference')).toHaveFocus();
});
```

**Comment by atomiks** [comment]
> Edit: looks like it is related to requestAnimationFrame. Making it sync in node_modules manually fixes the issue. Doesn't seem like the mock is actually being called/working in your setup file for some reason...

Seems like this works instead:


```js
Object.defineProperty(window, "requestAnimationFrame", {
  writable: true,
  value: (callback) => callback(),
});
```

**Comment by konsalex** [comment]
@atomiks can validate the above mocking technique works
