### ISSUE TITLE
[utils/dom] Why is `webkit` excluded from `filter` check

### ISSUE THREAD

**Issue by Westbrook** [floating-ui/floating-ui#2491]
https://github.com/floating-ui/floating-ui/blob/6b12fdef95d7b09f276816ce9aead601be55204d/packages/utils/dom/src/index.ts#L71

It seems like WebKit has [supported `filter` for some time now](https://caniuse.com/?search=filter), what causes Floating UI to exclude it in this check?

**Comment by atomiks** [comment]
Safari is weird about what CSS properties create a containing block: https://github.com/floating-ui/floating-ui/pull/2336

Also Chrome up until some recent version also ignored `filter`, it used to be a Firefox-only thing.

**Comment by Westbrook** [comment]
Interesting, it appears that this delta is what causes Safari to do this:
<img width="299" alt="image" src="https://github.com/floating-ui/floating-ui/assets/1156657/1823ba97-c7d7-4768-b0df-1d8e2f4ffb4d">

And Chrome/Firefox to do this:
<img width="228" alt="image" src="https://github.com/floating-ui/floating-ui/assets/1156657/751d6013-c937-4be3-87db-bd946c971392">

Note that the shadows on these elements are created via `filter`, which seems to be the only difference when walking the positioning code between the two.

**Comment by atomiks** [comment]
Maybe it changed in a recent Safari version or there's an unconsidered edge case. What version is being used?

**Comment by Westbrook** [comment]
Currently working with `Version 16.4 (18615.1.26.110.1)`. I've another system that _might_ have a slightly older version and will check into that later.

**Comment by atomiks** [comment]
Can you post a reproduction? Adding `filter` to the containing block tests doesn't reveal problems in Safari with raw positioning, but it looks like in your example there's a problem with clipping detection instead?

**Comment by atomiks** [comment]
I don't doubt there's a possible issue here, but going to close without a repro :)
