### ISSUE TITLE
Missing example of how to use native <dialog> element?

### ISSUE THREAD

**Issue by NullVoxPopuli** [floating-ui/floating-ui#2496]
I saw there there is a _very custom_ example for how to make a Dialog component: https://floating-ui.com/docs/dialog

But that's a lot of code, and I want to use native <dialog> to manage all the focus concerns.

I tried setting the `loop` on a `<dialog open>` and then wrapping `<dialog open>` in an if statement so I can choose to only show it if the user has clicked a button which sets a property to true, which would then render the `<dialog open>`. 

_however_, it seems that the transform is way off
![image](https://github.com/floating-ui/floating-ui/assets/199018/1eb64d93-7056-43b3-bf68-216804a29584)
![image](https://github.com/floating-ui/floating-ui/assets/199018/7b6bd7f1-a983-49c3-998f-fa76f1457013)

I manually edited the transform just to see what the values should be
![image](https://github.com/floating-ui/floating-ui/assets/199018/ce2c48c0-967c-4a7d-93b6-e8c56055ba3f)

idk if this is helpful, or if the origin is just _wrong_.
`<dialog>` defaults to center of the screen, so it could be that `computePosition` needs to account for that.
![image](https://github.com/floating-ui/floating-ui/assets/199018/17767291-c225-440d-a899-4b0561ca2a60)

(well, center top it seems)

I also tried the `absolute` strategy, but that also does goofy things
![image](https://github.com/floating-ui/floating-ui/assets/199018/f5258ce1-51c1-41e1-aa9b-b74f868acb75)

looks like the dialog is now shifting over my whole UI

This is in FireFox 118, but the same behavior is present in Chrome
with `@floating-ui/dom` 1.5.1

**Comment by NullVoxPopuli** [comment]
interesting.
I have a simpler demo, but it has a similar issue: 
![image](https://github.com/floating-ui/floating-ui/assets/199018/228b1caf-b628-4700-a131-60c91d836cf8)


what's a "top-layer" element?

**Comment by atomiks** [comment]
Probably because `transform` itself is being used to position it

**Comment by NullVoxPopuli** [comment]
Is that due to other middleware? Maybe not all middleware works with dialog?

Atm, i'm using, flip, shift, and offset

**Comment by atomiks** [comment]
Your screenshot shows the transform style:

<img width="976" alt="Screenshot 2023-08-21 at 9 19 54 pm" src="https://github.com/floating-ui/floating-ui/assets/22450188/bd2d3194-565c-4feb-bcb4-315539efe8a8">

**Comment by NullVoxPopuli** [comment]
ah! I found the code causing this mishap, I'll PR to that.
Thanks!!

https://github.com/CrowdStrike/ember-velcro/blob/1d8f77e1b1f85fd465c60f41d93110ec43530e29/ember-velcro/src/modifiers/velcro.ts#L93

**Comment by NullVoxPopuli** [comment]
:thinking: 

![image](https://github.com/floating-ui/floating-ui/assets/199018/b17c2c1e-f0a7-4326-8bc6-66ef01f021e8)


ran in to this -- setting `marign: 0` resolves
