### ISSUE TITLE
Support usage of `useListNavigation` without Floating context

### ISSUE THREAD

**Issue by sidx1024** [floating-ui/floating-ui#2497]
**Is your feature request related to a problem? Please describe.**
I want to use `useListNavigation` but the list is not inside a floating element.

**Describe the solution you'd like**
Would like if `useListNavigation` or a similar hook can be exposed that can be used without `context`. It would be really useful to avoid implementing keyboard navigation.

**Describe alternatives you've considered**
Tried to use `useListNavigation` without a floating context but it doesn't work.

**Comment by atomiks** [comment]
From: https://github.com/floating-ui/floating-ui/discussions/2517

> You can use the list navigation hook on regular non-floating elements by setting open: true permanently in useFloating. Everything will then work as normal even though the menu bar is not actually a floating element.

But yes this is a problem area and the above requires some workarounds I believe. The hook needs to be split into better primitives to work properly with non-floating element contexts.
