### ISSUE TITLE
Unable to Use Right Arrow Key to Open Submenus in Nested Dropdown Menu when virtual is set to true in useListNavigation

### ISSUE THREAD

**Issue by dwzkit** [floating-ui/floating-ui#2500]
**Describe the bug**
I'm building a dropdown menu based on the [official floating-ui DropDown example](https://floating-ui.com/). In my implementation, I modified the original Button to a TextInput element at the root level and set `useListNavigation` with `virtual: !isNested`. I've also set uuid id values.

While I can normally navigate through the root level menu items with the up and down arrow keys and maintain focus on the input, pressing the right arrow key on a menu item with submenus does not open the submenus. You can find the project code at [this sandbox](https://codesandbox.io/p/sandbox/jovial-mountain-89mzvx?file=/app/page.tsx).

- Are there any known solutions or workarounds for this issue?
- Can you provide guidance on properly handling keyboard navigation for submenus?

**To Reproduce**

You can find the project code at [this sandbox](https://codesandbox.io/p/sandbox/jovial-mountain-89mzvx?file=/app/page.tsx).

**Expected behavior**
Pressing the right arrow key should open the submenu items.The right arrow key does not open submenus when `virtual` is set to `true`.

**Screenshots**

**Context:**
 - OS: MacOS
 - Browser: Edge
 - Version: @floating-ui/react": "^0.25.1",

**Additional context**

**Comment by dwzkit** [comment]
Currently, my solution is to set virtual back to false and then handle this by focusing the input when a non-directional keydown event is detected. However, I find this solution to be inelegant:
```
// Determine if "hover" logic can run based on the modality of input. This
// prevents unwanted focus synchronization as menus open and close with
// keyboard navigation and the cursor is resting on the menu.
useEffect(() => {
  function onPointerMove(event: PointerEvent) {
    if (event.pointerType !== "touch") {
      setAllowHover(true);
    }
  }

  function onKeyDown(e: any) {
    setAllowHover(false);
    if (!isNested) {
      if (
        e.key !== "ArrowDown" &&
        e.key !== "ArrowUp" &&
        e.key !== "ArrowLeft" &&
        e.key !== "ArrowRight"
      ) {
        inputRef?.current?.focus();
      }
    }
  }

  window.addEventListener("pointermove", onPointerMove, {
    once: true,
    capture: true,
  });
  window.addEventListener("keydown", onKeyDown, true);
  return () => {
    window.removeEventListener("pointermove", onPointerMove, {
      capture: true,
    });
    window.removeEventListener("keydown", onKeyDown, true);
  };
}, [allowHover]);

const { isMounted, styles } = useTransitionStyles(context, {
  duration: { open: 100 },
});

const inputRef = useRef<HTMLInputElement>(null);
const referenceRef = useMergeRefs([
  refs.setReference,
  forwardedRef as any,
  inputRef,
]);

```

**Comment by atomiks** [comment]
Not sure of the best way to handle this. 

It's correct that the reference only captures the `keydown` event when it has focus as expected, so in this case it doesn't open the menu since it doesn't capture any events.

In this case, the root input reference needs to handle the event for the nested references. Doing this in a fully general way might be difficult.

Utilizing `FloatingTree` for the communication of parent<->child floating elements will likely work. If the root detects `ArrowRight` for example, then it should emit an event that the nested child can listen to and if it matches the `activeId`, then it opens its menu.

**Comment by dwzkit** [comment]
> 
Certainly! Here's the English translation of your response:

Thank you for your answer. I will try to use the FloatingTree communication mechanism to see if I can achieve the effect you described. I'm a beginner with floating-ui, so many concepts and working principles are new to me. Trying to use the communication mechanism to achieve the corresponding effect may present a significant challenge for me. Since the work progress is a bit rushed, I will temporarily proceed with the project using the "fake cursor" solution for now. If you could integrate the nested menu scenario into a standardized, general solution, that would be fantastic! Thank you for the answer.

**Comment by atomiks** [comment]
I went ahead and implemented what I said above, and it partially works. The major issue it has is that the root reference also needs to handle the main navigation keys (`ArrowUp` / `ArrowDown`) while the virtual cursor is inside the nested floating element - unless you have a new search input inside of the nested floating element to create a new "scope".

As you said, it's something that needs to be properly integrated into the library. Either that, or the library is missing the right primitives necessary to do this externally yourself

**Comment by dwzkit** [comment]
> I went ahead and implemented what I said above, and it partially works. The major issue it has is that the root reference also needs to handle the main navigation keys (`ArrowUp` / `ArrowDown`) while the virtual cursor is inside the nested floating element - unless you have a new search input inside of the nested floating element to create a new "scope".
> 
> As you said, it's something that needs to be properly integrated into the library. Either that, or the library is missing the right primitives necessary to do this externally yourself

Thank you very much for your explanation! What I am working on now is the development of an interaction feature similar to Notion Ai. In my view, Notion Ai is a combination of an Input and DropDown multi-level menu. Its characteristic is that the focus always remains on the Input box, and through cursor hovering or the use of keyboard arrows, you can conveniently operate the DropDown menu items, including selecting a menu, opening a submenu, hiding a submenu, etc. However, when you need to input content, you don't need to restore the input focus with the mouse first; you can directly input, and the DropDown menu will automatically disappear when inputting content in the input box. Initially, I didn't use any DropDown components but developed a set myself. However, I only implemented a single-level menu effect. When I needed to create embedded, deeper-level menus, I realized that this was a very complex and specialized development task, so I started looking for more suitable solutions.

<img width="914" alt="image" src="https://github.com/floating-ui/floating-ui/assets/41875799/522b5017-c963-46d3-9b1f-152ee3aa3f7e">
