### ISSUE TITLE
Export the unwrapElement helper as public API

### ISSUE THREAD

**Issue by jsnajdr** [floating-ui/floating-ui#2501]
The `ReferenceType` and `VirtualElement` types are part of Floating UI's public API, the `useFloating` hook both receives and returns virtual elements (`refs.setReference` etc.). Sometimes user code wants to do some work on these elements, too, and it would be nice if the `unwrapElement` helper was available. For extracting a native DOM element from the `ReferenceType` value, no matter if it contains a virtual or a native element.

I can submit a PR if there is agreement that this is a good idea.

**Comment by atomiks** [comment]
`refs.domReference.current` contains the DOM element (`refs.setPositionReference` sets `refs.reference.current` while the element `ref={}` prop sets the former), so not sure if this is necessary

**Comment by jsnajdr** [comment]
I didn't know that `refs.setPositionReference` exists. If I'm passing a `VirtualElement` as reference, should I prefer `refs.setPositionReference` over `refs.setReference`? The docs talk about distinction between "events" and "position" references, and I don't understand that.

`refs.domReference` is never set when the element is virtual, right?

Anyway, our use case was to extract the element's `ownerDocument`, either as `node.ownerDocument` or `node.contextElement.ownerDocument`. And the entire reason why we need to do that is work around #2518. I.e., to get the `ownerDocument.defaultView.frameElement`, find its scrolling ancestor, and attach `resize` and `scroll` listeners manually.

Once #2518 is fixed, all that will happen automatically, we can remove our custom code and this issue is no longer relevant.
