### ISSUE TITLE
Incorrect flip / hide behavior when the clipping ancestor is across a shadow-dom boundary

### ISSUE THREAD

**Issue by NullVoxPopuli** [floating-ui/floating-ui#2503]
**Describe the bug**

The floating element did not flip to the bottom of the reference when I expected

**To Reproduce**

1. Go to https://stackblitz.com/edit/web-platform-vl6nps?file=index.html (codesandbox has a ton of cache issues, it kept serving me old copies of my demo, so... stackblitz solves that (just don't use Safari, I guess -- only Chrome and FireFox are supported))
2. wait for the HTML to render
3. Scroll down until you see the outlined div with non-latin words in it.
4. keep scrolling until the outlined div goes up out of sight, and notice that the tooltip doesn't flip soon enough

**Expected behavior**

the `flip` middleware can find clipping ancestors across a shadow-boundary

**Screenshots**

![image](https://github.com/floating-ui/floating-ui/assets/199018/824a98d8-a3fe-4b97-a444-4df39537eeae)

![image](https://github.com/floating-ui/floating-ui/assets/199018/e2909ac3-5007-45e7-8a3e-a215af17329a)

What's goofy is that there is about `padding`px of correct behavior, just before the reference is moved entirely out of the viewable area
![image](https://github.com/floating-ui/floating-ui/assets/199018/4904e119-c1c0-4e64-9c0b-dbd11265c84d)

**Context:**
 - OS: Ubuntu
 - Browser: FireFox, Chrome
 - Version: floating-ui/dom@1.5.1

**Comment by NullVoxPopuli** [comment]
adding `elementContext: 'reference'` seems to resolve this issue (and removing it from the config re-reproduces the issue).

Is this expected?

**Comment by atomiks** [comment]
This is expected - the floating element only flips with respect to its own clipping boundary. Since it can appear outside of the scrolling container it won't try to avoid it. `elementContext: 'reference'` makes it use the reference's clipping context instead.
