### ISSUE TITLE
FloatingOverlay locksScroll problem if useTransitionStyles used to mount component

### ISSUE THREAD

**Issue by JuozasIzi1** [floating-ui/floating-ui#2504]
**Describe the bug**
FloatingOverlay locksScroll problem if useTransition used to mount upper component, and if I want to to close modal and right away open confirmation modal it will not locksroll on next modal. Next modal opens faster than previuos unmount, and lockSroll is removed by previous modal unmount.

```
  const { styles: backdropTransitionStyles, isMounted } = useTransitionStyles(context, {
    initial: transitionStyles[variant].backdrop,
    duration: variantTransitionDelays[variant].backdrop,
  });
```

```
    isMounted && (
      <FloatingPortal>
        <FloatingOverlay style={backdropTransitionStyles} lockScroll>
...
```

To repoduce:
bing onClose callabck with open another component. that onclose closes and open another component.

Possbile fix:
Some context provider of group of the floating modals?

Codesandbox example: https://codesandbox.io/s/lucid-grothendieck-zl8r6h?file=/src/App.tsx

**Comment by JuozasIzi1** [comment]
modal usage for example 
      <CombinePackagesModal
        isOpen={isOpen}
        packages={packages}
        pricePerPackage={pricePerPackage}
        onClose={() => setIsOpen(false)}
        onSave={myOrdersApi.consolidate}
        onConfirmationOpen={() => setIsConfirmationOpen(true)}
        titleTextKey="MyPackages.ConsolidateModal.Title"
        subtitleKey="MyPackages.ConsolidateModal.Subtitle"
        agreementTextKey="MyPackages.ConsolidateModal.Agreement"
        expressProcessingPrices={expressProcessingPrices}
        expressProcessingEnabled={true}
      />
      <CombinePackagesConfirmationModal isOpen={isConfirmationOpen} onClose={onConfirmationClose} />

**Comment by atomiks** [comment]
I think there needs to be a global set or map that holds currently mounted components and only removes the lock once there are none left mounted. That is similar to how the `aria-hidden` package works.

**Comment by JuozasIzi1** [comment]
@atomiks This PR loses paddingRight for body (compensation for scrollbar) if second modal activated right away after close
https://github.com/floating-ui/floating-ui/pull/2508

**Comment by atomiks** [comment]
Actually I think I might know why - it's because it's applying a `0` `paddingRight` (instead of removing it) since that's what's being measured due to there being no scrollbar from the previous lock.
