### ISSUE TITLE
Floating element doesn't trap focus if reference is a combobox

### ISSUE THREAD

**Issue by ariross-ef** [floating-ui/floating-ui#2505]
**Describe the bug**
When an input element has a `role="combobox"` with a dialog popup, the focus will not remain inside the floating dialog element when tabbing through.

I would like to be able to create a date picker combobox according to the [APG WCAG example](https://www.w3.org/WAI/ARIA/apg/patterns/combobox/examples/combobox-datepicker/) by allowing for an input to have a combobox role as well as keeping focus within the dropdown calendar component when a user enters into it.

**To Reproduce**

1. Go to https://codesandbox.io/s/floating-ui-react-dom-template-forked-3gmcqf
2. Click on the input field
3. Tab through dialog
4. See focus leave dialog instead of keeping focus trapped

**Expected behavior**
Once focus is inside the dialog, focus should remain inside until outside click or escape key is pressed.  Tabbing should cycle through the dialog and not be able to leave

**Additional Notes**
jest-axe tests fail because aria-expanded is placed on the input, but if input doesn't have a `role="combobox"`, then aria-expanded isn't valid

**Comment by atomiks** [comment]
You are right that `combobox`es have special handling in `modal` mode, and this particular scenario is not taken into account.

I think a prop on `FloatingFocusManager` is necessary to be able to distinguish between different types of comboboxes. In this case the floating element is a dialog with tabbable elements unlike a `listbox` for example.
