### ISSUE TITLE
@floating-ui+utils@0.1.1 annotation is necessary.

### ISSUE THREAD

**Issue by productdevbook** [floating-ui/floating-ui#2507]
**Describe the bug**
vue version used this problem

```
      src/tooltipContent.ts(76,14): error TS2742: The inferred type of 'OkuTooltipContent' cannot be named without a reference to '.pnpm/@floating-ui+utils@0.1.1/node_modules/@floating-ui/utils'. This is likely not portable. A type annotation is necessary.
 ```

**Screenshots**
![image](https://github.com/floating-ui/floating-ui/assets/38668796/30b8c376-d629-4d01-a852-31bb564dc7f7)

i used pnpm node 18.
It looks like it has an external problem.

**Comment by atomiks** [comment]
I don't understand this issue as you haven't given much context. It looks like a pnpm installation issue and possible version mismatches. Can you try uninstalling all Floating UI packages, and then re-installing them correctly?

**Comment by productdevbook** [comment]
```
import { defineConfig } from 'tsup'
import pkg from './package.json'

const external = [
  ...Object.keys(pkg.dependencies || {}),
  ...Object.keys(pkg.peerDependencies || {}),
  '@floating-ui/vue',
]

export default defineConfig((options) => {
  return [
    {
      ...options,
      entryPoints: ['src/index.ts'],
      external,
      dts: true,
      clean: true,
      target: 'node16',
      format: ['esm'],
      outExtension: () => ({ js: '.mjs' }),
    },
  ]
})

```

Actually, the problem occurs when I'm building a library and using what I've done elsewhere.

**Comment by productdevbook** [comment]
pnpm i node_modules in problem this library

<img width="434" alt="CleanShot 2023-08-27 at 22 29 31@2x" src="https://github.com/floating-ui/floating-ui/assets/38668796/8e356aa8-45d3-437b-8905-473164e5733a">

**Comment by productdevbook** [comment]
I guess this happens on workspace pnpm domains. I solved it this way. https://github.com/oku-ui/primitives/pull/335.

Thank you back.
