### ISSUE TITLE
Types fail with strict package managers

### ISSUE THREAD

**Issue by Methuselah96** [floating-ui/floating-ui#2512]
**Describe the bug**

The type declarations for `@floating-ui/react-dom` contain a dependency on `@floating-ui/core` despite not having a dependency on `@floating-ui/core`.

**To Reproduce**

1. Create a TypeScript project using `@floating-ui/react-dom` with a strict package manager like Yarn PnP with `skipLibCheck` set to `false`.
2. Run `tsc`.
3. Observe type error:

```
ERROR in node_modules/@floating-ui/react-dom/src/arrow.d.ts:1:42
TS2307: Cannot find module '@floating-ui/core' or its corresponding type declarations.
  > 1 | import type { Middleware, Padding } from '@floating-ui/core';
      |                                          ^^^^^^^^^^^^^^^^^^^
    2 | import { MiddlewareState } from '@floating-ui/dom';
    3 | import * as React from 'react';
    4 | export interface Options {
```

**Expected behavior**

No type errors.

**Screenshots**

**Context:**

**Additional context**

**Comment by atomiks** [comment]
Changing that import to `@floating-ui/dom` will work correctly.

**Comment by Methuselah96** [comment]
I considered opening a PR with that change, but It looked like the `Middleware` type exported from `@floating-ui/dom` was slightly different than the one exported from `@floating-ui/core` and I hadn't taken time to understand the difference. I'll go ahead and create a PR with this change if that doesn't seem like a concern.
