### ISSUE TITLE
useTypeahead blocking input for text fields

### ISSUE THREAD

**Issue by ChrisCoastal** [floating-ui/floating-ui#2514]
**Describe the bug**
When useTypeahead is wrapping an `<input>` or other field expecting user keydown events, the field will not receive the event (ie: text within the field will not update).

**To Reproduce**

Steps to reproduce the behaviour:
This demo is pulled from the [FloatingList](https://codesandbox.io/s/floating-ui-react-select-with-composable-children-qsuw76?file=/src/App.tsx) example
1. Go to [https://codesandbox.io/s/floating-ui-react-typeahead-input-xrdyqr?file=/src/App.tsx](https://codesandbox.io/s/floating-ui-react-typeahead-input-xrdyqr?file=/src/App.tsx)
2. Click on 'Select....' button
3. Click on an `<input>` from the dropdown menu
4. enter text (keyboard event)
5. See error (no text appears in input field; typeahead will focus other elements if matched)

**Expected behaviour**
The expectation is for the user to be able to type text into an controlled or uncontrolled`<input>` contained within a `FloatingList` component.

**Context:**
 - OS: Mac OS
 - Browser Chrome
 - Version [116]

**Additional context**
I believe this bug is due to `useTypeahead` stopping propagation of the keydown event.
Maybe a solution could be an exception for `useTypeahead`'s current behaviour when an `<input>` has focus. Or there could be some other sort of check that allows the event to propagate.

Please let me know if there is a preferred fix and I am happy to work on the issue.

**Comment by atomiks** [comment]
The hook (perhaps counterintuitively) isn't designed to be used with input fields aka comboboxes, only menu buttons. It's not meant to be used with something that can be typed into/filtered etc.

**Comment by atomiks** [comment]
Yes, as you can't tab through list items in native menus. They only have 1 tab stop.

**Comment by patrickjtoy** [comment]
@ChrisCoastal As someone who is currently developing on top of flowbite-react and who also came across this issue, I "solved" it like so:

```typescript
...
const allowedKeys = ["ArrowDown", "ArrowUp", "Enter"];

<input
  onKeyDown={(event) => {
    if (allowedKeys.includes(event.key)) {
      return;
    }

    event.stopPropagation();
  }}
/>
...
```

This allows for a "filtering" input to exist in the list, but it isn't perfect, i.e. the `useListNavigation` doesn't allow for keyboard navigation into the input, so there are definitely accessibility concerns in that regard. I'd love to hear if you find another workaround or if @atomiks and floating-ui would consider supporting combobox-style functionality in the future.

**Comment by atomiks** [comment]
@patrickjtoy do you mean something like this:

<img width="258" alt="Screenshot 2023-09-04 at 8 11 59 pm" src="https://github.com/floating-ui/floating-ui/assets/22450188/0602c3a3-bb9c-44d2-9df5-dca285052037">

This should be a regular dialog with a combobox input and a "non-floating" listbox inside it. `useTypeahead` wouldn't be used in this scenario.
