### ISSUE TITLE
[Vue]: Feature request for useClick hooks

### ISSUE THREAD

**Issue by filipbekic01** [floating-ui/floating-ui#2515]
I want to be able to open and close my dropdown using floating-ui original hooks.

Can't import useClick from npm package. Am I missing something or feature is not implemented yet?

Cheers

**Comment by atomiks** [comment]
The Vue package currently has no interaction composables as it's only a positioning wrapper. 

There's already an existing issue tracked here though: https://github.com/floating-ui/floating-ui/issues/2455
