### ISSUE TITLE
Runtime error for getElementRects function

### ISSUE THREAD

**Issue by tylerjlawson** [floating-ui/floating-ui#2520]
https://github.com/floating-ui/floating-ui/blob/698c2fa7dc9e9a9356f9ba2974dea86f42410c7e/packages/dom/src/platform/getElementRects.ts#L5

This line of code, when built in our nextjs app is resulting in the following runtime error:

<img width="958" alt="image" src="https://github.com/floating-ui/floating-ui/assets/26290074/b64d8f4e-95cf-481d-a7f1-a4e0a6409c87">

If I change the code to the following, the error goes away and seems to work as expected:

<img width="791" alt="image" src="https://github.com/floating-ui/floating-ui/assets/26290074/fe7165e2-b357-4331-8f76-efdcdeb7ddb2">

Questions:

1. Does anyone know why this error would be showing or why the fix works?
2. If changing the function definition is the best solution, would y'all accept a PR to change it?

Edit: It seems worth noting that this works in one of our nextjs apps, but not a different one and I am unsure of what the key difference would be here.

**Comment by atomiks** [comment]
It's a bug with SWC or the build system not this library, try upgrading the packages
