### ISSUE TITLE
[react] `useFocus` doesn't work with `elements.reference`

### ISSUE THREAD

**Issue by mayank99** [floating-ui/floating-ui#2521]
**Describe the bug**

When using `elements.reference`, `useHover` works fine but `useFocus` doesn't.

**To Reproduce**

1. Go to https://codesandbox.io/s/floating-ui-react-dom-template-forked-38qgfm?file=/src/App.js
2. Hover the button (using mouse) to see the tooltip
3. Focus the button (using keyboard) to see no tooltip

**Expected behavior**

Tooltip should appear on focus.

**Screenshots**

N/A

**Context:**
 - OS: macOS
 - Browser Firefox / Chrome
 - Version ?

**Additional context**

I'm not spreading `getReferenceProps` over the reference element, because the whole point of using `elements.reference` is to use it with ["external elements"](https://floating-ui.com/docs/react#external-elements) that I don't have access to. Moreover, `useHover` works without spreading the reference props, which makes me believe this is indeed a bug in `useFocus`.

**Comment by atomiks** [comment]
`useFocus` uses React's event handler props while `useHover` doesn't and only because of a bug with disabled elements due to the bubbling events they use.

Regarding external elements and the prop getters: https://github.com/floating-ui/floating-ui/issues/2128

**Comment by mayank99** [comment]
thanks for the response. could you say more about the bug with disabled elements? i try to use `aria-disabled` over `disabled` so that bug might not apply in my case

**Comment by atomiks** [comment]
Yeah with `aria-disabled` the bug doesn't exist, but it's the `mouseover`/`mouseout` events not firing correctly if there are disabled elements next to the hovered element compared to `mouseenter`/`mouseleave`
