### ISSUE TITLE
Floating elements wobble around reference during scrolling on mobile devices, even with animationFrame: true

### ISSUE THREAD

**Issue by Slapbox** [floating-ui/floating-ui#2530]
**Describe the bug**
Floating elements transiently detach from their reference elements on mobile devices, perhaps due to smooth scrolling. It does not seem to be related to a CPU bottleneck.

I also tried `strategy: 'fixed'` with no change in the issue.

**To Reproduce**

1. Copy the repro code below to a file on your computer
2. Use something like `http-server` to host it and access it via your mobile device. The issue is not readily apparent in emulators
3. Scroll to find the red/blue elements. Drag up and down quickly to scroll the page and note the wobble between the two

Repro code:

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Floating UI Demo</title>
  <script src="https://unpkg.com/@floating-ui/core"></script>
  <script src="https://unpkg.com/@floating-ui/dom"></script>
  <style>
    body, html {
      position: absolute;
      inset: 0;
      overflow: hidden;
    }
    .reference-element {
      width: 300px;
      height: 300px;
      background-color: red;
      margin-top: 40vh;
      margin-left: 40vw;
      margin-bottom: 200vh;
    }
    .floating-element {
      width: 150px;
      height: 150px;
      background-color: blue;
      position: absolute;
    }
    #wrapper {
      overflow: scroll;
      height: 2000px;
    }
    #portalRoot {
      position: absolute;
      inset: 0;
      pointer-events: none;
    }
  </style>
</head>
<body>
  <div id="portalRoot"></div>
  <div id="wrapper">
    <div class="reference-element"></div>
  </div>
  <script>
    const { computePosition, autoUpdate } = FloatingUIDOM;

    const referenceElement = document.querySelector('.reference-element');

    const floatingElement = document.createElement('div');
    floatingElement.classList.add('floating-element');
    const portalRoot = document.querySelector('#portalRoot');
    portalRoot.appendChild(floatingElement);

    const updatePosition = () => {
      computePosition(referenceElement, floatingElement, {
        placement: 'top-end',
      }).then(({ x, y }) => {
        Object.assign(floatingElement.style, {
          left: `${x}px`,
          top: `${y}px`,
        });
      });
    };

    // Initial position
    updatePosition();

    // Auto-update position
    autoUpdate(referenceElement, floatingElement, updatePosition, {
      ancestorScroll: true,
      ancestorResize: true,
      elementResize: true,
      layoutShift: true,
      animationFrame: true,
    });
  </script>
</body>
</html>
```

**Expected behavior**
Floating element adheres to reference element as well as it does on desktop browsers in this demo case requiring minimal processing power

**Context:**
 - OS: Android and iOS
 - Browser Chrome and Safari
 - Version Chrome for Android 116

**Additional context**

**Comment by Slapbox** [comment]
I tried making this in CodeSandbox as per the template but it's not really usable because of styling issues that seem to be specific to CodeSandbox. https://codesandbox.io/s/adoring-currying-27q5jn?file=/src/index.mjs

**Comment by atomiks** [comment]
The Sandbox is using v1.2.5 when the latest is v1.5.1, which with `animationFrame: true` seems to keep it anchored smoothly in comparison better even on desktop Chrome.

Regardless though, mobile browsers trend to update element positions quite asynchronously during scrolling compared to desktop browsers, so there's nothing that this library can do. You can try converting the styles to use `transform` instead of `top`/`left`, layer acceleration, etc. But it's something I've seen occur with the most basic vanilla reproduction anyway.

**Comment by Slapbox** [comment]
Hmm weird that the sandbox didn't default to or even show the latest version. Unfortunately my local test did use the latest versions.

Thanks very much for the tips @atomiks , I'll give them a try.

I noticed this issue isn't apparent in any of the docs and I wonder what the reason for that might be? Is it that the containing portal is scrolling along with the page, masking these limitations?

I think it would be good if the docs demonstrated these limitations. If one examines the docs and expect that the floating element will adhere to the reference element based on what you've seen in them, one could end up rather disappointed in the results when they implement it in their project.

Fortunately for our case I see possible workarounds, but I would have saved quite a lot of time going down this road.

**Comment by atomiks** [comment]
Yes, the elements on the docs are inside the same scrolling container as the reference (just the body), so it doesn't need to continually update while scrolling to remain anchored, unlike the layout shown in the Sandbox.

That's not always possible in all situations, but click outside behavior on touch devices tends to hide it when scrolling so they don't see it anyway.

Overall, it's a hard limitation of certain browsers' rendering engines.
