### ISSUE TITLE
Request: Properties on `Modifier` type be made optional

### ISSUE THREAD

**Issue by sydneyjodon-wk** [floating-ui/floating-ui#2531]
Hello 👋 

**Is your feature request related to a problem? Please describe.**

I'm wondering if these properties on `Modifier` can be made optional instead of required?

- `fn`
- `enabled`
- `phase`

Based on examples in the docs, it seems like they shouldn't be required. Here's [another example](https://codesandbox.io/s/popper-example-modifier-type-v9hrjq?file=/Demo.tsx) where it doesn't seem like those properties are required to be set to use the Modifier type. Is there a reason they are set to required?

**Describe the solution you'd like**

I made a [PR to make these three properties optional](https://github.com/floating-ui/floating-ui/pull/2524) - I'm not sure why CI is failing

**Comment by atomiks** [comment]
Thank you for the PR and issue, but we're currently not accepting features or API changes to Popper any longer. Bug fixes are still welcome though.

**Comment by sydneyjodon-wk** [comment]
@atomiks thank you for the response! Just to make sure I'm understanding, would you say that those properties are supposed to be required then? 

We are getting warnings about needing to set all those properties whenever we create a Modifier. I understand that you're no longer working on Popper, but I want to make sure it's okay to ignore those warnings on our end or is it safer to set those properties?

**Comment by atomiks** [comment]
The properties need to be set for custom modifiers yes (can't remember that well though). Built-in ones like passing options don't need it, iirc

**Comment by sydneyjodon-wk** [comment]
Awesome! Thank you!
