### ISSUE TITLE
Keyboard Navigation with useListNavigation in floating-ui/react@0.25.4 Does Not Fully Support onKeydown Event

### ISSUE THREAD

**Issue by dwzkit** [floating-ui/floating-ui#2537]
**Describe the bug**
Keyboard navigation with useListNavigation in floating-ui/react@0.25.4 doesn't fully support onKeydown events for the Enter key, while using a virtualized list (virtual=true).

I'm using the latest version of floating-ui/react@0.25.4 and testing keyboard navigation with the useListNavigation hook in a virtualized list (virtual=true). My goal is to execute corresponding menu actions when the Enter key is pressed.

I noticed that the onClick event works as expected for the menu items, but the onKeydown event is only responsive to ArrowRight and ArrowLeft keys. Given that it's an onKeydown event, my expectation is that it should listen to all keyboard keys. Specifically, when the Enter key is pressed, I would like to trigger subsequent actions by emitting an event like tree?.events.emit("onKeyDown").

Is this behavior intended, or is it a bug? Would appreciate any guidance on how to achieve my intended functionality.

**To Reproduce**

1. Implement useListNavigation with virtual=true based on the official DropDown example.
2. Use keyboard navigation to select a menu item.
3. Press the Enter key.
4. Observe that onClick works but onKeydown only responds to ArrowRight and ArrowLeft keys.

**Expected behavior**
The onKeydown event should be capable of listening to all keyboard keys. When the Enter key is pressed, subsequent actions should be triggered, potentially using tree?.events.emit("onKeyDown").

**Screenshots**
<img width="1008" alt="image" src="https://github.com/floating-ui/floating-ui/assets/41875799/c81f2386-ad97-462f-a35b-7804cb0e05cb">

<img width="1322" alt="image" src="https://github.com/floating-ui/floating-ui/assets/41875799/b5971ffc-1753-4b43-9c25-8ba13580605d">

**Context:**
 - Version :floating-ui/react@0.25.4

**Additional context**
Given that it's an onKeydown event, it should ideally be capable of recognizing all keys on the keyboard, including the Enter key, to perform the expected actions.

**Comment by atomiks** [comment]
When the Enter key is pressed, you need to handle actions yourself. The `virtualItemRef.current` value determines which element was "clicked" virtually.

**Comment by dwzkit** [comment]
After capturing the Enter event with the following code, I dispatched a Click event, triggering the same process as the Click event. Thank you for your answer.

```
    useEffect(() => {
      !isNested &&
        document?.addEventListener('keydown', (event) => {
          if (event.key === 'Enter') {
            const e = new Event('click', {
              bubbles: true,
              cancelable: true,
            });
            virtualItemRef.current.dispatchEvent(e);
          }
        });
      return () => {
        !isNested &&
          document?.removeEventListener('keydown', (event) => {
            console.log('element keydown', event.key);
          });
      };
    }, []);
```
