### ISSUE TITLE
Your library is not usable from browser via importmap, cause relative imports are missing ".js" extensions.

### ISSUE THREAD

**Issue by jogibear9988** [floating-ui/floating-ui#2539]
I try to use your library direct from browser via import map, but it would not work cause your imports in lack the ".js" extension.

Your library is used by shoelace webcomponents, and these won't work cause of missing extensions.
Shoelace explicitely uses your "dom" library

Tinycolor had the same issue: https://github.com/scttcper/tinycolor/issues/239
And was fixed and merged: https://github.com/shoelace-style/shoelace/issues/1542

I'll try to use shoelace in my designer https://node-projects.github.io/web-component-designer-demo/index.html

**Comment by atomiks** [comment]
The dist files are bundled though so there are only bare imports from the utils and core packages - you're referring to `@floating-ui/dom` right?

**Comment by jogibear9988** [comment]
yes. look for example, in the file "floating-ui.dom.esm.js" in the npm package.
if you have a export like this 
     export { getOverflowAncestors } from '@floating-ui/utils/dom';
it should contain the .js extension

**Comment by jogibear9988** [comment]
at least if the package should be usable direct from browsers via importmaps

**Comment by jogibear9988** [comment]
stop....

your @floating-ui/utils has the exports correctly listed, so I need to fix that I parse them correctly. So I need to fix something.
I'll do this and take a look again

**Comment by atomiks** [comment]
The `dist/floating-ui.dom.browser.mjs` (and its `core` counterpart) has utils bundled in. But yes, the exports should be correctly listed. Going to close unless a reproduction shows otherwise.
