### ISSUE TITLE
Upgrade demos

### ISSUE THREAD

**Issue by R-Bower** [floating-ui/floating-ui#2540]
**Is your feature request related to a problem? Please describe.**
Not a problem, but `react-scripts` is no longer ideal for quickstarting a React application.  Most of the demos are still using `react-scripts`.  

**Describe the solution you'd like**
Switch to vite. 

**Describe alternatives you've considered**
Continue using react-scripts.  

**Additional context**
I can create a PR in the next week.

**Comment by atomiks** [comment]
Which demos? This repo doesn't use `react-scripts`

**Comment by R-Bower** [comment]
The codesandbox links are using react-scripts.  All of the links on this page:
https://floating-ui.com/docs/react-examples

**Comment by atomiks** [comment]
That was just the default CodeSandbox templates at the time, and I kind of prefer it over the new templates anyway which seem to take a long time to load in comparison.
