### ISSUE TITLE
Vue useFloating cannot return middlewareData

### ISSUE THREAD

**Issue by hyu1982** [floating-ui/floating-ui#2546]
**Describe the bug**
Trying to return the middlewareData from floating-ui@vue returns nothing using useFloating

**To Reproduce**

```
<script setup lang="ts">
import { ref, onMounted } from 'vue';
import { offset, useFloating, flip, shift, arrow } from '@floating-ui/vue';

const referenceRef = ref(null);
const tooltipRef = ref(null);
const floatingArrow = ref(null);

const middleware = ref([offset(6), flip(), shift({padding: 3}), arrow({element: floatingArrow})]);
const { x, y, strategy, middlewareData } = useFloating(referenceRef, tooltipRef, {
  placement: 'bottom',
  middleware: middleware
});

onMounted(()=>{
    console.log(middlewareData);
    console.log(middlewareData.value);
    console.log(strategy.value);   
});
</script>
<template>
    <div  ref="referenceRef">
        Button
        </div>
        
        <div class="rounded-2"
            ref="tooltipRef" >
        
            this is a tooltip
            
            <div ref="floatingArrow" class="arrow"><i class="bi bi-caret-down-fill"></i></div>
        </div>
</template>
<style scoped>
.arrow{
    position: absolute;
    color: blueviolet;
}
</style>
```

1. Copy the code into any vue file and run it. The console will show nothing is returned using .value but not outputting the .value will show the _value inside it.

**Expected behavior**
It should return precisely the middleware data so the arrow key can be positioned. Currently it is returning {}

**Screenshots**
attached screenshot
![vue floating-ui bug](https://github.com/floating-ui/floating-ui/assets/1110947/0c0e7dd1-c092-4486-be75-2d450566928f)

**Comment by atomiks** [comment]
If you add `setTimeout()` around the access to `middlewareData.value`, is the object no longer empty?
