### ISSUE TITLE
floatingStyles are missing

### ISSUE THREAD

**Issue by alisher-aituarov** [floating-ui/floating-ui#2548]
**Describe the bug**
`floatingSltyes` field is not marked as optional in `UseFloatingReturn` but is missing in the return of `useFloating` return. 

**To Reproduce**

**Expected behavior**
My tooltip is not showing up because of this field's absence

**Context:**
 - OS: macos
 - Browser chrome
 - Version @floating-ui/react": "^0.25.4",

**Additional context**
removing argument passed to `useFloating` does not change anything

**Comment by alisher-aituarov** [comment]
@jpzwarte @arya @alexdilley @piecyk

**Comment by behindthedrapery** [comment]
ebat huinya

**Comment by paulvales** [comment]
![image](https://github.com/floating-ui/floating-ui/assets/13873237/6eb2aedc-d399-4573-9618-9cbea6dfda5c)

**Comment by rawork** [comment]
Seems like there is a bug in the library

**Comment by behindthedrapery** [comment]
![image](https://github.com/floating-ui/floating-ui/assets/64159962/3c14e931-a089-4009-9dc1-5100b6b9c13a)

**Comment by mrwbdv** [comment]
it is a definetely buggy library and has nothing to do with your code

**Comment by atomiks** [comment]
Make sure the version of `@floating-ui/react` that you have installed is actually `0.25.4` as you listed, and not an earlier version (<=`0.23.x`) where the `floatingStyles` property did not yet exist.  

There are countless CodeSandbox demos where the property exists and works, so clearly something in your setup is wrong.

**Comment by alisher-aituarov** [comment]
@atomiks i managed to get floatingStyles from hook, but tooltip does not render for some reason, maybe something is wrong with lib after all ?

**Comment by atomiks** [comment]
"For some reason" is not useful for us to help you; if you aren't going to post a reproduction demonstrating where something is broken here then I will have to close this issue.
