### ISSUE TITLE
popperJs/core

### ISSUE THREAD

**Issue by MKhasib** [floating-ui/floating-ui#2550]
**Describe the bug**
Popper top placement doesn’t get positioned correctly on Zoom 130% and decreasing Zoom down to 80% makes it work

**To Reproduce**
I am just using this code with ^2.11.2 version
  document.body.appendChild(this.popper.parentElement);
   this.popperJS = createPopper(
        this.referenceElm,
        this.popper,
        this.popperOptions,
      );

**Expected behavior**
popper should show as strictly close to the target

**Screenshots**
80% zoom works good
![Screenshot 2023-09-14 at 4 34 26](https://github.com/floating-ui/floating-ui/assets/57562096/b126fa6f-96be-438b-b589-204facf7cc8a)
130% zoom doesn't
![Screenshot 2023-09-14 at 4 31 23](https://github.com/floating-ui/floating-ui/assets/57562096/7d9149eb-4474-40cc-a5df-a6c89d7cb0fa)

**Context:**
all browsers

**Comment by atomiks** [comment]
We have now released [Floating UI v1](https://floating-ui.com/docs/motivation), the successor to Popper.

Don't worry, Popper 2 will **continue to receive new releases** with bug/security fixes provided by external contributors, but development of new features is not continuing at this point. We are also closing bugs related to it as us maintainers are focusing our energy on tracking issues with Floating UI, however you are welcome to create new pull requests to fix bugs in Popper, which we will review and merge, as many packages (such as MUI, Bootstrap, etc) still rely on it. 

Thanks!

**Comment by MKhasib** [comment]
In case someone needed some advice here
The problem was this makes the container off the screen causing the position to be shifted
document.body.appendChild(this.popper.parentElement);

The solution I went for is to set it as absoulate positioned to keep it inside the visible area of the screen

Thanks!
