### ISSUE TITLE
[React] Missing type for "refs.reference"

### ISSUE THREAD

**Issue by c0dester** [floating-ui/floating-ui#2565]
**Describe the bug**
I'm not sure if it's bug or desired behaviour. I've noticed that refs.reference is not using generic type passed to useFloating. That generic is being used only in setReference function. At the first glance it looks like refs.reference should also use generic. If setReference sets given generic, I expect, that refs.reference will be that generic's type

**To Reproduce**
Just take a look at [this line of code](https://github.com/floating-ui/floating-ui/blob/master/packages/react/src/types.ts#L93)

**Expected behavior**
Generic probably should be passed to refs.reference

**Context:**
None

**Additional context**
None

**Comment by atomiks** [comment]
This is expected as the generic type narrowing is applied to `refs.domReference` instead, as `refs.reference.current` can be a virtual element after using `refs.setPositionReference`.

**Comment by c0dester** [comment]
Thanks for clarification. The naming is a bit confusing, since setReference sounds like should be connected with reference, and setPositionReference should have positionReference counterpart. May be considered changing this in the future :). Thanks for now

**Comment by atomiks** [comment]
It's due it being better in terms of defaults (the reference by default is both the "events" and "position" reference together) and the fact that `@floating-ui/react` is a compatible superset of `@floating-ui/react-dom`, which only deals with positioning.

```js
// In both react-dom and react packages, this sets the position reference.
// In the latter it *also* sets the DOM reference.
<div ref={refs.setReference} />

// You can see why this would start to become a problem, and why the
// library does it the way it currently does.
<div ref={refs.setDOMReference />
```
