### ISSUE TITLE
External Elements useFloating 'elements does not exist'

### ISSUE THREAD

**Issue by Jack-Hewson9** [floating-ui/floating-ui#2567]
**Describe the bug**
[Following this guide](https://floating-ui.com/docs/react#external-elements)

I am receiving the error 

Argument of type '{ elements: { reference: Element; }; }' is not assignable to parameter of type 'Partial<UseFloatingProps<ReferenceType>>'.
  Object literal may only specify known properties, and 'elements' does not exist in type 'Partial<UseFloatingProps<ReferenceType>>'.

When I set `elements: { reference: anchor }`

I don't believe it's to do with what I'm setting the element but rather the attribute 'element' is not expected

**To Reproduce**
Follow the guide linked above

1. use setAnchor on the element you want as the anchor
2. on the component you want to be floating, use useFloating at include 'elements'
3. error

**Expected behavior**
Receives the reference element and uses it

**Screenshots**
![image](https://github.com/floating-ui/floating-ui/assets/141025260/ae9db500-446f-4838-97d7-bf9e31cfd023)

**Comment by atomiks** [comment]
You are on an old version, upgrade to the latest
