### ISSUE TITLE
Question: why visuallyHiddenDismiss renders 2 identical buttons?

### ISSUE THREAD

**Issue by smellai** [floating-ui/floating-ui#2570]
**Describe the bug**
Adding `visuallyHiddenDismiss` prop to `FloatingFocusManager` adds 2 close buttons to the DOM

![Screenshot 2023-09-22 alle 12 15 49](https://github.com/floating-ui/floating-ui/assets/1763268/45752deb-8a18-4aad-985f-e7158094f89c)

**To Reproduce**
https://codesandbox.io/s/zealous-cache-x83ncc?file=/src/App.tsx

**Expected behavior**
I would expect one button only?

**Comment by atomiks** [comment]
It offers a way to escape the floating element regardless of being located nearer the start or the end of a large floating element. (The start one isn't rendered for `combobox`es though.)

**Comment by smellai** [comment]
Thanks @atomiks ! is there any reference somewhere describing this pattern or you just found it works fine for users?

**Comment by atomiks** [comment]
`react-aria` does this and yes, it's fine for users and I tested it myself. It definitely increases accessibility by offering another way to escape the element to prevent being trapped.
