### ISSUE TITLE
Restrict useFocus to only elements that has `:focus-visible` pseudo class applied

### ISSUE THREAD

**Issue by okonet** [floating-ui/floating-ui#2574]
I'd like to make sure that the floating element is only triggered by elements that has [`:focus-visible`](https://developer.mozilla.org/en-US/docs/Web/CSS/:focus-visible) to provide a better UX for  keyboard and pointer users.

I would assume that in order to detect this, it would be sufficient to add a check

```javascript
event.target.matches(':focus-visible')
```

in this event listener:

https://github.com/floating-ui/floating-ui/blob/07d8e853c81925316bf712270f9533962bc19fda/packages/react/src/hooks/useFocus.ts#L106-L122

If that's correct, I could draft a PR to implement this. 

WDYT?

**Comment by atomiks** [comment]
Doesn't the `keyboardOnly` option achieve this?

**Comment by okonet** [comment]
Nope, since it treats the programmatic `.focus()` as a keyboard event. So when the focus returns to the element, it triggers the floating element to appear.

**Comment by atomiks** [comment]
Wonder if that should be changed then. Not sure of cases where the programmatic focus is necessary with that option.

**Comment by okonet** [comment]
By looking at the current code, I think the only way to actually change this is to follow my suggestion with an additional `.matches` check. This is the code that worked for me:

```diff
return {
      reference: {
-        onPointerDown({pointerType}) {
-          pointerTypeRef.current = pointerType;
-          blockFocusRef.current = !!(pointerType && keyboardOnly);
-        },
        onMouseLeave() {
          blockFocusRef.current = false;
        },
        onFocus(event) {
          if (blockFocusRef.current) {
            return;
          }

+          // Only trigger when `:focus-visible` is applied
+          const isFocusVisible = event.target.matches(':focus-visible');
+          if (!isFocusVisible && keyboardOnly) {
+            return;
+          }

          // Dismiss with click should ignore the subsequent `focus` trigger,
          // but only if the click originated inside the reference element.
          if (
            event.type === 'focus' &&
            dataRef.current.openEvent?.type === 'mousedown' &&
            isEventTargetWithin(dataRef.current.openEvent, domReference)
          ) {
            return;
          }

          onOpenChange(true, event.nativeEvent);
        },
```

**Comment by atomiks** [comment]
I have changed `keyboardOnly` option to `visibleOnly`. One problem is the `:focus-visible` selector is not broadly supported, especially older Safari, so I've added a fallback
