### ISSUE TITLE
Losing focus with `useFocus` not closing the floating element inside an iframe

### ISSUE THREAD

**Issue by okonet** [floating-ui/floating-ui#2575]
This actually breaks the `useFocus` inside an iframe. I just stumbled upon it while experimenting with #1717 in the Storybook.

_Originally posted by @okonet in https://github.com/floating-ui/floating-ui/pull/2560#discussion_r1335693237_

**Comment by okonet** [comment]
I took a liberty to move it here so it’s easier to keep the track of it and not release it accidentally.

**Comment by okonet** [comment]
I took a liberty to move it here so it’s easier to keep the track of it and not release it accidentally.

**Comment by atomiks** [comment]
Closing since it seems to be a better default to ignore blurring if there is no relatedTarget (https://github.com/floating-ui/floating-ui/pull/2560#discussion_r1338467824).

If necessary, the workaround is to add a blur listener to the iframe window and call `setIsOpen(false)`.

**Comment by okonet** [comment]
I thought the workaround will be added to the core. Currently it’s not possible to add any workarounds in storybook which is where it breaks.

**Comment by atomiks** [comment]
If this library can do it, then you can too. Just need to find the window that the reference element is in to attach the blur listener (`elements.domReference.ownerDocument.defaultView`).

**Comment by okonet** [comment]
I guess my point is: if the next release of the library will break every storybook, it will be quite annoying. That’s why I was suggesting to at least have an option to pick the behavior. Ideally, it could be handled auto-magically but I’m not sure it’s possible. Wdyt?

**Comment by atomiks** [comment]
The main issue is, should there even be an option given it seems to cause issues with some typical use cases based on Diego's comment? It just won't close when navigating outside the iframe, I don't think that's 'broken' necessarily

**Comment by okonet** [comment]
I think that both can be true. In case of storybook, for example, the focus moves out of the current document to the host document. The use cases we discussed were related to the focus moving out of the parent document to the browser chrome. Could the logic be applied to follow the focus outside the iframe and track it? So if there is another focused element in the parent document, the floating element should close. If no active element and the window has been reached, then it shouldn’t?

**Comment by atomiks** [comment]
Seems like traversing iframe documents works: https://github.com/floating-ui/floating-ui/pull/2583
