### ISSUE TITLE
Memlab reports memory leak when using react hooks in a web component

### ISSUE THREAD

**Issue by fedemp** [floating-ui/floating-ui#2576]
**Describe the bug**
I have a React app that renders a web components that renders a react component inside it. On user interaction, the web component is destroyed and the react component is unmounted.

I have tried [memlab](https://facebook.github.io/memlab/) and it reports a memory leak when using `refs.setReference` from `useFloating()`. It seems reference is not destroyed when the component is unmounted.

**To Reproduce**

I have created https://codesandbox.io/s/floating-ui-react-dom-template-forked-6jjm9g?file=/src/App.js so it's easier to check the code but to summarize the issue, suppose this web component.

```js
class MyWebComponent extends HTMLElement {
  root = null;
  connectedCallback() {
    const shadowRoot = this.attachShadow({ mode: "open" });
    const mountPoint = document.createElement("div");
    this.root = createRoot(mountPoint);

    shadowRoot.appendChild(mountPoint);

    this.root.render(<MyReactComponent />);
  }

  disconnectedCallback(): void {
    this.root.unmount();
  }
}
```

If `MyReactComponent` is defined using the `useRef` hook, memlab reports that everything is ok.

```jsx
function MyReactComponent() {
  const inputReference = useRef(null);
  return <input ref={inputReference} />;
}
```

But if use `useFloating`, memlab reports a memory leak.
```jsx
function MyReactComponent() {
  const {refs} = useFloating();
  return <input ref={refs.setReference} />;
}
```

Since you need to run memlab, I have created a repository with the same code mentioned above.

1. Clone https://github.com/fedemp/floatingweb
2. Install dependencies. `npm i`.
3. Start a server. `npm preview`.
4. Build the project `npm build`.
5. Run the good and bad scenarios. `npx memlab run -v --scenario sceneario.good.cjs` and `npx memlab run -v --scenario sceneario.bad.cjs`.

**Expected behavior**
No memory leaks reported by memlab.

**Screenshots**
![image](https://github.com/floating-ui/floating-ui/assets/735314/f648c7a3-f1e0-4274-94ca-904e21dd7ccd)

**Additional context**
You neeed Chrome/Chromium installed to run memlab and Puppeteer.

**Comment by atomiks** [comment]
Does it report a leak in this case?:

```js
function MyReactComponent() {
  const [el, setEl] = useState(null);
  return <input ref={setEl} />;
}
```

**Comment by atomiks** [comment]
I confirmed that the above case also reports a "leak" despite being a valid pattern to make refs reactive. 

So, I think it's either a false positive (in that it will get cleaned up eventually), potentially reporting wrong (since the state value gets set with `null` when unmounted), or some other problem with React itself. 

Going to close since it appears to be unrelated to the library.

**Comment by fedemp** [comment]
> Does it report a leak in this case?:
> 
> ```js
> function MyReactComponent() {
>   const [el, setEl] = useState(null);
>   return <input ref={setEl} />;
> }
> ```

Good catch. I will try reporting this to React. I guess using Web Components is not an usual use case, but maybe there's an explanation. Thanks for the help.
