### ISSUE TITLE
Can't bundle app using webpack and floating-ui as an peer dependency 

### ISSUE THREAD

**Issue by kazeens** [floating-ui/floating-ui#2580]
Here is the error

 error  in ./node_modules/@floating-ui/react-dom/dist/floating-ui.react-dom.esm.js

Module parse failed: Unexpected token (183:8)
You may need an appropriate loader to handle this file type.
|     computePosition(referenceRef.current, floatingRef.current, config).then(data => {
|       const fullData = {
|         ...data,
|         isPositioned: true
|       };

If you know the reason can be the reason I would be very appreciative of your help

I am using webpack and I have all loaders that process js

**Comment by atomiks** [comment]
This is likely a webpack 3 issue with the object spread operator. It's been 6 years since it's been a thing, please upgrade your webpack version or loaders to handle it.
