### ISSUE TITLE
Unnecessary logging in the browser console

### ISSUE THREAD

**Issue by Agnik7** [floating-ui/floating-ui#2585]
**Describe the bug**
Upon using the official website, the console gets filled with multiple "true" and "false" values.

**To Reproduce**

1. Open ['floating-ui.com'](https://floating-ui.com/) in Google Chrome.
2. Press `CTRL+Shift+i` in your keyboard to open the console.
3. You can see multiple true and false being displayed in the console.

**Expected behavior**
The console should be empty and such multiple true and false should not be displayed.

**Screenshots**
![Screenshot](https://github.com/floating-ui/floating-ui/assets/77234005/11af013b-204d-425c-900e-f3fd2dd4b1fe)

**Context:**
 - OS: Windows 10
 - Browser Chrome
 - Version 117.0.5938.132 (Official Build) (64-bit)

**Comment by atomiks** [comment]
Fixed by [3047c46](https://github.com/floating-ui/floating-ui/commit/3047c46be1562963fa8df8d69d2bb817e400757c)
