### ISSUE TITLE
[React] Find focusable children of reference if it's not focusable

### ISSUE THREAD

**Issue by atomiks** [floating-ui/floating-ui#2587]
**Describe the bug**
Focus management in the library expects the reference itself to be focusable in most cases, but if a wrapper is being used (or wrapping multiple focusable children) then logic will not work as expected.

**To Reproduce**
From https://github.com/floating-ui/floating-ui/discussions/2573

**Comment by AkshitGuptaIITR** [comment]
I'd like to work on this bug.

**Comment by mihkeleidast** [comment]
Then again, floating-ui also injects necessary aria props to the reference. How would those be forwarded to the focusable children? It feels like fixing this will make it "work" for only visual users, but the implementation will still be broken for assistive tech?

**Comment by atomiks** [comment]
I agree @mihkeleidast, I think this pattern is difficult to generalize. Going to close.
