### ISSUE TITLE
Focus returned from closing a dialog opens tooltip

### ISSUE THREAD

**Issue by hornta** [floating-ui/floating-ui#2591]
I have a button which has both a tooltip and dialog. Both the tooltip and dialog component are more or less copied from the reusable examples from the codesandbox in the documentation.

I understand why this happens because the tooltip is opened both onHover and onFocus and I still want this, but only if the focus "comes from" the user actively focusing it and not this programmatic return focus from the dialog. Is this possible to detect?

![3d37496e-adfd-44dc-8cfb-2ddb268c9e97](https://github.com/floating-ui/floating-ui/assets/4553604/23bd55dc-29fc-4b31-ab92-f295798ebf56)

I've modified `<Dialog>` to accept a render function as children so I can pass down the reference props to the button.
```jsx
<Dialog>
  <DialogTrigger asChild>
    {(props) => {
      return (
        <Tooltip2>
          <TooltipTrigger asChild>
            <button
              className="p-1 hover:bg-purple-25 rounded-full transition-colors"
              {...props}
            >
              <IconPlus className="text-purple-500" size={20} />
            </button>
          </TooltipTrigger>
          <TooltipContent>tooltip content</TooltipContent>
        </Tooltip2>
      );
    }}
  </DialogTrigger>
  <DialogContent>
    <DialogTitle>title</DialogTitle>
    <DialogBody>body</DialogBody>
    <DialogActions withCancelButton />
  </DialogContent>
</Dialog>
```

**Comment by atomiks** [comment]
I think this might be fixed in `v0.26.0`. It uses the `:focus-visible` selector by default (new `visibleOnly` option), and does not open on programmatic focus. If you're using the keyboard though then it will still show it.

**Comment by hornta** [comment]
I hoped so too seeing a similar issue like a week ago but unfortunately it didn't help. 

![ba7678bc-bbda-4ff5-9dc3-ca021b11a673](https://github.com/floating-ui/floating-ui/assets/4553604/e1ecd90d-61e8-4689-a854-3c1141b47319)

**Comment by atomiks** [comment]
> dialog was closed(using escape-key)

That's why. If you close it with a mouse it shouldn't happen?

**Comment by hornta** [comment]
Correct! Is what I'm wishing for unintuitive and/or goes against some accessibility practices(because that's not my intention)? It just feels weird having the tooltip open in this single case so, asking you that work a lot with this, what do you think is preferred?

**Comment by marcelorafaelfeil** [comment]
Hi,

I could work on this issue 😁

Could this issue be assigned to me?

**Comment by hornta** [comment]
> Hi,
> 
> I could work on this issue 😁
> 
> Could this issue be assigned to me?

I don't know if this behaviour is intentional or considered a bug. What do you have in mind?

**Comment by marcelorafaelfeil** [comment]
> > Hi,
> > 
> > I could work on this issue 😁
> > 
> > Could this issue be assigned to me?
> 
> I don't know if this behaviour is intentional or considered a bug. What do you have in mind?

In my point of view, the tooltip should only be displayed if the mouse is on the target, so if the mouse is not on the target, the tooltip should not be displayed.

**Comment by atomiks** [comment]
> Correct! Is what I'm wishing for unintuitive and/or goes against some accessibility practices(because that's not my intention)? It just feels weird having the tooltip open in this single case so, asking you that work a lot with this, what do you think is preferred?

I believe as soon as you start using keyboard modality, `:focus-visible` is triggered and so tooltips should begin showing. Of course, you can manually workaround this by disabling the `useFocus` hook using state conditionally when you want. I'll close this as workaroundable.
