### ISSUE TITLE
size: middlewareData is not populated with availableWidth/Height

### ISSUE THREAD

**Issue by okonet** [floating-ui/floating-ui#2592]
**Is your feature request related to a problem? Please describe.**

I'd like to use `middlewareData` from the `size` middleware in one of our components in React. Currently, its not possible since `middlewareData` is always empty.

**Describe the solution you'd like**
It would be great if besides the `apply` function I could get access to `middlewareData` after it's rendered.

**Describe alternatives you've considered**
I tried creating my own middleware that would call `size` inside the `fn()` but that doesn't seem to work.

**Comment by qayyum22** [comment]
@okonet can you please describe how to reproduce this issue and i would like to work on it .

**Comment by atomiks** [comment]
You can write the values to a ref or state and use that instead. `available{Height,Width}` are not returned in data, since they can't be applied after the lifecycle is finished right now.
