### ISSUE TITLE
useHover does not work for different element than ref

### ISSUE THREAD

**Issue by rijk** [floating-ui/floating-ui#2593]
**Describe the bug**
In my app, I have a clickable/hoverable area that is bigger than the reference point for the floating element. I always want that docked to the top right corner of the area, like this:

<img width="460" alt="image" src="https://github.com/floating-ui/floating-ui/assets/159500/316dee4d-fe92-4231-a66f-08670ebfa913">

<img width="397" alt="image" src="https://github.com/floating-ui/floating-ui/assets/159500/1da51e7c-08a9-40c5-b70f-108054648c0e">

<img width="353" alt="image" src="https://github.com/floating-ui/floating-ui/assets/159500/0de8439f-d598-4566-875a-366a33e7b511">

This works fine, except when using the `useHover` hook.

**To Reproduce**
https://codesandbox.io/s/kind-ben-wl9twm?file=/src/App.tsx

1. Click on the light blue box
3. Observe floating layer opens docked to the (1) in the top right
4. Hover the blue box
5. Observe nothing happening
6. Hover the (1)
7. Observe the floating layer opening

**Expected behavior**
When hovering the light blue box (where the `{...getReferenceProps()}` are applied), I'd expect the floating layer to open, similar to how `useClick` behaves.

**Context:**
 - OS: [mac]
 - Browser [chrome]
 - Version [@floating-ui/react 0.26.0]

**Comment by atomiks** [comment]
`useHover` does not have event bubbling, and only registers directly on the ref. In this case though, you can do the inverse by using `setPositionReference`:

```js
<div ref={refs.setReference} {...getReferenceProps()}>
  <div ref={refs.setPositionReference} />
</div>
```
