### ISSUE TITLE
Want to Add Docker Images in Project

### ISSUE THREAD

**Issue by Adidem23** [floating-ui/floating-ui#2605]
For Developers perpective , The local setup for running projects takes lot more time we can reduce this time by creating docker Images which allows us to run the project 

**Describe the solution you'd like**
I want to Create Docker Image for the proejct and after creating docker image everyone can use it for the developement and testing

**Comment by atomiks** [comment]
Thank you for the issue, however there aren't any plans to setup Docker for this repo as it works fine without it.

**Comment by Adidem23** [comment]
Okay , No Problem
