### ISSUE TITLE
Floating element position drifts when using transform property in useTransitionStyles

### ISSUE THREAD

**Issue by dwzkit** [floating-ui/floating-ui#2612]
**Describe the bug**
I am experiencing an issue with the positioning of a floating element in my React application when using the transform property within useTransitionStyles. When the transform property is applied, the floating element's position drifts upon being displayed. However, when the transform property is not applied, the floating element's position remains correct.

Here's a snippet of the React code I am using:

```
const { isMounted: aiDailogIsMounted, styles: aiDailogTransitionStyles } = useTransitionStyles(aiDailogContext, {
    initial: {
        opacity: 0,
        transform: "scale(0.8)",
    },
});

const {
    refs: aiDialogRefs,
    floatingStyles: aiDialogFloatingStyles,
    context: aiDailogContext,
} = useFloating({
    open: aiDialogOpenStatus,
    onOpenChange: setAiDialogOpenStatus,
    placement: "bottom-start",
    middleware: [
        offset({
            crossAxis: crossAxisOffset,
            mainAxis: 7,
        }),
        shift(),
    ],
});

useEffect(() => {
    requestAnimationFrame(() => {
        try {
            if (eventAiDialogData && eventAiDialogData.dom) {
                if (openSouce === "initButton") {
               aiDialogRefs.setReference(eventAiDialogData.dom);
          } else if (openSouce === "placeholder") {
            const targetElement = document.querySelector(
              ".empty-span-for-ai-placement"
            );
            aiDialogRefs.setReference(targetElement); 

            if (targetElement && eventAiDialogData?.dom)
              setCrossAxisOffset(
                eventAiDialogData?.dom.getBoundingClientRect().x -
                  targetElement?.getBoundingClientRect().x
              );
          } else {
            const targetElement = document.querySelector(
              ".empty-span-for-ai-placement"
            );
            aiDialogRefs.setReference(targetElement); 

            if (targetElement && eventAiDialogData?.dom)
              setCrossAxisOffset(
                eventAiDialogData?.dom.getBoundingClientRect().x -
                  targetElement?.getBoundingClientRect().x
              );
          }
            }
        } catch (error) {
            console.error("Error while setting reference:", error);
        }
    });
}, [eventAiDialogData?.dom, openSouce]);

...

{editor && aiDialogOpenStatus && aiDailogIsMounted && (
    <div
        ref={aiDialogRefs.setFloating}
        style={{
            ...aiDialogFloatingStyles,
            zIndex: 1,
            width: "calc(100% - 6rem)",
            ...aiDailogTransitionStyles,
        }}
    >
        <AIFloatingWrapper
            editor={editor}
            openSource={openSouce}
            aiCommandObj={aiCommandObj}
            isOpenAiInput={isOpenAiInput}
            userId={(userinfo as any)?.CasdoorUserID}
        />
    </div>
)}
```
**To Reproduce**

**Expected behavior**
I expect the floating element to maintain its position whether the transform property is applied or not.

**Screenshots**
- When the transform property is not applied, the floating element's position remains correct.
<img width="1268" alt="image" src="https://github.com/floating-ui/floating-ui/assets/41875799/24fe995c-9f84-41d5-8cff-5122016e92f8">

- The floating element's position drifts when the transform property is applied in useTransitionStyles.
<img width="1313" alt="image" src="https://github.com/floating-ui/floating-ui/assets/41875799/1585a213-fa47-41ee-b4a5-7ebb1f1d89f2">

**Context:**

**Additional context**

I would appreciate any insights into why the transform property is causing this behavior and how it can be resolved. Thank you!

**Comment by atomiks** [comment]
See the "Note" here: https://floating-ui.com/docs/useTransition#usetransitionstyles - you need to use a wrapper

**Comment by dwzkit** [comment]
> See the "Note" here: https://floating-ui.com/docs/useTransition#usetransitionstyles - you need to use a wrapper

Thanks!
