### ISSUE TITLE
The useHover works without put into the useInteractions

### ISSUE THREAD

**Issue by danielzagumennyi** [floating-ui/floating-ui#2614]
**Describe the bug**
The `useHover` works without put into the `useInteractions`

**To Reproduce**
Just use `useInteractions` hook with empty array. The rest of the hooks don't work unless you put them in the `useInteractions`.

```
useHover(context);
const { getReferenceProps, getFloatingProps } = useInteractions([]);
```

[Example](https://codesandbox.io/s/crazy-fog-5djzfj?file=/src/App.tsx:348-353)

**Comment by atomiks** [comment]
See https://github.com/floating-ui/floating-ui/issues/2521#issuecomment-1700028028
