### ISSUE TITLE
react-dom@2.0.3 broke strict type checking

### ISSUE THREAD

**Issue by gzm0** [floating-ui/floating-ui#2624]
Repeat of #2512.

This line: https://github.com/floating-ui/floating-ui/pull/2620/files#diff-d9cb4e974bdbbdd3c2c05fcfd67270b97205552f5bd0fc0e496265e497248e09R1 re-introduced a dependency on `@floating-ui/core` which breaks strict type checking:

```
@floating-ui/react-dom/src/arrow.d.ts(1,53): error TS2307: Cannot find module '@floating-ui/core' or its corresponding type declarations.
```

Reproduction is same as #2512.

**Comment by atomiks** [comment]
My mistake sorry, fix will be released soon

**Comment by gzm0** [comment]
:O that was fast. TY for the quick fix!
