### ISSUE TITLE
[React] `FloatingFocusManager` focus sequence skips the first element on reference element trigger

### ISSUE THREAD

**Issue by feliciackh** [floating-ui/floating-ui#2639]
`FloatingFocusManager` focus sequence skips the first element on reference element trigger

Link to reproduce: https://codesandbox.io/p/sandbox/floating-ui-react-dom-template-forked-pf835n?file=%2Fsrc%2FApp.js%3A41%2C1

1. Go to link
2. `Tab` to focus on reference button
3. `Enter` or `Space`: see button 1, floating content and button 2
4. `Tab` into floating elements, focus goes into button 2 before focus traps within floating elements

Expected behavior: Step 4, `Tab` into floating elements, focus goes into button 1 (follows dom tree) before focus traps within floating elements

- Browser: chrome
- Floating UI Version: 0.26.3

**Comment by atomiks** [comment]
The component relies on `open` and `onOpenChange` options being passed to `useFloating` from the `isOpen` `useState` call. It works once that is done.
