### ISSUE TITLE
Report why `autoUpdate()` is triggered

### ISSUE THREAD

**Issue by Westbrook** [floating-ui/floating-ui#2645]
**Is your feature request related to a problem? Please describe.** A clear and
concise description of what the problem is. Ex. I'm always frustrated when [...]

When using `autoUpdate()` I'd like to be able to know why the `update()` method has been called so I can do different things in response to the various triggers, e.g.:
- ancestorScroll => close
- ancestorResize => close
- elementResize => reposition
- layoutShift => ignore (currently possible via the options bag)

**Describe the solution you'd like** A clear and concise description of what you
want to happen.

I'd like to update to type of `autoUpdate()` from:
```
export declare function autoUpdate(reference: ReferenceElement, floating: FloatingElement, update: () => void, options?: AutoUpdateOptions): () => void;
```
to:
```
export declare function autoUpdate(reference: ReferenceElement, floating: FloatingElement, update: (Omit<AutoUpdateOptions, 'animationFrame'>) => void, options?: AutoUpdateOptions): () => void;
```
Or so. This way the additional argument in the `update()` method can pass `true`/`false` for which ever reason it's been called.

**Describe alternatives you've considered** A clear and concise description of
any alternative solutions or features you've considered.
I could wire up all the listeners, etc. that `autoUpdate()` bind on my own, but it seems like all the data/workflow are there and could be easily leveraged to supply this additional data.

**Additional context** Add any other context or screenshots about the feature
request here.
n/a

**Comment by atomiks** [comment]
So you mean:

```js
function handlePositionChange(reason: string) {
  if (reason === 'ancestor-scroll' || reason === 'ancestor-resize') {
    close();
  } else if (reason !== 'layout-shift') {
    computePosition(...);
  }
}

autoUpdate(reference, floating, handlePositionChange);
```

**Comment by Westbrook** [comment]
If you prefer that, sure.

I was thinking to not rely on magic strings:
```
function handlePositionChange(reason: Omit<AutoUpdateOptions, 'animationFrame'>) => void, options?: AutoUpdateOptions): () => void;
) {
  if (reason.ancestorScroll || reason.ancestorResize) {
    close();
  } else if (reason.elementResize) {
    computePosition(...);
  }
}

autoUpdate(reference, floating, handlePositionChange, { layoutShift: false });
```

---

I'm not sure how `elementResize: true` would give me this. Maybe there's something I'm overlooking...

At current, everything is `true` by default (in modern browsers):
```
  const {
    ancestorScroll = true,
    ancestorResize = true,
    elementResize = typeof ResizeObserver === 'function',
    layoutShift = typeof IntersectionObserver === 'function',
    animationFrame = false,
  } = options;
```
That means that `update()` is called for everything and doesn't know the specific reason in each call. Currently, I turn off `elementResize` and `layoutShift`, and then I need to force consumers to "know" when their element resizes and manually call the reposition workflow. I'd love to include `elementResize` and then know when it's one vs the others so I can do different things in response.

**Comment by atomiks** [comment]
> I'm not sure how elementResize: true would give me this. Maybe there's something I'm overlooking...

I mean the issue says when the popover resizes it doesn't re-align correctly to the anchor. The default options of `autoUpdate` handles this scenario, however:

> Currently, I turn off `elementResize` and `layoutShift`

I'm not sure what the reason for this is then?

**Comment by Westbrook** [comment]
Oh, I turn it off because there’s more contexts by which I close things right now than by which I’d update, which is why I was looking for reason. Multiple `autoUpdate()` feels weird, but if the options are completely non-overlapping that aligns pretty closely with what I’m trying to do here. Let me dig into that approach and get back with an update next week. Thanks for the idea!

**Comment by atomiks** [comment]
I'm pretty sure that works equivalently and I think it's a fine solution. Going to close with "has workaround"
