### ISSUE TITLE
[Core] TypeScript `type` import error `1.5.1`

### ISSUE THREAD

**Issue by moxpatwa** [floating-ui/floating-ui#2647]
Hello Team,
We are using react v 18.2.0 for our Frond end application and we have deleted node-modules and again run npm install, after that i have run npm run build. but we are getting below complied error:
![image (2)](https://github.com/floating-ui/floating-ui/assets/64414384/2a9bfe99-7be8-424d-9a94-7319ce275f8c)

can you please help on this as soon as possible?

**Comment by moxpatwa** [comment]
@atomiks if I upgrade typescript version to latest then it has problem with react-script@5.0.1
<img width="900" alt="image" src="https://github.com/floating-ui/floating-ui/assets/64414384/552de28b-866f-4bf4-af53-371a594d089c">

**Comment by atomiks** [comment]
To be honest, I didn't realize what version `import { type Type } from 'module'` syntax was introduced when refactoring that code internally, but it was `v4.5` from November 2021, before this library was even created, so it's over 2 years old now... 

If you're using a modern library like this released in December 2021, then it should be expected to at least be using versions of libraries and code from that era imo

**Comment by Quantum1248** [comment]
> To be honest, I didn't realize what version `import { type Type } from 'module'` syntax was introduced when refactoring that code internally, but it was `v4.5` from November 2021, before this library was even created, so it's over 2 years old now...
> 
> If you're using a modern library like this released in December 2021, then it should be expected to at least be using versions of libraries and code from that era imo

Yeah, I can agree with that. However,  I work in a company with many many app in ang11/12 that depends on our library so we can't update it to a more recent version. I would have made this change in a major version instead of a minor as it breaks retro compatibility. In our case, all our old versions of the library which used version "^1.2.9" of the "@floating-ui/dom" packages now breaks during installation. If it had been a major version, let's say 2.0.0, this would not have been a problem.

**Comment by Jonathan-Lou** [comment]
My ts version is 4.5,but still get colplied error.
/node_modules/_@floating-ui_core@1.5.1@@floating-ui/core/src/middleware/hide.d.ts(1,15): error TS1005: ',' expected.

**Comment by Jonathan-Lou** [comment]
> @Quantum1248 yeah fair enough:) I think it's reasonable to have an implicit contract for type syntax for each major version where the TS features used by the library's types never exceed a minor version higher than what's been used.
> 
> In this library's case, it was `4.1`, I think. I will publish a fix to remove that syntax shortly.
> 
> @Jonathan-Lou that's not possible, 4.5 will work. I'll fix this anyway though.

thanks a lot！May i ask when it will be published？
