### ISSUE TITLE
Floating UI Devtools

### ISSUE THREAD

**Issue by bsunderhus** [floating-ui/floating-ui#2649]
**Is your feature request related to a problem? Please describe.**
 
Debugging positioning issues is time consuming! There are also a lot of concepts to understand to know how positioning might be wrong, and it's quite hard to grasp how the way one is using Floating UI actually affects positioning itself.
 
**Describe the solution you'd like**
 
[Devtools for Floating UI positioned elements](https://chromewebstore.google.com/detail/floating-ui-devtools/ninlhpbnkjidaokbmgebblaehpokdmgb?hl=en) to  ease debugging without needing to use code breakpoints in Floating UI. Some datapoints to track for these devtools that come to my mind:
 
1. target element
2. floating element
3. middleware data
4. what caused a reset?!
7. original/flip position
 
**Additional context**
 
Hey there @atomiks @FezVrasta , I'm reaching out on behalf of [Fluent UI](https://github.com/microsoft/fluentui) library, we use Floating UI as one of our foundation dependencies for positioning components, such as [Menu](https://react.fluentui.dev/?path=/docs/components-menu-menu--default), [Tooltip](https://react.fluentui.dev/?path=/docs/components-tooltip--default) and [Popover](https://react.fluentui.dev/?path=/docs/components-popover--default) and other components.
 
It came to our attention a pattern of multiple partners and collaborators whom would contact us with problems/issues related to Fluent UI positioning components, and by the end of the day, with some investigation, most of those problems comes down to a lack of information between the person using our components and how does their use cases might actually influence on the appearance/positioning of those components, the number one strategy to debug those problems would involve using break points on the floating UI code to figure out how the configuration provided actually ends up impacting the element's styling.
 
We're most interested into collaborating with the creation of tools to mitigate this problem, as it seems to us that this is a complex issue and it'll not be easily solved by simply documenting countless edge cases. I'd love to have some feedback from you as authors of Floating UI on ideas and visions you might have for some sort of devtool that could help the community to better understand and deal with positioning problems.

As a first idea we took the liberty to develop [floating-ui-devtools](https://github.com/bsunderhus/floating-ui-devtools), but keep in mind that it's still quite beta.

**Comment by bsunderhus** [comment]
> Love the extension!

I'm glad to hear that 🤩

We're still investigating what is the best data to be showed by the devtools panel.
At the moment I'd say those are the main next todos:

1. Show data history (at the moment the panel displays the last available value provided through the middleware chain)
2. Visually improve the panel (at the moment I'm using a simple json viewer to showcase the raw data passed)
    * This also means we need to figure out what data is important and how to properly showcase it
3. Investigate other possible interesting interactions that the Devtools might do besides analyzing middleware data
4. Advocate for the community to use the devtools
   * Start documentation and proper examples on how to use it

And these would be some interesting unknown points:

1. There might be some data internal to Floating UI logic that might be interesting to have available to show in the extension panel (???)
2. It would be nice to have way of knowing which middleware caused a reset


Currently the devtools will support a custom panel for raw Floating UI middleware, and also FluentUI internals. It would also be nice to have other open source libraries that rely on Floating UI being covered here in the future

**Comment by ling1726** [comment]
Great job @bsunderhus 🥳🥳

> There might be some data internal to Floating UI logic that might be interesting to have available to show in the extension panel (???)

On that node there might be quite a lot of relevant within the `detectOverflow` utility which for the most part is the driver of a lot of the result for the end user:

* boundary evaluation
* offsetParent
* clipping ancestors
* scale

That data doesn't really surface up into any middleware. We do allow users to configure things like boundaries on our end so when they provide that we can surface that up, but what is done by default in Floating UI is a bit of black box for those points above. Do you think any of that is worth surfacing? what do you think would be a good way to do so? 

> It would be nice to have way of knowing which middleware caused a reset

Yeah we have been hit a few times on infinite middleware reset loops from our own middleware 🤦 that would be quite handy to debugging

**Comment by bsunderhus** [comment]
Ok, I'll consider this issue solved with the closing of https://github.com/floating-ui/floating-ui/pull/2653
I'll be following up with more issues to continue improving the devtools.

@FezVrasta, would be nice to have a label for `devtools` issues!

Here's the next steps I'm already working on:

- [ ] - Show data history (at the moment the panel displays the last available value provided through the middleware chain)
- [ ] - Automate extension publishing

Later on I'll be updating with more todos!
