### ISSUE TITLE
[Vue] Does not provide an export named 'FloatingFocusManager

### ISSUE THREAD

**Issue by JokerMartini** [floating-ui/floating-ui#2655]
The Vue package does not provide an export named 'FloatingFocusManager'.

1. Create a vue project and attempt to import the 'FloatingFocusManager'
```
import {
  useFloating,
  autoUpdate,
  flip,
  offset,
  shift,
  useRole,
  useDismiss,
  useInteractions,
  useListNavigation,
  useTypeahead,
  FloatingPortal,
  FloatingFocusManager,
  FloatingOverlay,
} from "@floating-ui/vue";
```

**Comment by atomiks** [comment]
Those modules listed/collapsed under `React` in the navbar are exclusive to React. There is no Vue equivalent currently, which only provides positioning features (equivalent to `@floating-ui/react-dom`).
