### ISSUE TITLE
Could not resolve "export-dirs"

### ISSUE THREAD

**Issue by trisys3** [floating-ui/floating-ui#2661]
**Describe the bug** A clear and concise description of what the bug is.

While serving through vite, I get a yarn error about not being able to resolve "export-dirs". The package is extremely deep in the package hierarchy, so I don't really know much more, and it would probably be pretty hard to create a repro repo. Regardless, please let me know how I can help in testing/reproducing.

**To Reproduce**

1. Install with yarn berry or later, in either pnp or node-modules mode.
2. Start up a vite server.

**Expected behavior** A clear and concise description of what you expected to
happen.

No resolution errors.

**Screenshots** If applicable, add screenshots to help explain your problem.

```bash
✘ [ERROR] Could not resolve "@floating-ui/utils/dom"

    node_modules/@floating-ui/dom/dist/floating-ui.dom.mjs:4:262:
       4 │ ...isTableElement, getContainingBlock } from '@floating-ui/utils/dom';
        ╵                                              ~~~~~~~~~~~~~~~~~~~~~~~~
 
   You can mark the path "@floating-ui/utils/dom" as external to exclude it from the bundle, which will remove this error.

 ✘ [ERROR] Could not resolve "export-dirs"

     node_modules/@floating-ui/utils/lib/index.js:3:25:
       3 │ module.exports = require('export-dirs')(__dirname);
         ╵                          ~~~~~~~~~~~~~

   You can mark the path "export-dirs" as external to exclude it from the bundle, which will remove this error. You can also surround this "require" call with a try/catch block to handle this failure at run-time instead of bundle-time.
```

**Context:**

- OS: linux alpine 3.18, through docker
- Browser: Google Chrome
- Versions:
-- @floating-ui/react-dom: 2.0.4
-- @floating-ui/dom: 1.5.3
-- @floating-ui/core: 1.5.2
-- @floating-ui/utils: 0.1.6
-- @mui/base: 5.0.0-beta.26
-- @mui/material: 5.14.20
-- yarn: 4.0.1
-- vite: 4.5.1
-- vite-plugin-ruby: 3.2.0
-- esbuild: 0.18.20

**Additional context** Add any other context about the problem here.

This error is triggered deep in the package hierarchy, by way of MUI. I have tried to include all transitive dependencies that I thought might be applicable, as well as the builder packages, but I may have missed some.

I think the error is ultimately triggered by esbuild, not vite, but I'm not sure. I'm also not sure if yarn is involved at all, and I haven't tried installing via node.

**Comment by atomiks** [comment]
>      node_modules/@floating-ui/utils/lib/index.js:3:25:

The `utils` package doesn't have a "lib" directory. I don't really know why this would be occurring in general but it's likely a bug that should filed to the relevant tools instead

**Comment by trisys3** [comment]
This is certainly a weird one. It looks like the `@floating-ui/utils` package is being replaced with the `utils` package. But not completely, as it expects the original package's dependencies, even though the generic package's dependencies are the ones referenced in the `package.json`.

This definitely looks like a yarn issue. I just hope that either I can make a good repro case out of this briar patch, or that yarn accepts my paltry repro-less issue.

**Comment by trisys3** [comment]
Actually, I think this is an issue with our internal Artifactory setup. Closing...
