### ISSUE TITLE
Mouseonly hover hook interferes with touch behaviour

### ISSUE THREAD

**Issue by cjp-psl** [floating-ui/floating-ui#2663]
When adding custom touch behaviour and using 'hover' hook with mouseOnly set to true, the float is incorrectly reshown after a touch operation which hides it.

**To Reproduce**

Sandbox : https://codesandbox.io/p/sandbox/festive-chatterjee-pf4mxs

* Set browser to touch device via dev tools (or use an actual touch device)
* Tap 'trigger' button once (float shown)
* Tap 'trigger' button again

**Expected behavior** 
Activation count increases and float is hidden

**Actual behaviour**
Activation count increases but float is re-displayed.

**Context:**

- OS: Tested in windows 11 (latest)
- Browser: issue present in both chrome and edge
- Version: 0.26.4 (current latest)

**Comment by atomiks** [comment]
`move: false` appears to fix the issue, which disables the `mousemove` listener.

**Comment by cjp-psl** [comment]
You're right! - I thought I had tested with the move flag set to false, but perhaps not with that exact prop combination.

Not sure if there is a way to maintain the move functionailty without the touch related issue (I'm guessing the browser is funneling touch behaviour to mousemove event?), but if not maybe a mention in the docs for the mouseOnly flag in case someone else gets tripped up.

Thanks for the quick response too btw.
