### ISSUE TITLE
[React] Support aria-activedescendant similarly to useFocus or useHover

### ISSUE THREAD

**Issue by Etienne-M** [floating-ui/floating-ui#2664]
## Description

*Use-case*: Display a tooltip when a button in a grid receives focus.

### Context
In a composite element, focus is frequently managed by setting the browser focus on the composite element, then setting `aria-activedescendant` to the id of the child element that the author wants to have focus.

### Possible implementation

What I suggest is a simple hook `useActiveDescendant`, that would:

1. Find the first parent node of the *reference element* that can receive browser focus;
2. Add event listeners for blur and focus events on this parent node;
3. Add a MutationObserver for specifically the `aria-activedescendant` attribute on this parent node;
4. When the parent node has both browser focus and the `aria-activedescendant` set to the ID of the reference element, display the tooltip. Otherwise, hide it.

This is a bit of a *dumb* implementation, since for `n` elements with tooltips in the same composite element, their would be `n` MutationObserver, `n` event listeners for blur and `n` event listeners for focus. If further optimization is needed, there could simply be a context so we don't unnecessarily register MutationObserver and event listeners.

**Comment by Etienne-M** [comment]
I'm unfamiliar with how contributions work in this project, but this seems easy enough. If there's appetite to include this in the library, I could provide an implementation

**Comment by atomiks** [comment]
The `Composite` component exported by this library uses roving focus instead of virtual focus, which alleviates the issues mentioned; what's the use case for virtual focus in this case? Typically it's only useful for comboboxes no?

**Comment by Etienne-M** [comment]
Hi @atomiks, thanks for reaching out!

Full disclosure, I am not by any mean an expert on this stuff, I try to make the most sense of this (often cryptic) stuff.

My understanding is that `aria-activedescendant` is an alternative to roving focus. If I look at the implementations for some of the patterns in [the ARIA authoring practice guide](https://www.w3.org/WAI/ARIA/apg/patterns/), some use roving focus, and some use `aria-activedescendant`. Here's [the documentation](https://www.w3.org/WAI/ARIA/apg/practices/keyboard-interface/#keyboardnavigationinsidecomponents) I've found useful on this subject.

All this to say that my understanding is that the current state of `floating-ui` is that it handles one way of managing focus inside components, but not the other. Could be by design, could be an omission.

I'm not looking to insist to bring this into the library if this is by design. To be transparent, I was going to create a hook directly in our project, and if there was desire to bring this in the library itself, I would have simply submitted a PR with our implementation. Side-note: kudos on the flexible design, it's easy to make our own hooks on top of the hooks available in the library

**Comment by atomiks** [comment]
`aria-activedescendant` (aka virtual focus) is required if you want DOM focus to stay on an input e.g. combobox. Otherwise, roving tabindex is better supported among screen readers I believe, and is simpler at least with how this library has implemented it. `Composite` could technically support comboboxes, but `useListNavigation` can handle it in a "non-floating" context already (always-open)
