### ISSUE TITLE
useFocus opens incorrectly on click/pointer in react-testing-library for visibleOnly

### ISSUE THREAD

**Issue by cjp-psl** [floating-ui/floating-ui#2666]
When executing inside react @testing-library (jest) with *useFocus* hook, float becomes incorrectly visible on .click() or .pointer() user actions.

This works as expected in browser.

**Steps to reproduce the behavior:**

* Create floating ui react component usage with only *useFocus* hook and button
* Create jest test using @testing-library, and trigger button click via testing library user actions 
* Check if float has been opened in test

Couldn't get a codesandbox for @testing-library running unfortunately due to recent codesandbox changes, but have created an isolated sample 
[FocusTestBug.test.tsx.txt](https://github.com/floating-ui/floating-ui/files/13706565/FocusTestBug.test.tsx.txt)

**Expected behaviour:**
Float is not shown in jest execution context.

**Investigation:**

I've tracked this to a couple of linked causes:

1. the target.match(':focus-visible') call (ln 129) throws an exception, as jsdom does not support that selector (and doesn't seem like they will anytime soon from [this](https://github.com/jsdom/jsdom/issues/3426) issues activity)

2. the pointer event generated by jsdom in @testing-library has no width or height prop set, so passes the *isVirtualPointerEvent* check in *pointerDown* (ln 112)
That in turn prevents keyboardModality from being set to false, which leads to visibleOnly fallback behaviour failing to prevent open event trigger in *onFocus*

I appreciate this isn't strictly speaking a floating-ui problem as browser behaviour is correct, but as component testing via jest and @testing-library is pretty common I wonder if this could be resolved by adjusting the *isVirtualPointerEvent* to return false if the user agent contains jsdom (like with similar android/safari checks already). The fallback behaviour would then work as expected.

For reference navigator.userAgent in jest execution reports for me as 
"Mozilla/5.0 (win32) AppleWebKit/537.36 (KHTML, like Gecko) jsdom/20.0.3"

**Comment by atomiks** [comment]
> the pointer event generated by jsdom in https://github.com/testing-library has no width or height prop set, so passes the isVirtualPointerEvent check in pointerDown (ln 112)
That in turn prevents keyboardModality from being set to false, which leads to visibleOnly fallback behaviour failing to prevent open event trigger in onFocus

Interestingly, in latest Chrome on Mac, it seems like `isVirtualPointerEvent` sometimes incorrectly returns `true` when clicking repeatedly. Doesn't seem to happen in Firefox or Safari. 

There might be an extra fix that needs to be added to the function.
