### ISSUE TITLE
Issue with Text Selection Visibility in Safari When Using FloatingFocusManager

### ISSUE THREAD

**Issue by dwzkit** [floating-ui/floating-ui#2674]
**Describe the bug** A clear and concise description of what the bug is.

I am experiencing an issue with text selection visibility in Safari when using FloatingFocusManager from floating-ui. When a floating menu is triggered upon text selection in a contenteditable div, and the mouse hovers over the first item of the dropdown menu, the focus shifts from the contenteditable div to the dropdown menu item. This focus shift is causing the selected text to lose its highlighted background in Safari, whereas in Edge and Firefox, the selected text maintains its visibility.
        
```
<FloatingPortal id={props.portalid}>
          {floatingVars.isMounted && (
            <FloatingFocusManager
              context={floatingVars.context}
              // Prevent outside content interference.
              modal={false}
              // Only return focus to the root menu's reference when menus close.
              returnFocus={false} 
              // Only initially focus the root floating menu.
              initialFocus={-1}
            >
              <div
                ref={floatingVars.refs.setFloating}
                className={module_styles.MenuContent}
                style={{
                  position: floatingVars.strategy,
                  top: floatingVars.y ?? 0,
                  left: floatingVars.x ?? 0,
                  width: "max-content",
                  ...floatingVars.styles,
                }}
                {...floatingVars.getFloatingProps()}
              >
                {cloneValidElementsWithProps(
                  menuContents,
                  menuState,
                  floatingVars
                )}
              </div>
            </FloatingFocusManager>
          )}
        </FloatingPortal>
```

**To Reproduce**

- Select text within a contenteditable div.
- Trigger a floating menu using FloatingFocusManager with initialFocus set to -1.
- Hover the mouse over the first item of the floating menu.
- Observe the change in text selection visibility in different browsers.

**Expected behavior** A clear and concise description of what you expected to happen.

The selected text should maintain its highlighted background (selection visibility) when the focus shifts to the floating menu, consistent across browsers including Safari.

**Actual Behavior:**
In Safari, the selected text loses its highlighted background upon focus shift, while in Edge and Firefox, the selection visibility remains.

**Screenshots** If applicable, add screenshots to help explain your problem.

**Edge**

The selected text maintain its highlighted background (selection visibility) when the focus shifts to the floating menu:
![20231225144129_rec_](https://github.com/floating-ui/floating-ui/assets/41875799/2a489acd-2ec5-4936-ad35-708f942a9e06)

**Safari**

In Safari, the selected text loses its highlighted background upon focus shift:
![20231225143905_rec_](https://github.com/floating-ui/floating-ui/assets/41875799/89c9dc39-6fc0-43ff-9969-0b4442e26706)

**Context:**
- OS: MacOS M1
- Browser [edge, safari]
- Version [@floating-ui/react": "^0.26.2",]

**Additional context** Add any other context about the problem here.

- A potential solution could be configuring FloatingFocusManager to not alter focus upon activation of the floating menu, but I am unsure how to achieve this.

**Comment by atomiks** [comment]
Thank you for the issue, however to debug this, I need a CodeSandbox reproduction. Otherwise, it takes up too much time without one. I can reopen if provided.
