### ISSUE TITLE
Show a floating bubble surrounding highlighted text

### ISSUE THREAD

**Issue by z0xyz** [floating-ui/floating-ui#2681]
## Shortcoming
The library supports showing a popover with respect to a separate element, but not with respect to any highlighted word.

## Suggestion
The ability to show a floating window in relative to any highlighted word e.g., selected word within any other website.

**Comment by atomiks** [comment]
It does support it: https://floating-ui.com/docs/virtual-elements

**Comment by z0xyz** [comment]
sorry.
The docs also mention react support. The code samples mention full-fledged react project. Does it support injecting those components into any other webpage?
So far, I'm currently developing an extension that injects the popover into other websites. The extension code injects HTML elements & basic CSS styling using plain javascript, but that's very limiting. Can floating-ui/react inject components using?
sorry if my question is outside the scope the library

**Comment by atomiks** [comment]
Yes, you can use React and any code that uses it in an extension, it works the same as in a web app like normal. Unless I'm misinterpreting what you're asking?

**Comment by z0xyz** [comment]
> Unless I'm misinterpreting what you're asking?

The extension injects the floating bubble in other 3rd-party websites, so I wanted to craft the bubble's content using react components for convenience.

**Comment by z0xyz** [comment]
@atomiks So Can I get to know whether this is possible or not in this very use case?

Also, `getBoundingClientRect()` positions the floating bubble at 0,0 coordinates when highlighting text at an input field.
