### ISSUE TITLE
scheduleUpdate seems to be not placing the popup element correctly

### ISSUE THREAD

**Issue by dineshpanda** [floating-ui/floating-ui#2686]
`scheduleUpdate` is not positioning popup element correctly on a Bootstrap offcanvas (drawer). 

**To Reproduce**

https://codepen.io/dineshpanda/full/BaboErr

1. Go to https://codepen.io/dineshpanda/full/BaboErr
2. Click on 'RIght offcanvas' button
3. Select a text in textarea
4. You will not see the popup element since it is hidden due to its position.

**Expected behavior** 
Popup element should appear at top of textarea.

**Context:**

- Browser chrome
- Version `1.16.1`

Popup element seems to be showing when I remove `scheduleUpdate`.

**Comment by atomiks** [comment]
Popper.js v1 is no longer maintained and hasn't been updated since 2019. For the latest supported library, use Floating UI.
