### ISSUE TITLE
@floating-ui/utils contains react as a peerDependency

### ISSUE THREAD

**Issue by alexfriesen** [floating-ui/floating-ui#2701]
**Describe the bug** A clear and concise description of what the bug is.

As I am using vue I don't expect react in my node_modules.
The Package: @floating-ui/utils list react as a peer dependency but I could not find any usage of react in its source files.

**To Reproduce**

1. Go to 'https://github.com/floating-ui/floating-ui/blob/master/packages/utils/package.json'
2. Look at 'peerDependencies'

**Expected behavior** A clear and concise description of what you expected to
happen.

I would suggest removing react as a peer dependency or mark it as optional.

**Comment by atomiks** [comment]
This should've been removed along with https://github.com/floating-ui/floating-ui/pull/2689 (previously, the peer dep wasn't actually specified until a recent turborepo refactor).
