### ISSUE TITLE
[react - useFloating] no way to control autoUpdate

### ISSUE THREAD

**Issue by KutnerUri** [floating-ui/floating-ui#2733]
**Describe the bug** A clear and concise description of what the bug is.
When using auto update with useFloating(), after initial mount, there is no way to turn it on or off.

I realize I could control it manually, but I kind of expect it to be a built in feature, like how the middleware have `enabled: boolean`.

```tsx
const { refs, floatingStyles, context } = useFloating({
  // ...;
  whileElementsMounted: props.autoUpdate ? autoUpdate : undefined,
});
```

**To Reproduce**

[CodeSandbox](https://codesandbox.io/p/sandbox/floating-ui-react-dom-template-forked-rv8tvk?file=%2Fsrc%2FApp.js%3A25%2C17&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clrdt461i00063b6gdgxjpe3h%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clrdt461i00023b6gzt46nv59%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clrdt461i00033b6gyzopiuiz%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clrdt461i00053b6gluieyxog%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clrdt461i00023b6gzt46nv59%2522%253A%257B%2522id%2522%253A%2522clrdt461i00023b6gzt46nv59%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrdtc7e200023b6gjmzrukvr%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A25%252C%2522startColumn%2522%253A17%252C%2522endLineNumber%2522%253A25%252C%2522endColumn%2522%253A17%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clrdtc7e200023b6gjmzrukvr%2522%257D%252C%2522clrdt461i00053b6gluieyxog%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrdt461i00043b6gno9v0mhb%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clrdt461i00053b6gluieyxog%2522%252C%2522activeTabId%2522%253A%2522clrdt461i00043b6gno9v0mhb%2522%257D%252C%2522clrdt461i00033b6gyzopiuiz%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clrdt461i00033b6gyzopiuiz%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

1. Look at "my tooltip"

**Expected behavior** - Tooltip should switch between auto updating and stationary every 2 seconds.

**Screenshots**
![Screenshot 2024-01-14 at 20 16 15](https://github.com/floating-ui/floating-ui/assets/5400361/010278b0-069e-4652-ac2b-d805f3206d54)

**Context:**

- OS: MacOs - 14.2.1
- Browser Chrome
- Version - 120

**Comment by atomiks** [comment]
Yeah, it's due to `whileElementsMounted` being non-reactive so it doesn't check if it changes to `undefined`:

https://github.com/floating-ui/floating-ui/blob/77fe7480a1a3a201452fd7b993f75065ed6bbdc5/packages/react-dom/src/useFloating.ts#L75

Workaround as you mentioned is to set it up manually in an effect and avoid the `whileElementsMounted` option

```js
useEffect(() => {
  if (isOpen && props.autoUpdate && elements.reference && elements.floating) {
    const cleanup = autoUpdate(
      elements.reference,
      elements.floating,
      update,
    );
    return cleanup;
  }
}, [isOpen, props.autoUpdate, elements, update]);
```

**Comment by KutnerUri** [comment]
and I'm guessing you don't want to make it reactive in case consumers pass a function. hmmph.

maybe create a hook, useAutoUpdate()?
```tsx
useAutoUpdate(context, { enabled: true, ...);
```

seems elegant enough, and it would make it possible to change the autoUpdate options

**Comment by atomiks** [comment]
The option can be made reactive if it changes from a function to `undefined`, which `useDismiss` does for `outsidePress`, just needs a fix and doesn't require a separate hook
