### ISSUE TITLE
Option is not scrolled into view when opening by clicking on reference

### ISSUE THREAD

**Issue by hornta** [floating-ui/floating-ui#2749]
https://codesandbox.io/p/devbox/floating-ui-scroll-mdwkmq

I've tried to make my component scroll to the currently selected option. It doesn't scroll to it when open by clicking with cursor. It does work when focusing the element with keyboard and pressing enter. 

It seems like this flag gets set to false when clicking with cursor, but not when using keyboard and that is what's causing my issue: https://github.com/floating-ui/floating-ui/blob/c74dc8e44521e0be244781dd746e0a1656d1f313/packages/react/src/hooks/useListNavigation.ts#L263-L266

![12996e23-a7aa-4a55-b7b5-0c93988dac70](https://github.com/floating-ui/floating-ui/assets/4553604/aa0b26c8-a567-4e89-82c6-24a05dd08344)

**Comment by atomiks** [comment]
Doesn't seem to happen with the [Select demo](https://codesandbox.io/p/sandbox/gallant-sea-rcg43b). 

In your demo, it scrolls correctly after a second click toggle. I wonder if one of the effects you're using in the component is causing an issue - I notice a lot of state sync'ing that maybe could be refactored.
