### ISSUE TITLE
autofocus input in floating element will make window scroll to top

### ISSUE THREAD

**Issue by SteveSuv** [floating-ui/floating-ui#2752]
# Description
if a autofocus input or textarea in floating element , when floating element open, the window will auto scroll to top.

# Code
```tsx
import { useState } from "react";
import {
  useFloating,
  useInteractions,
  useClick,
  useDismiss,
  offset,
  flip,
  autoUpdate,
  shift,
} from "@floating-ui/react";

const App = () => {
  const [open, setOpen] = useState(false);

  const { refs, floatingStyles, context } = useFloating({
    open,
    onOpenChange: setOpen,
    middleware: [offset(4), flip(), shift()],
    whileElementsMounted: autoUpdate,
  });

  const { getReferenceProps, getFloatingProps } = useInteractions([
    useClick(context),
    useDismiss(context),
  ]);

  return (
    <div
      style={{
        textAlign: "center",
      }}
    >
      <div style={{ marginTop: "80vh" }} />

      <button ref={refs.setReference} {...getReferenceProps()}>
        click
      </button>

      {open && (
        <div
          ref={refs.setFloating}
          style={{ ...floatingStyles }}
          {...getFloatingProps()}
        >
          {/* if add autoFocus, when open is true, the window will auto scroll to top */}
          <input autoFocus placeholder="search" />
        </div>
      )}

      <div style={{ marginTop: "80vh" }} />
    </div>
  );
};

export default App;

```

# GIF
![CPT2401181642-1510x827](https://github.com/floating-ui/floating-ui/assets/35391006/aab80d26-8072-4719-9578-8582e22c2dd8)

**Comment by atomiks** [comment]
This is due to the browser focusing the input before the floating element was positioned (where it's at the top-left of the window initially). Use `FloatingFocusManager` instead to manage focus

**Comment by SteveSuv** [comment]
> This is due to the browser focusing the input before the floating element was positioned (where it's at the top-left of the window initially). Use `FloatingFocusManager` instead to manage focus

Can you give a code example， I have tried to use FocusManager， but not valid，I don't know to pass what props，thanks

**Comment by atomiks** [comment]
```js
import { FloatingFocusManager } from '@floating-ui/react';
```

Only takes these two props to work:

```js
      {open && (
        <FloatingFocusManager context={context} modal={false}>
          <div
            ref={refs.setFloating}
            style={{ ...floatingStyles }}
            {...getFloatingProps()}
          >
            <input placeholder="search" />
          </div>
        </FloatingFocusManager>
      )}
```

**Comment by joelstein** [comment]
> This is due to the browser focusing the input before the floating element was positioned (where it's at the top-left of the window initially). Use `FloatingFocusManager` instead to manage focus

Thanks for this! I was very confused why `autoFocus` was doing this.

@atomiks You might consider mentioning on the FloatingFocusManager docs page _not_ to use the `autoFocus` prop.
