### ISSUE TITLE
Dynamic focus manager elements create ARIA violations.

### ISSUE THREAD

**Issue by elizabethsjudd** [floating-ui/floating-ui#2758]
We use the focus manager to handle keyboard navigation in a dropdown menu component. This implementation has Floating UI dynamically injecting `span[data-floating-ui-focus-guard]` elements to track focus movement. However, these elements have `aria-hidden="true"` and `tabindex="0"`, which is an invalid use of these attributes. Focusable elements can not be hidden from assistive technologies. This is creating errors when running Deque's Axe accessibility scan.

**To Reproduce**

1. Go to the existing [dropdown menu demo provided by floating-ui](https://codesandbox.io/p/sandbox/admiring-lamport-5wt3yg).
2. Click on popout button to open the demo in a new tab
3. Open the developer console and navigate to the [Deque Axe tool](https://chromewebstore.google.com/detail/axe-devtools-web-accessib/lhdoppojpmngadmnindnejefpokejbdd?hl=en-US&branded))
4. Open the dropdown menu
5. Scan the page using the Deque Axe tool

**Expected behavior** No violations from Deque Axe

**Screenshots**

![Screenshot 2024-01-18 at 12 50 57 PM](https://github.com/floating-ui/floating-ui/assets/1275779/4c12c801-fdcf-497e-8e87-89da0e643a51)

**Context:**

- OS: Mac
- Browser Chrome

**Comment by atomiks** [comment]
This is a false positive of the tool. Focus guards are exempt since focus is immediately moved somewhere else as soon as the guard receives focus - it needs `aria-hidden` and doesn't cause an actual issue.

**Comment by atomiks** [comment]
By the way, thank you for testing the demo(s)! Currently I try to extensively test with actual screen readers but there may be issues with some of the other demos? (I also notice there's "2" other issues in the screenshot)

I plan to revamp some of the demos and write full guides for the other components eventually, so it'd probably be good to use this.

**Comment by IlyaErshovDev** [comment]
I think I have a similar problem with the latest version (0.26.22) of the @floating-ui/react and 127.0.6533.119 chrome.
![issue](https://github.com/user-attachments/assets/2898d3a0-8ff3-4516-9a1e-666557b9bbbb)

After closing the popover, the focus is set to the trigger element, at which point the aria-hidden error occurs.

I am using a mapping condition using isMounted to display the animation. There is no such problem when using isOpen

`const TRANSITION_DURATION = 200; // мс

const PopoverContent = React.forwardRef<
  HTMLDivElement,
  HTMLProps<HTMLDivElement>
>(function PopoverContent({ children, ...props }, propRef) {
  const context = usePopoverContext();
  const { floatingConfig } = context;
  const ref = useMergeRefs([floatingConfig.refs.setFloating, propRef]);
  const { isMounted, status } = useTransitionStatus(floatingConfig.context, {
    duration: TRANSITION_DURATION,
  });

  const popoverStyles = clsx(styles.popover, lightThemeClassName);
  return (
    <>
      {isMounted && (
        <FloatingPortal>
          <FloatingFocusManager context={floatingConfig.context}>
            <div
              className={styles.popoverRoot}
              ref={ref}
              style={{ ...floatingConfig.floatingStyles }}
              {...context.getFloatingProps(props)}
            >
              <div className={popoverStyles} data-status={status}>
                {children}
              </div>
            </div>
          </FloatingFocusManager>
        </FloatingPortal>
      )}
    </>
  );
});`

**Comment by atomiks** [comment]
This may be another type of false positive (a bit different from the OP as it's not to do with the focus guards), if the `aria-hidden` gets removed asynchronously 1 tick later. 

Does the trigger or any of its ancestors (latter is more likely) have `aria-hidden` when you inspect the DOM when the error appears?

**Comment by IlyaErshovDev** [comment]
Only the `<main>` parent container with the `data-floating-ui-inert` attribute, as far as I understand, automatically receives `aria-hidden` from focus manager

**Comment by atomiks** [comment]
The attribute is assigned intentionally; my point is that the error appearing may not actually be causing harm or be a problem since it gets removed 1 "tick" (of the macro/microtask queue) later. The browser could be performing a synchronous check that doesn't account for it getting removed a split second later. Although, I know VoiceOver doesn't like async things (and it could actually be a real issue even though it gets removed if it's there upon immediate focus, leading to lack of announcements). 

That said, I can't reproduce this locally, so please create a reproduction on CodeSandbox or similar, and open a new issue if you can.
