### ISSUE TITLE
Position issue when scroller is inside another scroller

### ISSUE THREAD

**Issue by piszczu4** [floating-ui/floating-ui#2761]
**Describe the bug** A clear and concise description of what the bug is.

Hi, I'm using `floating-ui` to create floating menu for my rich text editor which itself is a scrollable area. The problem is that when I scroll this editor container, the floating menu does not follow the element to which it's attached. I made a codesandbox here (try to select some text and scroll the editor container), what should I change?

https://codesandbox.io/p/sandbox/controlled-bubble-menu-framer-latest-on-off-gzph6s?file=%2Fsrc%2FApp.js%3A40%2C1

**Comment by atomiks** [comment]
Ok I see!

> Do you have some suggestions?

You could animate `transform` only while selecting, or disable it while scrolling.

> Here is an official example with the same problem, how to solve it?

The context element needs to be a child of the scrolling container. You can add an empty div with the id/use a ref and it works.

```js
<div style={{ height: "200px", width: "200px", overflow: "auto" }}>
  <div id="context" />
  ...
</div>
```

**Comment by atomiks** [comment]
It is working, it's just you're not updating the position of the virtual element on scroll. `getBoundingClientRect()`  is returning the same values while scrolling as when you clicked, hence the position doesn't change.
