### ISSUE TITLE
Combine flip and shift middleware doesn't keep original placement

### ISSUE THREAD

**Issue by WebCimes** [floating-ui/floating-ui#2766]
**Describe the bug** 
I want to creating a floating element when I click a button, I set a placement "bottom" by default, but the flip middleware change the position of the floating element to the left side. But on the bottom placement, the floating element is not outside the overflow, so I don't understand why the flip middleware change the placement for the left side.

**To Reproduce**
You can see a demo of the problem on:
https://codesandbox.io/p/sandbox/green-bush-79m23l?file=%2Fsrc%2Findex.js%3A26%2C9-26%2C63

By default the floating element is set to "bottom" placement, but is final position is set to "left placement", like if it was outside the overflow.

**Expected behavior**
If you scroll down a little bit on the sandbox, the floating element will be set to the bottom placement, like I wanted for default placement, and you can notice it's not outside the overflow.
Also I want by default this floating element placement to bottom, and with the flip middleware **I want to allow every direction if the floating element it's hidden/outside overflow** of the viewport (`fallbackPlacements: ["top", "bottom", "left", "right"]`)

**Screenshots** 
By default wrong placement (left instead bottom):
![image](https://github.com/floating-ui/floating-ui/assets/43851969/d6895142-198e-4cd3-98c8-cd732f38a8a9)

That I want by default for placement (bottom):
![image](https://github.com/floating-ui/floating-ui/assets/43851969/1304df6a-4f2a-468a-b2d1-97d80d7690c5)

**Context:**
- OS: Windows
- Browser Firefox
- Version Floating UI 1.5.3

Thanks

**Comment by atomiks** [comment]
Set `crossAxis: false` in `flip()`.

See https://floating-ui.com/docs/flip#combining-with-shift

**Comment by WebCimes** [comment]
@atomiks  Thanks for your reply, I have already try to add `crossAxis: false` in `flip()` but when I do this, the floating element can no longer flip on left or right side, it only flip on top / bottom side. I want to permit the floating element to flip on all side (`fallbackPlacements: ["top", "bottom", "left", "right"]`).

Do you have an idea to do this?

Thanks

**Comment by atomiks** [comment]
It still flips to the left/right, but only if it overflows along the main (aka side) axis. So in the CodeSandbox demo, that means if the floating element overflows the bottom of the screen, it flips to the left.

There's an alternative, in which you place `shift()` _before_ `flip` and keep `crossAxis: true` (default):

```js
// Works fine for non-edge aligned placements
[shift(), flip()]
```

**Comment by WebCimes** [comment]
@atomiks thanks, I have try both solutions:
- with `crossAxis: false` the floating element go to the left side only if the viewport height is too small for contain the floating element on top and on bottom. (I have try to scroll bottom / top and right / left but the only way was viewport height smaller)
- with `shift()` before `flip()` all is working perfectly like I want! The default placement is conserved, and the other placements (include left) works well according the scroll axis and with default viewport height.

Thanks for your help and the tips!

**Comment by atomiks** [comment]
@WebCimes no problem, I think the docs should have a bigger heading section dedicated to this, with a demo highlighting the differences between each. Do you have a better CodeSandbox demo for this?

**Comment by WebCimes** [comment]
@atomiks It should be a great idea for the doc.

I have try to make 4 little sandbox for show the different step, (default placement `bottom` and `fallbackPlacements: ["top", "bottom", "left", "right"]` for all the sandbox):

- With `flip()` before `shift()` and `crossAxis: true` (default), final placement go on left side (flip before shift, it's like flip doesn't care about shift):
https://codesandbox.io/p/sandbox/nice-pateu-fgsmvj?file=%2Fsrc%2Findex.js%3A27%2C8

- With `flip()` before `shift()` and `crossAxis: false`, final placement still on top or bottom side, on normal viewport height:
https://codesandbox.io/p/sandbox/blue-smoke-yvhhk8?file=%2Fsrc%2Findex.js%3A29%2C12

- With `flip()` before `shift()` and `crossAxis: false`, final placement can go on left, and other sides, with small viewport height:
https://codesandbox.io/p/sandbox/admiring-smoke-7yys9m?file=%2Fsrc%2Findex.js%3A19%2C51

- With `shift()` before `flip()` and `crossAxis: true` (default), final placements works well in all direction:
https://codesandbox.io/p/sandbox/fervent-mountain-85fldn?file=%2Fsrc%2Findex.js%3A30%2C8

I hope it will be better for show the different ways.

Thanks :)

**Comment by WebCimes** [comment]
@atomiks With `shift()` before `flip()` just notice a small behavior, just before flip, the padding define (10px in de sandbox) in `shift()` (padding between floating element and the edge of the boundary) is not respect (the flip happen when the floating element is on the edge of the boudary)
Example : 
https://codesandbox.io/p/sandbox/naughty-neco-ddnrlt?file=%2Fsrc%2Findex.js%3A18%2C54

**Comment by atomiks** [comment]
Add `padding` in flip as well

**Comment by WebCimes** [comment]
thank you it's working, I hadn't thought of that
