### ISSUE TITLE
npm ERR! notarget No matching version found for @floating-ui/dom@^1.6.0.

### ISSUE THREAD

**Issue by bentaly** [floating-ui/floating-ui#2769]
**Describe the bug** A clear and concise description of what the bug is.

I'm trying to run an `npm update` but this package is a dependency on one of my project's dependencies and I'm getting the error.
```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @floating-ui/dom@^1.6.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

https://www.npmjs.com/package/@floating-ui/dom says it's at 1.6.0.

**To Reproduce**

Running  `npm view @floating-ui/dom` we can see it's at 1.5.4
```

@floating-ui/dom@1.5.4 | MIT | deps: 2 | versions: 63
Floating UI for the web
https://floating-ui.com

keywords: tooltip, popover, dropdown, menu, popup, positioning

dist
.tarball: https://nexus.harmonicsecurity.net/repository/npm/@floating-ui/dom/-/dom-1.5.4.tgz
.shasum: 28df1e1cb373884224a463235c218dcbd81a16bb
.integrity: sha512-jByEsHIY+eEdCjnTVu+E3ephzTOzkQ8hgUfGwos+bg7NlH33Zc5uO+QHz1mrQUOgIKKDD1RtS201P9NvAfq3XQ==
.unpackedSize: 143.7 kB

dependencies:
@floating-ui/core: ^1.5.3  @floating-ui/utils: ^0.2.0 

maintainers:
- fezvrasta <federico.zivolo@gmail.com>
- atomiks <cc.glows@gmail.com>

dist-tags:
latest: 1.5.4  

published 2 weeks ago by atomiks <cc.glows@gmail.com>

```

Not sure if this is an expected temporary lag (as it was published 9 hours or so ago, but thought I'd flag).

**Comment by atomiks** [comment]
> npm view @floating-ui/dom

Says `1.6.0` for me and installs fine. Try clearing your cache?

**Comment by bentaly** [comment]
<img width="778" alt="image" src="https://github.com/floating-ui/floating-ui/assets/4908256/03259a0b-6d7b-42a4-8216-635c6b60d616">


Still have the same issue, I'm using an internal registry, will see if that's related

**Comment by bentaly** [comment]
This was an internal registry issue. Apologies
