### ISSUE TITLE
[DOM] `popover` attribute collision detection fails with `absolute` strategy

### ISSUE THREAD

**Issue by ollicle** [floating-ui/floating-ui#2781]
When the floating element has a [popover](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/popover) attribute the overflow detection is failing.

**To Reproduce**

Demo: https://agate-equal-tang.glitch.me/
Demo code: https://glitch.com/edit/#!/agate-equal-tang

**Work around**

Don't use the computePosition 'absolute' strategy

1. Scroll the demo page up/down to place the buttons close to the top or bottom of the viewport…
2. before clicking the buttons.

**Expected behavior**

The non popover element is positioned as expected – avoiding the top/bottom of the viewport.

**Observed behaviour**

The popover element is not – cropped by the top of the viewport when the buttons are near the top.

**Context:**

Observed in:

- OS: Mac
- Chrome
- Version 121

**Comment by atomiks** [comment]
Also, it seems like positioning fails (when scrolling) with the `absolute` strategy if it's inside a containing block.

All of the tests for the top layer support were written using the `fixed` strategy, and it seems `absolute` needs some different checks.
