### ISSUE TITLE
Need help to make ui like this

### ISSUE THREAD

**Issue by venky9885** [floating-ui/floating-ui#2783]
### Discussed in https://github.com/floating-ui/floating-ui/discussions/2782

<div type='discussions-op-text'>

<sup>Originally posted by **venky9885** February  7, 2024</sup>
Help me to write code to make  field and popup to show attached to each other

[See this link](https://github.com/floating-ui/floating-ui/issues/2776#issuecomment-1925249565)</div>

**Comment by venky9885** [comment]
Also I need to know how to detect position after flipped

**Comment by atomiks** [comment]
Q&A can be kept in the discussions section, thank you!
