### ISSUE TITLE
computePosition is not returning position properly for SVG Element inside <mask> for FireFox

### ISSUE THREAD

**Issue by linusang** [floating-ui/floating-ui#2800]
**Describe the bug** A clear and concise description of what the bug is.
`computePosition()` is not calculating SVG elements as mask in FireFox browser properly.

**To Reproduce**

https://codesandbox.io/p/sandbox/adoring-black-phg3gd?file=%2Fsrc%2Findex.js

1. Open the above codesandbox in Firefox 
2. Should see the following (screenshot)
![image](https://github.com/floating-ui/floating-ui/assets/1967941/7f3594ea-240b-4410-bfef-07c1f67c992c)

**Expected behavior** A clear and concise description of what you expected to
happen.
1. Open the above codesandbox in Chrome
2. Should see the following (screenshot)
![image](https://github.com/floating-ui/floating-ui/assets/1967941/e0bbf4e3-0fad-4773-a264-47431c277315)

**Screenshots** If applicable, add screenshots to help explain your problem.
As above.

**Context:**

- OS: MacOS
- Browser: Chrome and FireFox
- Version: 
  - Chrome Version 121.0.6167.184 (Official Build) (arm64)
  - Firefox 122.0 (64-bit)

**Additional context** Add any other context about the problem here.

**Comment by atomiks** [comment]
In Firefox, the element returns the incorrect `.getBoundingClientRect()` value and 0 `width`/`height`.

I think this needs to be externally fixed by using a virtual element as the reference element.

```js
const virtualEl = {
  getBoundingClientRect() {
   if (!isFirefox) return maskRectElement.getBoundingClientRect();
    return {
      // correct values
    };
  },
  contextElement: maskRectElement,
};
```
