### ISSUE TITLE
When 'overflow: scroll' is applied to handle long floating content, the arrow is hidden too

### ISSUE THREAD

**Issue by annaruble** [floating-ui/floating-ui#2815]
**Describe the bug** 

I'm using floating-ui to build some Tooltips and some Popovers. Popovers are where I'm running into some trouble –

My popover has set defined height and width values. In most cases, the popovers content _should_ fit within those constraints, but I can't always guarantee that. If the content exceeds the provided space, it should offer a scroll in order to see the extended content without affecting the allotted height or width of the floating element.

However, due to the location of the arrow `div` living inside of the popover `div` and the positioning that is already set on those elements, when I set `overflow: scroll;` on the floating content, the arrow gets cut out of view due to it being "overflow" as a child element of the floating element.

**To Reproduce**
Forked from your [arrow middleware visualization example](https://floating-ui.com/docs/arrow#visualization), here's my [Code Sandbox link](https://codesandbox.io/p/sandbox/cranky-dijkstra-v9mpny?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cltj4rmtk00073b6i5hocbgj7%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cltj4rmtk00033b6ilqbd35nc%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cltj4rmtk00043b6i5vjb4sr7%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cltj4rmtk00063b6i103zrbuk%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cltj4rmtk00033b6ilqbd35nc%2522%253A%257B%2522id%2522%253A%2522cltj4rmtk00033b6ilqbd35nc%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cltotp7kg003o3b6hqoownslq%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A26%252C%2522startColumn%2522%253A14%252C%2522endLineNumber%2522%253A26%252C%2522endColumn%2522%253A14%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252Fstyles.css%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522cltotp7kg003o3b6hqoownslq%2522%257D%252C%2522cltj4rmtk00063b6i103zrbuk%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cltj4rmtk00053b6iboy16hdw%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522cltj4rmtk00063b6i103zrbuk%2522%252C%2522activeTabId%2522%253A%2522cltj4rmtk00053b6iboy16hdw%2522%257D%252C%2522cltj4rmtk00043b6i5vjb4sr7%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522cltj4rmtk00043b6i5vjb4sr7%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D) where this issue is clearly displayed

View the code sandbox link and see how it behaves with extra text in the floating element & `overflow: scroll` applied. The part of the arrow that should be visible is not able to be seen.

**Expected behavior** 
I would like to be able to have scrolling content in the floating element without losing the arrow.

**Screenshots** If applicable, add screenshots to help explain your problem.
A sample of my popover with overflow: scroll applied to the floating element, cutting off the arrow (turned red for visibility): 
![image](https://github.com/floating-ui/floating-ui/assets/32494683/16d2c7a3-deba-423c-9ebd-f38df07c2d8e)

**Context:**
N/A

**Additional context** 
N/A

**Comment by atomiks** [comment]
This is a CSS clipping issue, it can be solved by using a wrapper inside the floating element that has the `overflow` style applied, while the arrow is outside of it (but still inside the floating element).

**Comment by annaruble** [comment]
@atomiks That doesn't resolve the issue, it just migrates the problem - see screen recording. The screen behind the popover scrolls, but the arrow shifts up and it doesn't actually scroll the content itself, it scrolls the screen. 
https://github.com/floating-ui/floating-ui/assets/32494683/8a5177a2-6629-4b7d-a2a1-f09d82a069ba

The following screen recording is close to what I would expect, except the part of the arrow that's getting clipped off should stay present on the screen and locked to its position with the trigger element.
https://github.com/floating-ui/floating-ui/assets/32494683/17a27d5b-953a-40a5-9ada-b6f6e3844e27

Here's an approximation of my code with the valid positioning styles applied:
```
<div class="my-popover">
  <slot="my-trigger element"></slot>
  <div class="popover">
    <div class="floating-div">
      <div>Content inside the popover</div>
    </div>
    <div class="arrow"></div>
  </div>
</div>
</div>
```

with styling like this: 
```
.my-popover {
  position: relative;
  display: inline-block;
}

.popover {
  position: absolute;
  display: none;
  background: black;
  color: white;
  // we are setting the max width and height via the middleware provided by floating UI

  > .floating-div {
    overflow-y: scroll
  }
}

.arrow {
  position: absolute;
  width: 10px;
  height: 10px;
  background: inherit;
  transform: rotate(45deg);
}
```

If this truly is accomplishable within this library and as simple as you say, I'd love to see an example you put together with scrolling overflow content while keeping the arrow static. This feels like a common enough use case that a working example in the docs would be useful :) Thanks!

**Comment by atomiks** [comment]
That's because it needs a height to be able to scroll:
```css
  > .floating-div {
    overflow-y: scroll;
    height: 100%;
  }
```

**Comment by annaruble** [comment]
That worked when I set it to a defined value instead of a percentage -- thanks much!
