### ISSUE TITLE
Axe violations when using FloatingPortal and FloatingFocusManager

### ISSUE THREAD

**Issue by clay-anderson** [floating-ui/floating-ui#2823]
**Describe the bug**
When using FloatingPortal and FloatingFocusManager, the focus guard spans that are added are causing axe violations while testing with jest.

**To Reproduce**
I made a simple recreation of a component that I am working on, a header navigation item that opens a dropdown when clicked, and a test that checks to make sure there are no axe violations on that component when it is open in this [code sandbox](https://codesandbox.io/p/sandbox/floating-ui-react-dom-template-forked-kvt4js?file=%2Fsrc%2FApp.js%3A9%2C1). The test fails with the following error:
```
    expect(received).toHaveNoViolations(expected)

    Expected the HTML found at $('span[data-type="outside"][data-floating-ui-focus-guard=""][role="button"]:nth-child(2)') to have no violations:

    <span data-type="outside" tabindex="0" data-floating-ui-focus-guard="" style="border: 0px; height: 1px; margin: -1px; overflow: hidden; padding: 0px; position: fixed; white-space: nowrap; width: 1px; top: 0px; left: 0px;" role="button"></span>

    Received:

    "ARIA commands must have an accessible name (aria-command-name)"

    Fix any of the following:
      Element does not have text that is visible to screen readers
      aria-label attribute does not exist or is empty
      aria-labelledby attribute does not exist, references elements that do not exist or references elements that are empty
      Element has no title attribute

    You can find more information on this issue here: 
    https://dequeuniversity.com/rules/axe/4.7/aria-command-name?application=axeAPI
```
The FocusGuards that are getting added for the FloatingPortal and FloatingFocusManager are being [assigned `role="button"` in Safari](https://github.com/floating-ui/floating-ui/blob/master/packages/react/src/components/FocusGuard.tsx#L41-L47), but without any kind of accessible name so the test fails. We tried adding `guards={false}` to the FloatingFocusManager to workaround the failing test, but that did not solve the issue.

**Expected behavior**
Tests like this should pass, a possible solution would be adding an `aria-hidden` to the span. 

**Context:**
The versions of all the libraries being used is in the code sandbox package

**Comment by atomiks** [comment]
This has been reported several times, but it's not actually a real issue (which I guess you know). The focus guards need to receive focus for Safari VoiceOver's virtual cursor, which then immediately relocate focus elsewhere. The fact that it has no accessible name is irrelevant since focus isn't kept on the element. I'm not sure what workaround can be used for Axe specifically.
