### ISSUE TITLE
[React] `refs.floating.current` is `null` inside `useEffect` when using `FloatingPortal`

### ISSUE THREAD

**Issue by mwiencek** [floating-ui/floating-ui#2827]
**Describe the bug**

I'm using the `useFloating` hook from `@floating-ui/react`.

`refs.floating.current` is `null` inside `useEffect` when the floating element is wrapped in `FloatingPortal`.

**To Reproduce**

1. Go to https://codesandbox.io/p/sandbox/floating-ui-react-dom-template-forked-dhmfry
2. Click on the "Preview console" button (near the `https://dhmfry.csb.app/` URL input).
3. Observe that `floating.current` is defined for the first floating element (not using `FloatingPortal`) but is null for the second (using `FloatingPortal`).

Note: codesandbox only works for me in Chrome, not Firefox. 🤷

**Expected behavior**

I'd expect `refs.floating.current` to be defined inside `useEffect` regardless of whether `FloatingPortal` is used.

https://floating-ui.com/docs/useFloating#floating says that "You can access this inside an event handler or in an effect," and doesn't mention any exception for portals.

I didn't find any documentation relevant to this issue in https://floating-ui.com/docs/FloatingPortal either.

**Context:**

- OS: N/A
- Browser: Latest versions of Chrome & Firefox

**Comment by atomiks** [comment]
`FloatingPortal` has to create and mount a new node, which means it's not available until a second render pass. I recommend using `elements.floating` instead, since it'll reactively check if it exists:

```js
const {elements} = useFloating();

useEffect(() => {
  if (!elements.floating) return;
  // logic...
}, [elements.floating]);
```

**Comment by mwiencek** [comment]
Thanks @atomiks! I must have glossed over `elements` because the documentation implies that it wouldn't generally be used for effects:

> The elements as set by the refs, useful for access during rendering (as opposed to inside an event handler or an effect).

However, upon reading the code I see that the `elements` are actually stored in state and thus are reactive, which is exactly what I need. Thank you for pointing that out.

I guess this issue can be closed due to the technical limitation, but perhaps the documentation can be improved?

**Comment by atomiks** [comment]
Yeah the docs should probably be updated to specify that `refs` should only be used in event handlers, while `elements` used in effects and during render, since it enables reactive checks.
