### ISSUE TITLE
popper misplaced on Y axis

### ISSUE THREAD

**Issue by dakhnod** [floating-ui/floating-ui#2828]
Popper floats up on y axis under certain circumstances.

I am really hoping someone could hint me in the right direction here.
Under certain circumstances, I cannot quite pin it down, the Popper is influenced by some other containers and placed too high.

1. Go to https://codesandbox.io/p/sandbox/popper-only-twdjcy
2. Pay attention to the Popper being placed quite a bit higher than the "Clone of ..." span

**Expected behavior** 
I was expecting (hoping) the Popper to be directly on the top edge of the Span

- OS: Android, Linux, Windows
- Browser; Chrome, Firefox
- Version: latest

Sorry if this does not belong here, I have been desperately searching for a solution for a long time...
![127 0 0 1_3000_www_demo html (1)](https://github.com/floating-ui/floating-ui/assets/26143255/d483a901-0c6a-4a9c-a5e9-e95ad5dc50e0)

**Comment by atomiks** [comment]
Thank you for your issue,

We have now released [Floating UI v1](https://floating-ui.com/docs/motivation), the successor to Popper, where [this issue has been fixed](https://codesandbox.io/p/sandbox/popper-only-forked-f5s65j?file=%2Findex.html%3A2285%2C1). 

Popper 2 is no longer maintained and has ceased development, so this issue will be closed.
