### ISSUE TITLE
focus is visible even if keyboard is not being used

### ISSUE THREAD

**Issue by herzaso** [floating-ui/floating-ui#2836]
### Discussed in https://github.com/floating-ui/floating-ui/discussions/2806

<div type='discussions-op-text'>

<sup>Originally posted by **herzaso** February 25, 2024</sup>
I have a menu (floating-ui) that is opened with a click of a button.
When I click on any option, the menu is closed and the focus is not visible.
However, when I click on ESC key, the menu is dismissed and the focus is visible on the button trigger.

Is that intentional? Why is that?</div>

I'm sorry if opening an issue is not the right path - the discussion is 1 month old and I didn't know how to bump it

**Comment by atomiks** [comment]
Can you provide a CodeSandbox or similar reproduction?

**Comment by atomiks** [comment]
If you can provide one this issue can be re-opened. Thank you!
