### ISSUE TITLE
webcomponent floating UI: Panel Positioning Issue

### ISSUE THREAD

**Issue by ChellappanRajan** [floating-ui/floating-ui#2847]
**Describe the bug** 
       Floating UI positioning is incorrect when used with Web Components with popover attribute. It is working fine with normal example, not sure why it is happening only with shadomDOM.
  
[playground](https://lit.dev/playground/#project=W3sibmFtZSI6InNpbXBsZS1ncmVldGluZy50cyIsImNvbnRlbnQiOiJpbXBvcnQgeyBodG1sLCBjc3MsIExpdEVsZW1lbnQgfSBmcm9tICdsaXQnO1xuaW1wb3J0IHsgY3VzdG9tRWxlbWVudCwgcHJvcGVydHkgfSBmcm9tICdsaXQvZGVjb3JhdG9ycy5qcyc7XG5pbXBvcnQgJy4vbW9kYWwuanMnO1xuaW1wb3J0ICcuL3BhbmVsLmpzJztcbmltcG9ydCB7IHVzZUZsb2F0aW5nVUkgfSBmcm9tICcuL2Zsb2F0aW4tdWkuanMnO1xuQGN1c3RvbUVsZW1lbnQoJ3NpbXBsZS1ncmVldGluZycpXG5leHBvcnQgY2xhc3MgU2ltcGxlR3JlZXRpbmcgZXh0ZW5kcyBMaXRFbGVtZW50IHtcbiAgc3RhdGljIHN0eWxlcyA9IGNzc2BcbiAgICAgIC5wYW5lbHtcbiAgbWFyZ2luOiAwO1xuICBwYWRkaW5nOiAwO1xuICBib3JkZXI6IG5vbmU7XG4gIG92ZXJmbG93OiB2aXNpYmxlO31cbiAgICAgIGA7XG4gIGdldCBwYW5lbEVsZW1lbnQoKTogSFRNTEVsZW1lbnQge1xuICAgIHJldHVybiB0aGlzLnNoYWRvd1Jvb3QucXVlcnlTZWxlY3Rvcignc2ltcGxlLXBhbmVsJykhO1xuICB9XG5cbiAgcmVuZGVyKCkge1xuICAgIHJldHVybiBodG1sYFxuICAgICAgICA8bXktbW9kYWw-XG4gICAgICAgICAgPGRpdiBjbGFzcz1cInBhcmVudFwiID5cbiAgICAgICAgPGlucHV0IEBjbGljaz0keygpID0-IHtcbiAgICAgICAgaWYgKHRoaXMucGFuZWxFbGVtZW50LnN0eWxlLmRpc3BsYXkgPT09ICdibG9jaycpIHtcbiAgICAgICAgICB0aGlzLnBhbmVsRWxlbWVudC5zdHlsZS5kaXNwbGF5ID0gJ25vbmUnO1xuICAgICAgICB9IGVsc2Uge1xuICAgICAgICAgIHRoaXMucGFuZWxFbGVtZW50LnN0eWxlLmRpc3BsYXkgPSAnYmxvY2snO1xuICAgICAgICB9XG4gICAgICAgIHRoaXMucGFuZWxFbGVtZW50LnRvZ2dsZVBvcG92ZXIoKTtcbiAgICAgICAgY29uc3QgdHJpZ2dlclJlZiA9IHRoaXMuc2hhZG93Um9vdC5xdWVyeVNlbGVjdG9yKCdpbnB1dCcpO1xuICAgICAgICB1c2VGbG9hdGluZ1VJKHRyaWdnZXJSZWYsIHRoaXMucGFuZWxFbGVtZW50KTtcbiAgICAgIH1cbiAgICAgIH0gLz5cbiAgICAgICAgPHNpbXBsZS1wYW5lbCBjbGFzcz1cInBvcG92ZXJcIiBwb3BvdmVyIHN0eWxlPVwiZGlzcGxheTpub25lXCI-XG4gICAgICAgICAgPC9zaW1wbGUtcGFuZWw-XG4gICAgICAgIDwvZGl2PiAgXG4gICAgICAgICAgXG4gICAgICAgIDwvbXktbW9kYWw-XG4gICAgICAgIGA7XG4gIH1cbn1cbiJ9LHsibmFtZSI6ImluZGV4Lmh0bWwiLCJjb250ZW50IjoiPCFET0NUWVBFIGh0bWw-XG48aGVhZD5cbiAgPHNjcmlwdCB0eXBlPVwibW9kdWxlXCIgc3JjPVwiLi9zaW1wbGUtZ3JlZXRpbmcuanNcIj48L3NjcmlwdD5cbjwvaGVhZD5cbjxib2R5PlxuICA8c2ltcGxlLWdyZWV0aW5nIG5hbWU9XCJXb3JsZFwiPjwvc2ltcGxlLWdyZWV0aW5nPlxuPC9ib2R5PlxuIn0seyJuYW1lIjoicGFja2FnZS5qc29uIiwiY29udGVudCI6IntcbiAgXCJkZXBlbmRlbmNpZXNcIjoge1xuICAgIFwibGl0XCI6IFwiXjMuMC4wXCIsXG4gICAgXCJAbGl0L3JlYWN0aXZlLWVsZW1lbnRcIjogXCJeMi4wLjBcIixcbiAgICBcImxpdC1lbGVtZW50XCI6IFwiXjQuMC4wXCIsXG4gICAgXCJsaXQtaHRtbFwiOiBcIl4zLjAuMFwiXG4gIH1cbn0iLCJoaWRkZW4iOnRydWV9LHsibmFtZSI6Im1vZGFsLnRzIiwiY29udGVudCI6ImltcG9ydCB7aHRtbCwgY3NzLCBMaXRFbGVtZW50fSBmcm9tICdsaXQnO1xuaW1wb3J0IHtjdXN0b21FbGVtZW50LCBwcm9wZXJ0eX0gZnJvbSAnbGl0L2RlY29yYXRvcnMuanMnO1xuXG5AY3VzdG9tRWxlbWVudCgnbXktbW9kYWwnKVxuZXhwb3J0IGNsYXNzIE15TW9kYWwgZXh0ZW5kcyBMaXRFbGVtZW50IHtcbiAgc3RhdGljIHN0eWxlcyA9IGNzc2BcbiAgICAgIC5teS1tb2RhbCB7XG4gIGRpc3BsYXk6IGZsZXg7XG4gIGFsaWduLWl0ZW1zOiBjZW50ZXI7XG4gIGp1c3RpZnktY29udGVudDogY2VudGVyO1xuICBwb3NpdGlvbjogZml4ZWQ7XG4gIHdpZHRoOiAxMDB2dztcbiAgaGVpZ2h0OiAxMDB2aDtcbiAgaW5zZXQtYmxvY2stc3RhcnQ6IDA7XG4gIGluc2V0LWlubGluZS1zdGFydDogMDtcbiAgei1pbmRleDo1MDA7XG5cbiAgdmlzaWJpbGl0eTogaGlkZGVuO1xuICBiYWNrZ3JvdW5kLWNvbG9yOiAjYjRiNGI0NGY7XG4gICAgICBvcGFjaXR5OiAxO1xuICAgIHZpc2liaWxpdHk6IHZpc2libGU7XG59XG4gICAgICAubW9kYWxfX2hlYWRlciB7XG4gIGRpc3BsYXk6IGZsZXg7XG4gIGFsaWduLWl0ZW1zOiBjZW50ZXI7XG4gIGp1c3RpZnktY29udGVudDogc3BhY2UtYmV0d2VlbjtcbiAgcG9zaXRpb246IHJlbGF0aXZlO1xufVxuICAgICAgXG4gICAgICAubW9kYWxfX2hlYWRlci1jb250ZW50IHtcbiAgZGlzcGxheTogZmxleDtcbiAgYWxpZ24taXRlbXM6IGNlbnRlcjtcbiAganVzdGlmeS1jb250ZW50OiBmbGV4LXN0YXJ0O1xuICBmbGV4LXdyYXA6IHdyYXA7XG4gIGZsZXgtYmFzaXM6IDEwMCU7XG59XG5cbiAgICAgIFxuICAgICAgLm15LW1vZGFsIC5pcy1hY3RpdmUge1xuICAgIFxuICB9XG4gICAgICAubW9kYWxfX2JvZHkge1xuICBmbGV4LWJhc2lzOiAxMDAlO1xuICBvdmVyZmxvdzogYXV0bztcbn1cblxuICAgICAgYDtcblxuICBAcHJvcGVydHkoKVxuICBuYW1lID0gJ1NvbWVib2R5JztcblxuICByZW5kZXIoKSB7XG4gICAgcmV0dXJuIGh0bWxgXG4gICAgICAgIDxkaXZcbiAgICAgICAgY2xhc3M9XCJteS1tb2RhbCBpcy1hY3RpdmVcIlxuICAgICAgPlxuICAgICAgICA8YXJ0aWNsZSBwYXJ0PVwid2luZG93XCIgY2xhc3M9XCJtb2RhbF9fd2luZG93XCIgdGFiSW5kZXg9JHswfT5cbiAgICAgICAgICA8ZGl2ICBjbGFzcz1cIm1vZGFsX19oZWFkZXJcIj5cbiAgICAgICAgICAgIFxuICAgICAgICAgICAgPGRpdiBjbGFzcz1cIm1vZGFsX19oZWFkZXItY29udGVudFwiID5cbiAgICAgICAgICAgICAgPHNsb3QgIG5hbWU9XCJoZWFkZXJcIj48L3Nsb3Q-XG4gICAgICAgICAgICA8L2Rpdj5cbiAgICAgICAgICAgIDxzbG90IHBhcnQ9XCJwYXJ0LWFjdGlvbnNcIiBuYW1lPVwiYWN0aW9uc1wiPjwvc2xvdD5cbiAgICAgICAgICAgIFxuICAgICAgICAgIDwvZGl2PlxuXG4gICAgICAgICAgPGRpdiBjbGFzcz1cIm1vZGFsX19ib2R5XCI-PHNsb3QgcGFydD1cInBhcnQtZGVmYXVsdFwiPjwvc2xvdD48L2Rpdj5cbiAgICAgICAgIFxuICAgICAgICAgIDxkaXYgY2xhc3M9XCJtb2RhbF9fZm9vdGVyXCI-PHNsb3QgcGFydD1cInBhcnQtZm9vdGVyXCIgbmFtZT1cImZvb3RlclwiPjwvc2xvdD48L2Rpdj4gXG4gICAgICAgIDwvYXJ0aWNsZT5cbiAgICAgIDwvZGl2PlxuICAgICAgICBgO1xuICB9XG59IFxuIn0seyJuYW1lIjoicGFuZWwudHMiLCJjb250ZW50IjoiaW1wb3J0IHtodG1sLCBjc3MsIExpdEVsZW1lbnR9IGZyb20gJ2xpdCc7XG5pbXBvcnQge2N1c3RvbUVsZW1lbnQsIHByb3BlcnR5fSBmcm9tICdsaXQvZGVjb3JhdG9ycy5qcyc7XG5cbkBjdXN0b21FbGVtZW50KCdzaW1wbGUtcGFuZWwnKVxuZXhwb3J0IGNsYXNzIFNpbXBsZVBhbmVsIGV4dGVuZHMgTGl0RWxlbWVudCB7XG4gIHN0YXRpYyBzdHlsZXMgPSBjc3NgZGl2IHsgY29sb3I6d2hpdGU7YmFja2dyb3VuZDogYmx1ZTtib3JkZXI6MXB4IHNvbGlkIHJlZDsgaGVpZ2h0OjEwMHB4O3dpZHRoOjEwMHB4IH1gO1xuXG4gXG4gIHJlbmRlcigpIHtcbiAgICByZXR1cm4gaHRtbGBcbiAgICAgICAgPGRpdj5cbiAgICAgICAgICAgIFBhbmVsXG4gICAgICAgIDwvZGl2PlxuICAgICBcbiAgICAgICAgYDtcbiAgfVxufVxuIn0seyJuYW1lIjoiZmxvYXRpbi11aS50cyIsImNvbnRlbnQiOiJpbXBvcnQgeyBNaWRkbGV3YXJlU3RhdGUsIHBsYXRmb3JtLCBQbGFjZW1lbnQsIGFycm93LCBhdXRvUGxhY2VtZW50LCBjb21wdXRlUG9zaXRpb24sIGhpZGUsIG9mZnNldCwgc2hpZnQsIHNpemUgfSBmcm9tICdAZmxvYXRpbmctdWkvZG9tJztcblxuY29uc3QgbWlkZGxld2FyZSA9IFtcbiAgb2Zmc2V0KHsgbWFpbkF4aXM6IDAsIGNyb3NzQXhpczogMCB9KSxcbiAgb2Zmc2V0KDApLFxuICBhdXRvUGxhY2VtZW50KHsgYWxsb3dlZFBsYWNlbWVudHM6IFsnYm90dG9tLXN0YXJ0JywgJ3RvcC1lbmQnLCAnYm90dG9tLWVuZCcsICd0b3Atc3RhcnQnXSB9KSxcbiAgc2hpZnQoKSxcbiAgaGlkZSh7XG4gICAgc3RyYXRlZ3k6ICdyZWZlcmVuY2VIaWRkZW4nIC8vICdyZWZlcmVuY2VIaWRkZW4nIGJ5IGRlZmF1bHRcbiAgfSlcbl07XG5cbmV4cG9ydCBmdW5jdGlvbiB1c2VGbG9hdGluZ1VJKHRyaWdnZXIscGFuZWwpe1xuXG5jb21wdXRlUG9zaXRpb24odHJpZ2dlciwgcGFuZWwsIHtcbiAgbWlkZGxld2FyZTogbWlkZGxld2FyZSxcbiAgc3RyYXRlZ3k6J2ZpeGVkJ1xufSkudGhlbigoeyB4LCB5IH0pID0-IHtcbiAgT2JqZWN0LmFzc2lnbihwYW5lbC5zdHlsZSwge1xuICAgIGxlZnQ6IGAwcHhgLFxuICAgIHRvcDogYDBweGAsXG4gICAgdHJhbnNmb3JtOiBgdHJhbnNsYXRlKCR7eH1weCwgJHt5fXB4KWAsXG5cbiAgfSl9In1d)

**Context:**

**Additional context** Add any other context about the problem here.

**Comment by atomiks** [comment]
Floating element just needs `margin: 0`

**Comment by ChellappanRajan** [comment]
> Floating element just needs `margin: 0`

Hi @atomiks  Thanks for quick answer, It is working fine., Just curious can you please explain why we need to set margin:0?

**Comment by atomiks** [comment]
The native elements have the margins set by default. Margins affect absolutely positioned elements and since it's not considered when calculating the coords, it can be off without `margin: 0`.

**Comment by ChellappanRajan** [comment]
> The native elements have the margins set by default. Margins affect absolutely positioned elements and since it's not considered when calculating the coords, it can be off without `margin: 0`.

Thank you so much
