### ISSUE TITLE
Adaptive function

### ISSUE THREAD

**Issue by Gao-Jie-Christine** [floating-ui/floating-ui#2851]
When i use the  Adaptive tool named autofit.js, the Drop-down box will float .When i scroll my mouse wheel to change the browser screen size, the drop-down box's position will float as page proportions change but not  be stable and fixed.
![float_dropdownbox](https://github.com/floating-ui/floating-ui/assets/164596562/300aefb0-b614-4e50-bfe9-094c15552471)
![use_autofit](https://github.com/floating-ui/floating-ui/assets/164596562/502d5f7d-37e4-4e88-9e16-5a937dd5fe4f)

**Comment by atomiks** [comment]
Thank you for your issue, however there is not enough information to help. We need a reproduction to debug the issue, and the issue can be re-opened if provided.

**Comment by Gao-Jie-Christine** [comment]
[issue.md](https://github.com/floating-ui/floating-ui/files/14905389/issue.md)
