### ISSUE TITLE
autoUpdate never settle when reference is in a scrollable div

### ISSUE THREAD

**Issue by TeaBough** [floating-ui/floating-ui#2854]
**Describe the bug** 
The autoUpdate never settle when reference element in a div that scrolls.

**To Reproduce**
https://codesandbox.io/p/sandbox/cool-frost-fpx5xp

1. Start scrolling the gray area
2. Check the logs in the console

**Expected behavior** 
It should not autoUpdate indefinitely

**Additional context**
The issue arised at release `0.24.4`, no problem in `0.24.3`

**Comment by atomiks** [comment]
See https://github.com/floating-ui/floating-ui/issues/2831
