### ISSUE TITLE
The tooltip should be visible when I hover over it.

### ISSUE THREAD

**Issue by ns-harshp** [floating-ui/floating-ui#2856]
**Describe the bug** When I hover over the tooltip, it disappears, but I want that tooltip to stay.

**To Reproduce**
https://codesandbox.io/p/sandbox/react-floating-ui-tooltip-wvr3dk?file=%2Fsrc%2Ftooltip.tsx
https://codesandbox.io/p/sandbox/floating-ui-react-dom-template-forked-38qgfm?file=%2Fsrc%2FApp.js

1. Hover over the button
2. When you see tooltip then hover over tooltip

https://github.com/floating-ui/floating-ui/assets/159230132/d21c43e7-7942-4413-a4e6-122f04a7e211

**Comment by atomiks** [comment]
See https://floating-ui.com/docs/useHover#safepolygon

**Comment by anand24816** [comment]
Hey, @atomiks  , I am using safePolygon, but above problem still exist for me - 
https://codesandbox.io/p/sandbox/late-https-lu3833
