### ISSUE TITLE
Floating UI Position Incorrect When Modal is Nested Inside Drawer Component

### ISSUE THREAD

**Issue by ChellappanRajan** [floating-ui/floating-ui#2858]
We have developed custom modal, drawer, and datepicker components as web components using ShadowDOM. These components utilize the 'popover' attribute and 'floating-ui' internally for positioning the datepicker container. However, when we place a modal inside a drawer and then place a datepicker inside the drawer, the floating UI position becomes incorrect.

In the parent modal, I have applied 'transform: translate(-50%,-50%)'. If I remove that, the datepicker and floating UI positions work correctly.

I have created a repository [here](https://stackblitz.com/edit/vitejs-vite-jzzg6c?file=src%2Fdrawer.ts).

To see the issue, click the 'show drawer' button to open a new drawer on the right side. Then, click the input element; the panel position is incorrect.

**Screenshots** If applicable, add screenshots to help explain your problem.

**Context:**

**Additional context** Add any other context about the problem here.

**Comment by atomiks** [comment]
Is this not correct?
<img width="699" alt="Screenshot 2024-04-15 at 11 55 25 PM" src="https://github.com/floating-ui/floating-ui/assets/22450188/cba5333b-24cf-45bc-bd3f-702911e23204">

**Comment by ChellappanRajan** [comment]
> Is this not correct? <img alt="Screenshot 2024-04-15 at 11 55 25 PM" width="699" src="https://private-user-images.githubusercontent.com/22450188/322506014-cba5333b-24cf-45bc-bd3f-702911e23204.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyMDA0NjEsIm5iZiI6MTcxMzIwMDE2MSwicGF0aCI6Ii8yMjQ1MDE4OC8zMjI1MDYwMTQtY2JhNTMzM2ItMjRjZi00NWJjLWJkM2YtNzAyOTExZTIzMjA0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE1VDE2NTYwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI4MjRhMzdlNWI3OWRjYmNjMzYzOGU4ZWE4MDNlZjczOTk1NWVkOGU0NWFmNDZhNGQxYTQ4MGI1MjQzMTY1Y2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VrjG1Ig_nPURjomOZaFLseJcHVn-KmiwG_YtrKuE6Hs">

It is working fine on a small screen; however, if I go fullscreen on this page (https://vitejsvitejzzg6c-drf5--5173--7dbe22a9.local-credentialless.webcontainer.io/) and open the drawer, then clicking on the input field to open the panel causes the floating panel's position to be incorrect.

<img width="1434" alt="Screenshot 2024-04-15 at 10 26 42 PM" src="https://github.com/floating-ui/floating-ui/assets/22997191/a0615af0-7cd0-469b-b9ea-40dca475f917">

**Comment by atomiks** [comment]
Hmm, yeah I see that as well. Not sure what would cause it so will need some investigating.

**Comment by ChellappanRajan** [comment]
> Hmm, yeah I see that as well. Not sure what would cause it so will need some investigating.
> 
> > transform: translate(-50%,-50%)
> 
> A new "containing block" gets created in this situation, and most positioning bugs that appear now seem to be related to handling this layout situation
> 
> Looks like it's related to collision detection when using `shift()`. When removing that middleware, it's positioned correctly. One possible workaround is to use an empty boundary `shift({ boundary: [] })` instead of the default `clippingAncestors`. Now it will only detect the root viewport collision instead of the incorrectly-calculated `clippingAncestors`, which may be fine in many situations with top-layer elements...

Thank you for sharing the workaround. There is one more issue I found in our application regarding the issue with the hide middleware, it seems that it returns 'hide', which might be causing the panel to not open consistently. Do you think this could be related to the same issue you mentioned earlier
```

If I set the display property based on the hide flag, the panel always remains closed.

export function useFloatingUI(trigger: any, panel: any) {
  computePosition(trigger, panel, {
    middleware: middleware,
    strategy: 'fixed',
  }).then(({ x, y, middlewareData }) => {
    const { hide } = middlewareData;
    Object.assign(panel.style, {
      left: `0px`,
      top: `0px`,
      transform: `translate(${x}px, ${y}px)`,
      // display:hide ? 'none': 'block'
    });
  });
}
```
