### ISSUE TITLE
List navigation doesn't scroll to selected item when other focusable elements are present in popover

### ISSUE THREAD

**Issue by kevinkucharczyk** [floating-ui/floating-ui#2861]
**Describe the bug** A clear and concise description of what the bug is.
I'm building a "select" component, much like the [Emoji Picker](https://codesandbox.io/s/nameless-glade-kz3pfc?file=/src/App.tsx) example, where the floating element contains a search input to filter the select options below it.

Typically, the list navigation hook will scroll to the selected item (if present) when opening the popover:
![CleanShot 2024-04-16 at 08 09 13](https://github.com/floating-ui/floating-ui/assets/3127419/91086f15-140b-451f-b2e3-8613db33df17)

However, when the search input is present, the autoscroll-on-open doesn't happen:
![CleanShot 2024-04-16 at 08 08 53](https://github.com/floating-ui/floating-ui/assets/3127419/90e5572a-bad1-4cee-9ce0-1df9b0bf4e82)

**To Reproduce**
I have prepared two sandboxes (based on the [Emoji Picker](https://codesandbox.io/s/nameless-glade-kz3pfc?file=/src/App.tsx) and [Virtualized Select](https://codesandbox.io/s/l10rjs?file=/src/App.tsx) examples)
- without input: https://codesandbox.io/p/sandbox/frosty-austin-hsypk5?file=%2Fsrc%2FApp.tsx%3A21%2C25
- with input: https://codesandbox.io/p/sandbox/unruffled-ioana-mfyk6w?file=%2Fsrc%2FApp.tsx

1. Visit one of the sandboxes
2. Click the button to open the popover
3. Scroll down the list and select an item
4. Click the button again to open the popover

**Expected behavior** A clear and concise description of what you expected to
happen.
The popover should scroll to the selected element on open, even if an input is present.

**Context:**

- OS: macOS Ventura 13.4.1
- Browser: Chrome Version 123.0.6312.123, Firefox 124.0.2

**Comment by atomiks** [comment]
What if the input isn't part of the same scrolling container? The UI is problematic to begin with since the input is hidden if it scrolls to the item. The input and listbox should scroll separately so the input is always visible?

**Comment by kevinkucharczyk** [comment]
@atomiks that did work! https://codesandbox.io/p/sandbox/romantic-glitter-ll2gm3?file=%2Fsrc%2FApp.tsx%3A143%2C31

In my app, however, that still didn't fix it. I found that it's due to me using `FloatingList`, which I recreated in this example: https://codesandbox.io/p/sandbox/trusting-sunset-wgvtfc?file=%2Fsrc%2FApp.tsx%3A178%2C23

When `FloatingList` is used, the scroll doesn't happen - presumably because the element refs/indices are all set too late.
