### ISSUE TITLE
Tooltip position is not updated when resizing window

### ISSUE THREAD

**Issue by Stanzilla** [floating-ui/floating-ui#2862]
**Describe the bug** A clear and concise description of what the bug is.

I'm using FloatingUI in an Electron app with a navigation on the left side to draw tooltips for those menu items. When I resize the window, the tooltip positions are not updated and "disappear".

**To Reproduce**

> - @floating-ui/react-dom: https://codesandbox.io/s/floating-ui-react-dom-template-qfufud?file=/src/App.js

Getting a "forks are not allowed" error there.

The code is fairly simple though: 

```ts
import React, { useRef, useState } from 'react';
import { arrow, FloatingArrow, useFloating } from '@floating-ui/react';
import { NavLink, NavLinkProps } from 'react-router-dom';

interface Props extends NavLinkProps {
  title: string;
  image?: React.JSX.Element;
}

const NavigationLink = ({ title, image, ...rest }: Props) => {
  const arrowRef = useRef(null);
  const { refs, floatingStyles, context } = useFloating({
    placement: 'right',
    middleware: [
      arrow({
        element: arrowRef,
      }),
    ],
  });

  const [isHovered, setIsHovered] = useState(false);

  return (
    <NavLink
      ref={refs.setReference}
      {...rest}
      onMouseEnter={() => setIsHovered(true)}
      onMouseLeave={() => setIsHovered(false)}
      className={({ isActive }) =>
        `text-m group flex cursor-pointer items-center rounded-lg border border-transparent p-4 font-semibold text-white text-white hover:border-wago-red/50 hover:bg-wago-red/10 hover:shadow-sm hover:shadow-wago-red focus:outline-none${
          isActive
            ? ' text-m group flex items-center rounded-lg border border-wago-red/50 bg-wago-red/10 text-white shadow-sm shadow-wago-red focus:outline-none'
            : ''
        }`
      }
    >
      <div className="h-8 w-8 text-gray-300">{image ?? ' '}</div>
      <div
        ref={refs.setFloating}
        style={{
          ...floatingStyles,
          top: -24,
          left: 16,
        }}
        className={`z-50 rounded-lg bg-wago-light p-4 ${
          isHovered ? 'block' : 'hidden'
        }`}
      >
        <FloatingArrow
          ref={arrowRef}
          context={context}
          className="fill-wago-light"
          staticOffset="unset"
        />
        {title}
      </div>
    </NavLink>
  );
};

export default NavigationLink;
```

The tricky part is 

```ts
style={{
          ...floatingStyles,
          top: -24,
          left: 16,
        }}
```

if I remove that, it gets recalculated fine, but I need those offsets because it looks wrong otherwise.

![image](https://github.com/floating-ui/floating-ui/assets/75278/088687d8-d323-447e-9fcd-c82867bd737b)

1. The hard part is having an electron app to test
2. Include the above component in a place where the tooltip position would have to be recalculated when resizing a window
![image](https://github.com/floating-ui/floating-ui/assets/75278/d62d2e56-8a83-4db0-85bc-e8b7061c63dc)

after resize

![image](https://github.com/floating-ui/floating-ui/assets/75278/517f685d-a92e-4c91-91fc-1e22c39667c4)

**Expected behavior** A clear and concise description of what you expected to
happen.

The position is properly recalculated

**Screenshots** If applicable, add screenshots to help explain your problem.

**Context:**

- OS: [e.g. iOS] Linux
- Browser [e.g. chrome, safari] Chrome (Electron) 29.3.0
- Version [e.g. 22] "@floating-ui/react": "^0.26.12",

**Additional context** Add any other context about the problem here.

What I can do to fix it is something dumb like

```
const [resizeCount, setResizeCount] = useState(0); // Add a resizeCount state

  const handleResize = useCallback(() => {
    setResizeCount((prevCount) => prevCount + 1); // Update the resizeCount state to trigger a re-render
  }, []);

  useEffect(() => {
    window.addEventListener('resize', handleResize);

    return () => {
      window.removeEventListener('resize', handleResize);
    };
  }, [handleResize]);
  
  ...
  <div
        key={resizeCount}
        ref={refs.setFloating}
...
```

but I was hoping there is a better solution

**Comment by atomiks** [comment]
By default, floating elements don't remain anchored when scrolling and resizing because we don't know if you're conditionally rendering them or hiding them with CSS.

This is documented here: https://floating-ui.com/docs/react#anchoring

Add `whileElementsMounted: autoUpdate` to your options if conditionally rendering it.

> but I need those offsets because it looks wrong otherwise

You shouldn't need to do this. It's likely your anchor/reference element has some "invisible" padding that prevents it from being correctly centered visually but affects its layout still. If you make the anchor element correctly sized, you shouldn't need to add manual offsets which come with a variety of problems in certain situations.

**Comment by Stanzilla** [comment]
> By default, floating elements don't remain anchored when scrolling and resizing because we don't know if you're conditionally rendering them or hiding them with CSS.
> 
> This is documented here: [floating-ui.com/docs/react#anchoring](https://floating-ui.com/docs/react#anchoring)
> 
> Add `whileElementsMounted: autoUpdate` to your options if conditionally rendering it.
> 
> > but I need those offsets because it looks wrong otherwise
> 
> You shouldn't need to do this. It's likely your anchor/reference element has some "invisible" padding that prevents it from being correctly centered visually but affects its layout still. If you make the anchor element correctly sized, you shouldn't need to add manual offsets which come with a variety of problems in certain situations.

Interesting, If I add `whileElementsMounted: autoUpdate` it does indeed work better and I can drop my top offset to `0`, I still have to do the spread of the floatingStyles default though.
