### ISSUE TITLE
Duplicate generated type aliases

### ISSUE THREAD

**Issue by atomiks** [floating-ui/floating-ui#2863]
When hovering over some module definitions in VS Code, you'll see a `_2` indicating a separate type was generated. This happens for `Derivable` and `React` sometimes:

- `Derivable_2`
- `React_2`

```js
(alias) const shift: (options?: ShiftOptions | Derivable_2<ShiftOptions>) => Middleware
```

```js
(alias) function useInteractions(propsList?: Array<ElementProps | void>): {
    getReferenceProps: (userProps?: React_2.HTMLProps<Element>) => Record<string, unknown>;
    getFloatingProps: (userProps?: React_2.HTMLProps<HTMLElement>) => Record<string, unknown>;
    getItemProps: (userProps?: Omit<React_2.HTMLProps<HTMLElement>, 'selected' | 'active'> & ExtendedUserProps) => Record<string, unknown>;
}
```

@bsunderhus maybe you know how this issue could happen with the type generation?

**Comment by bsunderhus** [comment]
This seems to be related to https://github.com/microsoft/rushstack/issues/2479

**Comment by atomiks** [comment]
Ok, I think I know how to fix `Derivable_2` (it needs to use the DOM, not Core type), but I guess we can manually patch `React_2` back to `React` after the types have been generated.

**Comment by bsunderhus** [comment]
> Ok, I think I know how to fix `Derivable_2` (it needs to use the DOM, not Core type), but I guess we can manually patch `React_2` back to `React` after the types have been generated.

Is it necessary though? it still points to the same export which is the react package, and it's not like `React_2` is leaking....

**Comment by atomiks** [comment]
In `Derivable`'s case it has 1 looser property type than it should. As for `React`, it's just unsightly yeah

**Comment by bsunderhus** [comment]
please assign this issue to me @atomiks , I'll follow up with a PR ASAP

**Comment by bsunderhus** [comment]
Ok, it seems like by upgrading `api-extractor` to `7.43.1` solves this issue. I'll create a PR

**Comment by bsunderhus** [comment]
I can see that this strategy of adding a suffix is to avoid conflicts, in the case of `Derivable_2` is because there's a local definition of `Derivable` that makes sense to me. In the case of `React_2` for some reason API extractor is assuming there's a local definition of `React`?! that is weird
