### ISSUE TITLE
Implicit dependency on React 18 typings

### ISSUE THREAD

**Issue by drizzer14** [floating-ui/floating-ui#2866]
**Describe the bug**

`Composite.render` prop type `RenderProp` started being resolved as `any` after upgrading `@floating-ui/react` to 0.26.12. After looking at the typings of this prop I've noticed that it's using `React_2.JSX` namespace, which, as far as I know, was just `JSX` before [being deprecated in React 18](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/266eae5148c535e6b41fe5d0adb2ad23f302bc8a/types/react/index.d.ts#L3182) in favour of `React.JSX`. I did not find any mentions of `@floating-ui/react` requiring React 18 neither in the docs, nor in its `package.json`.

**To Reproduce**

1. Go to [sandbox](https://codesandbox.io/p/sandbox/floating-ui-composite-type-error-17-th3v3x) (which uses React 17).
2. Observe line 5 – `Namespace 'React' has no exported member 'JSX'`.
3. Observe line 6 – `JSX` namespace is globally available.
4. Observe line 9 – `Composite.render` argument resolves to `any`.
5. Observe original type of the `Composite.render` – `Namespace 'React' has no exported member 'JSX'`.

**Expected behavior**

`Composite.render` argument resolves to `React.HTMLAttributes<HTMLElement>` as seen [here](https://codesandbox.io/p/sandbox/floating-ui-composite-type-error-18-lkccv9) when React 18 is installed.

**Screenshots**

<img width="683" alt="image" src="https://github.com/floating-ui/floating-ui/assets/1790097/4fcee036-911f-4f5e-9c73-a3f2dfef0a73">
<img width="807" alt="image" src="https://github.com/floating-ui/floating-ui/assets/1790097/1b74af30-7c00-4bbe-8f04-60395e31b43a">
<img width="1132" alt="image" src="https://github.com/floating-ui/floating-ui/assets/1790097/1e460670-a788-4df8-a8b8-45b579468633">

**Context:**

- react@17.0.2
- typescript@5.1.6
- @floating-ui/react@0.26.12

**Comment by atomiks** [comment]
Oh sorry, I didn't realize that was a React 18-only type 🤦

**Comment by atomiks** [comment]
Hi, so it turns out this isn't actually a React 18 type. Both React 16 and 17 support this in their latest patch versions. The `17.0.2` patch is outdated in the CSB. I'm going to change this back because React 19 requires it.
