### ISSUE TITLE
UseInteractionsReturn is missing

### ISSUE THREAD

**Issue by rrojas-prmnt** [floating-ui/floating-ui#2873]
Hello!

I was using the `useInteractions` hook and needed to export the return type. However, I've discovered that this interface does not exist in `@floating-ui/react`. The only workaround is to recreate it myself. After considering this and comparing it to other hooks that already have the return type implemented, I'm wondering whether this interface should be created in the library or if I should implement it myself.

For more details, you can refer to the documentation on the return value of the `useInteractions` hook: https://floating-ui.com/docs/useInteractions#return-value. Is this a missing type in the library?

You can also compare it with the `useFloating` hook: https://floating-ui.com/docs/useFloating#return-value. In this case, the return type (UseFloatingReturn) already exists in the library.

<img width="680" alt="image" src="https://github.com/floating-ui/floating-ui/assets/124401196/6cdcaaa3-3cd7-4dd9-af82-76bcbf56503f">

_Originally posted by @rrojas-prmnt in https://github.com/floating-ui/floating-ui/discussions/2838_

**Comment by atomiks** [comment]
That type was for demonstration as it actually just uses the inferred return value. I've created it and exported here: https://github.com/floating-ui/floating-ui/pull/2879

Also, you can always use `type UseInteractionsReturn = ReturnValue<typeof useInteractions>` to extract the value yourself.
