### ISSUE TITLE
Regression in @floating-ui/react@0.26.10 and return focus

### ISSUE THREAD

**Issue by aversini** [floating-ui/floating-ui#2874]
**Describe the bug** 

I'm using the [Dropdown Menu](https://floating-ui.com/docs/react-examples) example.
Accessibility rules are requiring that the triggering element that opens the menu should receive it back when the menu is closed. This was working well until and including version `@floating-ui/react@0.26.9`.

Versions `@floating-ui/react@0.26.10` (and above) are breaking that behavior.

**To Reproduce**

Steps to reproduce the behavior (do not use Safari):

1. Go to https://codesandbox.io/p/sandbox/dank-wave-cfsdqy
2. Click on the first button, the focus ring indicates it is focused.
3. Click on the second button to open the menu.
4. Click on the second button again, to close the menu.

**Expected behavior** 
- the Menu button should be focused.

**Actual behavior**
- The first button gets the focus back.

**Context:**

- OS: Mac / Windows
- Browser Chrome
- Version 122

**Additional context**

- I'm not looking at Safari since this browser does not report visible focus on click of a button.
- With the exact [same example code](https://codesandbox.io/s/floating-ui-dom-template-utpx0u), simply switching from `@floating-ui/react@0.26.10` to `@floating-ui/react@0.26.9` resolves the issue (focus remains on the Menu button, when the menu is closed).

**Comment by atomiks** [comment]
This is due to the reference not being focused initially, since it opens on `mousedown` in which the `useClick` hook prevents it from recieving focus. The change caused it to use the actual previously focused element instead, but the reference is still likely more appropriate here.

Fix: https://github.com/floating-ui/floating-ui/pull/2876

**Comment by aversini** [comment]
Thanks for the quick fix @atomiks! I just tried it, it's all fixed 👍
