### ISSUE TITLE
Floating UI doesn't use the latest version of the callbacks from each render

### ISSUE THREAD

**Issue by LoganDark** [floating-ui/floating-ui#2894]
Every render, `useFloating` is called with a new options object that probably contains a bunch of callbacks (sometimes nested inside middlewares and the like).

Floating UI seems to be ignoring every render except the first one, and using old versions of the callbacks, which can reference state values from old renders that are no longer up to date.

**To Reproduce**

I tried to create a codesandbox, but it says the file's read only, all the share options are disabled and I can't figure out how to actually share a repro. :/

1. Make a state with `useState`
2. Use the state value inside a callback function
3. Update the state
4. Floating UI keeps using the old value

**Expected behavior** Floating UI should probably replace all the callbacks with wrappers that can always call the version from the latest render.

**Context:**

- Version: `0.26.14`

**Additional context**

this hook helps me to avoid this issue and successfully works around the problem:

```ts
import { useCallback, useRef } from 'react'

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export default function useCallbackWrapper<F extends (...args: any) => any>(func: F): F {
	const latest = useRef<F>(func)
	latest.current = func; // eslint-disable-next-line react-hooks/exhaustive-deps
	return useCallback(((...args) => latest.current(...args)) as F, [])
}
```

maybe you can use something like it

**Comment by atomiks** [comment]
Is the issue the same on `0.26.13`?

**Comment by LoganDark** [comment]
yes it looks like it. my render function logs the values of these variables, THEN the callbacks are called and they print the old values, so it seems floating UI is keeping around a reference to an old callback from an old render instead of using the most recent ones

**Comment by atomiks** [comment]
Okay, `.14` had a somewhat major refactor that I was curious was causing the problem. But if it's happening in the old version I'm skeptical it's this library's issue. `useEffectEvent` (the function you posted) is used internally where necessary, and the lint rules are enabled to ensure `useCallback`s have fresh values during rendering. 

Without a reproduction it's hard to debug - if you can, try to find some time to make a new CodeSandbox that reproduces the issue!

**Comment by LoganDark** [comment]
I have time, it's just all of codesandbox's buttons are disabled for some reason?
![image](https://github.com/floating-ui/floating-ui/assets/4723091/31ca69a7-1aba-46ca-b9c8-d7bff1ca2984)
 like, it literally just won't let me

**Comment by atomiks** [comment]
CodeSandbox's recent changes have been weird, try to create a brand new Sandbox entirely

**Comment by LoganDark** [comment]
![image](https://github.com/floating-ui/floating-ui/assets/4723091/553e1dee-3562-449e-9648-218f1388dea8)
how?

**Comment by LoganDark** [comment]
oh, it wants me to sign in, let me try that

**Comment by LoganDark** [comment]
[here you go](https://codesandbox.io/p/sandbox/floating-ui-react-dom-template-forked-djvgnf)

to reproduce:

- click the "add 10" button
- the tooltip does nothing
- click remount
- woah

**Comment by atomiks** [comment]
So this is an edge case where state values aren't fresh inside functions of middleware. Refs can be fresh, but they're also not reactive. 

To keep using state, which is both reactive and fresh, you need to inform Floating UI about the value changing:

```js
const sizeMiddleware = size({
  apply({ elements }) {
    elements.floating.style.height = `${state}px`;
  },
});

const reactiveSize = {
  ...sizeMiddleware,
  options: {
    ...sizeMiddleware.options,
    deps: [state],
  }
};

useFloating({
  middleware: [reactiveSize]
})
```

https://codesandbox.io/p/sandbox/floating-ui-react-dom-template-forked-vmtmz4?file=%2Fsrc%2FApp.js%3A22%2C1

Docs: https://floating-ui.com/docs/useFloating#option-reactivity

**Comment by LoganDark** [comment]
ok, thank you! that looks exactly like what I am running into

**Comment by LoganDark** [comment]
yep I can confirm even just

```diff
 			size({
 				apply({availableHeight, elements}) {
 					console.log('extraLeftPadding = %o, extraRightPadding = %o', extraLeftPadding, extraRightPadding)
 					elements.floating.style.width = `${elements.reference.getBoundingClientRect().width - leftPadding - rightPadding + 2 * unit}px`
 					elements.floating.style.maxHeight = `${Math.max(availableHeight, 20 * unit)}px` // 4 items
 				},
+				deps: [extraLeftPadding, extraRightPadding, unit]
 			}),
```

immediately fixes the issue

wonder if you should make this `deps` an official optional field so that typescript stops complaining at me

it'd probably be SUPER helpful for discoverability as well

**Comment by atomiks** [comment]
I was considering adding it as a second argument (like a dependency array), but the types were a bit annoying and I didn't think it was a major enough issue to add in, but I might try to look into it again

**Comment by jasosims** [comment]
Docs need to be updated. The current docs say:

> Specifying the dependencies as a second argument of any middleware function will keep it reactive:
>
> offset(() => value, [value]);
>
> This goes for any function option, including size()’s apply function.

...but that doesn't work. I had to find this issue to discover I actually need to pass dependencies for `size` like this:

```js
const middleware = [
  size({
    apply() { ... },
    deps: [dep1, dep2]
  })
]
```

**Comment by LoganDark** [comment]
> Docs need to be updated. The current docs say:
> 
> > Specifying the dependencies as a second argument of any middleware function will keep it reactive:
> > offset(() => value, [value]);
> > This goes for any function option, including size()’s apply function.
> 
> ...but that doesn't work. I had to find this issue to discover I actually need to pass dependencies for `size` like this:
> 
> ```js
> const middleware = [
>   size({
>     apply() { ... },
>     deps: [dep1, dep2]
>   })
> ]
> ```

Just to be clear, you tried this and it didn't work?

```js
const middleware = [
  size({
    apply() { ... }
  }, [dep1, dep2])
]
```
