### ISSUE TITLE
When the focused element of a `FloatingFocusManager` is removed from the dom focus escapes to the `body`

### ISSUE THREAD

**Issue by haagmm-ef** [floating-ui/floating-ui#2903]
While building a Wizard like flow with `FloatingFocusManager` and the Dialog behavior in react, we realized that once the "move to the next screen" button is pressed the focus leaves the Dialog and escapes to the `body` element.

We were able to work around it, but wanted to bring the issue to your attention.

**To Reproduce**
[Code Sandbox](https://codesandbox.io/p/sandbox/loving-goodall-2gt6l7)
[Sandbox Output Page](https://2gt6l7.csb.app/)

1. Go to output page to avoid iframe pain.
1. Enable screen reader.
1. Click on 'Delete Balloon'
1. Click on 'Confirm'
1. Screen reader does not announce that newly titled modal, focus has moved to the `body` (this can also be seen by calling `document.activeElement` in the inspector.

**Expected behavior** 

When an element of a Modal is removed from the active Dom the focus should move to the `dialog`

There is a `useEffect` call which is commented out which shows the expected behavior.  

**Context:**

- OS: Verified on MacOS and Window.
- Browser Chrome, Firefox, Edge
- Version `"@floating-ui/react": "0.26.15"`

**Comment by atomiks** [comment]
The Sandbox doesn't link to a reproduction, only the DOM template. Can you please update it?

> Version "@floating-ui/react": "0.23.0"

Can you also confirm this happens in the latest version `0.26.15`?

**Comment by atomiks** [comment]
Ok, I'm assuming that focus should be placed on the floating element here, if focus inside it gets lost/removed from the DOM. As you mentioned, you can workaround it atm by manually focusing the floating element when the element gets removed.
