### ISSUE TITLE
Update dependency of floating-ui/react-dom

### ISSUE THREAD

**Issue by HeyItsJs** [floating-ui/floating-ui#2917]
@floating-ui/react-dom is currently using  `1.0.0` of `@floating-ui/dom`. However there are certain bug fixes which require latest version. Current latest version of  `@floating-ui/dom` is `1.6.5`

**Comment by atomiks** [comment]
The dependency version is `^1.0.0` which uses the caret `^`, as it's compatible with all v1 versions. If you want to update `@floating-ui/dom` as a transitive dependency, you can run `pnpm update @floating-ui/dom` or the equivalent for npm/yarn, which updates the lockfile version despite it not being a direct dependency in your package.json. Another alternative is to uninstall the direct dep and re-install it, which automatically picks up all the latest transitive package versions for you.
