### ISSUE TITLE
Fixed element as child of `dialog` element wrapped by element with `container-type` is positioned incorrectly

### ISSUE THREAD

**Issue by Fattimo** [floating-ui/floating-ui#2918]
**Describe the bug** A clear and concise description of what the bug is.

Related Issue: #2395

Within a `container-type` set on a parent element with a modal dialog child, floating-ui does not position against elements within the dialog correctly

**To Reproduce**

https://codesandbox.io/p/sandbox/proud-platform-976wnp?file=%2Fsrc%2Findex.js

1. Click on the `control` button. This opens a dialog element that renders a tooltip positioned against the button expectedly. Click cancel to close the dialog
2. Click on the non-control button. This opens a dialog element which is a child of a container with `container-type` that renders a tooltip positioned against the button, but offset by some incorrect amount.

May need to refresh if running into issues, hot reload gets the sandbox into a stuck state sometimes

**Expected behavior** A clear and concise description of what you expected to
happen.

I expect the behavior to behave as it does in the control case

**Screenshots** If applicable, add screenshots to help explain your problem.
control
<img width="527" alt="image" src="https://github.com/floating-ui/floating-ui/assets/57023314/0fb64561-233f-4053-a287-99477d1be1bd">

container-type
<img width="537" alt="image" src="https://github.com/floating-ui/floating-ui/assets/57023314/fc864f1c-a8c1-4b06-a6bc-c5d03000fe6b">

**Context:**

Chrome 124 on macOS (Sonoma)

**Additional context** Add any other context about the problem here.

**Comment by scott-m-sarsfield** [comment]
Similar behavior applies when doing anything else to an element that would make it a "containing block" (like adding a transform).  The matter is that when inside a `dialog` element, it should use the html root element for position, since the dialog resets position.

...meanwhile, a possible workaround is to make the `dialog` a containing element by adding a useless transform style
```
dialog { transform: translate(0); }
```

(i'm not terribly aware of other consequences of forcing containing elements though.)

**Comment by Fattimo** [comment]
> Similar behavior applies when doing anything else to an element that would make it a "containing block" (like adding a transform). The matter is that when inside a `dialog` element, it should use the html root element for position, since the dialog resets position.

Probably need to be careful of the non-modal dialog then. I didn't look into it too deeply, but the HTML spec for `dialog` also supports the `.open()` function, which is non-top level mode for that html element. So perhaps the relevant check needs to be if the element is top level or not

**Comment by atomiks** [comment]
As @scott-m-sarsfield pointed out, the logic is to detect if something is a containing block is missing an `isTopLayer(element)` check while traversing. This a simple change and appears to fix the issue. I'll make a PR shortly
