### ISSUE TITLE
Missing fade out animation when FloatingArrow used with FloatingDelayGroup

### ISSUE THREAD

**Issue by apazzolini** [floating-ui/floating-ui#2932]
**Describe the bug** 

There's a missing fade-out animation on Tooltips if you use FloatingArrow inside of a FloatingDelayGroup due to FloatingArrow's invocation of `platform.isRTL`.

**To Reproduce**

1. Go to https://codesandbox.io/p/sandbox/clever-mahavira-3g74fx
2. Hover over Ref 1
3. Hover over Ref 2
4. Hover out
5. Notice that the fade out animation didn't trigger

**Expected behavior** 

The fade out animation should have triggered. (If you only hover over Ref 1 and then hover out, it correctly triggers)

**Context:**

- OS: Mac
- Browser Firefox, Chrome

**Additional context**

I've tracked this down to the usage of the `const isRTL = platform.isRTL(floating)` line in FloatingArrow. If you comment that line out, the animations work as expected.

**Comment by atomiks** [comment]
It seems like sticking the `isRTL` check in a layout effect instead fixes the issue.
