### ISSUE TITLE
onClick/onHover doesn't trigger for parent most dropdown

### ISSUE THREAD

**Issue by phazei** [floating-ui/floating-ui#2938]
I'm not sure if this is a bug or not, but the top item when using it as a dropdown doesn't trigger any click or hover event.

I've modified the dropdown example to demonstrate:
https://codesandbox.io/p/sandbox/gracious-sanne-dfwzn5?file=%2Fsrc%2FDropdownMenu.tsx%3A142%2C1

I added a console.log on the MenuComponent's FloatingNode's button inside getItemProps for onClick and onFocus.  I also added a onClick & onFocus prop to the \<Menu\>'s for "Edit" and "Copy as".

If you view the console, you can see the console.log's triggering for the "Copy as" menu, but the "Edit" button doesn't get triggered at all.  It's probably related, but if I add "style" to any of the Menu or MenuItems, it works for all except the root item as well.

If I'm doing something wrong there, please help, I'm not certain why it's not being called.

**Comment by atomiks** [comment]
Looks like the example needs the following condition for the root props to be passed:

```jsx
        {...getReferenceProps({
          ...(isNested
            ? parent.getItemProps({
                ...props,
                onClick: (event: React.MouseEvent<HTMLButtonElement>) => {
                  console.log("props CLICK");
                  props.onClick?.(event);
                },
                onFocus(event: React.FocusEvent<HTMLButtonElement>) {
                  console.log("props FOCUS");
                  props.onFocus?.(event);
                  setHasFocusInside(false);
                  parent.setHasFocusInside(true);
                },
              })
            : props),
        })}
```

**Comment by phazei** [comment]
Ah!  It's so obvious once you've pointed it out, lol.  Thank you for the quick response, works great now :D
