### ISSUE TITLE
Incorrect positioning when inside a Web Component slot, with a container that has a backdrop-filter

### ISSUE THREAD

**Issue by danwenzel** [floating-ui/floating-ui#2955]
**Describe the bug** 

When a tooltip is rendered within the slot of a web component, within a container that has a `backdrop-filter`, the tooltip ends up being positioned incorrectly. I've observed quite a variance in just _how far_ off the tooltip is, from just a few pixels to being completely off the page - depending on the rest of the context, but I've provided a simple reproduction below

**To Reproduce**

Here is a codesandbox that shows the issue (has a dependency on Lit): https://codesandbox.io/p/sandbox/floating-ui-dom-template-forked-xjn3yc?file=%2Fsrc%2Findex.js%3A8%2C16

**Screenshots** 

### Incorrectly positioned:

![image](https://github.com/floating-ui/floating-ui/assets/11724146/0106f32d-ca40-4afe-8e01-df66b1d863e3)

### Correctly positioned:

![image](https://github.com/floating-ui/floating-ui/assets/11724146/d57cf8d0-bc06-4dd9-8766-9429f15cd828)

![image](https://github.com/floating-ui/floating-ui/assets/11724146/d534d772-3f6a-4bfb-87b5-0882ee4ba72b)

**Context:**

- OS: [e.g. iOS]: MacOS Sonoma 14.5
- Browser [e.g. chrome, safari]: Chrome and Firefox. ~Safari does not seem to be affected~. Safari is affected as well, when using `-webkit-backdrop-filter`
- Version [e.g. 22]: Chrome Version 126.0.6478.127 (Official Build) (arm64), Firefox 127.0.2 (64-bit)

**Comment by atomiks** [comment]
I think this may be this [Shadow DOM bug](https://floating-ui.com/docs/platform#shadow-dom-fix)

It doesn't seem like the `composed-offset-position` (`offsetParent`) polyfill works in this case as it doesn't detect containing blocks correctly

cc: @jcfranco

**Comment by danwenzel** [comment]
Thanks, @atomiks - So if I understand correctly, this does _not_ have a workaround currently, right? Since the composed-offset-position trick doesn't work in this case?

**Comment by jcfranco** [comment]
> It doesn't seem like the composed-offset-position (offsetParent) polyfill works in this case as it doesn't detect [containing blocks correctly](https://github.com/jcfranco/composed-offset-position/blob/main/src/index.ts?rgh-link-date=2024-07-13T21%3A55%3A48Z#L71)

@atomiks I'll need to investigate further. A quick local test using `isContainingBlock` from `@floating-ui/utils` resulted in test failures.

@josepharhar could you provide any insights or pointers on this?

**Comment by josepharhar** [comment]
Not sure if it fixes the issue, but I think the polyfill needs to look at the computed value of backdropFilter, not just filter, since the browser implementation of offsetParent looks at both of those properties: https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/layout/layout_object.cc;l=1843-1850;drc=fa1e0cf5238e2600039f60af6909aefbd4cf003c

**Comment by jcfranco** [comment]
@atomiks Tests are passing now. I must have messed up the conditional expression previously, so thanks for the catch! I'll work on publishing an update this week. 

@josepharhar Thanks for chiming in!

**Comment by jcfranco** [comment]
[`composed-offset-position`](https://www.npmjs.com/package/composed-offset-position) has been updated and should mitigate this issue (see [updated example](https://codesandbox.io/p/sandbox/floating-ui-dom-composed-offset-position-iscontainingblock-repro-case-qgfhnx?file=%2Fsrc%2Findex.js%3A3%2C1)).

Many thanks, y'all!

**Comment by danwenzel** [comment]
Thanks, @jcfranco!  I see it's working in the updated example, but unfortunately this does not fix the issue in my app.

After some digging, it looks like the issue still remains when the container web component has a closed shadow root.

Here's an updated example: https://codesandbox.io/p/sandbox/floating-ui-dom-composed-offset-position-iscontainingblock-repro-case-forked-pklz3x?file=%2Fsrc%2Findex.js%3A17%2C4

**Comment by atomiks** [comment]
I believe it's impossible to traverse through closed shadow roots (feel free to correct) so there's no method that will work to find the correct offset parent.

**Comment by danwenzel** [comment]
Ah yes, thanks @atomiks! I'm starting to understand this all better thanks in part to https://developer.mozilla.org/en-US/docs/Web/CSS/Containing_block#identifying_the_containing_block

So _if_ there's an ancestor element with something like `backdrop-filter`, _and_ that element is inside of a separate web component from where the tooltip is, _and_ that separate web component has a closed shadow DOM, we'll hit this issue.

I was able to get it working by manually passing the `backdrop-filter` element down into the tooltip element.  It's a bummer we have to do this for these cases, but I'm guessing there's no alternative?

Do you think this is worth a blurb in the documentation?
