### ISSUE TITLE
'toValue' was not found in 'vue-demi' 

### ISSUE THREAD

**Issue by tasmanboat** [floating-ui/floating-ui#2959]
**Describe the bug**

My project uses vue 2.7.16, vue-demi 0.14.8 and @floating-ui/vue. When it uses @floating-ui/vue 1.0.7, it is fine. When it uses @floating-ui/vue 1.1.0, there is a build failure suggesting a wrong import. 

```
-  Building for development...
 ERROR  Failed to compile with 1 error 2:18:53 AM

 error  in ./node_modules/@floating-ui/vue/dist/floating-ui.vue.mjs

export 'toValue' (imported as 'toValue') was not found in 'vue-demi' 

(possible exports: EffectScope, Fragment, KeepAlive, Suspense, Teleport, Transition, TransitionGroup, Vue, Vue2, computed, createApp, customRef, defineAsyncComponent, defineComponent, del, effectScope, getCurrentInstance, getCurrentScope, h, hasInjectionContext, inject, install, isProxy, isReactive, isReadonly, isRef, isShallow, isVue2, isVue3, markRaw, mergeDefaults, nextTick, onActivated, onBeforeMount, onBeforeUnmount, onBeforeUpdate, onDeactivated, onErrorCaptured, onMounted, onRenderTracked, onRenderTriggered, onScopeDispose, onServerPrefetch, onUnmounted, onUpdated, provide, proxyRefs, reactive, readonly, ref, set, shallowReactive, shallowReadonly, shallowRef, toRaw, toRef, toRefs, triggerRef, unref, useAttrs, useCssModule, useCssVars, useListeners, useSlots, version, warn, watch, watchEffect, watchPostEffect, watchSyncEffect)
```

As I see in floading-ui repo `packages/vue/src/useFloating.ts` file, in version 1.1.0 it imports `toValue` from vue-demi package. That may be the reason. 

Would mods mind having a look? Thanks. 

I found no `toValue` in vue-demi 0.14.8, and I found `toValue` in vue 3.3 [here](https://vuejs.org/api/reactivity-utilities#tovalue)

**Comment by ryzr** [comment]
Introduced in PR: https://github.com/floating-ui/floating-ui/pull/2956

**Comment by atomiks** [comment]
@Mini-ghost

**Comment by Mini-ghost** [comment]
@tasmanboat  I apologize for not considering Vue 2 users when I made the update. I will soon submit a PR with the necessary fixes.
