### ISSUE TITLE
Absolutely positioned child with negative transforms always takes the top space and gets clipped off

### ISSUE THREAD

**Issue by arunks5** [floating-ui/floating-ui#2964]
I have reproduced the issue [here](https://lit.dev/playground/#project=W3sibmFtZSI6InNpbXBsZS1ncmVldGluZy50cyIsImNvbnRlbnQiOiJpbXBvcnQgeyBodG1sLCBjc3MsIExpdEVsZW1lbnQgfSBmcm9tICdsaXQnO1xuaW1wb3J0IHsgY3VzdG9tRWxlbWVudCwgcHJvcGVydHkgfSBmcm9tICdsaXQvZGVjb3JhdG9ycy5qcyc7XG5pbXBvcnQgJy4vbW9kYWwuanMnO1xuaW1wb3J0ICcuL3BhbmVsLmpzJztcbmltcG9ydCB7IHVzZUZsb2F0aW5nVUkgfSBmcm9tICcuL2Zsb2F0aW4tdWkuanMnO1xuQGN1c3RvbUVsZW1lbnQoJ3NpbXBsZS1ncmVldGluZycpXG5leHBvcnQgY2xhc3MgU2ltcGxlR3JlZXRpbmcgZXh0ZW5kcyBMaXRFbGVtZW50IHtcbiAgc3RhdGljIHN0eWxlcyA9IGNzc2BcbiAgICAgIC5wYW5lbHtcbiAgbWFyZ2luOiAwO1xuICBwYWRkaW5nOiAwO1xuICBib3JkZXI6IG5vbmU7XG4gIG92ZXJmbG93OiB2aXNpYmxlO31cbiAgICAgLnBhcmVudHtcbnBvc2l0aW9uOiByZWxhdGl2ZTt9IGBcbiAgICAgIDtcbiAgZ2V0IHBhbmVsRWxlbWVudCgpOiBIVE1MRWxlbWVudCB7XG4gICAgcmV0dXJuIHRoaXMuc2hhZG93Um9vdC5xdWVyeVNlbGVjdG9yKCdzaW1wbGUtcGFuZWwnKSE7XG4gIH1cblxuICByZW5kZXIoKSB7XG4gICAgcmV0dXJuIGh0bWxgXG4gICAgICAgIDxteS1tb2RhbD5cbiAgICAgICAgPHA-XG4gICAgICAgIFRoZSBkb21haW5zIHdpa2lwZWRpYS5vcmcgYW5kIHdpa2lwZWRpYS5jb20gKGxhdGVyIHJlZGlyZWN0aW5nIHRvIHdpa2lwZWRpYS5vcmcpIHdlcmUgXG4gICAgICAgIDwvcD5cbiAgICAgICAgICA8ZGl2IGNsYXNzPVwicGFyZW50XCIgPlxuICAgICAgICA8aW5wdXQgQGNsaWNrPSR7KCkgPT4ge1xuICAgICAgICBpZiAodGhpcy5wYW5lbEVsZW1lbnQuc3R5bGUuZGlzcGxheSA9PT0gJ2Jsb2NrJykge1xuICAgICAgICAgIHRoaXMucGFuZWxFbGVtZW50LnN0eWxlLmRpc3BsYXkgPSAnbm9uZSc7XG4gICAgICAgIH0gZWxzZSB7XG4gICAgICAgICAgdGhpcy5wYW5lbEVsZW1lbnQuc3R5bGUuZGlzcGxheSA9ICdibG9jayc7XG4gICAgICAgIH1cbiAgICAgICAgY29uc3QgdHJpZ2dlclJlZiA9IHRoaXMuc2hhZG93Um9vdC5xdWVyeVNlbGVjdG9yKCdpbnB1dCcpO1xuICAgICAgICB1c2VGbG9hdGluZ1VJKHRyaWdnZXJSZWYsIHRoaXMucGFuZWxFbGVtZW50KTtcbiAgICAgIH1cbiAgICAgIH0gLz5cbiAgICAgICAgPHNpbXBsZS1wYW5lbCBjbGFzcz1cInBvcG92ZXJcIiBzdHlsZT1cImRpc3BsYXk6bm9uZVwiPlxuICAgICAgICAgIDwvc2ltcGxlLXBhbmVsPlxuICAgICAgICA8L2Rpdj4gIFxuICAgICAgICBcbiAgICAgICAgICBcbiAgICAgICAgPC9teS1tb2RhbD5cbiAgICAgICAgYDtcbiAgfVxufVxuIn0seyJuYW1lIjoiaW5kZXguaHRtbCIsImNvbnRlbnQiOiI8IURPQ1RZUEUgaHRtbD5cbjxoZWFkPlxuICA8c2NyaXB0IHR5cGU9XCJtb2R1bGVcIiBzcmM9XCIuL3NpbXBsZS1ncmVldGluZy5qc1wiPjwvc2NyaXB0PlxuPC9oZWFkPlxuPGJvZHk-XG4gIDxzaW1wbGUtZ3JlZXRpbmcgbmFtZT1cIldvcmxkXCI-PC9zaW1wbGUtZ3JlZXRpbmc-XG48L2JvZHk-XG4ifSx7Im5hbWUiOiJwYWNrYWdlLmpzb24iLCJjb250ZW50Ijoie1xuICBcImRlcGVuZGVuY2llc1wiOiB7XG4gICAgXCJsaXRcIjogXCJeMy4wLjBcIixcbiAgICBcIkBsaXQvcmVhY3RpdmUtZWxlbWVudFwiOiBcIl4yLjAuMFwiLFxuICAgIFwibGl0LWVsZW1lbnRcIjogXCJeNC4wLjBcIixcbiAgICBcImxpdC1odG1sXCI6IFwiXjMuMC4wXCJcbiAgfVxufSIsImhpZGRlbiI6dHJ1ZX0seyJuYW1lIjoibW9kYWwudHMiLCJjb250ZW50IjoiaW1wb3J0IHtodG1sLCBjc3MsIExpdEVsZW1lbnR9IGZyb20gJ2xpdCc7XG5pbXBvcnQge2N1c3RvbUVsZW1lbnQsIHByb3BlcnR5fSBmcm9tICdsaXQvZGVjb3JhdG9ycy5qcyc7XG5cbkBjdXN0b21FbGVtZW50KCdteS1tb2RhbCcpXG5leHBvcnQgY2xhc3MgTXlNb2RhbCBleHRlbmRzIExpdEVsZW1lbnQge1xuICBzdGF0aWMgc3R5bGVzID0gY3NzYFxuICAgICAgLm15LW1vZGFsIHtcbiAgZGlzcGxheTogZmxleDtcbiAgYWxpZ24taXRlbXM6IGNlbnRlcjtcbiAganVzdGlmeS1jb250ZW50OiBjZW50ZXI7XG4gIHBvc2l0aW9uOiBmaXhlZDtcbiAgd2lkdGg6IDkwdnc7XG4gIGhlaWdodDogOTB2aDtcbiAgaW5zZXQtYmxvY2stc3RhcnQ6IDA7XG4gIGluc2V0LWlubGluZS1zdGFydDogMDtcbiAgei1pbmRleDo1MDA7XG5cbiAgdmlzaWJpbGl0eTogaGlkZGVuO1xuICBiYWNrZ3JvdW5kLWNvbG9yOiAjYjRiNGI0NGY7XG4gICAgICBvcGFjaXR5OiAxO1xuICAgIHZpc2liaWxpdHk6IHZpc2libGU7XG59XG4gICAgICAubW9kYWxfX2hlYWRlciB7XG4gIGRpc3BsYXk6IGZsZXg7XG4gIGFsaWduLWl0ZW1zOiBjZW50ZXI7XG4gIGp1c3RpZnktY29udGVudDogc3BhY2UtYmV0d2VlbjtcbiAgcG9zaXRpb246IHJlbGF0aXZlO1xufVxuICAgICAgXG4gICAgICAubW9kYWxfX2hlYWRlci1jb250ZW50IHtcbiAgZGlzcGxheTogZmxleDtcbiAgYWxpZ24taXRlbXM6IGNlbnRlcjtcbiAganVzdGlmeS1jb250ZW50OiBmbGV4LXN0YXJ0O1xuICBmbGV4LXdyYXA6IHdyYXA7XG4gIGZsZXgtYmFzaXM6IDEwMCU7XG59XG5cbiAgICAgIFxuICAgICAgLm15LW1vZGFsIC5pcy1hY3RpdmUge1xuICAgIFxuICB9XG4gICAgICAubW9kYWxfX2JvZHkge1xuICBmbGV4LWJhc2lzOiAxMDAlO1xuICBvdmVyZmxvdzogYXV0bztcbiAgICAgIG1heC1oZWlnaHQ6IDE1MHB4O1xufVxuLm1vZGFsX193aW5kb3cge1xuYm9yZGVyOiAycHggc29saWQgcmVkO1xufVxuICAgICAgYDtcblxuICBAcHJvcGVydHkoKVxuICBuYW1lID0gJ1NvbWVib2R5JztcblxuICByZW5kZXIoKSB7XG4gICAgcmV0dXJuIGh0bWxgXG4gICAgICAgIDxkaXZcbiAgICAgICAgY2xhc3M9XCJteS1tb2RhbCBpcy1hY3RpdmVcIlxuICAgICAgPlxuICAgICAgICA8YXJ0aWNsZSBwYXJ0PVwid2luZG93XCIgY2xhc3M9XCJtb2RhbF9fd2luZG93XCIgdGFiSW5kZXg9JHswfT5cbiAgICAgICAgICA8ZGl2ICBjbGFzcz1cIm1vZGFsX19oZWFkZXJcIj5cbiAgICAgICAgICAgIFxuICAgICAgICAgICAgPGRpdiBjbGFzcz1cIm1vZGFsX19oZWFkZXItY29udGVudFwiID5cbiAgICAgICAgICAgICAgPHNsb3QgIG5hbWU9XCJoZWFkZXJcIj48L3Nsb3Q-XG4gICAgICAgICAgICA8L2Rpdj5cbiAgICAgICAgICAgIDxzbG90IHBhcnQ9XCJwYXJ0LWFjdGlvbnNcIiBuYW1lPVwiYWN0aW9uc1wiPjwvc2xvdD5cbiAgICAgICAgICAgIFxuICAgICAgICAgIDwvZGl2PlxuXG4gICAgICAgICAgPGRpdiBjbGFzcz1cIm1vZGFsX19ib2R5XCI-PHNsb3QgcGFydD1cInBhcnQtZGVmYXVsdFwiPjwvc2xvdD48L2Rpdj5cbiAgICAgICAgIFxuICAgICAgICAgIDxkaXYgY2xhc3M9XCJtb2RhbF9fZm9vdGVyXCI-PHNsb3QgcGFydD1cInBhcnQtZm9vdGVyXCIgbmFtZT1cImZvb3RlclwiPjwvc2xvdD48L2Rpdj4gXG4gICAgICAgIDwvYXJ0aWNsZT5cbiAgICAgIDwvZGl2PlxuICAgICAgICBgO1xuICB9XG59IFxuIn0seyJuYW1lIjoicGFuZWwudHMiLCJjb250ZW50IjoiaW1wb3J0IHtodG1sLCBjc3MsIExpdEVsZW1lbnR9IGZyb20gJ2xpdCc7XG5pbXBvcnQge2N1c3RvbUVsZW1lbnQsIHByb3BlcnR5fSBmcm9tICdsaXQvZGVjb3JhdG9ycy5qcyc7XG5cbkBjdXN0b21FbGVtZW50KCdzaW1wbGUtcGFuZWwnKVxuZXhwb3J0IGNsYXNzIFNpbXBsZVBhbmVsIGV4dGVuZHMgTGl0RWxlbWVudCB7XG4gIHN0YXRpYyBzdHlsZXMgPSBjc3NgZGl2IHsgY29sb3I6d2hpdGU7YmFja2dyb3VuZDogYmx1ZTtib3JkZXI6MXB4IHNvbGlkIHJlZDsgaGVpZ2h0OjIwMHB4O3dpZHRoOjEwMHB4IH1cbjpob3N0e1xucG9zaXRpb246YWJzb2x1dGU7XG59YDtcblxuIFxuICByZW5kZXIoKSB7XG4gICAgcmV0dXJuIGh0bWxgXG4gICAgICAgIDxkaXY-XG4gICAgICAgICAgICBQYW5lbFxuICAgICAgICA8L2Rpdj5cbiAgICAgXG4gICAgICAgIGA7XG4gIH1cbn1cbiJ9LHsibmFtZSI6ImZsb2F0aW4tdWkudHMiLCJjb250ZW50IjoiaW1wb3J0IHsgTWlkZGxld2FyZVN0YXRlLCBwbGF0Zm9ybSwgUGxhY2VtZW50LCBhcnJvdywgYXV0b1BsYWNlbWVudCwgY29tcHV0ZVBvc2l0aW9uLCBoaWRlLCBvZmZzZXQsIHNoaWZ0LCBzaXplIH0gZnJvbSAnQGZsb2F0aW5nLXVpL2RvbSc7XG5pbXBvcnQgeyBvZmZzZXRQYXJlbnQgfSBmcm9tICdjb21wb3NlZC1vZmZzZXQtcG9zaXRpb24nO1xuXG5jb25zdCBtaWRkbGV3YXJlID0gW1xuICBvZmZzZXQoeyBtYWluQXhpczogMCwgY3Jvc3NBeGlzOiAwIH0pLFxuICBvZmZzZXQoMCksXG4gIGF1dG9QbGFjZW1lbnQoeyBhbGxvd2VkUGxhY2VtZW50czogWydib3R0b20tc3RhcnQnLCAndG9wLWVuZCcsICdib3R0b20tZW5kJywgJ3RvcC1zdGFydCddIH0pLFxuICBzaGlmdCgpLFxuICBoaWRlKHtcbiAgICBzdHJhdGVneTogJ3JlZmVyZW5jZUhpZGRlbicgLy8gJ3JlZmVyZW5jZUhpZGRlbicgYnkgZGVmYXVsdFxuICB9KVxuXTtcblxuZXhwb3J0IGZ1bmN0aW9uIHVzZUZsb2F0aW5nVUkodHJpZ2dlcixwYW5lbCl7XG4gY29uc3QgZ2V0T2Zmc2V0UGFyZW50ID1cbiAgICAgIChlbGVtZW50OiBFbGVtZW50KSA9PiBwbGF0Zm9ybS5nZXRPZmZzZXRQYXJlbnQoZWxlbWVudCwgb2Zmc2V0UGFyZW50KSA7XG5jb21wdXRlUG9zaXRpb24odHJpZ2dlciwgcGFuZWwsIHtcbiAgICAgICAgcGxhY2VtZW50OiAnYm90dG9tLXN0YXJ0JyAsXG5cbiAgbWlkZGxld2FyZTogbWlkZGxld2FyZSxcbiAgc3RyYXRlZ3k6J2Fic29sdXRlJyxcbiAgcGxhdGZvcm06IHtcbiAgICAgICAgLi4ucGxhdGZvcm0sXG4gICAgICAgIGdldE9mZnNldFBhcmVudFxuICAgICAgfVxufSkudGhlbigoeyB4LCB5IH0pID0-IHtcbiAgT2JqZWN0LmFzc2lnbihwYW5lbC5zdHlsZSwge1xuICAgIGxlZnQ6IGAwcHhgLFxuICAgIHRvcDogYDBweGAsXG4gICAgdHJhbnNmb3JtOiBgdHJhbnNsYXRlKCR7eH1weCwgJHt5fXB4KWAsXG5cbiAgfSl9In1d)

I have a container (class=modal__body) which is 150px height and overflow as auto
Inside the container, i have a text passage and an input-field.
This input-field is the reference element and has position as relative. On clicking of the input, our floating element is displayed which is positioned absolute and transformed using floating-ui.

In the floating ui config, if I provide
  autoPlacement({ allowedPlacements: ['bottom-start','bottom-end'] }),

the floating element is displayed below and our container scroll appears which looks good.

But, if I provide 
  autoPlacement({ allowedPlacements: ['bottom-start', 'top-end', 'bottom-end', 'top-start'] }),

the floating element always displays at the top-end and it is clipping off.

1. click on the input field
2. floating element appears which is clipped off

**Expected behavior** Even when the allowedPlacements has ['bottom-start', 'top-end', 'bottom-end', 'top-start'], floating ui should 
know that the element will be clipped off by the overflow container and should display below, since if displayed below atleast we can scroll to see the floating element.

We need to provide all four placement because, in this scenario, it is clipping off on the top. But in other scenarios , floating element can be displayed on top without clipping off, if it is not placed inside a container with max-height.

**Screenshots**<img width="743" alt="image" src="https://github.com/floating-ui/floating-ui/assets/161848096/e5121149-19d5-4dc8-ab57-97bfda9de99d">

**Context:**

- OS: windows 10
- Browser chrome
- Version 126

**Comment by atomiks** [comment]
This is kind of an ambiguous case given it's only valid when the scrolling direction is top-down. I don't think it's wise to make it aware of this kind of scrolling context (in that the floating element being inserted allows it to scroll down). The most obvious solution here is to ensure the floating element doesn't get clipped by this small container by appending it to a node outside.
