### ISSUE TITLE
Cannot read properties of undefined (reading 'current')

### ISSUE THREAD

**Issue by Arkellys** [floating-ui/floating-ui#2965]
**Describe the bug**

I'm getting the following error with version `0.26.18` of `@floating-ui/react`:

```
TypeError: Cannot read properties of undefined (reading 'current')
    at floating-ui.react.mjs:3601:1
    at mountMemo (react-dom-client.development.js:6820:1)
    at Object.useMemo (react-dom-client.development.js:22432:1)
    at exports.useMemo (react.development.js:1514:1)
    at useListNavigation (floating-ui.react.mjs:3599:1)
    at Floating (app.bundle.js:125220:78)
    at callComponentInDEV (react-dom-client.development.js:517:1)
    at renderWithHooks (react-dom-client.development.js:5780:1)
    at updateFunctionComponent (react-dom-client.development.js:7881:1)
    at beginWork (react-dom-client.development.js:9503:1)

The above error occurred in the <Floating> component.
```

First `at` leads to:

```js
 const activeItem = listRef.current.find(item => (item == null ? void 0 : item.id) === activeId);
```

**To Reproduce**

I get the error because I don't pass the parameter `listRef` to `useListNavigation`. However, this is for a floating element which is not a list, so this hook has `enabled` to `false`.

**Expected behavior**

The [listRef](https://floating-ui.com/docs/uselistnavigation#listref) parameters is marked as required, so *I suppose* this is the expected behavior. However, the docs mention default value for this param is an empty array, and the version introducing the error is marked as a patch.

Is `listRef` now mandatory even when the hook is disabled? If so, I think this should have been a breaking change and the docs should be updated to remove the mention of a default value.

**Context:**

- OS: Windows
- Browser: Electron v31
- Versions: 
  - `@floating-ui/react`: `0.26.18`
  - `react`: `19.0.0-rc-e684ca66ab-20240619`

**Comment by atomiks** [comment]
That line shouldn't run when `enabled` is false, since the `reference` prop getters aren't returned in that case. Repro?

**Comment by Arkellys** [comment]
Alright, so is it something that should be fixed or is the error expected?

**Comment by atomiks** [comment]
The fix we should make here is to avoid reading `listRef.current` in render, which isn't allowed by React. Since it's wrapped in `React.useMemo`, it made it less obvious to spot it was breaking that rule. This was also the case in the previous version but only when `enabled` was `true`, so this error didn't happen
