### ISSUE TITLE
Memory leak when autoUpdate iframe gets swapped out

### ISSUE THREAD

**Issue by pzaczkiewicz-athenahealth** [floating-ui/floating-ui#2969]
**Describe the bug**

Since #2518, If autoUpdate is triggered off a trigger in an iframe and the iframe gets swapped out for a new one, then the event listeners placed on the top-level ancestor may not get cleaned up.

We have an internal React app that uses autoUpdate within an iframe. This iframe is frequently "swapped out" for a new URL 100s of times within the lifetime of the parent window. We're using the return value of useEffect to call the autoUpdate cleanup function, but React does not call this function when the entire iframe is changed or reloaded.

Adding event listeners on `beforeunload` improves the situation, but repeated integration tests do detect some accumulated event listeners. Meanwhile, our parent window does not do any scrolling. For us, it would be best if we could attach the event listener to the local window `<body>` rather than the top-level `<body>`.

**To Reproduce**

I don't have a minimal example repo yet. I may be able to assist with writing the solution.

We use Storybook to demo our components, and Storybook uses iframes. The bug can be reproduced in Storybook by right-clicking and selecting "Reload Frame" within the context menu. Event listeners accumulate on `<body>`. While reloading the frame is not a typical workflow, it is likely the easiest pathway to reproduce the issue.

**Comment by atomiks** [comment]
> We're using the return value of useEffect to call the autoUpdate cleanup function, but React does not call this function when the entire iframe is changed or reloaded.

I'm not sure I fully understand the issue? How is this a memory leak if you're the one responsible for cleaning up the nodes in this scenario - I'm assuming this issue doesn't exist when using `whileElementsMounted`? The nodes in the array are the same as the ones that get registered, so if you call `cleanup()` at the correct times, then it should clean them up correctly

**Comment by pzaczkiewicz-athenahealth** [comment]
I'll write a reproduction repo when I have time. Still dealing with fallout from this memory leak.

I didn't know about [whileElementsMounted](https://floating-ui.com/docs/usefloating#whileelementsmounted), but I still feel it wouldn't save us here. Our site uses iframes to render the header / footer, and sometimes a side panel of the main website. The main website is itself an iframe, thus the top-level URL never changes, and a full page reload never occurs. The "main content" iframe changes its URL periodically, but the top-level website doesn't reload until the user times out due to inactivity. This iframe switching logic is > 20 years old, so patching it to call a yet-to-be-defined cleanup function is risky, and would take time to patch.

One limitation of both [whileElementsMounted](https://floating-ui.com/docs/usefloating#whileelementsmounted) and [autoUpdate](https://floating-ui.com/docs/autoUpdate) is that they both assume that you'll have some sort of hook later on to call the callback function. When an iframe is unloaded, React does not call useEffect cleanup functions. Ordinarily this wouldn't be a problem, because all event listeners are removed from a window if the window is swapped out. With iframes, these event listeners "break out" of the window that defined them.  At best, we can add a `beforeunload` listener to call this cleanup function, but MDN notes that `beforeunload` is not 100% reliable. We've demonstrated as well in our integration tests.

Our workaround for now is to not call autoUpdate when our Popover is invisible. It's a good practice anyway, but the possibility of a leak remains if the iframe is unloaded while the Popover is visible.

I can appreciate that adding an event listener to _all_ the ancestors is a useful feature to deal with the parent page scrolling the child iframe. We don't have that behavior in our app, so having an argument to autoUpdate that prevents listeners from breaking out of the current iframe feels like the best compromise between functionality and risk.

**Comment by atomiks** [comment]
I don't believe this is a memory leak unless you have a reproduction proving that calling `cleanup()` still leaves listeners regisrtered on nodes. It's the consumer's responsibility to ensure this function gets called at the correct time. I can reopen if a repro is provided.
