### ISSUE TITLE
Calculate Position does not work for child elements of container-type: inline-size

### ISSUE THREAD

**Issue by jake-macadamian** [floating-ui/floating-ui#2971]
### Discussed in https://github.com/floating-ui/floating-ui/discussions/2970

<div type='discussions-op-text'>

<sup>Originally posted by **jake-macadamian** July  9, 2024</sup>
I'm using @floating-ui/dom@1.6.7 and it's calculating the wrong position.
```
<div> -- container-type: inline-size
   <div popovertarget></div> -- Target Element
   <div popover></div> -- Popover Element
</div>
```
It calculates the position as if the container were at the top left corner of the screen.  When I disable the container-type it calculates the position correctly.</div>

[View issue here](https://codesandbox.io/p/sandbox/loving-haibt-hqxx6v?file=%2Fsrc%2Fstyles.css%3A26%2C29)

**Comment by atomiks** [comment]
Please add a reproduction to the issue!

**Comment by jake-macadamian** [comment]
Added.  The sandbox link I used was forked from a previous issue.
Curiously I actually get different positions in my actual project.  For my actual project it jumps to the top left of the screen.  Here though it's jumping down to the bottom.

**Comment by atomiks** [comment]
Thanks. I can see two problems here:

- `margin: 0` needs to be applied to top layer elements, as the default user agent style's margin affects the position.
- You need to move `.showPopover()` before `computePosition`. It's not "rendered" (with layout/size to measure) for the call so it has 0 size.

When both of those are addressed the position looks correct, suggesting there isn't a bug for this particular layout.

**Comment by jake-macadamian** [comment]
Confirmed, it was as easy as that 🙂 ty
