### ISSUE TITLE
FloatingFocusManager modal still allows functionality on outside elements

### ISSUE THREAD

**Issue by alexcarpenter** [floating-ui/floating-ui#2983]
**Describe the bug** A clear and concise description of what the bug is.

When using the `FloatingFocusManager` with `modal={true}` users can still interact with the page e.g. hover interactions are possible.

**To Reproduce**

https://codesandbox.io/p/sandbox/heuristic-moser-n2j6lp

1. Go to https://codesandbox.io/p/sandbox/heuristic-moser-n2j6lp
2. Open popover
3. Hover button with text "Hover me should not work when popover open"
4. See hover state triggered

**Expected behavior** A clear and concise description of what you expected to
happen.

In the video shown below, I would expect not to be able to interact with the button outside of the popover. The button should not trigger its hover state since modal is true.

**Screenshots** If applicable, add screenshots to help explain your problem.

https://github.com/user-attachments/assets/25b64747-95b7-40f8-9f8c-c2f5bdb8c3f6

**Context:**

**Additional context** Add any other context about the problem here.

Based on this bullet point in the docs, i'd assume the hover interactivity should not be happening when the popover is opened.

> The popover and its contents are the only elements that can receive focus. When the popover is open, the user cannot interact with the rest of the page (nor can screen readers) until the popover is closed.

**Comment by atomiks** [comment]
`FloatingFocusManager` only handles the concept of modal **focus**, not modality in general (i.e. including hover). The `FloatingOverlay` component can be used to create a backdrop that blocks pointer-events for the hover modality, to be used in conjunction with the modal focus management
