### ISSUE TITLE
Popover element position not updating when the body is scrollable

### ISSUE THREAD

**Issue by ddegan** [floating-ui/floating-ui#2990]
**Describe the bug**
When the body is scrollable, the floating element remains in a fixed position.  We are using on the floating element the [popover](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/popover) attribute.

**To Reproduce**

1. Go to [this CodeSandbox](https://codesandbox.io/p/sandbox/popover-ui-scroll-issue-yvm4zl?file=%2Findex.html%3A9%2C11)
2. Click on the "Open" button
3. Scroll down
4. See that the floating element doesn't follow the reference element

**Expected behavior** 
The floating element should remain anchored to the reference element

**Version of the library**
`@floating-ui/dom@1.6.3`

**Additional context** 
We found a workaround, adding a custom middleware that subtracts the body's scrollTop value to the computed y coordinate.

```
private getScrollTop(): number {
    return (document.scrollingElement || document.documentElement).scrollTop;
}

[......]

const shiftCustomMiddleware = {
      name: 'shiftCustomMiddleware',
      fn: ({y}) => {
        return {
          y: y - this.getScrollTop()
    };
  }
};

const callback = ()=> {
   computePosition(reference, floating, {
      middleware: [
          shiftCustomMiddleware
     ]
   });
}

autoUpdate(reference, floating, callback);
```

**Comment by atomiks** [comment]
https://floating-ui.com/docs/autoUpdate

**Comment by atomiks** [comment]
The [initial styles](https://floating-ui.com/docs/computePosition#initial-layout) aren't applied, it's not an absolutely positioned element
