### ISSUE TITLE
isRTL function at floating-ui.dom.mjs:433:26 might cause forced reflow

### ISSUE THREAD

**Issue by Sinongamess** [floating-ui/floating-ui#2995]
This function checks if an element's text direction is right-to-left (RTL) by using getComputedStyle, which can trigger a forced reflow：

```
function isRTL(element) {
  return getComputedStyle(element).direction === 'rtl';
}
```
Please let me know if there are better ways to handle this or if there's an existing workaround to reduce the forced reflows caused by this function.

Thank you.

**Comment by atomiks** [comment]
`getComputedStyle` calls are used all over the codebase, I think this is just the first one that gets triggered and is highlighted. There's no way to avoid it though
