### ISSUE TITLE
Root menu focus moves when press the `Home` or `End` keys in an opened submenus.(using virtual nested dropdownMenu) 

### ISSUE THREAD

**Issue by sunyoungBae** [floating-ui/floating-ui#3001]
**Describe the bug**
I'm building a virtual nested dropdown menu based on the [this guide](https://github.com/floating-ui/floating-ui/pull/2528#issuecomment-1712408062).
* `virtual` is set to true in useListNavigation

When I execute the following steps, I want the focus of the submenu to move.(It works fine if I don't use `virtual: true`.) But now the focus in the root menu (1 depth menu) moves.
1. `Edit balloon` button click to focus on the button.
2. Use the`ArrowDown` key to move to 'Pop with'
3. Use the `ArrowRight` key, which automatically opens the sub-menu and moves to 'Knife'
4. Use the `ArrowDown` key to move to 'Pin'(ArrowDown, ArrowUp keys move well inside the submenu)
5. Use the `Home` Key or `End` Key!!

Are there any known solutions or workarounds for this issue?

**To Reproduce**

[Example](https://codesandbox.io/p/devbox/jovial-mountain-89mzvx?file=%2Flib%2Fcomponents%2FDropdownMenu.tsx%3A136%2C1&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clzjjw6aw00083b6lv01gqi5d%2522%252C%2522sizes%2522%253A%255B86.2426614481409%252C13.757338551859107%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clzjjw6av00033b6lwsjk03v0%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clzjjw6av00053b6ljfpqzhvk%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clzjjw6av00073b6l5jgzffg0%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B40%252C60%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clzjjw6av00033b6lwsjk03v0%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clzjjw6av00023b6lk8bowcua%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A136%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A136%252C%2522endColumn%2522%253A1%257D%255D%252C%2522filepath%2522%253A%2522%252Flib%252Fcomponents%252FDropdownMenu.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clzjjw6av00033b6lwsjk03v0%2522%252C%2522activeTabId%2522%253A%2522clzjjw6av00023b6lk8bowcua%2522%257D%252C%2522clzjjw6av00073b6l5jgzffg0%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clzjjw6av00063b6liilfn8t0%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clzjjw6av00073b6l5jgzffg0%2522%252C%2522activeTabId%2522%253A%2522clzjjw6av00063b6liilfn8t0%2522%257D%252C%2522clzjjw6av00053b6ljfpqzhvk%2522%253A%257B%2522id%2522%253A%2522clzjjw6av00053b6ljfpqzhvk%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clzjjw6av00043b6l7rxq4wq7%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clzjjw6av00043b6l7rxq4wq7%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A22.75%257D) of upgrading only `@floating-ui/react` version from the guide above('Describe the bug').

It is the same as the steps described above('Describe the bug').

**Expected behavior**

Pressing `Home` or `End` key in submenu should move focus submenu items.
* I think you're missing some handling([like this code](https://github.com/floating-ui/floating-ui/blob/master/packages/react/src/hooks/useListNavigation.ts#L854-L892)) of the `home` and `end` key.(this is just a guess.)

**Screenshots** If applicable, add screenshots to help explain your problem.

**Context:**

- OS: mac OS(Sonoma)
- Browser: Chrome
- Version: @floating-ui/react : 0.26.22

**Additional context** Add any other context about the problem here.

**Comment by atomiks** [comment]
The CodeSandbox demo doesn't seem to work correctly at all when navigating with arrow keys, not even considering Home/End behavior. Can you make one using the [MenuVirtual demo](https://github.com/floating-ui/floating-ui/blob/master/packages/react/test/visual/components/MenuVirtual.tsx) in this repo instead?

**Comment by sunyoungBae** [comment]
@atomiks Yes, I created an [example](https://codesandbox.io/p/sandbox/floating-ui-menu-virtual-q48wj7?file=%2Fsrc%2FMenuVirtual.jsx%3A7%2C18) using the MenuVirtual demo you mentioned.
In this example, pressing Home/End on a submenu still navigates to the root menu.

![Aug-16-2024 10-50-35](https://github.com/user-attachments/assets/1ba411aa-2b2b-48cf-b8e9-74ef6f269ba7)
