### ISSUE TITLE
useClick does not bind event listeners to external reference, while useHover does

### ISSUE THREAD

**Issue by mihkeleidast** [floating-ui/floating-ui#3003]
**Describe the bug**

When passing an external reference to useFloating, hover event listeners are automatically added to the reference, while click events are not.

There seems to be a bunch of code in useHover hook that does this: https://github.com/floating-ui/floating-ui/blob/master/packages/react/src/hooks/useHover.ts#L330-L331

But useClick only returns the interaction hook props that have to be manually added to the reference - which, if the reference is totally external, is a bit difficult: https://github.com/floating-ui/floating-ui/blob/master/packages/react/src/hooks/useClick.ts#L107

**To Reproduce**

Here is a hover-opened popover opening and closing perfectly fine when just passing reference to useFloating: https://codesandbox.io/p/sandbox/sleepy-diffie-74r9wq

Here is a popover without hover, only click, that does not open/close when interacting with the trigger: https://codesandbox.io/p/sandbox/reverent-blackburn-mx63m6?workspaceId=c29cbdb5-5dfa-412a-a5ba-2d4dac233d12

Realistically I'm using the first one, where both hover and click are both active at the same time, to enable both fast opening for mouse users and keyboard / screen reader user support.

**Expected behavior**

Would expect click event listeners to be added to reference as well, so it would open and close.

**Context:**

- OS: Windows 10
- Browser: Edge
- Version: 127

**Additional context**

This can be worked around by manually adding/removing click event listeners, but I'm not sure if the various other event handlers that the hook returns would also be needed to be added. I think it would be preferred if the various interaction hooks all behaved similarly - either all of them should add event listeners in the same manner to external reference, or none of them should. Right now it is a bit inconsistent.

Not sure about other interaction hooks at the moment like useFocus, those should likely also be looked at.

**Comment by atomiks** [comment]
With the [`useFloatingRootContext`](https://floating-ui.com/docs/useInteractions#external-reference) hook, interaction props can be placed upon an external reference easily now. `useHover` registers listeners manually as a workaround to fix bugs with event delegation (this is mentioned in the `useHover` docs.)

**Comment by mihkeleidast** [comment]
`useFloatingRootContext` requires an actual shared parent component for both the reference and floating element, have to "extract" the tooltip ref there, etc, which is quite complex really.

My current usecase is that the component accepts either a string id of the reference (`<Tooltip referenceElement="some-id" />`), or the reference directly (`<Tooltip referenceElement={triggerRef} />`), the reference itself can be completely separate from the floating component.

My main point here is about consistency, I can add the click event listeners manually as well (as I'm doing today with popper.js), just weird I only have to handle one interaction method as a workaround, not all of them.

**Comment by mihkeleidast** [comment]
Feel free to close as a wontfix if it will stay this way - I'm fine with the workaround & mostly understand that it's still needed to spread the props to the trigger element. I think I need to add a solution so this could be done to my component and then work through all the usecases to convert them to the new solution.
