### ISSUE TITLE
`size` with `shift` doesn't fill the viewport when resizing

### ISSUE THREAD

**Issue by madoci** [floating-ui/floating-ui#3011]
### Discussed in https://github.com/floating-ui/floating-ui/discussions/3005

<div type='discussions-op-text'>

<sup>Originally posted by **madoci** August 14, 2024</sup>

**Describe the bug**

When using `shift` with `crossAxis` set to true, along with `size`, the `availableHeight` (or `availableWidth` if placement is left or right) doesn't increase to the actual available height when the floating element shifts over the reference.

**To Reproduce**

1. Go to https://codesandbox.io/s/modest-dream-dy5ns6?file=/src/index.js
2. Resize the window down until the tooltip hits the top and starts shrinking.
3. Resize the window up.
4. The tooltip moves down, but stays the same size. Its starts growing again when the top hits the bottom of the reference.

**Expected behavior**

When resizing up, the tooltip should regrow to fill the new available space.

**Screenshots**
![Capture d’écran du 2024-08-14 15-36-35](https://github.com/user-attachments/assets/10543973-2a7a-4103-956c-2437fc52e07c)

**Context:**

- OS: Debian
- Browser: Chrome 127.0.6533.99
- Version: @floating-ui/dom 1.6.10

**Additional context**

I think the issue lies here : 

https://github.com/floating-ui/floating-ui/blob/a8b7a88a73f780c59b89bb8c6e3db16ec589a43d/packages/core/src/middleware/size.ts#L85-L95

The `availableHeight` or `availableWidth` is set to `maximumClippingHeight` when shifting, but only on the main shift axis.
In fact, this code seems overcomplicated to me. The `overflowAvailable<size>` is set before to the min between some value and `maximumClipping<size>`, so `min(overflowAvailable<size>, maximumClipping<size>)` is equivalent to `overflowAvailable<size>`. And since `available<size>` is set before to `overflowAvailable<size>`, the ternary condition essentially means `If alignment or noShift, do nothing. Otherwise, set to maximumClipping<size>`. So the condition could be put in the `if... else...`. It doesn't change much, but it will allow me to simplify my proposal.

The `available<size>` should be set to `maximumClipping<size>` if there is a shift along its axis, even if it's on the placement axis. Something like this would work : 
```js
if (state.middlewareData.shift?.x && !(alignment && isYAxis)) {
  availableHeight = maximumClippingHeight;
}
if (state.middlewareData.shift?.y && !(alignment && !isYAxis)) {
  availableHeight = maximumClippingHeight;
}
```

This works in my case, but I don't know the side effects it can have.

However, during testing on the codesandbox, I noticed that the behaviour also depends on the padding given to `shift` and `size`. The behaviour explained here shows when we use the same padding for both middleware. In the codesanbox, you can clik on the "Show other tooltips" button to display a tooltip where `size` has less padding than `shift`, and one where `size` has more padding than `shift`. With less padding, the tooltip resize almost correctly (it has some weird deferment when approaching its max height). With more padding, the tooltip shifts only when it cannot shrink anymore.

This appears to come from what `detectOverflow` returns. With the code above, all of these cases seems to be fixed, but I don't know if this is a bug of the `detectOverflow` function or if it works as intended.</div>

**Comment by madoci** [comment]
While attempting to fix this, I found out that the bug also appears on the `shift` main axis if the floating is aligned (the `shift` must be placed before the `size`).

> Steps to reproduce the behavior:
> 
> 1. Go to https://codesandbox.io/p/sandbox/floating-ui-react-dom-template-qfufud
> 2. Click on "before" in the "Add shift" section.
> 3. Resize the container to reduce its width to the minimum.
> 4. Resize the container to increase its width a bit.
> 5. The floating element doesn't regrow to take the newly available space.

The proposed solution above seems to fix both issues, and as far as I know does not have unwanted side effects. But one problem remains. To guess if the floating can shift along an axis, I use the `shift.x` and `shift.y`. But these values can be equal to 0 even if a shift is allowed. It shows when we add the `shift` after initial placement.

> Steps to reproduce the behavior:
> 
> 1. Click on "before" in the "Add shift" section.
> 2. The floating element stays the same width (under 300px) while it could shift to grow to its ideal width of 300px.

Is there a way to know, in the `size` function, the axis along which `shift` is enabled ?

I also have a few questions about the testing of the `size` middleware (in [Size.tsx](https://github.com/floating-ui/floating-ui/blob/a8b7a88a73f780c59b89bb8c6e3db16ec589a43d/packages/dom/test/visual/spec/Size.tsx)) : 
- What are the benefits of adding a `flip` ? It doesn't directly interact with `size`, and it hides some issues that arise when using `shift` with `size`. So it feels like it is doing more harm than good.
- Why is the `shift` added **after** the `size` when there is an alignment ? I think that it doesn't test much since the `size` happens as if there was no `shift`, and the `shift` happens normally, only with the new calculated size.

**Comment by atomiks** [comment]
> The proposed solution above seems to fix both issues, and as far as I know does not have unwanted side effects. 

Can you submit a PR with the changes? If tests don't fail, then that is true, otherwise the existing logic has some purpose. But no way to know unless the tests get run.

> Is there a way to know, in the size function, the axis along which shift is enabled ?

`shift`  would need to return the `mainAxis` and `crossAxis` options inside of its `data` return so `size` can read `middlewareData.shift?.mainAxis` for example.

- There are tests for when `flip` is added in the array as it does cause some changes, memory is hazy unless I directly looked why
- `shift` could be added after or before in the array by the consumer; ideally both combinations could be tested to see if the expected behavior still works
