### ISSUE TITLE
After closing the submenu, pressing the `Enter` key selects an item within the submenu.(using virtual nested dropdownMenu)

### ISSUE THREAD

**Issue by sunyoungBae** [floating-ui/floating-ui#3030]
**Describe the bug** A clear and concise description of what the bug is.

When I close a submenu and press the `Enter` key, I expect the currently focused item, i.e. the parent item of the submenu, to be clicked. However, currently the items in the submenu are being clicked before closing.

If it is not a bug, I would appreciate it if you could let me know a solution.

**To Reproduce**

1. Go to [codesandbox](https://codesandbox.io/p/sandbox/floating-ui-menu-virtual-click-tj8m34?workspaceId=79fa430e-0033-4659-a9df-1d34337554d0)
2. Expand Preview console
3. Click on `Input`
4. Use the `ArrowDown` key to move to 'Copy as'
5. Use the `Enter` key to trigger click event and then `'clicked Copy as'` message appears in the console.
6. Use the `ArrowRight` key, which automatically open the sub-menu and moves to 'Text'
7. Use the `Enter` key to trigger click event and then `'clicked Text'` message appears in the console.
8. Use the `ArrowLeft` key, which automatically close the sub-menu and moves to 'Copy as'
9. Use the `Enter` key to trigger click event and then `'clicked Text'` message appears in the console.

**Expected behavior** A clear and concise description of what you expected to
happen.

In the final step, the message `'clicked Copy as'` should appear, not `'clicked Text'`.

**Screenshots** If applicable, add screenshots to help explain your problem.

![Aug-29-2024 18-12-46](https://github.com/user-attachments/assets/c0d03aa3-fe01-4e5f-8abc-75ec64bed691)

**Context:**

- OS: mac OS(Sonoma)
- Browser: Chrome
- Version: @floating-ui/react : 0.26.22

**Additional context** Add any other context about the problem here.

**Comment by atomiks** [comment]
Looks like a bug. I imagine a workaround is to check if the item that was clicked was a selectable item or just a submenu trigger.
