### ISSUE TITLE
Why is there a calculation error, a content calculation error, when the width on the right side is insufficient.

### ISSUE THREAD

**Issue by parlay96** [floating-ui/floating-ui#3031]
Why is there a calculation error, a content calculation error, when the width on the right side is insufficient.

![image](https://github.com/user-attachments/assets/e5e1d8b5-0f8a-4b39-9b4b-1607f75593ee)

![image](https://github.com/user-attachments/assets/a63eff23-85b2-4f95-b567-23659065db33)

version: popperjs+core@2.11.8

**Comment by atomiks** [comment]
Popper is no longer supported

**Comment by parlay96** [comment]
@atomiks 
![image](https://github.com/user-attachments/assets/aa3d2f8e-7ee9-4008-99a3-2b565a3ed12c)
I want to know how to create a floating UI like I did with Popper is before?, Or rather, how can I use the floating UI like Popper is, as shown in this diagram

**Comment by parlay96** [comment]
@atomiks 
![image](https://github.com/user-attachments/assets/a8e4541f-2095-4474-9857-423b4e7b96cd)
For example, I still don't want to give up on the previous usage of Popper is.
