### ISSUE TITLE
[FocusManager] ReturnFocus is bad with autoFocus inside floating element when no reference

### ISSUE THREAD

**Issue by deviun** [floating-ui/floating-ui#3038]
Hi! 

**Good case:** When render floating element **with** reference element and floating has input[**autoFocus**] inside, on close floating element focus will returns to reference.

**Good case:** When render floating element **without** reference element and floating has first input element, input will be focused automatically, and on close focus returns to button that was clicked to open floating.

**Bad case:** When render floating element **without** reference and floating has input[**autoFocus**] inside, on close floating element focus returns to closest button, and not button that clicked to open floating.

https://github.com/floating-ui/floating-ui/blob/master/packages/react/src/components/FloatingFocusManager.tsx#L576

`getPreviouslyFocusedElement` returns undefined.

Demo - https://codesandbox.io/p/sandbox/floating-ui-autofocus-restore-focus-hfc7hl?workspaceId=931d42fe-8789-4c5d-aada-5b75e144648f

"@floating-ui/react": "0.26.23"

**Comment by atomiks** [comment]
The native `autofocus` DOM property isn't supported because it runs before the positioning effect executes, which causes the scroll-to-top of the page bug when scrolled down. The `initialFocus` prop on `FloatingFocusManager`, or a custom `autoFocus` prop which runs inside an effect to call `.focus()` are properly supported alternatives

**Comment by Anatoool** [comment]
> The native `autofocus` DOM property isn't supported

Do you have plans to support it? As far as I understand, many UI libraries that rely on popper.js will have to force their users to rework the interface from using the native autofocus to something else during the migration to floating-ui.

**Comment by atomiks** [comment]
Popper has this same issue
