### ISSUE TITLE
Passing `undefined` for `crossAxis` value in the `offset` middleware breaks the calculations

### ISSUE THREAD

**Issue by CernyMatej** [floating-ui/floating-ui#3044]
**Describe the bug** A clear and concise description of what the bug is.

**To Reproduce**
https://codesandbox.io/p/sandbox/bold-elbakyan-ndyslm?file=%2Fsrc%2Findex.js%3A11%2C7

1. Pass the following options to the `offset` middleware:
```ts
offset({
  mainAxis: 10,
  crossAxis: undefined,
}),
```

**Expected behavior**
The popup should not be offset along the crossAxis but should remain runctional.

**Screenshots**
<img width="412" alt="image" src="https://github.com/user-attachments/assets/c62c8582-35d1-4541-b9db-c2f921fa4204">
<img width="472" alt="image" src="https://github.com/user-attachments/assets/afbd2c57-9b3e-4f89-9589-a98b91d0c42a">

**Context:**

- OS: macOS
- Browser chrome
- Version 128.0.6613.137

**Comment by atomiks** [comment]
Fixed by https://github.com/floating-ui/floating-ui/commit/2e9e109bbbf070f2e376d715597c9eaf4b1fff76, not released yet
