### ISSUE TITLE
touch event outside of floating element causes interactive element to be triggered

### ISSUE THREAD

**Issue by mblumenstingl-n11** [floating-ui/floating-ui#3048]
**Describe the bug**

The behavior on buttons in the background should be identical when using `click` or `tap` (touchscreen) events.
When using `useDismiss` clicking or tapping on a non-interactive element outside the floating element causes the floating element to be closed.
When clicking on an interactive element (such as a button) outside the floating element the floating element is hidden and the click event listener on the outside button is not triggered.
However, when tapping on an interactive element (such as a button) outside the floating element the floating element is hidden and the click event listener on the outside button is triggered.

**To Reproduce**

https://codesandbox.io/p/sandbox/4jm9s7

1. Go to https://codesandbox.io/p/sandbox/4jm9s7 using a Desktop browser with touch events disabled
2. Click on 'open menu'
3. Click on 'change background color'
   expected and actual result: menu (floating element) is closed,background color is not changed
5. Go to https://codesandbox.io/p/sandbox/4jm9s7 using a Mobile browser with touch events enabled
6. Tap on 'open menu'
7. Tap on 'change background color'
  expected result: menu is closed, background color is not changed (same as with the Desktop browser)
  actual result: menu (floating element) is closed but background color is not changed

**Expected behavior**
When clicking and tapping outside the floating element (while `useDismiss` is active) the behavior should be identical:
- floating element closes
- click/tap event on another element outside the floating element is not propagated

This works as expected for click events but not for touch (tap) events.

**Context:**

- Windows, Google Chrome 128.0.6613.138
- Android, Galaxy S22, Google Chrome 128.0.6613.146

**Comment by atomiks** [comment]
You can change the `outsidePressEvent` option of `useDismiss` to `mousedown`, which solves this problem as it's better suited to elements with dimming backdrops: https://floating-ui.com/docs/useDismiss#outsidepressevent

**Comment by mblumenstingl-n11** [comment]
that was super quick and it works - thank you @atomiks !

**Comment by khemarato** [comment]
Had this same issue. @atomiks, why not default outsidePressEvent to 'mousedown'?
