### ISSUE TITLE
useClick toggle does not work bcs dataRef.current.openEvent is undefined in onClick handler

### ISSUE THREAD

**Issue by tomaszrondio** [floating-ui/floating-ui#3054]
I use Floating UI to create dropdowns in React. I have separate component that handles whole logic where I pass AnchorRef as prop. Therefore I have to attach all event listeners etc "manually" like that:

```
    useLayoutEffect(() => {
      const anchorEl = anchorElementRef?.current;

      // first is a safe check (anchorElement is mandatory). If ref is passed it means that it is a controlled component
      if (!anchorEl || ref) return;

      const entries = Object.entries(getReferenceProps());

      for (const [key, value] of entries) {
        if (typeof value === 'function') {
          anchorEl.addEventListener(
            reactToDomEventType[key] as keyof ElementEventMap,
            vallue as EventListenerOrEventListenerObject,
          );
        } else if (typeof value === 'string') {
          anchorEl.setAttribute(key, value);
        }
      }

      return () => {
        ...removing stuff
        }
      };
    }, [anchorElementRef]);
```

issue is that onClick handler fired by external anchor element opens but does not close the floating element.  
There is this line:
`if (open && toggle && (dataRef.current.openEvent ? dataRef.current.openEvent.type === 'click' : true)) ` dataRef.current.openEvent is always undefined therefore it always opens. Outside click works like a charm though.

What am I missing?

- OS: [mac os]
- Browser [chrome, safari]
- Version [0.26.24]

**Comment by atomiks** [comment]
This method of assigning props is subject to break at any time and has before and is not supported. The reason is the `event.nativeEvent` property is what is used to assign the event but this doesn't work in non-React contexts. 

The `useFloatingRootContext()` is supported, which allows you to assign props from a higher component in a tree while still using React props without hacks that can break.
