### ISSUE TITLE
Arrow middleware does not work with new Vue useTemplateRef

### ISSUE THREAD

**Issue by hugoattal** [floating-ui/floating-ui#3058]
**Describe the bug** A clear and concise description of what the bug is.

**To Reproduce**

Here's how we should use template ref from the documentation: https://floating-ui.com/docs/arrow

```vue
<script setup>
const reference = ref(null);
const floating = ref(null);
const floatingArrow = ref(null);
 
const {floatingStyles} = useFloating(reference, floating, {
  mdidleware: [arrow({element: floatingArrow})],
});
</script>
 
<template>
  <div ref="floating" :style="floatingStyles">
    <div ref="floatingArrow"></div>
  </div>
</template>
```

But since Vue 3.5, it's now recommended to use `useTemplateRef()`: https://vuejs.org/guide/essentials/template-refs.html

```vue
<script setup>
const reference = useTemplateRef("reference");
const floating = useTemplateRef("floating");
const floatingArrow = useTemplateRef("floatingArrow ");
 
const {floatingStyles} = useFloating(reference, floating, {
  mdidleware: [arrow({element: floatingArrow})],
});
</script>
 
<template>
  <div ref="floating" :style="floatingStyles">
    <div ref="floatingArrow"></div>
  </div>
</template>
```

It does work for `reference` and `floating`.

However, it does not work for `floatingArrow`:
![image](https://github.com/user-attachments/assets/9b842a16-ead5-4d15-9900-df04c223ce8c)

It seems like the reference is being written on, which is unexpected with the `useTemplateRef()`.

---

If you want, I can try to suggest a PR if I find the bug.

**Comment by vpreseault** [comment]
Just spun up a new vite app to try this out and `useTemplateRef()` works fine. You have a few typos in the provided code snippet. If you pasted them directly from your project, maybe start with fixing those:
- `mdidleware` -> `middleware`
- `useTemplateRef("floatingArrow ")` -> `useTemplateRef("floatingArrow")`

I don't think those should be the issue though. Here is the code from my test:
```vue
<script setup>
import { useFloating, arrow} from '@floating-ui/vue'
import { useTemplateRef} from 'vue';

const arrowRef = useTemplateRef('arrowRef')
const floatingRef = useTemplateRef('floatingRef')
const triggerRef = useTemplateRef('triggerRef')

const {floatingStyles} = useFloating(triggerRef, floatingRef, {
  middleware: [
    arrow({
      element: arrowRef,
    }),
  ],
})
</script>

<template>
  <div>
    <button ref="triggerRef">Click me</button>
    <div class="floating" ref="floatingRef" :style="floatingStyles">
      <div class="arrow" ref="arrowRef"></div>
      Floating
    </div>
  </div>
</template>

<style scoped>
.floating {
  color: #000;
  background-color: #fff;
  padding: 10px;
  border-radius: 5px;
}
.arrow {
  position: absolute;
  transform: rotate(45deg);
  width: 20px;
  height: 20px;
  background: #fff;
  z-index: -1;
  pointer-events: none;
}
</style>
```

Result on Chrome:
![image](https://github.com/user-attachments/assets/309146e0-e951-4733-b957-f9313880a460)

Dependencies:
```
  "dependencies": {
    "@floating-ui/vue": "^1.1.5",
    "vue": "^3.5.10"
  },
  "devDependencies": {
    "@vitejs/plugin-vue": "^5.1.4",
    "typescript": "^5.5.3",
    "vite": "^5.4.8",
    "vue-tsc": "^2.1.6"
  }
  ```
  Node version: v20.11.0
  npm version: 10.9.0

**Comment by atomiks** [comment]
Closing based on @vpreseault's result
