### ISSUE TITLE
Popper.js throws null exception using Firefox web browser

### ISSUE THREAD

**Issue by HowardFedTec** [floating-ui/floating-ui#3062]
**Describe the bug** A clear and concise description of what the bug is.

A unhandled null exception is thrown in popper.js.

e is null b@https://unpkg.com/@popperjs/core@2:5:2505 
x@https://unpkg.com/@popperjs/core@2:5:2668 
w@https://unpkg.com/@popperjs/core@2:5:2722 
setOptions@https://unpkg.com/@popperjs/core@2:5:8209 
setOptionsOnInstance@https://localhost:4343/_content/KristofferStrube.Blazor.Popper/KristofferStrube.Blazor.popper.js:43:21

This issue does not occur in Chrome or MS Edge. It only occurs in Firefox.

I am unable to produce a sample that causes this error right now, but I'll keep trying to do so.

N/A

**Expected behavior** A clear and concise description of what you expected to
happen.
The popper tooltip should display without exception.

**Screenshots** If applicable, add screenshots to help explain your problem.
e is null b@https://unpkg.com/@popperjs/core@2:5:2505 
x@https://unpkg.com/@popperjs/core@2:5:2668 
w@https://unpkg.com/@popperjs/core@2:5:2722 
setOptions@https://unpkg.com/@popperjs/core@2:5:8209 
setOptionsOnInstance@https://localhost:4343/_content/KristofferStrube.Blazor.Popper/KristofferStrube.Blazor.popper.js:43:21

**Context:**

- OS: Windows 11
- Browser Firefox
- Version 130.0.1 (64-bit)
- Visual Studio Enterprise Version 17.11.4

dotnet --info
.NET SDK:
 Version:           8.0.401
 Commit:            811edcc344
 Workload version:  8.0.400-manifests.251308be
 MSBuild version:   17.11.4+37eb419ad

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22631
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.401\

.NET workloads installed:
Configured to use loose manifests when installing new manifests.
 [android]
   Installation Source: VS 17.11.35312.102
   Manifest Version:    34.0.113/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.android\34.0.113\WorkloadManifest.json
   Install Type:        FileBased

 [maui-windows]
   Installation Source: VS 17.11.35312.102
   Manifest Version:    8.0.82/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.maui\8.0.82\WorkloadManifest.json
   Install Type:        FileBased

 [maccatalyst]
   Installation Source: VS 17.11.35312.102
   Manifest Version:    17.5.8030/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.maccatalyst\17.5.8030\WorkloadManifest.json
   Install Type:        FileBased

 [ios]
   Installation Source: VS 17.11.35312.102
   Manifest Version:    17.5.8030/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.ios\17.5.8030\WorkloadManifest.json
   Install Type:        FileBased

 [wasm-tools-net6]
   Installation Source: VS 17.11.35312.102
   Manifest Version:    8.0.8/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.workload.mono.toolchain.net6\8.0.8\WorkloadManifest.json
   Install Type:        FileBased

 [wasm-tools-net7]
   Installation Source: VS 17.11.35312.102
   Manifest Version:    8.0.8/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.workload.mono.toolchain.net7\8.0.8\WorkloadManifest.json
   Install Type:        FileBased

 [wasm-tools]
   Installation Source: VS 17.11.35312.102
   Manifest Version:    8.0.8/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.workload.mono.toolchain.current\8.0.8\WorkloadManifest.json
   Install Type:        FileBased

 [aspire]
   Installation Source: VS 17.11.35312.102
   Manifest Version:    8.1.0/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.aspire\8.1.0\WorkloadManifest.json
   Install Type:        FileBased

Host:
  Version:      8.0.8
  Architecture: x64
  Commit:       08338fcaa5

.NET SDKs installed:
  8.0.400 [C:\Program Files\dotnet\sdk]
  8.0.401 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.33 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.33 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.33 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

**Additional context** Add any other context about the problem here.

**Comment by atomiks** [comment]
Popper is unsupported
