### ISSUE TITLE
useListNavigation onNavigation is called multiple times

### ISSUE THREAD

**Issue by PiWar** [floating-ui/floating-ui#3069]
1. Open [Dropdown Menu (including submenus)](https://codesandbox.io/s/admiring-lamport-5wt3yg?file=/src/DropdownMenu.tsx)
2. Check the number of calls to setActiveIndex

Screen from my work
![image](https://github.com/user-attachments/assets/632f01bd-a548-4886-828a-54a004d3e803)

**Comment by atomiks** [comment]
Since `onNavigate` will call a setter like `setActiveIndex` with the same argument, it’s idempotent and doesn’t cause unnecessary re-renders with regular usage
