### ISSUE TITLE
FloatingDelayGroup doesn't play nice with other floating elements

### ISSUE THREAD

**Issue by herzaso** [floating-ui/floating-ui#3071]
### Discussed in https://github.com/floating-ui/floating-ui/discussions/3068

Although there was no real discussion, I couldn't find the problem in my code and it doesn't work.
I hope this will get more visibility as an issue

<div type='discussions-op-text'>

<sup>Originally posted by **herzaso** October  3, 2024</sup>
I'm not sure how to use FloatingDelayGroup.
I've prepared a [codesandbox](https://codesandbox.io/p/sandbox/floating-ui-delay-group-yq8nyn?file=%2Fsrc%2Findex.tsx%3A12%2C7) demonstrating the problem I have.

What you'll notice there:
* I have a usePopover hook that is used for all types of popovers
* I've implemented Tooltip and Popover components that use usePopover
* `App` is wrapped with `FloatingDelayGroup` (since I want all of the tooltips to have no delay if they are close to one another)
* **If Tooltip is placed inside Popover, it closes the Popover on hover**
* If you comment out `FloatingDelayGroup` in `index.tsx` everything will work (except for the delay feature)

What's wrong with my implementation?</div>

**Comment by atomiks** [comment]
The Sandbox is private

**Comment by herzaso** [comment]
Sorry, it should be public now

**Comment by atomiks** [comment]
This component structure/single use hook isn't compatible with delay groups - the components that `useDelayGroup` can't ever have a `parent` -> `child` relationship, they must all be siblings. With click-only triggered popovers, the popover parent doesn't need delay grouping enabled, which would avoid this issue. If you have hoverable popovers with delays that can be inside click popovers, then children & parents need to read from different `FloatingDelayGroup` providers, which to be fair is not really well supported currently if you're wrapping it around your entire app tree

**Comment by herzaso** [comment]
Ok, so just to verify - if I clone usePopover and remove the delayGroup from there (tooltips would use the usePopover with delay and dialogs would use the usePopover without the delay - that should work? (I need to support tooltips inside anything else apart from other tooltips ofc)

Any chance that useDelayGroup would be conditional? (Get another ‘enabled’ parameter which will allow using a single custom hook for both use cases)

**Comment by atomiks** [comment]
Yeah, cloning the hook and removing `useDelayGroup` for the tooltip-like components should work. And, an `enabled` option if added would work to prevent the need to clone (it has been requested somewhere actually, but I forgot about it)

Though there might be some valid cases where a component used as both a parent and a child with delay grouping (e.g. popover that can be configured to be triggered on click or hover + click, for infotips rather than tooltips, which would then be nested inside a parent popover). I'm not sure of a solution to this given React will read the first context provider it encounters; it'd need to be able to read contexts conditionally based on an `id` or something.

**Comment by herzaso** [comment]
I’ll try that, thanks.

Regarding the context, instead of creating a context for each group, maybe you can create a single context which will hold all groups, so when the user asks for a new group, he will provide an ID and you’d add that id to a map in the context?
That way, you have only one context for all the groups and the user can pass the ID around so you’d know which values to use.

**Comment by atomiks** [comment]
That could likely work. For now, I'll just add an `enabled` option to `useDelayGroup` to solve the most common issue

**Comment by herzaso** [comment]
that would be great. In that case, I'll wait with cloning my hook

**Comment by herzaso** [comment]
This could be closed. The new `enabled` option seems to work as expected.
Thanks @atomiks
