### ISSUE TITLE
In the useListNavigation hook, onNavigate is being called twice, causing activeIndex to increment twice.

### ISSUE THREAD

**Issue by geunheejung** [floating-ui/floating-ui#3077]
1. Enter "아" in the input field.
2. When the suggested search terms appear below, press the down arrow key on the keyboard.
3. In this case, the focus moves to the second item instead of the first item.

As a result, the activeIndex increases by 2.

- https://codesandbox.io/p/sandbox/floral-cdn-rwnrgj

https://github.com/user-attachments/assets/3d728fd5-a921-4c5c-a742-a9ba26247c52

**Comment by atomiks** [comment]
When I paste that character in and press ArrowDown it doesn't skip for me and only gets called once (browser: Chrome 129). Does it need to be typed in?

**Comment by geunheejung** [comment]
@atomiks 
Yes, that's correct. You need to type the character in directly. The activeIndex calculates correctly once it has been computed at least once. However, if you refresh the page, and in the initial state where the activeIndex has not been calculated, if you directly input Korean characters instead of English and then navigate the suggested search terms using the keyboard, the index increases by two.

**Comment by atomiks** [comment]
I suppose it might be related to compositional input/IME. It'd be helpful if you could take a look at the `useListNavigation` hook and add some logs to see why it's getting called twice and incrementing incorrectly

**Comment by geunheejung** [comment]
@atomiks 
Thank you for your prompt response. May I kindly ask if it might take more than a month for this issue to be resolved?

**Comment by atomiks** [comment]
I was able to set up a Korean IME on Mac thanks to ChatGPT

When I type "d" then "k" on my keyboard, it creates that character. However when I press ArrowDown after that, it still doesn't skip like before. Are you on Windows instead of Mac? Not sure why it's not reproducing for me?
