### ISSUE TITLE
`useClick`'s keyboard event works differently from mouse clicks.

### ISSUE THREAD

**Issue by sunyoungBae** [floating-ui/floating-ui#3086]
**Describe the bug** A clear and concise description of what the bug is.

I used `useClick` to toggle the open state of the trigger button.
Here, if you toggle the open state using a `mouse click`, there are no activated items when the dropdown is opened.(`activeIndex: null`)
However, if you toggle the open state using the keyboard(`Enter` or `Space`), the first item will be activated when the dropdown opens.(`activeIndex: 0`)

Is there a way to set it to work the same way as a mouse?

**To Reproduce**

[CodeSandBox](https://codesandbox.io/p/sandbox/floating-ui-menu-virtual-forked-65m7c9?workspaceId=79fa430e-0033-4659-a9df-1d34337554d0)

* Mouse click: Click `input`.
* Using the keyboard: Focus on `input` and press `Enter` or `Space`.

**Expected behavior** 

When you toggle the open state using the keyboard, no items are activated.(`activeIndex: null`) In other words, it operates the same as a mouse click.

**Screenshots**

| Mouse Click | Keyboard Press |
|-------------|-----------------|
| ![image-mouse](https://github.com/user-attachments/assets/8912ab83-2786-4c5f-b756-219a41c3f445) | ![image-keyboard](https://github.com/user-attachments/assets/0fbf5675-990c-40a8-ad62-a2edae55deb8)  |

**Context:**

- OS: mac OS(Sonoma)
- Browser: Chrome
- Version: @floating-ui/react : 0.26.25

**Comment by atomiks** [comment]
`useListNavigation` has an option called `focusItemOnOpen`, which can be set to `false`. `auto` (the default) has this behavior difference.

**Comment by sunyoungBae** [comment]
Thank you for the quick reply!!!
