### ISSUE TITLE
Flickering Issue when using FloatingOverlay

### ISSUE THREAD

**Issue by HassounHadi** [floating-ui/floating-ui#3087]
**Describe the bug** A clear and concise description of what the bug is.
![Screenshot 2024-10-18 110735](https://github.com/user-attachments/assets/7821ebb5-04b3-4809-a41d-46e35f9b91e0)
![Screenshot 2024-10-18 110745](https://github.com/user-attachments/assets/e04f4b24-dd2e-4f45-a483-78233c308c66)
![Screenshot 2024-10-18 110751](https://github.com/user-attachments/assets/b1482dc3-3ce3-49af-9eb0-1c917093dc0b)

In the above screenshots you can see the Popover component I've created.
It was working 100% until I needed to lock scroll when the popover is opened. So I had to add the FloatingOverlay component to use the lockScroll prop.
Worked well no more scrolling if the popover is open. But then I noticed an issue in a different component that uses the Popover.
![Screenshot 2024-10-18 111630](https://github.com/user-attachments/assets/1b0479cd-7ef7-4c18-aa02-0ebc1eedb674)

This is my Tooltip component you can see the issue in the below recording.

https://github.com/user-attachments/assets/f524a3d1-6ca6-4dfb-9342-9b8c521b3544

You can notice how the cursor is changing.

I was able to narrow it down to the FloatingOverlay component 
when I did not use it the issue was resolved but couldn't figure out how.

**To Reproduce**

**Expected behavior** A clear and concise description of what you expected to
happen.

**Screenshots** If applicable, add screenshots to help explain your problem.

**Context:**

**Additional context** Add any other context about the problem here.

**Comment by atomiks** [comment]
FloatingOverlay blocks pointer events which triggers `mouseleave` events to fire. You can disable `pointer-events` on it, or ensure the trigger lies on a higher z-index than it.

**Comment by HassounHadi** [comment]
> FloatingOverlay blocks pointer events which triggers `mouseleave` events to fire. You can disable `pointer-events` on it, or ensure the trigger lies on a higher z-index than it.

I tried a tailwind class 'pointer-events-none' it removed the flickering issue but then the lockScroll did not work
