### ISSUE TITLE
Placement in computePosition is not getting respected when allowedPlacements is used in autoPlacement in middleware

### ISSUE THREAD

**Issue by arunks5** [floating-ui/floating-ui#3088]
**Describe the bug** 
Iam having a middleware 
`const middleware = [
  offset({ mainAxis: 0, crossAxis: 0 }),
  offset(0),
  autoPlacement({
    allowedPlacements: [
      'top',
      'right',
      'bottom',
      'left',
      'top-start',
      'top-end',
      'right-start',
      'right-end',
      'bottom-start',
      'bottom-end',
      'left-start',
      'left-end',
    ],
  }),
  shift(),
  // shift({boundary:[]}),
  hide({
    strategy: 'referenceHidden', // 'referenceHidden' by default
    boundary: [],
  }),
];`

allowedPlacements is used in autoPlacement. 
But, when using placement in computePosition , placement is not getting respected and floating element is displayed somewhere else.
**To Reproduce**
I have created a [repo](https://stackblitz.com/edit/vitejs-vite-bmk9sy?file=src%2Fdrawer.ts,src%2Fgreet.ts,src%2Fmodal.ts,src%2Fpicker.ts,src%2Ffloating.ts)

1. Select 'left' radio button which passes, left as placement in computePosition
2. Click on show drawer
3. Click on the input-field
4. The floating element is displayed somewhere else, not on the left side
5. If I remove the allowedPlacement array from autoPlacement, floating element correctly displays on the left side.

**Expected behavior**
The floating element should display on the left side. Only when there is no space or some constraints, is should make use of allowedPlacement arrray in autoPlacement

**Screenshots** If applicable, add screenshots to help explain your problem.

**Context:**

**Additional context** Add any other context about the problem here.

**Comment by atomiks** [comment]
The repo has a runtime error, that as far as I can tell is the only reason for it not working. It has nothing to do with `autoPlacement`
