### ISSUE TITLE
Clicking outside FloatingPortal's to close all parent and child portals does not work correctly on React v16.14.0

### ISSUE THREAD

**Issue by vladimir-skikh** [floating-ui/floating-ui#3092]
Let us have several floating portals nested inside each other. For example, floating portal 1 with an input field inside and floating portal 2 with a button to change the value in the input field. When implementing this behavior using the React library version 16.14.0, a bug occurs in which in order to close both floating portals by clicking outside their tree, you have to click twice. This problem does not exist when implemented through the React library version 18.3.1.

**To Reproduce**
Here is a demo [sandbox](https://codesandbox.io/p/sandbox/q8wshf).

1. Click on button 'Open Popover'
2. Input text 'open' in field to open nested Popover
3. Click outside both floating elements

**Expected behavior** 
Clicking outside of floated elements should close both the parent and nested floated elements, as happens when using the React library version 18

**Screenshots**
https://github.com/user-attachments/assets/b81f2744-82c2-4fd8-b2ec-29866f3befbe

**Context:**

- OS: Windows 11
- Browser: Edge 
- Version v.130.0.2849.46

**Comment by An525ish** [comment]
I'd like to work on this

**Comment by atomiks** [comment]
Does this work in React 17 at least? Although 16 is technically a supported peer dep currently, it hasn't been tested for and works limitedly. In the next minor, the minimum should become React 17 since 16 is too old to support now.

**Comment by atomiks** [comment]
I checked React 17 in the Sandbox and it works correctly like 18. 

As far as I can recall, 17 is easier to upgrade to than 18 and was released over 4 years ago now. For a while, 16.8 with Hooks was easy enough to support a wide range of versions, but issues like this are indicating it's time to drop support for it since it's not worth debugging. Most other React libraries have done so too

**Comment by oliviertassinari** [comment]
@atomiks Use of React 16.8 is indeed not that high:

<img width="572" alt="SCR-20241031-ruyg" src="https://github.com/user-attachments/assets/58a9f01b-404b-4e53-babf-b586532c7d72">

https://tools-public.mui.com/prod/pages/npmVersion?package=react-dom

**Comment by atomiks** [comment]
@oliviertassinari and also, newer libraries like Base UI (and to a lesser extent this library) have an advantage since most of those legacy apps running 16 often can't adopt new dependencies anyway. Most looking to adopt a new lib will be running a modern version.
