### ISSUE TITLE
React FloatingPortal component: Incorrect root node selection for portal rendering

### ISSUE THREAD

**Issue by bsvetlik** [floating-ui/floating-ui#3099]
Despite passing a custom root node to FloatingPortal, the portal is still being rendered in the default portal:

`<FloatingPortal root={portalNode}>` // the passed portalNode is ignored

As a result, the portal is rendered in the wrong location (see attached screenshots).

This is a regression introduced in version @floating-ui/react@0.26.7 as a result of this fix:
"fix(FloatingPortal): unconditional rendering with Suspense"

When I replaced the useFloatingPortalNode() function from @floating-ui\react\dist\floating-ui.react.esm.js with the same function from version react@0.26.6, the issue was resolved.

**Screenshots**
Version react@0.26.6
![v0 26 6-floating-portal](https://github.com/user-attachments/assets/d7c524cc-7efd-4a4e-bf24-08e7f9e32e1b)
Version react@0.26.7
![v0 26 7-floating-portal](https://github.com/user-attachments/assets/40923c8c-7d9d-4e43-9ed7-f97f9f8f6b94)

- OS: Windows 10
- Browser: Chrome, Firefox
- Version: from @floating-ui/react@0.26.7 to the last version @floating-ui/react@0.26.24

**Comment by atomiks** [comment]
How are you passing `portalNode`?

**Comment by bsvetlik** [comment]
The _portalNode_ is passed as property to the _FloatingPortal_ component:
`<FloatingPortal root={portalNode}>`
In our case the _portalNode_ is the <body> element from the other window, that is used as rendering container, but does not contain JS code.

**Comment by atomiks** [comment]
There’s a test for the `root` prop, and testing locally, the portaled content is injected into the portal node when using a ref or state to pass the element. Are you storing the portal node in state? A reproduction is necessary here to debug.

**Comment by bsvetlik** [comment]
I am not storing the the portal node in state. It is obtained in this function:
```
export function getFloatingPortalNode(floatingContext) {
  const ownerDocument = floatingContext?.elements?.domReference?.ownerDocument;
  return ownerDocument?.body;
}
```
I am using the latest React version 18.3.1.

**Comment by atomiks** [comment]
Ok, this makes sense. When `FloatingPortal` is rendered in JSX, the root has to be available when it's mounted, otherwise it renders into the body and doesn't update. One workaround is to ensure the `FloatingPortal` is only rendered when `open` (conditionally rendered, recommended on the docs), which should cause the root to be available on open, after the trigger's owning body exists

To fix this internally, we could check if `root` has been specified/is not `undefined` in order to wait for it to exist before assuming it needs to use the fallback `body`. In this case, if your function doesn't return `null`, it will need to be updated to do so for the fix to work.

**Comment by bsvetlik** [comment]
Excellent work! You correctly diagnosed the issue without needing a reproduction. By simply swapping two lines of code, the problem was resolved:
```
      <FloatingPortal root={portalNode}>
        {visible && (
          <FloatingFocusManager
```
=>
```
      {visible && (
        <FloatingPortal root={portalNode}>
          <FloatingFocusManager
```
I'm not sure why I didn't consider that initially; perhaps it didn't work as expected in older versions of floating-ui. Thank you very much!
