### ISSUE TITLE
FloatingFocusManager: mouseleave does not always prevent returnFocus when using safePolygon

### ISSUE THREAD

**Issue by mihkeleidast** [floating-ui/floating-ui#3129]
**Describe the bug**

Sometimes, when using hover toggleable popover, when closing the popover from safe polygon area, focus is moved back to previous focused element. This is unexpected as the previously focused element may have a focus trigger on it's own that opens some other element.

**To Reproduce**

https://codesandbox.io/p/sandbox/intelligent-beaver-8lh66v

1. Focus the input
2. While the input is focused, open/close the Popover once with hover
3. Click on body (anywhere outside the input to blur it)
4. Now open the Popover with hover, and close it by triggering the safePolygon change reason.
5. Focus moves back to input, which is unexpected.

Note that sometimes step 2 is not necessary, happens even without it, but with 2 included I could always reproduce this, so I included it anyway.

**Expected behavior**

I expect the focus not to be returned to anything if the closing reason is hover, does not matter if mouseleave is caused by simple hover or safePolygon hover.

**Screenshots**

https://github.com/user-attachments/assets/cd995d66-bd7d-4c71-ac2d-4dd8abd953ea

**Context:**

- OS: Windows
- Browser: Edge
- Version: 131

**Additional context**

If I looked at the code here: https://github.com/floating-ui/floating-ui/blob/master/packages/react/src/components/FloatingFocusManager.tsx#L525

It checks for "hover" change reason, but when using safePolygon the reason is actually "safe-polygon". I think that accounting for "safe-polygon" in that if statement may fix the issue.

Sidenote: the fact that "safe-polygon" is a possible change reason may be a bit unexpected in other scenarios as well. For example, if I want to track the change reason externally, but only care whether it's hover/click, I need to "normalize" the reason given from onOpenChange manually myself.

Also, given that in that scenario, the reference element ref should also be available, even if the focus is moved back to anything, the correct place to return focus to would be the reference, not the previously focused element. If that happened instead, this issue would be less annoying.

**Comment by atomiks** [comment]
> Sidenote: the fact that "safe-polygon" is a possible change reason may be a bit unexpected in other scenarios as well. For example, if I want to track the change reason externally, but only care whether it's hover/click, I need to "normalize" the reason given from onOpenChange manually myself.

I've also found this to be more annoying than not. I don't think the granularity of knowing this state is really worth it, but idk.

> Also, given that in that scenario, the reference element ref should also be available, even if the focus is moved back to anything, the correct place to return focus to would be the reference, not the previously focused element. If that happened instead, this issue would be less annoying.

Good point as well
