### ISSUE TITLE
[React] Deprecate `inner` and `useInnerOffset`

### ISSUE THREAD

**Issue by atomiks** [floating-ui/floating-ui#3133]
This technique of aligning an inner element to the reference has poor performance with longer lists, doesn't fit with the middleware paradigm, doesn't work on touch, and has a better custom alternative using native `onScroll` that needs to be encouraged instead - though it is unfortunately hard to implement yourself. However, I suspect both of these are very rarely used to begin with.

**Comment by pdrbrnd** [comment]
hi @atomiks just noticed this deprecation. Do you have any examples on how to implement a custom alternative?
