### ISSUE TITLE
Flip with offset doesn't take offset into account

### ISSUE THREAD

**Issue by hi-rai** [floating-ui/floating-ui#3149]
**Describe the bug**

Flip with offset still considers the floating elements size for flipping and doesn't account for offset

**To Reproduce**

[Codesandbox link](https://codesandbox.io/p/sandbox/busy-margulis-jqqynf) - On scrolling down, the tooltip doesn't flip even if it reaches the top edge. It flips on scrolling further

**Expected behavior**

The tooltip should flip immediately when it touches the top edge

**Screenshots**

<img width="1099" alt="Screenshot 2024-12-05 at 8 34 16 PM" src="https://github.com/user-attachments/assets/3815234a-954e-4e8b-80da-e05cf209e0cd">

**Comment by atomiks** [comment]
This is because it's offsetting after `flip()` has done its work. Just need to place `offset()` before `flip()` in the array.
