### ISSUE TITLE
Deployment pipelines all down after removing @popperjs/core from NPM

### ISSUE THREAD

**Issue by joshfester** [floating-ui/floating-ui#3153]
I have dozens of applications that depend on the @popperjs/core NPM package (because they all use Bootstrap). All of them have broken deployments now because it is no longer on NPM. 

My solution will be to find an old build and vendor it into these projects. But this will be a major time sink, and I doubt I'll be the only one. Is it possible to reinstate the old NPM package for people in this situation? There could be some clear messaging that it is no longer maintained and provide some upgrade links. But for now this feels like a major rug pull 🙁

**Comment by joshfester** [comment]
Looks like this was fixed, maybe unintentional

**Comment by FezVrasta** [comment]
We never removed and will never remove `@popperjs/core` from npm.

https://www.npmjs.com/package/@popperjs/core
