### ISSUE TITLE
Vue3: Arrow doesn't flip with floating element

### ISSUE THREAD

**Issue by jasonsrogers** [floating-ui/floating-ui#3161]
Arrow stays position on the same side of the floating element if it is flipped or not. 

For example: 
if an item has a placement of top, the arrow will show at the bottom of the floating element when displaying normally. 
When the item is close to the top of the page, the floating element flips to bottom but arrow stays at the bottom of the floating element.

Expected: arrow position flips sides.

Code sandbox demo:
https://codesandbox.io/p/sandbox/vue-floating-ui-forked-f4d5mh?file=%2Fsrc%2FApp.vue%3A88%2C17

Steps to reproduce the behaviour:
None, sandbox show arrow (red rectangle) at bottom when flipped (default state of sandbox)
If you change the target css from
margin: 50px auto;
to
margin: 150px auto;
This will unflip and show the arrow displaying properly.

**Expected behavior** 
Arrow should also flip to opposing side of the floating element 

**Screenshots** 
<img width="541" alt="Screenshot 2024-12-13 at 14 51 37" src="https://github.com/user-attachments/assets/394271a0-7207-4ef0-a83f-9ab7ee68f668" />

**Context:**

- OS: macOs and windows
- Browser chrome, brave, safari
- Version latests

**Additional context** Add any other context about the problem here.

**Comment by atomiks** [comment]
This is just a mistake in using Vue's reactivity system. The value is stale because it's not inside a `computed()` call:

This works:
```js
const oppositeSide = computed(() => OPPOSITE_SIDE_BY_SIDE[side.value]);
```

(Aside from the fact that the inner element is 20px but the outer one is 16px and is being used for measurement, so it's 4px off)
