### ISSUE TITLE
useListNavigation home/end internal logic

### ISSUE THREAD

**Issue by R-Bower** [floating-ui/floating-ui#3169]
**Describe the bug** A clear and concise description of what the bug is.

Similar to https://github.com/floating-ui/floating-ui/issues/3082 but that has been resolved.

The useListNavigation uses internal logic to determine whether to enable home/end keys.  The reference element has to be a [typeable element](https://github.com/floating-ui/floating-ui/blob/master/packages/react/src/utils.ts#L194) with `role="combobox"`.  

I'd like the ability to override the this behavior.  The reasoning is that my reference element isn't always an input element.  Sometimes it's a div that wraps the input element, but this doesn't trigger the [internal logic](https://github.com/floating-ui/floating-ui/blob/e61070e24ac03f92d43d3aafe8dea4b8fd968af2/packages/react/src/hooks/useListNavigation.ts#L614) that disables the home/end keys. I've tried to override or cancel the home/end events but nothing seems to work when `virtual: true` is set.  

Is it possible to include an extra prop to disable this functionality outright?  I'm willing to submit a PR for this.

**Comment by mihkeleidast** [comment]
> The reasoning is that my reference element isn't always an input element. Sometimes it's a div that wraps the input element.

If you spread getReferenceProps onto the reference element, how do you ensure all the aria etc attributes still end up on the input?

Sounds like this div wrapping the input without proper ref and prop forwarding may break expected accessibility behaviors.

Maybe a sandbox example of how you've set this up currently would help understand this.

**Comment by R-Bower** [comment]
> If you spread getReferenceProps onto the reference element, how do you ensure all the aria etc attributes still end up on the input?

Manually, with careful consideration.

**Comment by R-Bower** [comment]
Then the floating element is placed relative to the input element, which isn't desirable for my use case.

**Comment by atomiks** [comment]
> Then the floating element is placed relative to the input element, which isn't desirable for my use case.

It sounds like you just want to set the position reference to the outer element? https://floating-ui.com/docs/react#changing-the-positioning-reference-while-retaining-events

**Comment by R-Bower** [comment]
Doh, I missed that config option.  I'll give this a shot.  Thank you!
